// Generates a side-by-side comparison from two Tool rows when the pair has no
// pre-curated entry in the comparisons table. Renders 7 criteria using the same
// shape as compare/[slug]/page.tsx expects, plus a summary line.

export interface AutoTool {
  slug: string
  name: string
  tagline: string
  logo_url: string | null
  website_url: string | null
  pricing_type: string
  pricing_free_tier: boolean
  pricing_starting_price: number | null
  rating: number
  review_count: number
  pros: string[] | null
  cons: string[] | null
  use_cases: string[] | null
  integrations: string[] | null
  tags: string[] | null
}

export interface AutoCriterion {
  name: string
  tool_a_score: number
  tool_b_score: number
  notes: string | null
  sort_order: number
}

export interface AutoComparison {
  slug: string
  tool_a_slug: string
  tool_b_slug: string
  summary: string
  winner: string | null
  criteria: AutoCriterion[]
  scoreA: number
  scoreB: number
  isAutoGenerated: true
}

// Returns slug `a-vs-b` where a < b alphabetically. Used to canonicalise URLs
// so /compare/a-vs-b and /compare/b-vs-a do not produce duplicate index targets.
export function canonicalPairSlug(slugA: string, slugB: string): string {
  const [a, b] = slugA < slugB ? [slugA, slugB] : [slugB, slugA]
  return `${a}-vs-${b}`
}

export function parsePairSlug(slug: string): { a: string; b: string } | null {
  const match = slug.match(/^(.+)-vs-(.+)$/)
  if (!match) return null
  return { a: match[1], b: match[2] }
}

function priceScore(t: AutoTool): number {
  if (t.pricing_type === 'free') return 5
  if (t.pricing_free_tier) {
    if (!t.pricing_starting_price) return 4.5
    if (t.pricing_starting_price <= 15) return 4.5
    if (t.pricing_starting_price <= 30) return 4
    if (t.pricing_starting_price <= 60) return 3.5
    return 3
  }
  if (!t.pricing_starting_price) return 3
  if (t.pricing_starting_price <= 15) return 4
  if (t.pricing_starting_price <= 30) return 3.5
  if (t.pricing_starting_price <= 60) return 3
  return 2.5
}

function freeTierScore(t: AutoTool): number {
  if (t.pricing_type === 'free') return 5
  if (t.pricing_free_tier) return 4
  if (t.pricing_type === 'ltd') return 3
  return 1.5
}

function ratingTo5(rating: number): number {
  // Already on 5-scale; round to 0.5 steps for display.
  return Math.max(1, Math.round(rating * 2) / 2)
}

function depthScore(t: AutoTool): number {
  const features = (t.pros?.length ?? 0) + (t.use_cases?.length ?? 0)
  if (features >= 10) return 5
  if (features >= 7) return 4.5
  if (features >= 5) return 4
  if (features >= 3) return 3.5
  return 3
}

function integrationScore(t: AutoTool): number {
  const n = t.integrations?.length ?? 0
  if (n >= 8) return 5
  if (n >= 5) return 4.5
  if (n >= 3) return 4
  if (n >= 1) return 3.5
  return 3
}

function popularityScore(t: AutoTool): number {
  if (t.review_count >= 5000) return 5
  if (t.review_count >= 1000) return 4.5
  if (t.review_count >= 250) return 4
  if (t.review_count >= 50) return 3.5
  return 3
}

function easeScore(t: AutoTool): number {
  // Crude proxy: tools with free tier and lower price are usually easier to start.
  let base = 3.5
  if (t.pricing_free_tier || t.pricing_type === 'free') base += 0.5
  if (t.pricing_starting_price && t.pricing_starting_price <= 20) base += 0.5
  if (t.review_count >= 1000) base += 0.5
  return Math.min(5, base)
}

export function generateAutoComparison(
  toolA: AutoTool,
  toolB: AutoTool,
): AutoComparison {
  const criteria: AutoCriterion[] = [
    {
      name: 'Output Quality',
      tool_a_score: ratingTo5(toolA.rating),
      tool_b_score: ratingTo5(toolB.rating),
      notes: `Derived from aggregate ratings (${toolA.review_count.toLocaleString()} vs ${toolB.review_count.toLocaleString()}).`,
      sort_order: 1,
    },
    {
      name: 'Ease of Use',
      tool_a_score: easeScore(toolA),
      tool_b_score: easeScore(toolB),
      notes: 'Estimated from free-tier availability and entry pricing.',
      sort_order: 2,
    },
    {
      name: 'Pricing Value',
      tool_a_score: priceScore(toolA),
      tool_b_score: priceScore(toolB),
      notes: `${toolA.name}: ${toolA.pricing_starting_price ? '$' + toolA.pricing_starting_price + '/mo' : toolA.pricing_type}. ${toolB.name}: ${toolB.pricing_starting_price ? '$' + toolB.pricing_starting_price + '/mo' : toolB.pricing_type}.`,
      sort_order: 3,
    },
    {
      name: 'Free Tier',
      tool_a_score: freeTierScore(toolA),
      tool_b_score: freeTierScore(toolB),
      notes: `${toolA.name}: ${toolA.pricing_free_tier || toolA.pricing_type === 'free' ? 'yes' : 'no'}. ${toolB.name}: ${toolB.pricing_free_tier || toolB.pricing_type === 'free' ? 'yes' : 'no'}.`,
      sort_order: 4,
    },
    {
      name: 'Feature Depth',
      tool_a_score: depthScore(toolA),
      tool_b_score: depthScore(toolB),
      notes: 'Estimated from documented pros and use cases.',
      sort_order: 5,
    },
    {
      name: 'Integrations',
      tool_a_score: integrationScore(toolA),
      tool_b_score: integrationScore(toolB),
      notes: `${toolA.integrations?.length ?? 0} integrations vs ${toolB.integrations?.length ?? 0}.`,
      sort_order: 6,
    },
    {
      name: 'Adoption',
      tool_a_score: popularityScore(toolA),
      tool_b_score: popularityScore(toolB),
      notes: 'User adoption proxy from aggregate review volume.',
      sort_order: 7,
    },
  ]

  const scoreA = criteria.reduce((s, c) => s + c.tool_a_score, 0)
  const scoreB = criteria.reduce((s, c) => s + c.tool_b_score, 0)

  let winner: string | null = null
  if (scoreA - scoreB >= 1.5) winner = toolA.slug
  else if (scoreB - scoreA >= 1.5) winner = toolB.slug

  const summary = buildSummary(toolA, toolB, scoreA, scoreB)

  return {
    slug: canonicalPairSlug(toolA.slug, toolB.slug),
    tool_a_slug: toolA.slug,
    tool_b_slug: toolB.slug,
    summary,
    winner,
    criteria,
    scoreA,
    scoreB,
    isAutoGenerated: true,
  }
}

function buildSummary(a: AutoTool, b: AutoTool, sA: number, sB: number): string {
  const closer = Math.abs(sA - sB) < 1.5
  if (closer) {
    return `${a.name} and ${b.name} are closely matched on the seven criteria below. ${a.name} is rated ${a.rating.toFixed(1)}/5 across ${a.review_count.toLocaleString()} aggregate ratings; ${b.name} is rated ${b.rating.toFixed(1)}/5 across ${b.review_count.toLocaleString()}. Pick by which feature gap matters most for your workflow.`
  }
  const winner = sA > sB ? a : b
  const loser = sA > sB ? b : a
  return `${winner.name} edges ${loser.name} on the seven criteria below. ${winner.name} is rated ${winner.rating.toFixed(1)}/5 across ${winner.review_count.toLocaleString()} ratings, ahead of ${loser.name} at ${loser.rating.toFixed(1)}/5 from ${loser.review_count.toLocaleString()}. Editorial review of this pair is pending - the auto-generated comparison below is based on data signals alone.`
}

export function buildWhenToPick(toolA: AutoTool, toolB: AutoTool): { whenA: string; whenB: string } {
  const aFree = toolA.pricing_free_tier || toolA.pricing_type === 'free'
  const bFree = toolB.pricing_free_tier || toolB.pricing_type === 'free'
  const aCheaper = (toolA.pricing_starting_price ?? Infinity) < (toolB.pricing_starting_price ?? Infinity)
  const aBetterRated = toolA.rating > toolB.rating + 0.2
  const aMoreAdopted = toolA.review_count > toolB.review_count * 1.5

  const reasonsA: string[] = []
  if (aFree && !bFree) reasonsA.push('you need a free tier')
  if (aCheaper && !aFree) reasonsA.push(`budget is the priority ($${toolA.pricing_starting_price}/mo vs $${toolB.pricing_starting_price}/mo)`)
  if (aBetterRated) reasonsA.push(`output quality is the priority (${toolA.rating.toFixed(1)} vs ${toolB.rating.toFixed(1)})`)
  if (aMoreAdopted) reasonsA.push(`team adoption matters (${toolA.review_count.toLocaleString()} ratings vs ${toolB.review_count.toLocaleString()})`)
  if (reasonsA.length === 0) reasonsA.push(`its specific use cases (${toolA.use_cases?.slice(0, 2).join(', ') ?? 'see tool page'}) match yours`)

  const reasonsB: string[] = []
  if (bFree && !aFree) reasonsB.push('you need a free tier')
  if (!aCheaper && toolB.pricing_starting_price) reasonsB.push(`budget is the priority ($${toolB.pricing_starting_price}/mo vs $${toolA.pricing_starting_price}/mo)`)
  if (!aBetterRated && toolB.rating > toolA.rating + 0.2) reasonsB.push(`output quality is the priority (${toolB.rating.toFixed(1)} vs ${toolA.rating.toFixed(1)})`)
  if (!aMoreAdopted && toolB.review_count > toolA.review_count * 1.5) reasonsB.push(`team adoption matters (${toolB.review_count.toLocaleString()} ratings vs ${toolA.review_count.toLocaleString()})`)
  if (reasonsB.length === 0) reasonsB.push(`its specific use cases (${toolB.use_cases?.slice(0, 2).join(', ') ?? 'see tool page'}) match yours`)

  return {
    whenA: `Pick ${toolA.name} when ${reasonsA.join(', and ')}.`,
    whenB: `Pick ${toolB.name} when ${reasonsB.join(', and ')}.`,
  }
}
