-- descriptions-update-6.sql
-- Descriptions for tools from tools-batch-12.sql
-- Tools: sora, avoma, instantly-ai, recraft-ai, hedra, tana, pipio, hypercontext, adobe-podcast, warp
-- Run in Supabase SQL Editor

UPDATE tools SET description = 'Sora is OpenAI''s text-to-video generation model, capable of creating realistic and imaginative video scenes from written prompts. Released and made widely available in late 2024, Sora can generate videos up to a minute long while maintaining visual quality, subject consistency, and coherent motion. It understands complex physical interactions, multiple characters, and nuanced camera movements, making it the most technically capable video generation model from a major AI lab at launch.

The tool is designed for filmmakers, content creators, and marketing teams who want to prototype visual ideas without a film crew. Sora accepts text prompts, existing images, or short video clips as input, and can extend, remix, or generate entirely new footage. Access is available through ChatGPT Plus and Pro plans, positioning it as a premium feature within the OpenAI ecosystem. For teams already using ChatGPT for content workflows, Sora offers a natural extension into AI video without switching platforms.'
WHERE slug = 'sora';

UPDATE tools SET description = 'Avoma is an AI meeting intelligence platform that handles the full meeting lifecycle - scheduling, transcription, summarization, and coaching. It joins calls automatically, generates structured notes organized by topic, and tracks action items and decisions without manual effort. The platform integrates with major calendar systems, CRMs like Salesforce and HubSpot, and video conferencing tools including Zoom, Google Meet, and Microsoft Teams.

Beyond basic transcription, Avoma includes conversation intelligence features built for sales and customer success teams. Managers can review call recordings with AI-generated insights, track talk ratios, monitor keyword mentions, and identify coaching opportunities. The system benchmarks individual reps against team averages, helping sales leaders replicate top performer behaviors across the organization. For revenue-focused teams that want meeting intelligence at a lower price point than Gong or Chorus, Avoma is a compelling option.'
WHERE slug = 'avoma';

UPDATE tools SET description = 'Instantly is an AI-powered cold email outreach platform designed for sales teams and agencies that send high volumes of personalized emails. The platform manages unlimited sending accounts, automatically rotates between them to preserve deliverability, and includes AI tools to personalize emails at scale using prospect data. Built-in warmup features gradually increase sending volume to avoid spam filters and protect sender reputation across all connected accounts.

The platform includes a B2B lead database with over 160 million verified contacts, allowing users to build targeted prospect lists without a separate prospecting tool. Instantly''s AI can write personalized email sequences, A/B test subject lines, and score leads based on engagement signals. For agencies managing cold outreach for multiple clients, the unlimited seats and white-label reporting make it a practical alternative to tools that charge per user or per sending account. Teams that prioritize deliverability and volume over complex multi-channel sequences will find Instantly well-suited to their workflow.'
WHERE slug = 'instantly-ai';

UPDATE tools SET description = 'Recraft is an AI design tool specializing in vector graphics, brand illustration, and consistent visual style across large volumes of assets. Unlike general-purpose image generators, Recraft allows users to define a brand style and generate images, icons, and illustrations that match it consistently across different prompts, solving a core challenge with AI image generation for professional design work. The platform supports SVG output natively, making generated assets directly editable in Illustrator or Figma without conversion.

The tool is particularly strong for UI/UX designers and brand teams who need to produce large volumes of on-brand visual content quickly. Recraft supports generating icons, app screenshots, marketing illustrations, and product images all within a defined visual language. It was the first AI model to reach the top spot on the Hugging Face image generation leaderboard in 2024, signaling strong technical performance alongside its design-focused workflow. For teams where visual consistency matters more than one-off creative experiments, Recraft fills a gap that general image generators leave open.'
WHERE slug = 'recraft-ai';

UPDATE tools SET description = 'Hedra is an AI video generation platform that creates realistic talking avatar videos from a portrait image combined with an audio track. Users upload or generate a character image, provide a voiceover or text-to-speech audio file, and Hedra animates the character to lip-sync with natural facial movements and expressions. The output quality is among the highest available for portrait animation, making it popular for educational videos, spokesperson content, and synthetic media production.

The platform targets content creators, marketers, and educators who need to produce talking-head videos at scale without on-camera talent or a film crew. Hedra''s Character-1 model handles diverse languages, accents, and expressions while preserving the visual identity of the input character across different audio tracks. Enterprise use cases include multilingual content localization, customer-facing video at scale, and internal training materials where recording live footage is impractical. For teams exploring AI-generated presenters, Hedra offers a purpose-built solution with production-quality output.'
WHERE slug = 'hedra';

UPDATE tools SET description = 'Tana is an AI-powered knowledge management tool built around a node-based structure that allows users to organize information as a graph rather than a linear document hierarchy. Every piece of information in Tana is a node that can be tagged, referenced, and queried using a built-in command system. The platform''s AI features include automatic extraction of people, tasks, and decisions from notes, and a conversational interface for querying stored knowledge across all connected nodes.

Designed for power users who need a research and thinking environment rather than a simple note-taking app, Tana bridges the gap between knowledge databases and task management. Users can create custom schemas for contacts, projects, meetings, and research, then use filtering and search to surface relevant information across all nodes. Tana is particularly popular among writers, researchers, and executives who want an AI-augmented second brain that adapts to complex personal workflows. Its learning curve is steeper than Notion or Obsidian, but the depth of customization it enables rewards the investment.'
WHERE slug = 'tana';

UPDATE tools SET description = 'Pipio is an AI video production platform focused on digital human avatars for professional corporate and marketing video content. Users select from a library of photorealistic AI actors or create custom avatars, then input a script to generate a polished talking-head video in minutes. The platform supports multiple languages and voice styles, and allows customization of the avatar''s appearance, background, and presentation style to match specific brand guidelines.

The platform targets marketing teams, learning and development departments, and media agencies that need to produce spokesperson videos, training content, or multilingual product demonstrations without scheduling live video shoots. Pipio''s AI actors maintain consistent appearance and delivery quality across multiple videos, making it practical for organizations that need dozens of videos with a unified on-screen presenter. Integrations with popular video editing workflows and support for standard output formats make it easy to incorporate Pipio-generated footage into broader production pipelines.'
WHERE slug = 'pipio';

UPDATE tools SET description = 'Hypercontext is an AI meeting management platform designed to improve the quality and outcomes of recurring team meetings, particularly one-on-ones and leadership check-ins. It structures meetings with shared agendas, goal tracking, and automated meeting notes, encouraging both managers and direct reports to arrive prepared. After each meeting, Hypercontext generates summaries and tracks action items against documented team OKRs, creating a continuous record of accountability.

The platform is built on the premise that better-structured meetings lead to higher employee engagement and clearer organizational alignment. HR and people operations teams use Hypercontext to track OKR progress across the organization, while managers use it to run effective performance conversations grounded in documented context. Integrations with Slack, Google Calendar, and Zoom make it straightforward to embed Hypercontext into existing workflows. For companies investing in management quality and trying to reduce ineffective meeting culture, Hypercontext provides structure and data that other meeting tools do not.'
WHERE slug = 'hypercontext';

UPDATE tools SET description = 'Adobe Podcast is an AI-powered audio production tool within the Adobe Creative Cloud ecosystem, best known for its Enhance Speech feature. The tool removes background noise, room echo, and microphone artifacts from voice recordings with a single click, transforming audio recorded on a laptop microphone into studio-quality sound. This makes it particularly valuable for remote workers, podcasters, and video creators who lack access to professional recording equipment or a treated recording space.

Beyond audio cleanup, Adobe Podcast provides browser-based recording for remote interviews, synchronized transcript editing where deleting words removes the corresponding audio, and basic multi-track editing. The Enhance Speech feature is available as a free standalone tool at podcast.adobe.com, while the full platform is included in Adobe Creative Cloud subscriptions. For content creators already in the Adobe ecosystem, it integrates naturally with Premiere Pro and Audition for advanced post-production workflows. The speech enhancement technology is frequently cited as among the best available for voice audio restoration.'
WHERE slug = 'adobe-podcast';

UPDATE tools SET description = 'Warp is a modern AI-powered terminal for macOS and Linux that replaces traditional command-line interfaces with a more intelligent development environment. It includes a built-in AI assistant that accepts natural language queries and returns the correct shell command, eliminating the need to search documentation or Stack Overflow for syntax. Warp also offers command history search, auto-completion, shared workspaces for teams, and a block-based interface where each command and its output are grouped as a distinct unit.

The terminal is designed for developers who spend significant time in the command line but want the productivity features normally found in IDEs. Teams can share terminal sessions, annotate commands, and build shared workflows directly in Warp. The AI features support multiple models and can explain what a command does before you run it, reducing errors and accelerating onboarding for developers working with unfamiliar codebases or infrastructure. Warp is free for individuals, with paid team plans unlocking collaboration and sharing features for engineering organizations.'
WHERE slug = 'warp';
