-- descriptions-update-8.sql
-- Descriptions for 10 tools from tools-batch-15.sql
-- Tools: humata, play-ht, wellsaid, lmstudio, kittl, looka, popai, picsart, uizard, stability-ai
-- Format: plain prose, 2 paragraphs, 150-250 words each
-- No em dashes. Run in Supabase SQL Editor.

UPDATE tools SET description = 'Humata is an AI-powered document intelligence platform that lets you chat with any PDF, research paper, contract, or report as if you were asking questions to a human expert. Upload a file and Humata instantly reads the entire document, allowing you to ask questions, get summaries, and extract specific information without scrolling through hundreds of pages. It is particularly popular with students, lawyers, researchers, and analysts who regularly work with dense documents.

The platform supports multi-document querying, so you can upload several related files and ask questions that draw on information from all of them simultaneously. Humata cites exact page numbers and passages in its answers, making it easy to verify the source of any claim. A free tier allows limited pages per month, while paid plans start at $9.99 per month for higher volume and team features. For anyone whose job involves reading and processing large volumes of text, Humata significantly reduces the time spent searching for specific information.'
WHERE slug = 'humata';

UPDATE tools SET description = 'Play.ht is a professional AI voice generation platform offering over 900 realistic voices across 142 languages and accents. It converts any text to speech with fine-grained controls for pacing, emphasis, pauses, and pronunciation - producing output that sounds natural enough for commercial use in podcasts, videos, e-learning, and voice applications. The platform is used by content creators, marketing teams, and developers who need high-quality AI narration without hiring voice talent.

Play.ht also supports voice cloning, allowing you to create a synthetic version of your own voice or a licensed voice model from a short audio sample. The API is well-documented and widely used for integrating text-to-speech into applications, customer service flows, and automated media pipelines. Pricing starts at $31.20 per month for personal use, with higher-tier plans for commercial projects and API access. For teams producing large volumes of audio content, Play.ht can dramatically reduce production costs compared to traditional voice recording.'
WHERE slug = 'play-ht';

UPDATE tools SET description = 'WellSaid Labs is an enterprise-grade AI voice platform focused specifically on professional narration quality. Unlike general-purpose TTS tools, WellSaid is built for corporate training, e-learning, and marketing content where consistency and a natural, authoritative tone are critical. Its studio voices are created in collaboration with real voice actors, meaning the output preserves the warmth and expression of human narration while being generated instantly from text.

The platform offers a browser-based studio where teams can write scripts, assign voices, adjust delivery, and download audio files without any technical setup. WellSaid supports collaborative projects, allowing multiple team members to work on the same script simultaneously. It does not offer a free tier - pricing starts at $44 per month - reflecting its positioning as a professional tool for organizations rather than individual creators. For L&D teams, instructional designers, and brand marketers who need consistent, high-quality narration at scale, WellSaid is among the best options available.'
WHERE slug = 'wellsaid';

UPDATE tools SET description = 'LM Studio is a free desktop application for running large language models locally on your own computer. It supports models from the Hugging Face ecosystem, including Llama 3, Mistral, Phi, Gemma, and dozens of other open-weight models, with a simple interface for downloading, managing, and chatting with them. Because everything runs on-device, LM Studio offers complete privacy - your conversations never leave your machine, making it appealing for developers, researchers, and privacy-conscious users.

The application includes a built-in chat interface similar to ChatGPT, as well as a local API server that is fully compatible with the OpenAI API format. This means you can point any OpenAI-compatible application or SDK to your local LM Studio server and use local models as a drop-in replacement for cloud APIs. LM Studio requires a Mac, Windows, or Linux machine with sufficient RAM and ideally a GPU for reasonable inference speeds. It is completely free, with no usage limits - the only cost is your own hardware. For developers experimenting with LLMs or building applications that need on-device AI, LM Studio is the most accessible entry point.'
WHERE slug = 'lmstudio';

UPDATE tools SET description = 'Kittl is a graphic design platform built specifically for creating print-ready and commercial-quality designs without needing professional design skills. It offers an extensive library of editable templates for t-shirts, logos, posters, labels, and merchandise, with AI tools that generate design elements, suggest color palettes, and help turn rough ideas into polished artwork. The platform is widely used by small business owners, Etsy sellers, print-on-demand creators, and apparel designers.

What distinguishes Kittl from tools like Canva is its focus on typography-heavy and illustrative design styles that are common in merchandise and brand identity work. The AI text effects feature generates stylized lettering in seconds, and vector export ensures designs can be scaled to any size without quality loss. A free tier covers basic use, while paid plans start at $10 per month for commercial licensing and higher export resolution. For creators who sell custom merch or need brand-ready design assets without a design degree, Kittl is one of the most practical tools available.'
WHERE slug = 'kittl';

UPDATE tools SET description = 'Looka is an AI-powered brand identity platform that generates logos, brand kits, and business collateral from a short questionnaire about your company. You enter your business name, select visual styles and colors you like, and Looka produces dozens of logo concepts instantly. Once you choose a direction, you can customize every element - icon, font, color, layout - using a drag-and-drop editor before purchasing the final files.

Beyond logos, Looka generates a complete brand kit including business card designs, social media templates, email signatures, and website builder assets, all using your chosen logo and color palette for visual consistency. This makes it useful for founders and freelancers who want cohesive brand materials without hiring a designer or subscribing to multiple tools. Pricing is one-time rather than subscription-based for the logo alone, starting at around $20 for basic files. A Brand Kit subscription ($96/year) adds ongoing access to all branded templates. For early-stage businesses that need a professional identity quickly, Looka is a cost-effective starting point.'
WHERE slug = 'looka';

UPDATE tools SET description = 'PopAi is an AI assistant and document productivity platform that combines chat, document analysis, image generation, and presentation creation in a single interface. It functions as a general-purpose AI workspace where you can upload files and ask questions, generate images from text prompts, create slide decks from outlines, and chat with an AI assistant for research and writing tasks. The platform is designed for students, professionals, and small teams who want a single tool rather than multiple specialized apps.

The document chat feature supports PDFs, Word files, and web content, with the AI providing cited answers from uploaded material. The presentation generator can turn a topic or outline into a multi-slide deck with layout suggestions in minutes. PopAi offers a free tier with daily message limits and a pro plan at $9.99 per month for higher usage and access to more powerful underlying models. It occupies a similar space to Perplexity and ChatGPT but adds document and presentation features that those platforms handle less directly. For users who want an all-in-one AI workspace without managing multiple subscriptions, PopAi offers strong value.'
WHERE slug = 'popai';

UPDATE tools SET description = 'Picsart is a mobile-first photo and video editing platform with a growing suite of AI-powered creative tools. It is one of the most widely downloaded creative apps globally, offering AI background removal, AI-generated photo filters, object erasing, image upscaling, and AI image generation from text prompts. The platform targets social media creators, influencers, and casual users who need fast, professional-looking edits without Photoshop-level complexity.

The AI tools in Picsart are designed for speed - most effects apply in a single tap with no manual selection or masking required. The background remover handles hair and fine detail accurately, the AI image generator produces social-ready visuals quickly, and the editing tools are optimized for the vertical formats used on Instagram, TikTok, and Snapchat. A free tier provides access to core features with watermarks, while the Gold subscription at $5 per month removes watermarks and unlocks the full tool library. For content creators who produce high volumes of social media visuals on mobile, Picsart is one of the most capable and affordable options available.'
WHERE slug = 'picsart';

UPDATE tools SET description = 'Uizard is an AI-powered UI design tool that generates wireframes, mockups, and app screens from text descriptions, hand-drawn sketches, or screenshots of existing products. It is designed for product managers, founders, and non-designers who need to communicate design ideas without learning Figma or hiring a designer. You can describe an app feature in plain language - "a mobile checkout screen with a cart summary and payment fields" - and Uizard generates a realistic mockup in seconds.

The platform also includes a screenshot scanner that converts any existing app or website screenshot into an editable Uizard design, making it easy to remix or improve existing UI patterns. Teams can collaborate on designs in real time, share interactive prototypes with stakeholders, and export assets for developer handoff. A free tier supports basic projects with up to 3 screens, while paid plans start at $12 per month for unlimited screens and AI generation. Uizard is not a replacement for professional UI design tools, but it is an excellent fit for early-stage product validation, internal prototyping, and design-to-developer communication without a dedicated design team.'
WHERE slug = 'uizard';

UPDATE tools SET description = 'Stability AI is the research company behind Stable Diffusion, the open-source image generation model that underpins a large portion of the AI image generation ecosystem. While the company offers its own products and APIs for image, video, audio, and 3D generation, Stability AI is most widely known as the organization that made advanced image generation accessible by releasing model weights publicly. Developers, researchers, and creators use Stability AI models via the API, via tools like ComfyUI and Automatic1111, or through consumer products built on top of the models.

The Stability AI API provides access to their latest generation models including Stable Diffusion 3 and Stable Image Ultra, offering both standard image generation and advanced capabilities like structure control and style transfer. The API pricing is usage-based with a free credit tier for testing. For production workloads at scale, Stability AI models are often deployed on dedicated GPU infrastructure for cost control. Stability AI occupies a unique position in the market as both a commercial API provider and an open-source research organization, making its models foundational to the broader AI image generation landscape.'
WHERE slug = 'stability-ai';
