-- Session 17: Descriptions Batch D — 10 tools from tools-batch-3.sql
-- Run in Supabase SQL Editor
-- Plain prose, no markdown. Paragraphs separated by \n\n

UPDATE tools SET description = 'Monday.com is a cloud-based work operating system used by more than 200,000 organisations worldwide. It gives teams a single, flexible platform to plan projects, assign tasks, track progress, and report on results — all in one place and without needing to stitch together multiple specialised apps.

The platform is built around visual boards that can be configured to represent almost any workflow: sprint planning for engineering teams, content calendars for marketing, deal pipelines for sales, or construction project timelines. Automations eliminate repetitive manual work — for instance, automatically assigning tasks when a status changes or notifying a manager when a deadline is approaching. More than 200 integrations connect Monday to Slack, Google Drive, Jira, Salesforce, and other tools in a typical enterprise stack. Monday AI assists with task summarisation, writing update descriptions, and suggesting action items from meeting notes. Plans start at $9 per seat per month (billed annually) for the Basic tier. Standard at $12 per seat per month adds automations and integrations. Pro at $19 per seat per month includes time tracking, dependencies, and advanced reporting.'
WHERE slug = 'monday';

UPDATE tools SET description = 'ClickUp is an all-in-one productivity platform designed to replace project management, document collaboration, and goal tracking with a single tool. It is used by teams across engineering, marketing, design, and operations who want to consolidate multiple SaaS subscriptions into one workspace.

The core of ClickUp is its hierarchy: workspaces are divided into spaces, folders, and lists — each containing tasks that can be viewed as lists, boards, Gantt charts, calendars, timelines, or whiteboards. This flexibility means the same platform works for a developer managing a sprint backlog and a designer organising a creative brief. Docs lets teams write and embed documentation directly alongside their tasks, so meeting notes, product specs, and SOPs live next to the work they describe. ClickUp Brain, the platform''s AI assistant, generates task summaries, writes status updates, creates subtasks from descriptions, and answers questions about work across the workspace. The free plan is generous with unlimited tasks and members. Unlimited at $7 per member per month removes most usage caps. Business at $12 per member per month adds advanced automation and dashboard features.'
WHERE slug = 'clickup';

UPDATE tools SET description = 'Miro is an online collaborative whiteboard platform used by product, design, and cross-functional teams to think visually and work together in real time, regardless of location. With more than 80 million users, it is one of the most widely adopted digital whiteboards in enterprise environments.

The infinite canvas hosts sticky notes, flowcharts, wireframes, mind maps, process diagrams, and retrospective boards — all in a single shared space. Templates for common workshop formats — design sprints, Agile retrospectives, OKR planning, customer journey mapping — mean teams can start structured sessions in minutes without building from scratch. Real-time cursors let distributed teams see each other''s contributions live, making Miro a strong replacement for in-person whiteboarding sessions. Miro AI generates diagram shapes from text descriptions, summarises sticky note clusters from brainstorms, and converts handwritten workshop outputs into structured formats. The free plan supports up to 3 boards. Starter at $8 per member per month removes board limits. Business at $16 per member per month adds SSO, advanced security, and admin controls. Miro is particularly strong for UX teams, product managers, and consultancies that run structured workshops regularly.'
WHERE slug = 'miro';

UPDATE tools SET description = 'QuillBot is an AI paraphrasing and writing tool used primarily by students, researchers, and non-native English speakers who need to rewrite, refine, or summarise existing text. With more than 35 million monthly active users, it is one of the most widely used writing assistants focused specifically on reworking and improving prose.

The paraphraser is the core feature. It rewrites a block of text using one of several modes: Standard, Fluency, Formal, Academic, Simple, Creative, and Shorten. Fluency mode corrects grammar while preserving the original meaning. Academic mode shifts vocabulary to suit scholarly writing, making QuillBot particularly useful for students adapting source material or researchers reworking technical content for different audiences. The Summariser condenses long documents, articles, or research papers into key points — useful for quickly extracting essential ideas from long-form content. The Grammar Checker and Chrome extension let users access QuillBot''s features directly inside the tools where they already write. The free plan covers basic paraphrasing up to 125 words. Premium at $8.33 per month (billed annually) removes length limits, unlocks all paraphrase modes, and adds the full summariser.'
WHERE slug = 'quillbot';

UPDATE tools SET description = 'Pika is an AI video generation platform that converts text prompts, images, and short video clips into high-quality video content. It is designed for creators, marketers, and social media professionals who want to produce engaging video without video editing skills or production equipment.

The text-to-video feature generates short clips from a written description, specifying camera movement, scene content, style, and action. Image-to-video animates still photos or illustrations into motion, which is useful for bringing product images or artwork to life on social platforms. The video editing features allow users to extend a generated clip, modify specific elements within a scene, or swap out backgrounds using AI-powered tools. Pika''s output is optimised for short-form social video — clip lengths and aspect ratios align with TikTok, Instagram Reels, and YouTube Shorts formats. For marketing teams and content creators who need a constant stream of short video assets, Pika reduces production time and cost significantly compared to traditional video editing workflows. The free plan provides limited generation credits per month. Basic at $8 per month and Standard at $24 per month increase credit allowances and remove watermarks. Pro at $55 per month is designed for creators producing video content at high volume.'
WHERE slug = 'pika';

UPDATE tools SET description = 'Suno is an AI music generation platform that creates fully produced songs from text prompts. Users describe a style, mood, topic, or lyrical theme, and Suno generates complete audio tracks with vocals, instruments, and production — not just backing tracks or MIDI sequences.

The generation quality is notably high for an AI music tool. Suno handles genre diversity well, producing credible hip-hop, indie pop, folk, electronic, metal, jazz, and classical pieces from text descriptions. Users can provide their own lyrics or let Suno generate them. The resulting tracks include singing, harmonies, and instrumental arrangements that would typically require a full production session to create. For content creators, the primary use case is background music and soundtrack creation for videos, podcasts, social posts, and games — without paying licensing fees for commercially licensed tracks. For musicians and producers, Suno serves as a rapid ideation tool for exploring song concepts before committing to a full production. The free plan allows 50 song generations per day with non-commercial usage rights. Pro at $8 per month and Premier at $24 per month increase daily generation limits and grant commercial usage rights for monetised content.'
WHERE slug = 'suno';

UPDATE tools SET description = 'Asana is a work management platform used by teams to coordinate projects, track tasks, and manage workflows across departments. It is one of the longest-established tools in project management software, with more than 150,000 paying organisations using it across engineering, marketing, operations, and HR.

The core interface organises work into projects, tasks, and subtasks, with views including lists, boards, timelines, and calendars. Workflow Builder lets teams create automated rules that trigger actions — moving a task to a new section when a status changes, sending a notification when a deadline passes, or routing a form submission to the right team. For recurring processes like client onboarding or product launches, Asana templates codify the standard workflow so it can be repeated without manual setup. Asana AI generates task descriptions, summarises project status updates, and identifies risks in project timelines. For project managers overseeing multiple workstreams, AI-generated status summaries reduce the time spent writing updates for stakeholders. The free plan supports teams up to 10 users with unlimited tasks. Premium at $10.99 per user per month adds timelines and reporting. Business at $24.99 per user per month includes workload management, portfolios, and advanced integrations.'
WHERE slug = 'asana';

UPDATE tools SET description = 'Adobe Express is Adobe''s quick-design platform for creating social media graphics, short videos, flyers, presentations, and other visual content without the complexity of Photoshop or Illustrator. It is aimed at marketers, small business owners, educators, and content creators who need professional-looking visuals produced quickly.

The editor works from templates across hundreds of formats — Instagram posts, LinkedIn banners, YouTube thumbnails, email headers, and printed flyers. Adobe Express AI adds generative capabilities directly into the design workflow: text-to-image generates custom visuals from prompts, Generative Fill replaces or extends image elements, and Remove Background eliminates backgrounds with one click. Adobe Express includes Adobe Fonts, giving every design access to thousands of professional typefaces. Brand kits let teams store logos, colours, and approved fonts so every design stays on-brand without manual configuration. The free plan includes a generous set of templates and basic AI credits. Premium at $9.99 per month adds premium templates, full Adobe Fonts access, and more AI generation credits. Adobe Express is included in most Adobe Creative Cloud subscriptions, making it the natural quick-design tool for anyone already in the Adobe ecosystem.'
WHERE slug = 'adobe-express';

UPDATE tools SET description = 'Zoom is the video conferencing and communications platform that became the default infrastructure for remote work. With more than 300 million daily meeting participants at its peak, Zoom is the most widely recognised name in video communication and continues to be the standard tool for business video calls, webinars, and virtual events.

The core product offers HD video meetings with screen sharing, recording, breakout rooms, reactions, and built-in chat. Zoom Rooms extends the platform to conference room hardware. Zoom Phone is a cloud telephone system built on the same infrastructure. Zoom Webinars and Zoom Events handle large-format broadcasts for audiences of hundreds or thousands of participants. Zoom AI Companion — included at no extra charge on paid plans — generates meeting summaries and transcripts automatically after each call, suggests action items from the conversation, and answers questions about what was discussed during a meeting. For organisations running many meetings, automatic summarisation reduces the burden of manual note-taking significantly. The free plan supports meetings up to 40 minutes with up to 100 participants. Pro at $13.32 per month per user removes the time limit. Business at $18.32 per month per user adds managed domains, SSO, and company branding.'
WHERE slug = 'zoom';

UPDATE tools SET description = 'Slack is a team messaging and collaboration platform used by organisations of all sizes to replace email for internal communication. It is built around channels — topic, project, or team-specific spaces where conversations are organised and searchable rather than buried in individual inboxes.

The channel model is Slack''s primary differentiator from email. Each channel preserves its full conversation history, meaning new team members can read back through context without asking colleagues to forward threads. Threads keep replies organised within a message rather than flooding the main channel feed. Integrations with more than 2,600 apps — including GitHub, Jira, Google Drive, Salesforce, and Zoom — route notifications and actions directly into Slack, reducing context switching. Slack AI, available as an add-on to paid plans, generates channel recaps and conversation summaries, answers questions by searching across message history, and summarises long threads. For teams managing many simultaneous projects across dozens of channels, these features reduce the cognitive overhead of staying current. The free plan retains 90 days of message history and supports 10 app integrations. Pro at $7.25 per user per month provides full message history and unlimited integrations. Business+ at $12.50 per user per month adds SSO and compliance exports.'
WHERE slug = 'slack';
