-- descriptions-update-7.sql
-- Descriptions for tools from tools-batch-14.sql
-- Tools: superhuman, klap, d-id, readwise, vizard, chatpdf, remove-bg, fliki, decktopus, groq
-- Run in Supabase SQL Editor AFTER tools-batch-14.sql

UPDATE tools SET description = 'Superhuman is an AI-powered email client that rebuilds the inbox experience from the ground up for speed and focus. Built on keyboard shortcuts, instant performance, and AI-assisted triage, it processes email faster than any native app. The AI Triage feature surfaces important messages, auto-summarizes long threads, and drafts replies in your writing style - cutting inbox time by an average of four hours per week for most users.

The tool is designed for executives, founders, and professionals who treat inbox zero as a productivity discipline. Superhuman integrates with Gmail and Outlook, preserving your existing email address while replacing the interface entirely. Features like Snippets (saved reply templates), Read Statuses (open tracking), and Follow-up Reminders give power users granular control over their communication workflow. At $30 per month, it is a premium product aimed at users for whom reclaimed hours justify the cost.'
WHERE slug = 'superhuman';

UPDATE tools SET description = 'Klap is an AI video repurposing tool that automatically clips long-form video content into short, platform-ready segments for TikTok, Instagram Reels, and YouTube Shorts. Upload a video or paste a YouTube URL and Klap analyzes the transcript, identifies the most engaging moments, adds animated captions, and exports multiple clips in the correct vertical format. The process takes minutes rather than the hours required to manually clip and caption content.

Content creators, podcasters, and social media managers use Klap to multiply the reach of every video they produce without extra production time. The AI understands hook quality, pacing, and viewer retention patterns to prioritize clips most likely to perform on short-form platforms. Klap supports podcast recordings, webinars, YouTube videos, and course content as input. For creators already producing long-form video who want a short-form presence without a separate editing workflow, Klap is one of the most practical repurposing tools available.'
WHERE slug = 'klap';

UPDATE tools SET description = 'D-ID is an AI video generation platform specializing in realistic talking avatar videos from a still image and audio or text input. Users upload a portrait photo, provide a script or select a text-to-speech voice, and D-ID generates a video of the subject speaking with natural lip sync, facial animation, and head movement. The technology is used for AI-generated presenters, digital twins, customer service avatars, and multilingual video content at scale.

Creative Reality Studio, D-ID''s main product, targets marketing teams, e-learning developers, and enterprise organizations that need talking-head videos without on-camera talent. The platform supports over 100 languages and can generate videos from AI-generated characters, brand mascots, or real people with consent. For content teams that produce training materials, product explainers, or customer-facing video at high volume, D-ID offers a practical path to production-quality talking-head video without scheduling a film crew.'
WHERE slug = 'd-id';

UPDATE tools SET description = 'Readwise is an AI-powered reading tool that helps you retain and reconnect with everything you read across books, articles, newsletters, podcasts, and PDFs. It aggregates highlights from Kindle, Instapaper, Pocket, and web articles into a single library, then resurfaces them via daily digests and a spaced repetition review system. The Readwise Reader app adds full-featured read-it-later functionality with AI summarization, note-taking, and document-level chat directly in the reading view.

Knowledge workers, researchers, and avid readers use Readwise to build a searchable, annotated library of everything they consume online. The AI can summarize documents, answer questions about a book based on your highlights, and surface related notes across your entire reading history. For professionals who read extensively but struggle to act on what they learn, Readwise bridges the gap between passive reading and active knowledge retention. The tool pairs well with note-taking systems like Obsidian, Notion, and Roam Research via native export integrations.'
WHERE slug = 'readwise';

UPDATE tools SET description = 'Vizard is an AI video repurposing platform that transforms long-form recordings into multiple short-form clips optimized for social media. Upload a video or import from YouTube and Vizard automatically identifies key moments, generates captions, resizes for vertical formats, and produces clips ready for TikTok, Instagram, LinkedIn, and YouTube Shorts. The platform processes video faster than real-time and lets users refine selections or manually clip sections using a browser-based editor.

Marketing teams, course creators, and content agencies use Vizard to scale video repurposing across multiple clients and platforms. The AI analyzes speaker segments, topic transitions, and engagement patterns to select clips most likely to retain viewers. Vizard supports pre-recorded content and live stream recordings from Zoom and StreamYard. For organizations publishing regular video content who want consistent short-form output without a dedicated editor, Vizard offers batch processing and team collaboration features at a per-minute pricing model.'
WHERE slug = 'vizard';

UPDATE tools SET description = 'ChatPDF is a tool that lets you upload any PDF and have a conversation with it using AI. Ask questions, request summaries, extract specific data points, and get citations linked to the source page in the document. The tool works with research papers, contracts, textbooks, and financial reports, returning answers grounded in the document rather than general AI knowledge. Claims are referenced to specific passages, making it useful for fact-checking and document review.

Students, researchers, and professionals use ChatPDF to process large documents faster than manual reading allows. A 200-page annual report can be summarized in minutes, and specific clauses in a legal contract can be located by asking plain-language questions. The free tier allows a limited number of PDFs and pages per day, with paid plans removing limits and enabling larger files. For users who regularly process dense professional or academic documents, ChatPDF reduces document review time by replacing keyword search with conversational retrieval.'
WHERE slug = 'chatpdf';

UPDATE tools SET description = 'Remove.bg is an AI-powered background removal tool that processes images in seconds using computer vision to separate subjects from their backgrounds with pixel-precise accuracy. It handles complex edges including hair strands, fur, and transparent objects that traditional manual cutout tools struggle with. The tool is available as a web app, API, integrations for Photoshop and other design tools, and desktop apps for batch processing.

Photographers, e-commerce teams, and designers use Remove.bg to automate background removal at scale. An e-commerce company can process thousands of product photos in minutes rather than hours of manual retouching. The API makes it practical to integrate into existing photo workflows, content management systems, and automated publishing pipelines. For teams with high volumes of product photography or portrait editing, Remove.bg eliminates one of the most time-consuming manual post-production tasks while maintaining quality that rivals manual cutouts on most subjects.'
WHERE slug = 'remove-bg';

UPDATE tools SET description = 'Fliki is an AI video creation tool that generates videos from text scripts, articles, or blog posts using AI-generated voiceovers and a library of stock visuals. Users input a text prompt or paste existing content, select a voice from over 1,900 AI voices across 75+ languages, and Fliki generates a narrated video with matched visuals automatically. The tool targets content creators and marketers who want to produce voiceover videos without recording equipment or video editing experience.

Teams use Fliki to convert written content - blog posts, newsletters, and scripts - into video format for YouTube, LinkedIn, and social media. The AI voice quality is among the better text-to-speech options available, with realistic pacing and intonation. Fliki also supports AI avatars for talking-head videos and custom voice cloning for a consistent branded voice across all content. For marketing teams already producing written content at scale who want a video presence without additional production overhead, Fliki bridges the gap between text-first and video-first content strategies.'
WHERE slug = 'fliki';

UPDATE tools SET description = 'Decktopus is an AI presentation builder that generates complete slide decks from a topic description or outline prompt. Users describe the presentation topic and audience, and the AI produces a structured deck with suggested content, appropriate layouts, and visual design applied automatically. Decktopus handles the structure and formatting decisions that slow down most presentation workflows, letting users focus on refining content rather than building slides from scratch.

Teams and individuals use Decktopus for pitch decks, educational presentations, client reports, and internal business updates where a clean, professional-looking result is needed without a full design process. The tool includes a template library for common presentation types and allows customization of branding, colors, and fonts. Built-in form and response collection features let presenters gather audience feedback directly within the presentation. For professionals who need to produce a large number of presentations quickly and lack dedicated design resources, Decktopus provides a faster alternative to PowerPoint or Google Slides without requiring design skills.'
WHERE slug = 'decktopus';

UPDATE tools SET description = 'Groq is an AI inference company that built custom Language Processing Units (LPUs) designed to run large language models significantly faster than GPU-based alternatives. The practical result for end users is chat.groq.com, a free web interface that lets anyone interact with models like Llama 3, Mixtral, and Gemma at speeds reaching 500+ tokens per second - noticeably faster than any other publicly accessible AI chat interface. This speed difference is perceptible in real-time conversations and makes Groq practical for tasks where rapid iteration matters.

Developers and power users use Groq''s API to build applications requiring low-latency AI responses, including real-time transcription, live coding assistance, and customer-facing products where speed affects user experience. The free tier includes generous API limits that cover most experimental and personal use cases. Groq runs open-source and partner models with optimized inference, making it a neutral infrastructure layer rather than a model vendor. For users who want the fastest available AI responses with access to competitive open-source models at minimal cost, Groq is one of the most technically differentiated options available.'
WHERE slug = 'groq';
