-- S190 Mode B catalog expansion: 5 head-term missing slugs to unlock peer-double potential
-- across image-gen, B2B sales intent, enterprise marketing automation, video hosting, and code-AI cohorts.
-- Each pick passed S86 Tool Selection Quality Bar (Gate 1 favicon + HTTP, Gate 2 importance,
-- Gate 3 catalog fit).
-- Peer-double targets confirmed live in catalog (Block A verify-s190 part1+part2 2026-06-13).
-- Idempotency: ON CONFLICT (slug) DO NOTHING. Safe to re-run.

INSERT INTO tools (
  slug, name, tagline, description, logo_url, website_url, affiliate_url,
  pricing_type, pricing_free_tier, pricing_starting_price, rating, review_count,
  featured, trending, editor_pick, tags, pros, cons, use_cases, integrations,
  pricing_verified_at
) VALUES

-- 1. DALL-E 3 - OpenAI image-gen head-term, peer-double for midjourney/firefly/stable-diffusion S184/leonardo S164/flux S165
('dall-e-3', 'DALL-E 3',
'OpenAI image model embedded in ChatGPT and the API for natural-language image generation.',
'DALL-E 3 is the third generation image model from OpenAI, originally released in October 2023 and continuously updated since. It is the image generator embedded inside ChatGPT (free tier with daily limits, unlimited on Plus and Team), available via the OpenAI API at roughly 4 to 8 cents per image depending on resolution, and the default backend when Microsoft Designer or Bing Image Creator generate images. The defining trait vs Midjourney and Stable Diffusion is prompt adherence: DALL-E 3 reads long natural-language descriptions and renders the exact composition asked for, including legible text inside images and correct spatial relationships, with much less prompt engineering than competitors require. Style flexibility is broad (photorealistic, illustrated, vector, painted, 3D render) but the model is less tuned for the hyper-aesthetic stylized output that Midjourney specialists prefer. Content policy is the strictest of major image generators: no public figures, no copyrighted characters, strict on violence and adult content. For non-technical users who want one image right from a paragraph of description rather than iterating a short prompt, DALL-E 3 stays the lowest-friction pick in 2026.',
'', 'https://openai.com/index/dall-e-3', 'https://openai.com/index/dall-e-3',
'freemium', true, 20, 4.5, 5800,
false, false, false,
ARRAY['image-ai', 'ai-assistants'],
ARRAY['Best in class prompt adherence on long descriptive prompts',
'Embedded in ChatGPT so non-technical users access it without a separate app',
'Renders legible text inside images much more reliably than Midjourney v6',
'API access at 4 to 8 cents per image scales for product use cases',
'Strict content policy reduces brand-safety risk for enterprise teams'],
ARRAY['Less aesthetic out of the box than Midjourney v7 stylized output',
'Strict content policy blocks public figures and many creative use cases',
'No batch generation, grid view, or seed reuse like Midjourney',
'Style consistency across a series of images is weaker than Leonardo or Flux',
'Pricing inside ChatGPT Plus is uncapped only for Team and Enterprise seats'],
ARRAY['One-shot images from natural-language descriptions for blog posts and slides',
'Product mockups and concept art for non-designer founders',
'Marketing visuals with legible on-image text (headlines, badges, CTAs)',
'Educational illustrations and editorial figures',
'API-driven image generation inside SaaS products'],
ARRAY['microsoft-365', 'zapier', 'slack', 'notion'],
'2026-06-13 00:00:00+00'),

-- 2. ZoomInfo - B2B intent and contact data head-term, peer-double for apollo S185/clearbit/6sense/demandbase S129
('zoominfo', 'ZoomInfo',
'B2B intent data and contact database with real-time buyer signals across millions of accounts.',
'ZoomInfo is the largest B2B contact and intent data platform on the market, listed on NASDAQ as ZI since 2020 with a coverage claim of more than 300 million professional contacts and over 100 million companies. The platform stitches together direct-dial phone numbers, verified email, org charts, technographic data (what tools each company uses), firmographic data, and proprietary intent topics that show which accounts are actively researching specific buying categories. SalesOS surfaces the contact and signal layer to AEs and SDRs, MarketingOS routes intent-qualified accounts into automation, OperationsOS pushes enriched data into Salesforce or HubSpot in real time, and Engage runs cadence sequences on top. The big tradeoffs are price (annual contracts only, no public pricing, entry deals run 15,000 to 30,000 USD per year for a small team) and contract lock-in via annual commits with hard renewal terms. Apollo competes on price and freemium access, Cognism on EU GDPR-compliant data, Clearbit (now HubSpot Breeze Intelligence) on enrichment depth. For an enterprise outbound team that needs the deepest dataset plus intent topics under one roof, ZoomInfo stays the category leader in 2026.',
'', 'https://www.zoominfo.com', 'https://www.zoominfo.com',
'paid', false, 1500, 4.4, 8200,
false, false, false,
ARRAY['crm-sales', 'analytics'],
ARRAY['Largest verified B2B contact dataset (300M-plus contacts, 100M-plus companies)',
'Proprietary intent topics signal which accounts are researching buying categories',
'Native real-time sync with Salesforce, HubSpot, Outreach, and Salesloft',
'Org chart and reporting structure data uncommon in alternatives',
'Compliance posture with GDPR and CCPA documented at the dataset level'],
ARRAY['No public pricing, sales-led only, annual contracts run 15k to 30k USD entry',
'Annual lock-in with hard renewal terms vs Apollo monthly freemium',
'Data quality on long-tail SMB accounts weaker than mid-market and enterprise',
'Interface dense and steep learning curve vs lighter weight alternatives',
'EU contact coverage smaller than Cognism on GDPR-native records'],
ARRAY['Enterprise outbound sales prospecting with intent-qualified accounts',
'Account based marketing targeting and journey orchestration',
'Sales territory planning with org chart and firmographic data',
'CRM data hygiene and contact record enrichment',
'Buyer signal monitoring for renewals and competitive displacement'],
ARRAY['salesforce', 'hubspot', 'slack', 'microsoft-365', 'gmail', 'linkedin'],
'2026-06-13 00:00:00+00'),

-- 3. Marketo Engage - Adobe enterprise marketing automation head-term, peer-double for activecampaign S189/hubspot S139/mailchimp S164/klaviyo S141
('marketo', 'Marketo Engage',
'Adobe enterprise marketing automation for B2B lead nurture, scoring, and journey orchestration.',
'Marketo was founded in 2006 by Phil Fernandez, went public in 2013, was taken private by Vista Equity in 2016 for 1.79 billion USD, and was acquired by Adobe in 2018 for 4.75 billion USD where it rebranded as Marketo Engage and joined the Experience Cloud. It is the default enterprise B2B marketing automation platform across mid-market and Fortune 500 marketing teams, designed around email-driven nurture campaigns, lead scoring models, account based marketing journeys, and revenue attribution. The Smart Campaigns workflow builder, lead scoring matrix, dynamic content rules, and integration with Adobe Analytics and Salesforce CRM are the differentiators that keep it in enterprise stacks despite the steep learning curve and high price (Growth tier starts around 1250 USD per month, Standard around 3200, Select and Prime tiers six figures annually). HubSpot competes downmarket on ease of use, Pardot (now Salesforce Marketing Cloud Account Engagement) competes within the Salesforce ecosystem, ActiveCampaign at a tenth of the price for SMB teams. For a B2B enterprise marketing team running multi-touch nurture campaigns at scale with Salesforce as the CRM of record, Marketo Engage remains the category default in 2026.',
'', 'https://business.adobe.com/products/marketo/adobe-marketo', 'https://business.adobe.com/products/marketo/adobe-marketo',
'paid', false, 1250, 4.3, 5400,
false, false, false,
ARRAY['seo-marketing', 'automation'],
ARRAY['Industry default for B2B enterprise marketing automation with Salesforce',
'Smart Campaigns workflow builder handles multi-touch journeys at scale',
'Lead scoring model and account based marketing capabilities mature and battle tested',
'Adobe Experience Cloud integration unlocks attribution back to Analytics',
'Marketo University and certified consultant ecosystem deep for enterprise teams'],
ARRAY['Steep learning curve, typically requires a Marketo admin or agency partner',
'Pricing starts around 1250 USD per month with annual contracts and Adobe sales cycle',
'Dated UI and slower iteration cadence vs HubSpot or ActiveCampaign',
'Email editor and landing page builder weaker than modern competitors',
'Setup and migration projects commonly take 3 to 6 months for enterprise rollouts'],
ARRAY['Enterprise B2B nurture campaigns with lead scoring and journey orchestration',
'Account based marketing programs tied to Salesforce opportunity stages',
'Multi-touch attribution and revenue cycle modeling for marketing ops',
'Trigger-based engagement programs across email, web, and webinars',
'Compliance-heavy marketing in regulated industries (healthcare, financial services)'],
ARRAY['salesforce', 'slack', 'microsoft-365', 'snowflake', 'segment', 'gmail'],
'2026-06-13 00:00:00+00'),

-- 4. Wistia - B2B video hosting peer-double for loom S167/heygen S159/synthesia S159/descript S141
('wistia', 'Wistia',
'Video hosting and analytics built for marketing teams that need data on every play.',
'Wistia is the video hosting platform that marketing teams choose when YouTube branding, distracting recommended videos, or shallow analytics will not work for the use case. Founded in 2006 in Cambridge Massachusetts and bootstrapped for over a decade before taking growth equity in 2017, Wistia built its product around three differentiators: a custom-branded player with no YouTube logos or recommendations, granular per-second heatmaps showing exactly which moments get rewatched and which get skipped, and lead capture forms (called Turnstile) that embed inside the video to gate the next chapter on email submission. The Soapbox screen recorder, Channels feature for serial video content, Live virtual event hosting, and native integrations with HubSpot, Marketo, Pardot, and Salesforce for play-data attribution round out the platform. Pricing is freemium: Free plan hosts 3 videos, Plus starts at 24 USD per month for 10 videos with light analytics, Pro at 99 USD adds heatmaps and Turnstile, Advanced at 399 USD covers larger libraries and SSO. Vidyard competes on sales team use cases (personal video recording at scale), Vimeo on creator and event hosting, Loom on async screen recording. For a marketing team where each play needs to drive a measurable next step, Wistia stays the cleanest pick in 2026.',
'', 'https://wistia.com', 'https://wistia.com',
'freemium', true, 24, 4.5, 1800,
false, false, false,
ARRAY['video-ai', 'seo-marketing'],
ARRAY['Custom branded player with zero YouTube logos or distracting recommendations',
'Per-second heatmaps show which moments get rewatched and which get skipped',
'Turnstile lead capture forms embed inside the video for email gating',
'Native sync with HubSpot, Marketo, Pardot, and Salesforce for play attribution',
'Channels feature turns a library into a Netflix-style series browser'],
ARRAY['Higher per-video pricing than YouTube or Vimeo at comparable storage tiers',
'Free tier capped at 3 videos and 200 GB monthly bandwidth',
'Player customization deep but requires brand and design time investment',
'Live virtual event feature less mature than Vimeo or Restream',
'Sales team use case (personal video at scale) better served by Vidyard'],
ARRAY['Marketing landing page videos with branded player and CTA overlays',
'On-demand webinars and product demos with lead capture gating',
'Customer education and onboarding video libraries',
'Sales-enablement video assets for the marketing site and resource hub',
'Video attribution feeding into HubSpot, Marketo, or Salesforce lead scoring'],
ARRAY['hubspot', 'salesforce', 'slack', 'microsoft-365', 'zapier', 'segment'],
'2026-06-13 00:00:00+00'),

-- 5. GitHub Copilot - code-AI head-term, peer-double for cursor S133/codeium S141/cody S185/copilot-microsoft S141/continue-dev S186/tabnine S181
('github-copilot', 'GitHub Copilot',
'AI code completion from GitHub and OpenAI, the original mainstream code AI since 2021.',
'GitHub Copilot is the original mainstream AI code assistant, launched as a Technical Preview in June 2021 and reaching general availability in June 2022. Built by GitHub in partnership with OpenAI on the Codex model, then upgraded through GPT-3.5, GPT-4, and now multiple frontier models including Claude 3.5 Sonnet and GPT-4o in the model picker, Copilot now spans inline code suggestions, multi-line block completion, Copilot Chat for inline questions and code generation, Copilot Workspace for full task planning with multi-file edits, Copilot for Pull Requests for review summaries and auto-generated descriptions, and Copilot for CLI for terminal command suggestions. IDE support covers VS Code (deepest integration), JetBrains IntelliJ family, Neovim, Visual Studio, and Xcode beta. Pricing: free for verified students, open source maintainers, and teachers via GitHub Education; Individual at 10 USD per month or 100 USD per year; Business at 19 USD per seat per month with admin controls and IP indemnification; Enterprise at 39 USD per seat with policy management and Copilot Chat in github.com. Cursor competes on deeper agentic IDE features in a fork of VS Code, Codeium on a strong free tier, Cody from Sourcegraph on enterprise codebase context, Continue on open source self-hosting. For most developers in 2026, GitHub Copilot is still the default starter pick because of native GitHub integration, IDE breadth, and enterprise IP indemnification.',
'', 'https://github.com/features/copilot', 'https://github.com/features/copilot',
'freemium', true, 10, 4.6, 9800,
false, false, false,
ARRAY['code-ai', 'ai-assistants'],
ARRAY['Original mainstream code AI with the broadest IDE support (VS Code, JetBrains, Neovim, Visual Studio)',
'Model picker now includes Claude 3.5 Sonnet, GPT-4o, and other frontier models',
'Free for verified students, open source maintainers, and teachers via GitHub Education',
'Enterprise tier includes IP indemnification for generated code',
'Copilot Chat and Copilot Workspace handle multi-file edits and PR review summaries'],
ARRAY['Cursor offers deeper agentic IDE workflows on its VS Code fork',
'Codeium and Continue both offer stronger free tiers for solo developers',
'Cody from Sourcegraph indexes the whole codebase more deeply for enterprise context',
'No native self-hosted option, unlike Continue or Tabnine on-premise',
'Code suggestions still occasionally hallucinate APIs or fabricate package names'],
ARRAY['Inline code completion across full-stack development workflows',
'Pair programming with Copilot Chat for explanation, refactor, and bug fixes',
'Pull Request review summaries and auto-generated descriptions',
'CLI command suggestions and shell helper inside the terminal',
'Enterprise rollouts with IP indemnification and policy management on the Business tier'],
ARRAY['github', 'microsoft-365', 'slack', 'jira'],
'2026-06-13 00:00:00+00')

ON CONFLICT (slug) DO NOTHING;

-- Post-INSERT verification: confirm 5 new slugs landed
SELECT slug, name, rating, review_count, pricing_type, pricing_starting_price
FROM tools
WHERE slug IN ('dall-e-3', 'zoominfo', 'marketo', 'wistia', 'github-copilot')
ORDER BY slug;
