-- tools-batch-22.sql
-- 10 new tools: DB 242 → 252
-- AI Coding tools: code assistants, editors, and developer productivity
-- ON CONFLICT (slug) DO NOTHING (idempotent)

INSERT INTO tools (slug, name, tagline, description, logo_url, website_url, affiliate_url, tags, pricing_type, pricing_free_tier, pricing_starting_price, rating, review_count, featured, trending, editor_pick, pros, cons, use_cases)
VALUES

-- 1. Tabnine
('tabnine', 'Tabnine', 'AI code completion for enterprise teams with privacy-first deployment',
'Tabnine is one of the longest-established AI code completion tools, now in its second major generation with substantially improved model quality. The platform supports over 80 programming languages and integrates with VS Code, JetBrains IDEs, Visual Studio, Neovim, and other editors through plugins. What distinguishes Tabnine for enterprise use is its privacy architecture: teams can deploy Tabnine on their own infrastructure or use air-gapped models that never send code to external servers, which matters significantly for organisations with strict IP protection requirements. The AI learns from the team''s own codebase over time, surfacing completions and suggestions informed by internal patterns, naming conventions, and architectural choices specific to the project. Tabnine supports whole-line and full-function completions, a chat interface for code explanation and generation, and context-aware refactoring suggestions. The free tier includes basic completions with limited context length. Individual Pro plans cost $12 per user per month. Enterprise plans with private deployment and admin controls are priced per seat with volume discounts. For teams where code privacy is non-negotiable, Tabnine''s private deployment option is its strongest differentiator against cloud-only competitors.',
'https://www.google.com/s2/favicons?domain=tabnine.com&sz=64',
'https://tabnine.com', 'https://tabnine.com',
ARRAY['code-ai', 'developer-tools', 'productivity'], 'freemium', true, 12.00, 4.4, 6800, false, true, false,
ARRAY['Privacy-first with private cloud and air-gapped deployment options', 'Learns from your codebase for personalised completions', 'Supports 80+ languages and 40+ editors', 'Strong enterprise governance with team-level controls'],
ARRAY['Free tier is more limited than Codeium or GitHub Copilot free tier', 'Chat features less capable than newer entrants at similar price point', 'Private deployment requires IT infrastructure investment'],
ARRAY['Enterprise code completion with IP protection requirements', 'Team-level AI coding with private model deployment', 'Multi-language codebases needing consistent completions across IDEs']),

-- 2. Phind
('phind', 'Phind', 'AI search engine built specifically for developers and technical queries',
'Phind is an AI-powered search engine designed for developers, combining web search with large language model reasoning to surface code examples, documentation, and technical answers. Where general AI chatbots generate answers from training data alone, Phind retrieves current documentation, GitHub repositories, Stack Overflow threads, and technical blogs, then synthesises them into a coherent answer with cited sources. This makes Phind significantly more reliable for rapidly evolving APIs, library-specific questions, and debugging scenarios where outdated training data would produce wrong answers. The interface shows search results alongside the AI answer, letting developers verify sources and drill into original documentation. Phind supports technical queries across all major programming languages, frameworks, and cloud platforms. The free tier uses a mix of models including GPT-4 class responses with rate limits. The Pro plan at $20 per month provides access to Claude 3.5 Sonnet and GPT-4o with higher rate limits and faster responses. Phind''s developer-specific training means search results are filtered for technical relevance rather than general web popularity, making it substantially faster than standard search engines for coding research.',
'https://www.google.com/s2/favicons?domain=phind.com&sz=64',
'https://phind.com', 'https://phind.com',
ARRAY['code-ai', 'research', 'developer-tools'], 'freemium', true, 0.00, 4.5, 3200, false, true, false,
ARRAY['Developer-specific search filters technical noise from general web results', 'Cites sources so answers can be verified against original documentation', 'Current information from live web retrieval, not just training data', 'Free tier is genuinely capable for daily development research'],
ARRAY['Rate limits on free tier for extended sessions', 'Less useful for non-technical queries outside development context', 'Advanced model access requires Pro subscription'],
ARRAY['API and library documentation lookup during development', 'Debugging and error message research with current solutions', 'Framework comparison and architecture decision research']),

-- 3. Blackbox AI
('blackbox-ai', 'Blackbox AI', 'AI coding assistant for code generation, completion, and technical search',
'Blackbox AI is a developer-focused AI assistant offering code generation, autocomplete, and a technical search function built into the coding workflow. The platform integrates with VS Code and browser environments, letting developers generate code from natural language prompts, complete functions, and search for real-time code examples without leaving their editor. Blackbox AI''s search indexes code repositories, documentation, and developer forums specifically, surfacing working code examples rather than general web content. One notable feature is the ability to extract code from videos: the tool can identify and copy code shown in tutorial videos, which saves time when following along with YouTube programming tutorials. The free tier is generous with unlimited code generation requests, making it accessible to students and independent developers who need AI assistance without budget constraints. Paid plans add priority responses, longer context windows, and team features at competitive price points. Blackbox AI has a large user base particularly among early-career developers and bootcamp students who need accessible AI coding help.',
'https://www.google.com/s2/favicons?domain=blackbox.ai&sz=64',
'https://blackbox.ai', 'https://blackbox.ai',
ARRAY['code-ai', 'developer-tools'], 'freemium', true, 0.00, 4.2, 9100, false, false, false,
ARRAY['Unlimited free tier with no daily usage caps on code generation', 'Code extraction from videos is a unique time-saving feature', 'Developer-specific search indexes code repositories and documentation', 'Large active community with accessible pricing'],
ARRAY['Model quality trails Copilot and Cursor for complex completions', 'Interface can feel cluttered compared to editor-native tools', 'Less suitable for enterprise environments with strict data policies'],
ARRAY['Code generation from natural language prompts for common patterns', 'Learning to code with accessible free AI assistance', 'Quick code examples and syntax lookup without leaving the editor']),

-- 4. Continue Dev
('continue-dev', 'Continue', 'Open-source AI code assistant that connects to any LLM inside VS Code and JetBrains',
'Continue is an open-source AI coding assistant that gives developers full control over which language model powers their coding workflow. Rather than locking into a proprietary model, Continue connects to any LLM - Claude, GPT-4, local Ollama models, or any OpenAI-compatible API - through a configuration file. This architecture matters for three reasons: privacy-conscious teams can run fully local models with no data leaving the machine, cost-sensitive teams can use cheaper models for routine completions and expensive models for complex reasoning tasks, and enterprise teams can point Continue at self-hosted models that comply with internal data policies. The editor experience includes inline code completions, a chat panel for multi-turn coding conversations, the ability to highlight code and ask questions in context, and slash commands for common operations. Continue integrates with VS Code and JetBrains IDEs. The tool itself is free and open-source under an Apache 2.0 license. Users pay only for the model API they connect, which can be zero cost when using locally hosted models through Ollama or LM Studio. Continue has a strong developer community and active GitHub repository with regular updates.',
'https://www.google.com/s2/favicons?domain=continue.dev&sz=64',
'https://continue.dev', 'https://continue.dev',
ARRAY['code-ai', 'developer-tools', 'open-source'], 'free', true, 0.00, 4.5, 2400, false, true, false,
ARRAY['Fully open-source with Apache 2.0 license and active community', 'Connects to any LLM including local models for complete privacy', 'Flexible model routing: cheap models for completions, powerful for reasoning', 'No vendor lock-in - switch models without changing your workflow'],
ARRAY['Initial setup requires configuring API keys or local model installation', 'Quality depends entirely on the model you connect - no curated defaults', 'Smaller feature set than commercial alternatives like Cursor'],
ARRAY['Privacy-sensitive development where code cannot leave the machine', 'Teams wanting open-source AI tooling without proprietary dependencies', 'Cost-optimised coding with mix of local and API models']),

-- 5. Cody (Sourcegraph)
('cody', 'Cody', 'AI coding assistant from Sourcegraph with deep codebase context and enterprise search',
'Cody is Sourcegraph''s AI coding assistant, built on top of the company''s code intelligence platform that has indexed billions of lines of code across enterprise engineering organisations. What distinguishes Cody from most AI coding tools is its codebase context engine: rather than working only with the files open in your editor, Cody can retrieve relevant context from across an entire large codebase, finding related functions, interfaces, and patterns that inform better completions and answers. This makes Cody particularly valuable for developers working in large monorepos or complex microservice architectures where relevant code is scattered across hundreds of files. The AI supports completions, chat, and a command system for common coding tasks like generating unit tests, explaining selected code, and suggesting refactors. Cody integrates with VS Code, JetBrains IDEs, and the Sourcegraph web interface. The free tier is available for individual developers with access to Claude and other models. Enterprise plans include Sourcegraph''s full code search and intelligence platform alongside Cody, making it a comprehensive developer productivity platform for large engineering teams.',
'https://www.google.com/s2/favicons?domain=sourcegraph.com&sz=64',
'https://sourcegraph.com/cody', 'https://sourcegraph.com/cody',
ARRAY['code-ai', 'developer-tools'], 'freemium', true, 0.00, 4.3, 2700, false, false, false,
ARRAY['Codebase-wide context retrieval beyond just the open files', 'Built by Sourcegraph with deep expertise in large-scale code intelligence', 'Free tier includes access to multiple frontier models including Claude', 'Strong in large monorepos and complex enterprise codebases'],
ARRAY['Full enterprise context features require Sourcegraph Enterprise subscription', 'More complex setup than lightweight alternatives for individual developers', 'Less suitable for small single-repo projects where deep context is less valuable'],
ARRAY['AI-assisted development in large enterprise codebases and monorepos', 'Code explanation and refactoring with full repository context', 'Unit test generation and code review assistance for complex systems']),

-- 6. Zed
('zed', 'Zed', 'High-performance AI-native code editor built in Rust for professional developers',
'Zed is a next-generation code editor built from scratch in Rust, designed for performance and collaboration, with AI deeply integrated rather than bolted on. The editor loads and responds faster than Electron-based alternatives like VS Code, which matters for large codebases where editor lag reduces flow. Zed''s AI features include an inline assistant that transforms selected code, a full chat panel powered by Anthropic''s Claude and other models, and context-aware completions. The editor supports real-time collaborative editing - multiple developers can share a session and code together in real time, similar to Google Docs for code, with zero configuration required. Zed is open-source with a free personal tier and a paid Pro plan at $10 per month that includes additional AI credits beyond the free monthly allocation. The editor targets professional developers and teams who prioritise performance and want a modern alternative to VS Code without switching to a fully AI-controlled environment like Cursor. Zed is available on macOS and Linux, with Windows support in development. Extension support is actively growing and the editor is approaching VS Code parity for common language server and debugging workflows.',
'https://www.google.com/s2/favicons?domain=zed.dev&sz=64',
'https://zed.dev', 'https://zed.dev',
ARRAY['code-ai', 'developer-tools'], 'freemium', true, 0.00, 4.6, 4100, true, true, false,
ARRAY['Exceptional editor performance built in Rust - noticeably faster than VS Code', 'Real-time collaborative editing built in with no plugins required', 'Open-source with active development and growing extension ecosystem', 'Claude-powered AI deeply integrated into the editing workflow'],
ARRAY['Windows support still in development - macOS and Linux only currently', 'Extension ecosystem smaller than VS Code - some niche language servers missing', 'Fewer AI automation features than Cursor for agentic coding workflows'],
ARRAY['Professional development where editor performance impacts daily productivity', 'Real-time pair programming and collaborative coding sessions', 'Developers wanting a modern, open-source VS Code alternative with built-in AI']),

-- 7. Supermaven
('supermaven', 'Supermaven', 'Ultra-fast AI code completion with a 1 million token context window',
'Supermaven is an AI code completion tool engineered for speed and context length. The system uses a proprietary architecture that delivers completions faster than other AI coding assistants while supporting a 1 million token context window - large enough to include an entire large codebase as context for more relevant completions. Where other completions tools understand a few files at once, Supermaven can reference hundreds of files when generating suggestions, surfacing completions that reflect patterns from across the project rather than just the immediate code. The tool integrates with VS Code and JetBrains editors through plugins. Supermaven was founded by Jacob Jackson, the original creator of Tabnine, and focuses on code completion rather than building a comprehensive chat-based coding assistant. The free tier includes basic completions with limited context. The Pro plan at $10 per month unlocks the full 1 million token context window and priority model access. Supermaven is particularly popular among developers who find existing completions tools too slow or too narrow in context, producing suggestions that feel disconnected from the broader codebase architecture.',
'https://www.google.com/s2/favicons?domain=supermaven.com&sz=64',
'https://supermaven.com', 'https://supermaven.com',
ARRAY['code-ai', 'developer-tools'], 'freemium', true, 0.00, 4.4, 1500, false, true, false,
ARRAY['1 million token context window for whole-codebase-aware completions', 'Fastest completion latency of major AI code assistants', 'Created by the original founder of Tabnine with deep completion expertise', 'Lightweight plugin - no editor slowdown or heavy resource usage'],
ARRAY['Focused purely on completions - no chat assistant or agentic features', 'Smaller community and ecosystem than GitHub Copilot or Tabnine', 'Full context window requires Pro subscription'],
ARRAY['High-speed code completion for latency-sensitive development workflows', 'Large codebase completion where context across many files improves accuracy', 'Teams who want pure completion quality without the chat-assistant overhead']),

-- 8. Aider
('aider', 'Aider', 'AI pair programmer for terminal-based development with full git integration',
'Aider is an open-source AI pair programming tool that runs in the terminal and integrates directly with git. The workflow is distinct from editor plugins: you start a session in your project directory, add relevant files to the context, describe what you want to change in plain English, and Aider applies the changes as git commits with descriptive messages. This approach keeps every AI-generated change tracked in version history, making it easy to review, revert, or understand what was changed and why. Aider supports Claude, GPT-4, Gemini, and many other models through API, and works with any codebase in any language. It is particularly strong at multi-file refactoring tasks where changes need to be consistent across many files simultaneously - Aider maps dependencies and applies coordinated changes rather than requiring the developer to edit each file individually. Aider benchmarks highly on coding tasks compared to other AI coding tools and has an active open-source community contributing improvements. The tool itself is free under an Apache 2.0 license. API costs for the connected LLM apply separately, with Claude typically being the recommended model for complex tasks.',
'https://www.google.com/s2/favicons?domain=aider.chat&sz=64',
'https://aider.chat', 'https://aider.chat',
ARRAY['code-ai', 'developer-tools', 'open-source'], 'free', true, 0.00, 4.5, 2900, false, true, false,
ARRAY['Full git integration - every AI change is a reviewable, revertable commit', 'Strong at multi-file refactoring with cross-file dependency awareness', 'Open-source with Apache 2.0 license and very active community', 'Benchmarks among the highest of any AI coding tool on coding tasks'],
ARRAY['Terminal-based workflow is a barrier for developers accustomed to editor UI', 'API costs for LLM backend can add up on complex refactoring tasks', 'Less intuitive for simple one-off completions where an editor plugin is faster'],
ARRAY['Multi-file refactoring with coordinated changes across the codebase', 'Terminal-native development workflows with git-first version control', 'Complex code changes where full commit history is important for audit trails']),

-- 9. CodeGPT
('codegpt', 'CodeGPT', 'AI coding assistant for VS Code and JetBrains connecting to 30+ AI models',
'CodeGPT is an AI coding assistant extension for VS Code and JetBrains that gives developers a single interface to connect and switch between multiple AI models. Rather than committing to one model provider, CodeGPT supports 30+ models including OpenAI, Anthropic, Google, Mistral, Cohere, and local models through Ollama, letting developers choose the best model for each task. The extension includes a chat panel for multi-turn conversations about code, inline code generation, explanation of selected code, unit test generation, and documentation writing. CodeGPT Agents can perform more complex multi-step tasks like creating new features, refactoring modules, and generating test suites with minimal prompting. The free tier includes limited credits monthly. CodeGPT Plus plans start at $9.99 per month for expanded credits and additional model access. CodeGPT has a large user base with over 2 million VS Code extension installs, making it one of the more widely adopted multi-model coding assistants available. It is particularly popular among developers who want to experiment with different models without installing separate extensions for each provider.',
'https://www.google.com/s2/favicons?domain=codegpt.co&sz=64',
'https://codegpt.co', 'https://codegpt.co',
ARRAY['code-ai', 'developer-tools'], 'freemium', true, 0.00, 4.2, 7300, false, false, false,
ARRAY['Connects to 30+ AI models through a single VS Code extension', 'Supports local models via Ollama for offline and private development', 'Large install base with 2 million+ VS Code users', 'CodeGPT Agents handle multi-step coding tasks autonomously'],
ARRAY['Free tier credit limits are modest compared to competitors', 'Jack-of-all-models approach means less optimisation than purpose-built tools', 'Interface complexity can overwhelm developers who just want simple completions'],
ARRAY['Multi-model experimentation to find the best AI for your specific stack', 'Local model usage for offline development or privacy requirements', 'VS Code users wanting a single extension for multiple AI providers']),

-- 10. Pieces for Developers
('pieces-for-developers', 'Pieces for Developers', 'AI-powered developer productivity platform for saving, searching, and reusing code snippets',
'Pieces for Developers is an AI-powered productivity layer for developers, focused on capturing, organising, and reusing code snippets and developer context across the entire workflow. The core workflow: when you find a useful code snippet, Pieces captures it with full context - the language, source, related files, tags, and the conversation you were having when you found it. The AI then makes this library searchable by natural language, code similarity, or contextual clues, so finding the right snippet later takes seconds rather than searching through browser bookmarks or code comments. Pieces runs locally on the device with an on-device AI model, meaning your code and snippets never leave the machine. The tool integrates with VS Code, JetBrains, Visual Studio, Chrome, and other developer tools through plugins. Beyond snippet management, Pieces includes a long-term memory feature that tracks developer context across sessions, an AI chat assistant powered by local and cloud models, and workflow activity tracking. The personal free tier is available indefinitely with local storage. Team plans for shared snippet libraries and cloud sync require paid subscriptions.',
'https://www.google.com/s2/favicons?domain=pieces.app&sz=64',
'https://pieces.app', 'https://pieces.app',
ARRAY['code-ai', 'developer-tools', 'productivity'], 'freemium', true, 0.00, 4.3, 2100, false, false, false,
ARRAY['On-device AI with no code ever sent to external servers', 'Captures full context with snippets - source, language, and related conversation', 'Natural language search across your personal snippet library', 'Integrates with VS Code, JetBrains, Chrome, and other developer tools'],
ARRAY['Niche use case - most developers manage snippets with simpler solutions', 'On-device AI requires reasonable hardware for good performance', 'Team collaboration and cloud sync require paid subscription'],
ARRAY['Building a personal library of reusable code patterns across projects', 'Privacy-first development where all context stays on the local machine', 'Developer workflows requiring fast retrieval of past solutions and code examples'])

ON CONFLICT (slug) DO NOTHING;
