-- tools-batch-48.sql
-- 10 AI UX Research tools
-- All slugs verified NOT present in any prior tools-batch file
-- Run after compare-batch-47.sql

INSERT INTO tools (slug, name, tagline, description, logo_url, website_url, affiliate_url, tags, pricing_type, pricing_free_tier, pricing_starting_price, rating, review_count, featured, trending, editor_pick, pros, cons, use_cases)
VALUES

('dovetail',
 'Dovetail',
 'AI-powered research repository that synthesises customer insights from interviews, surveys, and support data',
 'Dovetail is a user research repository and analysis platform that helps product and design teams make sense of qualitative data at scale. Teams upload interview recordings, survey responses, support tickets, NPS comments, and sales call transcripts, and Dovetail AI automatically tags themes, groups insights by pattern, and surfaces the most frequently mentioned issues across all data sources. The core problem Dovetail solves is research fragmentation: insights from a usability study done in January exist in one researcher''s notes, customer feedback from March is in a spreadsheet, and support trends are in a separate tool - none of it connected. Dovetail creates a searchable repository where all customer intelligence is centralised, tagged, and queryable by any team member. Highlights from interviews can be clipped into short video or audio segments and shared directly in Slack or Notion, making it easy to communicate customer pain points to engineering or executive teams with raw evidence rather than a slide deck summary. The AI sentiment analysis identifies patterns across hundreds of feedback entries that would take a researcher days to process manually. Dovetail integrates with Zoom, Loom, Google Meet, Intercom, Zendesk, and Productboard. It is used by research teams at Spotify, Amplitude, and Atlassian to centralise customer intelligence and make it accessible to the whole product organisation.',
 NULL,
 'https://dovetail.com',
 'https://dovetail.com',
 ARRAY['ux-research', 'user-research', 'product', 'qualitative-research', 'insights'],
 'freemium',
 true,
 0.00,
 4.6, 1840,
 false, false, false,
 ARRAY['AI automatically tags themes across interview transcripts and survey data', 'Centralises all customer intelligence into one searchable repository', 'Video and audio highlight clipping makes insights shareable across the org', 'Integrates with Zoom, Intercom, Zendesk, and Productboard'],
 ARRAY['Most powerful for teams with dedicated researchers generating significant qualitative data', 'Free plan limits project and storage capacity meaningfully', 'Analysis quality depends on tagging consistency across the team'],
 ARRAY['Centralising user interview insights for a product team across multiple studies', 'Building a searchable customer evidence library from support and NPS data', 'Sharing video highlights from customer calls with engineering and leadership teams']),

('maze',
 'Maze',
 'Rapid user testing platform for prototype testing, surveys, and card sorting without a researcher',
 'Maze is a rapid user testing platform that lets product and design teams run unmoderated usability tests, prototype tests, and surveys without scheduling research sessions. Connect a Figma, InVision, or Marvel prototype and Maze distributes it to participants from its built-in panel of over 100,000 testers, or to your own recruited participants via a sharable link. Participants complete tasks on the prototype in their own time, and Maze records where they click, where they get stuck, and how long each task takes. The quantitative output - task success rates, time-on-task, misclick rates, and heatmaps - is available in a results dashboard within hours rather than the days or weeks of scheduling and conducting moderated sessions. Maze also includes tree testing for information architecture validation and card sorting for navigation structure decisions, plus a survey builder for collecting preference data. The AI analysis layer identifies the highest-impact usability issues from task completion patterns and open-text responses, surfacing a prioritised list of problems without requiring the researcher to manually review every session recording. Maze integrates with Figma, Notion, Jira, and Slack for distributing results. It is used by design and product teams at Uber, Brex, and Strava for continuous, lightweight usability validation alongside regular design iteration.',
 NULL,
 'https://maze.co',
 'https://maze.co',
 ARRAY['ux-research', 'usability-testing', 'prototype-testing', 'user-testing', 'product'],
 'freemium',
 true,
 0.00,
 4.5, 2310,
 false, false, false,
 ARRAY['Unmoderated prototype testing delivers results in hours, not weeks', 'Built-in panel of 100,000+ testers removes participant recruitment friction', 'Quantitative task data - success rates, heatmaps, misclick rates - is actionable immediately', 'Integrates directly with Figma for prototype connection without export'],
 ARRAY['Unmoderated format misses the "why" behind user behaviour visible in moderated sessions', 'Panel quality varies by niche demographic and professional segments', 'Tree testing and card sorting features are less advanced than dedicated tools'],
 ARRAY['Rapid prototype validation before a design goes to development', 'Testing information architecture with card sorting across many participants quickly', 'Collecting quantitative usability benchmarks to track design improvements over time']),

('sprig',
 'Sprig',
 'In-product research platform for capturing user feedback and behaviour in real time during the actual experience',
 'Sprig is an in-product user research platform that captures feedback and behavioural signals from users while they are actively using the product - not after the session in a separate survey. The platform embeds lightweight micro-surveys that appear contextually during the product experience - a five-second satisfaction question after completing a task, a feature request prompt after a new feature is used, or a churn exit survey triggered when a user cancels. Because the prompt appears in context, response rates are significantly higher than email surveys and the feedback is more specific and actionable. Sprig also includes session recordings and heatmaps to capture behavioural data alongside attitudinal survey data, allowing teams to see not just what users say but what they actually do. The AI analysis layer processes open-text responses at scale - identifying sentiment trends, clustering feedback themes, and surfacing the top issues mentioned across thousands of responses without manual coding. Sprig integrates with Segment, Amplitude, Mixpanel, Figma, and Slack. Product teams use it for ongoing continuous discovery - running permanent in-product surveys that generate a constant stream of user intelligence rather than one-off research projects. Used by Notion, Loom, Dropbox, and PayPal for always-on user feedback collection integrated directly into the product experience.',
 NULL,
 'https://sprig.com',
 'https://sprig.com',
 ARRAY['ux-research', 'user-feedback', 'product', 'microsurveys', 'session-recording'],
 'freemium',
 true,
 0.00,
 4.4, 890,
 false, false, false,
 ARRAY['In-product surveys capture feedback in context with higher response rates', 'AI analysis processes thousands of open-text responses automatically', 'Combines attitudinal survey data with behavioural session recordings', 'Always-on continuous discovery replaces periodic one-off research projects'],
 ARRAY['Most valuable for products with sufficient user volume to generate meaningful survey data', 'In-product survey frequency must be managed carefully to avoid disrupting the experience', 'Session recording storage limits apply on lower-tier plans'],
 ARRAY['Running contextual micro-surveys after key product actions to capture satisfaction data', 'Identifying why users are churning with triggered exit surveys at cancellation', 'Combining session recordings with in-product feedback to understand usability issues']),

('lyssna',
 'Lyssna',
 'Remote user research platform for preference testing, prototype testing, and interview recruitment',
 'Lyssna is a remote user research platform - formerly known as UsabilityHub - that covers the most common types of rapid, unmoderated research: first-click tests, preference tests, five-second tests, prototype tests, and surveys. First-click tests show a design and record where participants click first, validating whether the primary call to action or navigation is intuitive. Five-second tests expose a design for five seconds and ask what participants remembered, measuring immediate comprehension of a value proposition or page layout. Preference tests show two or three design options and ask which one participants prefer, with the option to collect reasoning. These quick-turn tests are designed to replace opinion-based design debates with evidence in hours rather than days. Lyssna''s participant panel covers over 690,000 people with demographic filtering by age, country, job role, and device type. The platform also includes a live interview module with integrated scheduling, consent management, and session recording, making it possible to run both quick unmoderated tests and deeper moderated interviews from a single tool. AI generates written summaries of test results and highlights the key findings without requiring manual analysis of every response. Lyssna is used by design teams at Canva, Shopify, and Square for rapid preference validation and concept testing early in the design process.',
 NULL,
 'https://lyssna.com',
 'https://lyssna.com',
 ARRAY['ux-research', 'usability-testing', 'preference-testing', 'user-testing', 'prototype-testing'],
 'freemium',
 true,
 0.00,
 4.4, 1120,
 false, false, false,
 ARRAY['First-click, five-second, and preference tests deliver results in hours', 'Panel of 690,000+ participants with demographic targeting', 'Covers both unmoderated tests and moderated live interviews in one platform', 'AI result summaries reduce manual analysis time significantly'],
 ARRAY['Five-second and preference tests provide directional data rather than deep insight', 'Live interview module is less mature than dedicated interview tools like Lookback', 'Free plan limits monthly test responses and panel access'],
 ARRAY['Quick preference testing between two design directions before committing to one', 'Five-second tests validating whether a landing page communicates its value proposition', 'First-click testing to validate navigation structure and CTA placement']),

('lookback',
 'Lookback',
 'Moderated and unmoderated user interview platform for capturing rich qualitative research sessions',
 'Lookback is a user research platform built for conducting and capturing high-quality moderated and unmoderated interview sessions. For moderated research, Lookback provides a video call environment where the researcher watches a participant use a website, app, or prototype in real time, can annotate moments during the session, and sees the participant''s screen, face, and audio simultaneously. The participant experience is seamless - they join via a link without installing software. For unmoderated research, participants complete tasks independently while Lookback records their screen, voice, and camera, with the researcher reviewing sessions asynchronously. The platform is designed for research quality: high-resolution recordings, reliable capture even on slower connections, and a structured tagging and note-taking system for analysis. Lookback supports both remote and in-person research modes, making it flexible for a variety of study formats. The highlight reel feature allows researchers to compile key moments from multiple sessions into a short evidence video that can be shared with stakeholders who were not present. Lookback integrates with research repositories including Dovetail and EnjoyHQ, as well as calendar and scheduling tools for participant management. It is used by UX research teams who conduct high-stakes, high-quality research sessions where the nuance of participant reactions and the depth of moderated probing are essential to the research questions being investigated.',
 NULL,
 'https://lookback.io',
 'https://lookback.io',
 ARRAY['ux-research', 'user-interviews', 'usability-testing', 'qualitative-research', 'session-recording'],
 'paid',
 false,
 25.00,
 4.3, 640,
 false, false, false,
 ARRAY['High-quality session recording with screen, face, and audio captured simultaneously', 'Real-time annotation during moderated sessions highlights key moments instantly', 'Highlight reel creation for sharing evidence with stakeholders who missed the session', 'Works for remote and in-person research without participant software installation'],
 ARRAY['No free plan - requires a paid subscription from $25/month', 'Analysis features are less mature than dedicated repositories like Dovetail', 'Less suitable for high-volume unmoderated testing compared to Maze or Lyssna'],
 ARRAY['Conducting moderated usability sessions with real-time researcher annotation', 'Running unmoderated prototype tests that require face and voice capture', 'Building stakeholder highlight reels from a series of user interview sessions']),

('optimal-workshop',
 'Optimal Workshop',
 'Information architecture research tools for card sorting, tree testing, and first-click testing',
 'Optimal Workshop is a suite of information architecture and navigation research tools used by UX researchers and designers to validate how users understand and navigate information structures. The three core tools cover the most important IA research methods. Treejack tests whether users can find information within a proposed navigation structure by presenting the tree as text without any visual design, isolating the structural logic from design influence. Optimal Sort runs card sorting studies where participants group content items into categories and name those categories, revealing the mental models users bring to a product''s content. Chalkmark runs first-click tests showing a design and asking participants to click where they would go first to complete a task, validating whether the most important actions are findable. A fourth tool, Questions, handles survey research for any research question that does not require behavioural observation. Optimal Workshop has a built-in participant panel for recruiting testers without sourcing participants independently. The analysis tools calculate agreement scores, dendrograms for card sort groupings, and success rates for treejack tasks, providing the statistical output that IA research decisions need to be defensible. Used by research teams at large organisations to validate information architecture before investing in development, and by consultants running IA audits for clients with complex navigation structures.',
 NULL,
 'https://optimalworkshop.com',
 'https://optimalworkshop.com',
 ARRAY['ux-research', 'information-architecture', 'card-sorting', 'tree-testing', 'user-testing'],
 'freemium',
 true,
 0.00,
 4.2, 780,
 false, false, false,
 ARRAY['Gold standard for information architecture research with treejack and card sorting', 'Statistical analysis - agreement scores and dendrograms - supports defensible IA decisions', 'Built-in participant panel removes recruitment friction for standard IA studies', 'Free plan available for individual researchers running small-scale studies'],
 ARRAY['Specialised for IA research - not a general-purpose usability or interview platform', 'Interface feels dated compared to more modern research tools', 'Panel quality is lower for niche B2B or specialist professional demographics'],
 ARRAY['Validating a website navigation redesign before development begins', 'Card sorting to understand how users categorise product features for a new information structure', 'First-click testing to confirm whether navigation labels lead users to the right destination']),

('userlytics',
 'Userlytics',
 'Enterprise remote user testing platform with global panel access and AI video analysis',
 'Userlytics is a remote unmoderated and moderated user research platform used by enterprise product and UX teams for large-scale, high-quality usability testing. The platform provides access to a global panel of over 2 million participants with detailed demographic and professional filtering - age, country, device type, industry, job title, and screener questions that ensure only qualified participants complete the study. Studies can test websites, mobile apps, prototype designs, competitor products, or specific interface flows, with participants completing tasks while their screen, voice, and camera are recorded. Userlytics AI analyses video recordings to detect sentiment, flag moments of confusion or frustration, and generate written summaries of key findings across a participant set without requiring a researcher to watch every video in full. The platform supports both unmoderated studies where participants complete tasks independently and moderated live sessions where a researcher guides the participant in real time. The enterprise plan includes a dedicated customer success manager, custom SLA agreements, and integration with data warehouses and enterprise research stacks. Userlytics is used by enterprise research teams at Adobe, HP, and Visa who need to run large-scale international studies across multiple languages and device types with consistent quality.',
 NULL,
 'https://userlytics.com',
 'https://userlytics.com',
 ARRAY['ux-research', 'usability-testing', 'enterprise', 'user-testing', 'video-analysis'],
 'paid',
 false,
 49.00,
 4.2, 520,
 false, false, false,
 ARRAY['Global panel of 2 million+ participants with detailed demographic filtering', 'AI video analysis detects sentiment and confusion without watching every session', 'Supports both unmoderated and live moderated research in one platform', 'Enterprise plans include dedicated success management and custom SLAs'],
 ARRAY['Higher pricing than simpler tools like Maze or Lyssna for smaller teams', 'Interface has more complexity than necessary for smaller studies', 'AI analysis quality improves significantly with larger participant sets (10+ sessions)'],
 ARRAY['Enterprise usability studies across multiple countries and languages simultaneously', 'Competitive benchmarking research testing your product against competitor interfaces', 'Large-scale accessibility research across different device types and assistive technologies']),

('dscout',
 'Dscout',
 'Mobile diary study and remote research platform for capturing experiences in the real world',
 'Dscout is a remote research platform specialised in diary studies and in-context research - capturing user experiences as they happen in daily life rather than in a controlled lab or research session. Participants use the Dscout mobile app to complete research missions: recording short videos of their experience using a product, taking photos of how they perform a task, or answering questions triggered at specific moments throughout their day. This longitudinal approach captures the genuine, in-context experience that laboratory or session-based research misses - how a product fits into a user''s actual routine, the moments of frustration that occur over days of use rather than a single test session, and the environmental context that shapes how the product is used. Dscout Live is a moderated interview module that enables remote video interviews with participants, complementing diary study data with deeper qualitative probing. The platform includes participant recruitment from its own panel or management of externally recruited participants. Dscout AI analyses video diary entries and open-text responses to identify recurring themes and emotional signals across a participant set. Used by research teams at Google, Airbnb, and Johnson and Johnson for in-context research where the lived experience matters - product design for real-world conditions, service design, and innovation research where usage context is the primary research question.',
 NULL,
 'https://dscout.com',
 'https://dscout.com',
 ARRAY['ux-research', 'diary-studies', 'qualitative-research', 'mobile-research', 'user-testing'],
 'paid',
 false,
 0.00,
 4.3, 410,
 false, false, false,
 ARRAY['Diary study format captures real-world usage context over time, not just lab behaviour', 'Mobile app enables in-context data collection throughout participants'' daily lives', 'Longitudinal research reveals how experiences evolve over days and weeks of use', 'AI analysis identifies themes across video diary entries without manual review of all content'],
 ARRAY['Custom pricing requires a conversation with sales - not self-serve for individual researchers', 'Diary studies take days or weeks to complete - not suitable for rapid research needs', 'Mobile app experience varies across participant devices and connectivity quality'],
 ARRAY['Longitudinal research on how a product integrates into users'' daily routines over time', 'In-context research capturing real-world conditions that affect product usage', 'Innovation research exploring unmet needs in natural life contexts before a product exists']),

('respondent',
 'Respondent',
 'Professional participant recruitment platform for finding qualified B2B and specialist research participants',
 'Respondent is a participant recruitment marketplace that connects UX researchers and product teams with qualified research participants, particularly for hard-to-reach professional and specialist audiences. Most user research participant panels are consumer-focused, making it difficult to recruit software engineers, CFOs, healthcare workers, HR directors, or other professional personas who match a specific buyer profile. Respondent addresses this by maintaining a database of verified professionals who have provided their employment, role, and industry information and who participate in paid research sessions. Researchers post study requirements - target role, industry, company size, seniority, and screening questions - and Respondent matches and schedules participants who meet the criteria. Participants are compensated for their time at rates reflecting their professional value, which attracts higher-quality respondents than low-incentive panels. Studies can be conducted through the researcher''s preferred platform including Zoom, Lookback, or UserZoom, with Respondent handling recruitment, scheduling, incentive payments, and no-show protection. Respondent is used by B2B product teams, enterprise UX researchers, and market research firms that need specific professional profiles for interviews, usability tests, focus groups, and diary studies. The platform also handles participant verification and fraud prevention, which is a persistent challenge for self-serve recruitment at scale.',
 NULL,
 'https://respondent.io',
 'https://respondent.io',
 ARRAY['ux-research', 'participant-recruitment', 'b2b-research', 'user-research', 'qualitative-research'],
 'paid',
 false,
 0.00,
 4.3, 560,
 false, false, false,
 ARRAY['Specialist B2B participant recruitment for hard-to-reach professional personas', 'Verified professional profiles with employment and role validation', 'Handles scheduling, incentive payments, and no-show protection automatically', 'Works with any research platform - researchers use their preferred tools'],
 ARRAY['Per-participant pricing can be high for specialist professional audiences', 'Not suitable for consumer research where standard panels are more cost-effective', 'Study setup and participant matching takes 1 to 3 days - not suitable for same-day research needs'],
 ARRAY['Recruiting software engineers or developers for B2B product usability research', 'Finding healthcare professionals or compliance officers for regulated industry research', 'Sourcing C-suite or director-level participants for enterprise market research interviews']),

('playbook-ux',
 'PlaybookUX',
 'Affordable unmoderated and moderated user testing with built-in participant panel and analysis tools',
 'PlaybookUX is a user testing platform that covers both unmoderated prototype and website tests and moderated live interview sessions at a price point accessible to smaller product and design teams. For unmoderated studies, researchers upload a prototype or URL, define tasks, and participants from the built-in panel complete sessions with screen, voice, and camera recording. For moderated research, PlaybookUX provides a video interview environment with session recording and a live note-taking panel. The built-in participant panel covers a range of demographic and professional profiles with screener questions to filter for specific personas. AI analysis transcribes all session recordings automatically, identifies key moments flagged by participant behaviour, and generates a summary of the most common themes across a set of sessions - reducing the manual analysis work required after data collection. PlaybookUX pricing is designed to be more affordable than enterprise alternatives like UserZoom or Userlytics, with per-session pricing that works for teams running occasional studies rather than continuous research programmes. The platform integrates with Figma for prototype testing and with Slack for sharing highlights. PlaybookUX is positioned as the accessible entry point for product and design teams that want to run research independently without a dedicated researcher or a large research operations budget.',
 NULL,
 'https://playbookux.com',
 'https://playbookux.com',
 ARRAY['ux-research', 'usability-testing', 'user-testing', 'prototype-testing', 'qualitative-research'],
 'paid',
 false,
 49.00,
 4.1, 290,
 false, false, false,
 ARRAY['Covers unmoderated and moderated research in one affordable platform', 'AI transcription and theme analysis reduces post-session manual work', 'Per-session pricing works for teams running occasional studies without a subscription', 'Figma integration for direct prototype testing without export'],
 ARRAY['Panel size and demographic depth is smaller than enterprise alternatives', 'AI analysis quality is good for themes but less nuanced than Dovetail for complex qualitative synthesis', 'Less suitable for large-scale enterprise research with complex participant requirements'],
 ARRAY['Running affordable unmoderated usability tests on a prototype before development handoff', 'Conducting moderated interviews with product team observers without a dedicated research platform', 'Smaller product teams validating design decisions with real users on a limited research budget'])

ON CONFLICT (slug) DO NOTHING;
