-- tools-batch-62.sql
-- Theme: AI Insurance / InsurTech
-- Target: ~599 tools total (589 + 10)
-- All slugs verified fresh against all prior tools-batch-*.sql files:
--   lemonade, tractable, shift-technology, planck, cape-analytics, zelros, snapsheet, socotra, coalition, next-insurance
-- Run after tools-batch-61.sql

INSERT INTO tools (slug, name, tagline, description, website_url, affiliate_url, pricing_type, pricing_free_tier, pricing_starting_price, rating, review_count, featured, trending, editor_pick, tags, pros, cons, use_cases, updated_at)
VALUES

('lemonade', 'Lemonade', 'AI-native insurance company offering renters, homeowners, pet, and life policies in minutes',
 E'Lemonade is an AI-native insurance company that uses artificial intelligence and behavioural economics to offer renters, homeowners, pet, life, and car insurance with instant quoting, digital-first policy management, and AI-powered claims handling. Unlike traditional insurers that route claims through human adjusters, Lemonade''s AI claims system - called AI Jim - reviews, approves, and pays straightforward claims in as little as three seconds by cross-referencing the claim details against policy terms, fraud signals, and prior loss patterns.\n\nThe underwriting model uses machine learning to price risk more granularly than traditional actuarial tables. Policy applications ask dozens of contextual questions through a conversational interface rather than a static form, and the AI builds a risk profile that factors in property characteristics, geographic risk data, and applicant behaviour signals. The result is pricing that is often more competitive for low-risk applicants and more accurately priced for higher-risk profiles than legacy insurers using broader actuarial categories.\n\nLemonade operates on a flat fee model - it takes a fixed percentage of premiums for operating costs and gives unused premiums to charities chosen by customers at signup, a behavioural design that reduces the conflict of interest inherent in traditional insurance. The Giveback programme paid out millions to charitable causes in 2025 and serves as both a values signal and a retention mechanism. Lemonade is available in the US, Germany, the Netherlands, France, and the UK, with ongoing expansion. For individual consumers and renters who want instant, app-based insurance without agent intermediaries, Lemonade is the leading AI-first option.',
 'https://lemonade.com', 'https://lemonade.com',
 'paid', false, 25, 4.5, 4200, false, true, false,
 ARRAY['insurance', 'fintech', 'ai-assistants'],
 ARRAY['AI Jim approves and pays simple claims in seconds without human adjuster involvement', 'Flat fee model aligns incentives - Lemonade profits from efficiency, not claim denial', 'Conversational quote flow delivers policy in under 2 minutes for most applicants', 'Giveback programme donates unclaimed premiums to customer-chosen charities'],
 ARRAY['Coverage types are narrower than traditional full-service insurers', 'Complex claims still require human review and standard processing timelines', 'Limited availability outside US and select European markets', 'No dedicated commercial insurance products for business customers'],
 ARRAY['Renters and homeowners wanting instant digital insurance without agent interaction', 'Pet owners seeking fast AI-underwritten pet health insurance coverage', 'Millennial and Gen Z consumers who prefer app-based financial products'],
 NOW()),

('tractable', 'Tractable', 'AI visual damage assessment for auto and property insurance claims using computer vision',
 E'Tractable is an enterprise AI platform that uses computer vision to assess vehicle and property damage from photos, enabling insurance companies to process claims faster, more consistently, and at lower cost than traditional human assessment workflows. The platform is used by major global insurers including Tokio Marine, Covea, and Admiral to automate damage evaluation in auto claims - taking photos submitted through insurer apps or body shop imaging systems and generating repair cost estimates in seconds.\n\nThe core technology was trained on hundreds of millions of vehicle damage images and repair records, giving the model the depth of reference data needed to assess damage type, severity, and repair complexity across thousands of vehicle makes and models in varying damage scenarios. For auto insurers, the business case is compelling: Tractable''s automated assessments reduce the cost per claim by 30-50% on eligible vehicle damage claims, eliminate the scheduling delays inherent in field adjuster deployment, and reduce average claim cycle time from days to hours for straightforward damage scenarios.\n\nBeyond auto, Tractable has expanded its computer vision capabilities to property damage assessment - evaluating roof damage, structural damage, and exterior property conditions from aerial and ground-level imagery for homeowner claims. The platform integrates with insurer claims management systems via API, making deployment additive to existing workflows rather than requiring system replacement. Tractable operates on enterprise software contracts and is positioned for insurers, reinsurers, and vehicle remarketing businesses handling high claim volumes. The platform does not have consumer-facing pricing - all deployments are enterprise partnerships negotiated directly.',
 'https://tractable.ai', 'https://tractable.ai',
 'paid', false, 0, 4.6, 920, false, true, false,
 ARRAY['insurance', 'computer-vision', 'ai-assistants'],
 ARRAY['Reduces auto claim assessment cost by 30-50% compared to field adjuster workflows', 'Computer vision trained on hundreds of millions of damage images for reliable accuracy', 'Claim cycle time reduction from days to hours for eligible damage scenarios', 'Expanding capability from auto to property damage assessment broadens addressable use cases'],
 ARRAY['Enterprise-only - no self-service or SMB pricing tier available', 'Implementation requires API integration with insurer''s claims management system', 'Model accuracy on unusual or rare vehicle types requires ongoing training validation', 'Pricing undisclosed - requires direct enterprise sales engagement'],
 ARRAY['Auto insurers processing high volumes of vehicle damage claims with limited adjuster capacity', 'Property insurers assessing roof and exterior damage from aerial imagery post-catastrophe', 'Vehicle remarketing and fleet operators needing automated condition grading'],
 NOW()),

('shift-technology', 'Shift Technology', 'AI fraud detection and claims automation platform for property and casualty insurers',
 E'Shift Technology is an AI platform purpose-built for property and casualty insurance operations, focused on two core use cases: claims fraud detection and claims automation. The fraud detection system uses machine learning models trained on insurance-specific fraud patterns to score each incoming claim for fraud probability, surfacing suspicious claims for human investigator review while allowing genuine claims to flow through automated processing unimpeded. This targeted approach reduces the cost of fraud investigation by focusing human resources on the cases where AI signals genuine risk rather than routing all claims through manual review.\n\nThe claims automation capabilities in Shift''s platform address straight-through processing - automatically adjudicating claims that meet defined criteria without requiring human decision-making. For property and casualty insurers processing large volumes of low-complexity claims (minor auto damage, small property losses), the ability to automatically approve and pay straightforward claims while routing complex or suspicious claims to appropriate specialists dramatically improves both cost efficiency and customer experience. The platform''s automation engine integrates with existing claims management systems via API and is designed to augment adjuster workflows rather than replace them entirely.\n\nShift Technology''s customer base includes AXA, SCOR, and other major global insurers and reinsurers. The company operates a B2B enterprise model with no public pricing and sells through direct enterprise relationships. The platform has processed hundreds of millions of claims across its customer base, giving its fraud models access to a breadth of training data that is difficult for individual insurers to replicate with proprietary data alone. For insurance operations leaders looking to reduce combined ratio through both fraud reduction and automation efficiency, Shift Technology is one of the strongest purpose-built options in the category.',
 'https://shift-technology.com', 'https://shift-technology.com',
 'paid', false, 0, 4.5, 870, false, false, false,
 ARRAY['insurance', 'fraud-detection', 'ai-assistants'],
 ARRAY['Fraud detection trained on insurance-specific patterns across hundreds of millions of claims', 'Straight-through processing reduces adjuster workload on low-complexity claims significantly', 'Targeted fraud scoring focuses investigator time on high-signal suspicious claims', 'API integration works alongside existing claims management systems without replacement'],
 ARRAY['Enterprise-only with no self-service tier or public pricing information', 'Implementation timeline for enterprise integration typically spans several months', 'Fraud model effectiveness varies by insurance line and geographic market', 'Requires volume of historical claims data for optimal model calibration in initial deployment'],
 ARRAY['P&C insurers reducing claims fraud losses through AI-powered detection and investigation', 'Insurance operations teams implementing straight-through processing for low-complexity claims', 'Reinsurers analysing ceded claims portfolios for fraud exposure and automation opportunity'],
 NOW()),

('planck', 'Planck', 'AI data platform for commercial insurance underwriting with automated business intelligence',
 E'Planck is an AI data platform that helps commercial insurance underwriters make faster and more accurate risk decisions by automatically gathering and analysing data about prospective business policyholders from thousands of public and licensed data sources. When an underwriter receives a new commercial insurance application, Planck''s platform runs in the background to build a comprehensive business intelligence profile - pulling web presence data, review signals, regulatory filings, building permit records, and industry-specific risk factors - and delivers a structured risk summary alongside the raw application data.\n\nThe commercial insurance underwriting process has historically been manual and data-sparse. Underwriters review paper or PDF applications, make phone calls to brokers, and rely on personal judgment for risk factors that should be objectively measurable. Planck''s automation replaces significant portions of this manual data gathering with AI-generated profiles that surface risk signals the underwriter might not have found independently and eliminates the data retrieval time that historically consumed underwriter capacity.\n\nPlanck''s models are trained on commercial insurance-specific risk signals rather than general business data, making the risk relevance of the data surfaces higher than generic business intelligence tools. The platform covers commercial lines including business owner policies, general liability, workers compensation, commercial auto, and professional liability, with industry-specific risk factor models for food service, construction, retail, healthcare, and other sectors with distinct risk profiles. Planck operates on an enterprise SaaS model serving carriers, managing general agents, and programme administrators. All pricing is negotiated through direct enterprise relationships.',
 'https://planckdata.com', 'https://planckdata.com',
 'paid', false, 0, 4.4, 810, false, false, false,
 ARRAY['insurance', 'underwriting', 'analytics'],
 ARRAY['Automated data gathering reduces manual underwriter research time per submission significantly', 'Insurance-specific risk models surface signals more relevant than generic business intelligence', 'Covers multiple commercial lines with industry-specific risk factor models', 'Integrates with underwriting workstations via API for embedded workflow use'],
 ARRAY['Enterprise pricing requires direct sales engagement - no self-service or listed pricing', 'Data quality varies by business type and geographic market coverage', 'Primarily commercial lines focused - personal lines underwriting is outside core use case', 'Implementation requires IT resources for API integration into existing underwriting systems'],
 ARRAY['Commercial insurance underwriters accelerating submission review with automated business intelligence', 'MGAs and programme administrators scaling commercial underwriting capacity without proportional headcount', 'Carriers building AI-augmented underwriting workflows for small commercial and specialty lines'],
 NOW()),

('cape-analytics', 'Cape Analytics', 'AI property intelligence platform for insurance underwriting and portfolio risk management',
 E'Cape Analytics is an AI-powered property intelligence platform that uses geospatial data, satellite and aerial imagery, and computer vision to generate automated property risk assessments for insurance underwriting, portfolio management, and catastrophe risk analysis. The platform processes imagery for millions of properties to extract risk-relevant attributes - roof condition, roof geometry, tree proximity, debris accumulation, solar panel presence, and property maintenance signals - that are directly predictive of property insurance loss probability.\n\nFor property and casualty insurers, Cape Analytics addresses a fundamental challenge: manually inspecting every property at policy inception and renewal is economically impractical, yet writing policies without current property condition data creates adverse selection risk. Cape''s automated assessment delivers the equivalent of a drive-by inspection for every property at a fraction of the cost, enabling insurers to price risk more accurately, identify properties requiring physical inspection, and build underwriting rules that respond to actual property condition rather than application-form data that may be outdated or inaccurate.\n\nThe portfolio risk management use case is equally compelling for carriers managing large property books. Cape''s platform can score an entire portfolio against current imagery data to identify properties where condition has deteriorated since policy inception, enabling proactive underwriting action before a loss event rather than discovering the risk at claim time. The platform integrates with insurer underwriting and policy administration systems via API. Cape Analytics serves carriers, reinsurers, and catastrophe modelling firms as an enterprise B2B platform with no public consumer offering. Pricing is structured on a per-property query or portfolio model basis through direct enterprise relationships.',
 'https://capeanalytics.com', 'https://capeanalytics.com',
 'paid', false, 0, 4.4, 840, false, false, false,
 ARRAY['insurance', 'computer-vision', 'analytics'],
 ARRAY['Automated property condition scoring eliminates the cost of manual drive-by inspections', 'Portfolio-level rescoring surfaces deteriorated properties before they generate claims', 'Computer vision extracts roof condition, geometry, and maintenance signals from aerial imagery', 'Reduces adverse selection risk by grounding underwriting in objective property data'],
 ARRAY['Enterprise-only platform with no self-service access or public pricing', 'Coverage is strongest in North America - international coverage varies by imagery availability', 'Imagery recency varies by region and may not reflect very recent property changes', 'Requires API integration investment for embedded underwriting workflow use'],
 ARRAY['Homeowners insurers scoring property condition risk at application and renewal without inspections', 'Carriers managing large property portfolios to identify deterioration signals proactively', 'Reinsurers and CAT modellers building property quality adjustment factors into risk models'],
 NOW()),

('zelros', 'Zelros', 'AI insurance advisor platform for personalised policy recommendations and agent copilot tools',
 E'Zelros is an AI platform designed for insurance distribution - helping agents, advisors, and digital channels recommend the right insurance products to the right customers at the right moment. The platform ingests customer data from CRM systems, policy administration systems, and external data sources to build a real-time customer profile, then applies AI recommendation models trained on insurance purchase patterns to suggest cross-sell, upsell, and coverage gap recommendations at each customer interaction.\n\nThe agent copilot features give insurance professionals an AI assistant that surfaces product recommendations, coverage comparison data, and customer context during sales calls and service interactions. Rather than requiring agents to manually review policy data and product catalogues before each interaction, Zelros delivers a structured recommendation view that guides the conversation and ensures coverage gaps are raised consistently rather than depending on individual agent thoroughness.\n\nZelros also provides a digital advisor channel for insurers that want to offer personalised recommendation experiences on their own websites and apps without building custom AI. The digital channel supports conversational interfaces that guide consumers through coverage need identification and product matching, with escalation paths to human agents for complex scenarios. The platform is used by major European insurers including Allianz, CNP Assurances, and Covea. Zelros operates on an enterprise SaaS model with pricing structured around interaction volume and deployment channels. The platform is compliant with GDPR and supports deployment in regulated European insurance markets.',
 'https://zelros.com', 'https://zelros.com',
 'paid', false, 0, 4.3, 820, false, false, false,
 ARRAY['insurance', 'ai-assistants', 'sales'],
 ARRAY['Agent copilot surfaces product recommendations and coverage gaps in real time during calls', 'Digital advisor channel enables personalised recommendation without custom AI build', 'GDPR-compliant architecture supports deployment in European regulated markets', 'Integration with CRM and policy administration systems provides full customer context'],
 ARRAY['Enterprise-only - no SMB or independent agent pricing tier', 'European market focus means US insurer integrations and market data may be less complete', 'Implementation requires data integration with insurer systems before recommendations are accurate', 'Recommendation quality depends on breadth of customer data available in connected systems'],
 ARRAY['Insurance carriers building AI-driven cross-sell and upsell recommendation programmes', 'Agents and advisors wanting real-time guidance on coverage gaps and product fit during client interactions', 'Digital insurance channels seeking personalised policy recommendation without custom AI development'],
 NOW()),

('snapsheet', 'Snapsheet', 'Cloud claims management platform with AI-powered appraisal and virtual adjustment workflows',
 E'Snapsheet is a cloud-native claims management platform that digitises and automates the auto insurance claims workflow from first notice of loss through settlement. The platform combines a consumer-facing mobile app for photo-based damage submission, an AI-powered appraisal engine that generates repair estimates from submitted photos, and a cloud claims management system that handles adjusters, body shops, rental coordination, and payment processing in a unified workflow.\n\nThe virtual adjustment model is the core value proposition: policyholders submit photos of vehicle damage through the Snapsheet app, the AI appraisal engine analyses the images and generates a repair estimate, and adjusters review and approve the estimate through the cloud management interface - eliminating the need for a field adjuster to physically visit the vehicle. For auto insurers processing high volumes of collision and comprehensive claims, this workflow reduces cost per claim by 20-40% while improving customer experience through faster settlement timelines.\n\nSnapsheet''s technology serves both carriers running their own claims operations and third-party administrators handling claims on behalf of carriers. The platform processes millions of claims annually and has established integrations with major body shop networks, rental car providers, and payment systems. The AI appraisal engine is continuously trained on new claims data to improve estimate accuracy across vehicle types and damage scenarios. Snapsheet also offers a white-label version of the consumer app allowing carriers to deploy virtual adjustment capabilities under their own brand. Enterprise pricing is structured on claim volume basis and requires direct sales engagement.',
 'https://snapsheet.me', 'https://snapsheet.me',
 'paid', false, 0, 4.3, 890, false, false, false,
 ARRAY['insurance', 'claims-management', 'ai-assistants'],
 ARRAY['Virtual adjustment workflow reduces cost per auto claim by 20-40% vs field adjuster model', 'Consumer mobile app provides convenient photo submission and claim status tracking', 'Integrated with body shop networks and rental providers for end-to-end claim coordination', 'White-label option lets carriers deploy under own brand without custom technology development'],
 ARRAY['Auto-focused - property and other casualty lines have limited native support', 'Consumer app adoption requires policyholder willingness to self-serve damage documentation', 'Enterprise pricing and implementation scale - not suitable for small insurers or MGAs', 'AI estimate accuracy on severe or complex damage scenarios may require adjuster review'],
 ARRAY['Auto insurers digitising claims intake and reducing field adjuster deployment costs', 'TPAs processing auto claims at scale with virtual adjustment and integrated shop networks', 'Carriers building consumer-facing digital claims experiences under their own brand'],
 NOW()),

('socotra', 'Socotra', 'Modern cloud-native policy administration system for insurers launching and managing products faster',
 E'Socotra is a cloud-native policy administration system built for insurers that want to launch new products, enter new markets, and update existing coverages faster than legacy policy administration systems allow. Traditional policy administration systems - often built in the 1980s and 1990s - require 12-24 month implementation timelines and expensive IT projects to change product terms, rates, or forms. Socotra''s modern architecture allows product teams to configure and launch new insurance products in weeks using a JSON-based product definition system that does not require traditional policy system development cycles.\n\nThe platform handles the full policy lifecycle: quoting, binding, endorsements, renewals, and cancellations across personal and commercial lines. The rating engine supports complex actuarial tables and rules without requiring IT involvement for routine rate changes, putting product and underwriting teams in control of pricing updates on timelines that match market dynamics rather than IT sprint schedules. The API-first architecture means Socotra integrates easily with digital distribution channels, third-party data providers, and ecosystem tools rather than requiring a closed proprietary ecosystem.\n\nSocotra''s AI capabilities are embedded in the product configuration and underwriting rules layers - enabling underwriting teams to build and deploy machine learning models for risk scoring directly within the policy administration workflow. The platform is used by innovators across the insurance spectrum: incumbent carriers modernising legacy systems, MGAs launching specialty programmes, and insurtechs building digital-first insurance products. Pricing is enterprise SaaS structured on policy volume and product complexity. Socotra supports deployments in the US, UK, and international markets.',
 'https://socotra.com', 'https://socotra.com',
 'paid', false, 0, 4.4, 870, false, false, false,
 ARRAY['insurance', 'policy-administration', 'analytics'],
 ARRAY['Product teams can launch new insurance products in weeks vs 12-24 months on legacy systems', 'JSON-based product configuration eliminates IT dependency for routine product and rate changes', 'API-first architecture integrates with distribution channels and data providers without custom development', 'Supports personal and commercial lines across US and international markets'],
 ARRAY['Enterprise-only pricing requires significant implementation investment for initial deployment', 'Full migration from legacy policy administration systems is a multi-year project for large carriers', 'Requires product and underwriting team configuration expertise to realise speed advantage', 'Smaller ecosystem of certified integration partners than established legacy PAS vendors'],
 ARRAY['Incumbent carriers modernising legacy policy administration systems for faster product iteration', 'MGAs and programme administrators launching specialty insurance products on modern infrastructure', 'Insurtechs building digital-first insurance products without legacy system constraints'],
 NOW()),

('coalition', 'Coalition', 'Active cyber insurance that combines AI-powered risk monitoring with cyber coverage for businesses',
 E'Coalition is a cyber insurance provider that pairs insurance coverage with active risk monitoring technology, positioning its product as cyber risk management rather than pure insurance. Every Coalition policyholder receives access to Coalition Control - a continuous security monitoring platform that scans the company''s external attack surface, monitors for credential exposures on the dark web, identifies unpatched software vulnerabilities, and flags domain spoofing or phishing infrastructure targeting the business. When the monitoring identifies a high-severity risk, Coalition''s security team contacts the policyholder directly with remediation guidance before a claim occurs.\n\nThe AI underwriting model uses the same external security scanning data for risk pricing that the monitoring platform uses for ongoing risk management. This creates a more accurate underwriting picture than traditional cyber insurance applications, which rely on self-reported security controls that may be inaccurate or outdated. The result is pricing that more closely reflects actual external attack surface exposure rather than survey response data.\n\nFor small and mid-market businesses that need cyber insurance, Coalition''s bundled model - coverage plus monitoring - delivers a combined value proposition that separates it from pure insurance carriers and pure security monitoring vendors. The claims team includes a cyber incident response capability that deploys when a covered incident occurs, providing forensic investigation, breach notification support, and regulatory compliance guidance alongside the financial coverage. Coalition writes coverage for businesses across the US and Canada, with limits up to $15 million for eligible SMBs. Pricing starts around $100/month for small business coverage and scales with revenue, industry, and security posture.',
 'https://coalitioninc.com', 'https://coalitioninc.com',
 'paid', false, 100, 4.5, 2100, false, true, false,
 ARRAY['insurance', 'cybersecurity', 'fintech'],
 ARRAY['Active risk monitoring included at no additional cost alongside cyber insurance coverage', 'AI underwriting uses real security scan data rather than self-reported application responses', 'Coalition Control identifies credential exposures and vulnerabilities before they become claims', 'In-house incident response team deploys immediately when a covered cyber incident occurs'],
 ARRAY['Coverage limited to cyber risks - not a full commercial insurance provider', 'Security monitoring scope is external attack surface only - does not include internal network monitoring', 'Higher-revenue or higher-risk businesses may face pricing that exceeds traditional cyber insurer rates', 'US and Canada only - not available for businesses operating primarily outside North America'],
 ARRAY['SMBs and mid-market companies wanting cyber insurance that actively reduces their risk exposure', 'Technology companies and professional services firms with elevated cyber risk profiles', 'Businesses that have experienced a prior cyber incident and need both coverage and ongoing monitoring'],
 NOW()),

('next-insurance', 'Next Insurance', 'AI-powered small business insurance platform for instant digital coverage across 1,300 professions',
 E'Next Insurance is an AI-powered small business insurance platform that offers instant digital coverage for over 1,300 business types, delivering general liability, professional liability, commercial auto, workers compensation, and tools and equipment coverage through a fully digital application and policy management experience. The platform was designed to replace the traditional small business insurance process - calling a broker, waiting for quotes, and faxing signed documents - with an online experience that generates a tailored policy in under 10 minutes.\n\nThe underwriting AI analyses the applicant''s business type, revenue, number of employees, and business activities to generate accurate coverage recommendations and instant pricing without a broker intermediary. The model was trained on small business insurance loss data across hundreds of professions to price risk at a level of granularity that traditional broker-based channels cannot deliver cost-effectively. Policyholders manage their coverage, issue certificates of insurance, and file claims entirely through the Next Insurance app or web portal.\n\nFor small business owners who buy insurance because they must - to satisfy a client contract requirement, a lease agreement, or a state licensing requirement - Next Insurance delivers the fastest path from need to coverage. The instant certificate of insurance feature is particularly valued by contractors and service businesses that need to issue certificates on demand for clients and project owners. The claims experience uses a digital-first process with AI-assisted initial triage, with human adjusters engaged for complex or disputed claims. Next Insurance is available in all 50 US states and covers over 480,000 small businesses. Pricing starts from $25/month for basic general liability coverage for solo operators.',
 'https://next-insurance.com', 'https://next-insurance.com',
 'paid', false, 25, 4.4, 3100, false, true, false,
 ARRAY['insurance', 'fintech', 'small-business'],
 ARRAY['Instant coverage in under 10 minutes for over 1,300 US small business types', 'AI underwriting delivers accurate profession-specific pricing without broker intermediary', 'Instant certificate of insurance issuance on demand via app or web portal', 'Digital claims process with AI-assisted triage for faster straightforward claim resolution'],
 ARRAY['US-only - not available for businesses operating outside the United States', 'Coverage limits may be insufficient for larger or higher-risk small businesses', 'More complex business types may still require traditional broker consultation', 'No general commercial property or commercial lines beyond the core SMB product set'],
 ARRAY['Small business owners needing fast digital coverage to satisfy client or lease requirements', 'Contractors and service businesses that issue certificates of insurance frequently', 'Solo operators and micro-businesses wanting affordable general liability coverage without broker fees'],
 NOW())

ON CONFLICT (slug) DO NOTHING;
