-- tools-batch-45.sql
-- 10 AI Meeting Intelligence & Transcription tools
-- All slugs verified NOT present in any prior tools-batch file
-- Run after compare-batch-44.sql

INSERT INTO tools (slug, name, tagline, description, logo_url, website_url, affiliate_url, tags, pricing_type, pricing_free_tier, pricing_starting_price, rating, review_count, featured, trending, editor_pick, pros, cons, use_cases)
VALUES

('grain',
 'Grain',
 'AI meeting recorder that clips, highlights, and shares key moments from video calls',
 'Grain is an AI meeting recorder that focuses on making insights from video calls shareable and actionable, not just stored. During a meeting, Grain automatically transcribes and records the conversation. After the meeting, AI identifies key moments, generates a summary, and lets users clip specific segments into short video highlights that can be shared directly in Slack, Notion, or via link. Sales teams use Grain to clip customer objections, product managers use it to capture user research insights, and managers use it to share performance feedback without requiring everyone to watch the full recording. The workflow is closer to video editing than traditional note-taking - individual moments are treated as standalone content worth sharing, not just timestamps in a long transcript. Grain integrates with Salesforce and HubSpot, automatically syncing call summaries and key moments to contact and deal records. The free plan allows unlimited recordings with a 10-hour storage limit.',
 NULL,
 'https://grain.com',
 'https://grain.com',
 ARRAY['meeting-intelligence', 'transcription', 'video', 'sales-enablement'],
 'freemium',
 true,
 0.00,
 4.5, 920,
 false, false, false,
 ARRAY['Video clip sharing makes insights actionable rather than just stored', 'CRM sync pushes key moments directly to Salesforce and HubSpot records', 'Free plan allows unlimited recordings with generous storage', 'Excellent for sharing user research clips with product teams'],
 ARRAY['Less suitable as a full conversation intelligence platform like Gong', 'Clip-first workflow requires more active curation than auto-summary tools', 'Storage limits on lower plans can fill quickly for heavy recording users'],
 ARRAY['Sales call coaching and key moment sharing', 'User research session highlight reels', 'Customer insight library for product teams']),

('read-ai',
 'Read AI',
 'AI meeting copilot with real-time summaries, engagement scores, and action items',
 'Read AI is an AI meeting assistant that analyses meetings in real time, producing summaries, action items, and engagement metrics as the conversation unfolds. Unlike tools that only process recordings after a meeting ends, Read AI provides a live summary and action item list that updates throughout the call, so participants can confirm shared understanding before disconnecting. The engagement scoring feature analyses speaking time, sentiment, and participation patterns to give meeting organisers visibility into which meetings are draining versus energising their teams. Read AI works across Zoom, Google Meet, and Microsoft Teams without requiring a bot to join the call - it processes audio directly. The reports include a meeting score, executive summary, questions asked, decisions made, and a full transcript. For leadership teams running many back-to-back meetings, Read AI is one of the few tools that gives data on whether meetings are actually productive rather than just captured.',
 NULL,
 'https://read.ai',
 'https://read.ai',
 ARRAY['meeting-intelligence', 'transcription', 'productivity', 'ai-assistant'],
 'freemium',
 true,
 0.00,
 4.4, 1480,
 false, false, false,
 ARRAY['Real-time summaries update during the meeting not just after', 'Engagement scoring surfaces which meetings are productive versus draining', 'Works without a bot joining the call on Zoom and Google Meet', 'Covers speaking time, sentiment, and participation analytics'],
 ARRAY['Engagement scoring can feel invasive in some team cultures', 'Free plan limits the number of meetings per month', 'Less focused on sales workflow than Gong or Chorus'],
 ARRAY['Executive and leadership team meeting intelligence', 'One-on-one meeting productivity tracking', 'Team engagement and burnout monitoring']),

('jamie',
 'Jamie',
 'Privacy-first AI meeting assistant that takes notes without joining the call',
 'Jamie is an AI meeting notetaker designed for privacy-conscious users and teams in regulated industries. Unlike most AI meeting tools that require a bot to join the call, Jamie runs locally on the user''s device and processes audio without sending the raw meeting audio to a cloud server. The app listens to the system audio, transcribes in real time, and generates a structured summary with action items, decisions, and key topics organised by section. Jamie supports over 15 languages and produces summaries that maintain the structure of the conversation rather than flattening everything into bullet points. Because Jamie does not join the meeting as a participant, other attendees are never notified that AI is transcribing - useful for external client meetings, interviews, and one-on-ones where adding a bot would feel intrusive. The free plan allows 10 meetings per month with full feature access.',
 NULL,
 'https://jamie.ai',
 'https://jamie.ai',
 ARRAY['meeting-intelligence', 'transcription', 'privacy', 'productivity'],
 'freemium',
 true,
 0.00,
 4.3, 640,
 false, false, false,
 ARRAY['No bot joins the call - invisible to other meeting participants', 'Local audio processing for privacy-sensitive meetings', 'Structured summaries organise notes by section and topic', 'Supports 15+ languages for international teams'],
 ARRAY['Requires the user to run the desktop app rather than a cloud-native setup', 'Less suitable for teams that want shared meeting recordings', 'Free plan limited to 10 meetings per month'],
 ARRAY['Client-facing meetings where a bot would seem intrusive', 'Regulated industries with audio data privacy requirements', 'One-on-one performance conversations and interviews']),

('sembly-ai',
 'Sembly AI',
 'AI team assistant that attends meetings and identifies risks, decisions, and tasks',
 'Sembly AI positions itself as a team-level meeting assistant rather than just a personal notetaker. When Sembly attends a meeting, it produces a transcript, summary, and action items - standard for the category - but also applies AI analysis to identify risks mentioned in the conversation, decisions that were made, and questions that were raised but not answered. The Smart Summaries feature organises meeting output by type of content rather than chronologically, so the reader can jump directly to the decisions section, the action items, or the open questions without reading through the whole meeting narrative. Sembly integrates with Jira, Asana, Trello, and Linear for direct task creation from meeting action items. The platform supports 48 languages and works across Zoom, Google Meet, Microsoft Teams, and Webex. Team workspaces let managers see summaries from all team meetings in one view, useful for staying across multiple projects without attending every standup.',
 NULL,
 'https://sembly.ai',
 'https://sembly.ai',
 ARRAY['meeting-intelligence', 'transcription', 'team-productivity', 'project-management'],
 'freemium',
 true,
 0.00,
 4.2, 780,
 false, false, false,
 ARRAY['Smart Summaries organise output by decision type rather than chronologically', 'Risk and open question identification adds analysis beyond transcription', 'Direct task creation in Jira, Asana, and Linear from action items', 'Team workspace gives managers visibility across all team meetings'],
 ARRAY['Less polished interface than newer competitors', 'Smart Summary quality varies with meeting structure and topic clarity', 'Team plan pricing can be expensive for larger organisations'],
 ARRAY['Project team standup and planning meeting summaries', 'Risk identification in client and vendor meetings', 'Cross-team meeting oversight for managers']),

('meetgeek',
 'MeetGeek',
 'Automatic meeting recorder with AI highlights and team meeting library',
 'MeetGeek is an automatic meeting recorder and AI assistant that builds a searchable library of every meeting a team has. The tool joins video calls automatically based on calendar invitations, records and transcribes the session, and generates an AI summary with action items and highlights. The meeting library becomes a searchable archive: team members can search for a topic across all past meetings and find the relevant moment, rather than trying to remember which call covered what. MeetGeek supports over 30 meeting templates for different meeting types - sales calls, customer discovery, team retrospectives, one-on-ones - each with a customised summary structure that captures the information most relevant to that meeting type. The platform integrates with Notion, Slack, HubSpot, Salesforce, and Zapier for automatic distribution of summaries. MeetGeek is one of the most affordable options in the category with a free plan covering 5 hours of transcription per month.',
 NULL,
 'https://meetgeek.ai',
 'https://meetgeek.ai',
 ARRAY['meeting-intelligence', 'transcription', 'team-productivity', 'knowledge-management'],
 'freemium',
 true,
 0.00,
 4.3, 890,
 false, false, false,
 ARRAY['Searchable meeting library across all past recordings and transcripts', '30+ meeting templates produce structured summaries by meeting type', 'Affordable free plan with 5 hours of transcription per month', 'Strong integrations with Notion, Slack, and CRM platforms'],
 ARRAY['AI summaries less nuanced than premium tools like Otter or Fireflies', 'No real-time transcription during the meeting', 'Template selection requires manual configuration per meeting type'],
 ARRAY['Building a searchable archive of past team meetings', 'Sales discovery and customer call library', 'Team retrospective and planning meeting notes']),

('notta',
 'Notta',
 'Fast AI transcription and meeting notes for voice and video across 104 languages',
 'Notta is an AI transcription and meeting assistant built for international teams and anyone who regularly processes audio or video content in multiple languages. The platform transcribes audio files, video files, and live meetings in 104 languages at up to 10 times the speed of real-time for uploaded recordings. Notta attends meetings as a bot on Zoom, Google Meet, and Microsoft Teams, or can transcribe audio directly from a phone call using the mobile app. The AI summary extracts action items, key topics, and a structured overview from the transcript. Notta''s strength is breadth: it handles podcast episodes, sales calls, lectures, interviews, and internal meetings with equal ease, making it useful for content teams that work across multiple audio formats. The collaborative notes feature lets teams highlight, annotate, and share specific sections of a transcript with colleagues.',
 NULL,
 'https://notta.ai',
 'https://notta.ai',
 ARRAY['transcription', 'meeting-intelligence', 'multilingual', 'productivity'],
 'freemium',
 true,
 0.00,
 4.4, 1260,
 false, false, false,
 ARRAY['104 language support covers the most international teams in the category', 'Handles uploaded audio and video files as well as live meetings', 'Mobile app transcribes phone calls directly', 'Collaborative annotation and highlighting for shared notes'],
 ARRAY['AI summaries are less structured than dedicated meeting intelligence tools', 'Free plan limited to 120 minutes of transcription per month', 'Less useful for conversation intelligence and coaching use cases'],
 ARRAY['International team meeting transcription', 'Podcast and interview content processing', 'Multilingual customer call transcription']),

('tactiq',
 'Tactiq',
 'Real-time meeting transcription with ChatGPT-powered summaries in the browser',
 'Tactiq is a browser extension that adds real-time transcription to Google Meet, Zoom, and Microsoft Teams calls without requiring a bot to join. It captures the live transcript as the conversation unfolds and lets users highlight key moments with a single click during the meeting. After the meeting, Tactiq connects to ChatGPT, Claude, or Gemini to generate customised summaries - users can choose from preset prompts or write their own to extract exactly the output they need from the transcript. This prompt-based approach is more flexible than fixed-template summaries: a product manager can ask for feature requests mentioned, a salesperson can ask for objections raised, and a recruiter can ask for candidate red flags - all from the same transcript. Tactiq syncs completed transcripts to Notion, Google Docs, HubSpot, and Slack automatically.',
 NULL,
 'https://tactiq.io',
 'https://tactiq.io',
 ARRAY['meeting-intelligence', 'transcription', 'ai-assistant', 'productivity'],
 'freemium',
 true,
 0.00,
 4.3, 1540,
 false, false, false,
 ARRAY['No bot joins the call - runs as a Chrome extension invisibly', 'Prompt-based AI summaries let users extract any information from the transcript', 'Connects to ChatGPT, Claude, and Gemini for flexible summary generation', 'One-click highlight capture during the meeting for key moments'],
 ARRAY['Chrome extension only - does not work on Safari or Firefox', 'AI summary quality depends on prompt writing skill', 'Less suitable as a team-wide meeting intelligence platform'],
 ARRAY['Individual meeting notes with custom AI-generated summaries', 'Sales call follow-up with tailored next-step extraction', 'Research interviews with prompt-customised analysis']),

('chorus',
 'Chorus',
 'Enterprise conversation intelligence platform by ZoomInfo for sales coaching',
 'Chorus is a conversation intelligence platform from ZoomInfo that analyses sales calls, demos, and customer meetings at enterprise scale. Every call is automatically recorded, transcribed, and scored against the team''s sales methodology - talk-to-listen ratio, competitor mentions, next steps confirmed, and questions asked. Managers use Chorus to review calls without sitting in on them, identify which reps are executing the playbook, and coach through specific call moments rather than generic feedback. The Deal Intelligence feature tracks which deals have slowing momentum based on call frequency and engagement patterns. Chorus integrates natively with Salesforce, syncing call activity, talk tracks, and deal signals to opportunity records. Because Chorus is part of the ZoomInfo platform, customers that already use ZoomInfo for prospecting data get direct enrichment from call intelligence back into their go-to-market workflows.',
 NULL,
 'https://chorus.ai',
 'https://chorus.ai',
 ARRAY['meeting-intelligence', 'sales-enablement', 'conversation-intelligence', 'enterprise'],
 'paid',
 false,
 0.00,
 4.3, 2180,
 false, false, false,
 ARRAY['Enterprise-grade call scoring against custom sales methodologies', 'Deal Intelligence identifies stalling opportunities before they die', 'Native Salesforce integration syncs call intelligence to deal records', 'ZoomInfo platform integration connects call data with prospecting intelligence'],
 ARRAY['Pricing is enterprise-tier with no self-serve option', 'Requires full ZoomInfo engagement for best value', 'Implementation complexity is higher than lighter meeting tools'],
 ARRAY['Enterprise sales team call coaching and methodology enforcement', 'Deal health monitoring for large opportunity pipelines', 'Sales manager review and rep performance analysis']),

('modjo',
 'Modjo',
 'Revenue intelligence platform that turns sales call insights into team coaching',
 'Modjo is a revenue intelligence and sales conversation platform built for B2B sales teams that want to turn call recordings into systematic coaching. Unlike general meeting tools, Modjo is designed specifically around sales workflows: calls are automatically tagged by deal stage, rep, and topic, managers can leave timestamped comments on specific call moments, and team leaders can build a library of best-call examples for training new reps. The AI analyses calls against sales methodology markers - objection handling, discovery question depth, competitive positioning - and surfaces patterns across the team rather than just individual call metrics. Modjo integrates with HubSpot, Salesforce, Pipedrive, and most European CRM platforms, making it particularly popular with French and European B2B sales teams. The platform positions itself as a coaching tool rather than a surveillance tool, with emphasis on sharing calls that demonstrate good practice alongside calls that need improvement.',
 NULL,
 'https://modjo.ai',
 'https://modjo.ai',
 ARRAY['meeting-intelligence', 'sales-enablement', 'conversation-intelligence', 'coaching'],
 'paid',
 false,
 0.00,
 4.4, 680,
 false, false, false,
 ARRAY['Sales-specific workflow with deal stage tagging and rep-level analytics', 'Team coaching library with best-call examples for new rep onboarding', 'European CRM integrations make it popular with EMEA sales teams', 'Manager comment threads on specific call moments for targeted feedback'],
 ARRAY['No free tier - requires a paid plan from day one', 'Less suitable for non-sales meeting intelligence use cases', 'Smaller user base and community than Gong or Chorus'],
 ARRAY['B2B sales team call coaching and methodology training', 'New sales rep onboarding with best-call library', 'Sales manager team performance review without attending every call']),

('airgram',
 'Airgram',
 'AI meeting assistant with pre-meeting agendas, real-time notes, and follow-up tasks',
 'Airgram is an AI meeting tool that covers the full meeting lifecycle - before, during, and after the call. Before a meeting, Airgram lets participants collaborate on a shared agenda so everyone arrives with aligned expectations. During the meeting, it transcribes in real time and lets participants highlight key moments. After the meeting, AI generates a structured summary with action items, decisions, and discussion points organised by agenda item. This agenda-first approach means Airgram summaries are structured around the meeting''s intended topics rather than following a generic template, producing output that is easier to use for follow-up. Airgram integrates with Google Calendar and Outlook for automatic meeting joining, and with Notion, Slack, and ClickUp for post-meeting task distribution. The collaborative note-taking features make it well suited to teams that want a single shared record of each meeting rather than individual notetakers producing separate versions.',
 NULL,
 'https://airgram.io',
 'https://airgram.io',
 ARRAY['meeting-intelligence', 'transcription', 'productivity', 'team-productivity'],
 'freemium',
 true,
 0.00,
 4.2, 560,
 false, false, false,
 ARRAY['Pre-meeting agenda collaboration aligns expectations before the call starts', 'Summaries organised by agenda item rather than generic bullet points', 'Collaborative real-time notes create a single shared team record', 'Integrates with Notion, Slack, and ClickUp for task distribution'],
 ARRAY['Less sophisticated AI analysis than dedicated conversation intelligence tools', 'Smaller integration ecosystem than Fireflies or Otter', 'Free plan limited to 5 hours of transcription per month'],
 ARRAY['Structured team meetings with pre-built agendas', 'Client project kickoff and status meetings', 'All-hands and team meeting note distribution'])

ON CONFLICT (slug) DO NOTHING;
