-- tools-batch-12.sql: 10 new tools (DB: 143 → 153)
-- Run in Supabase SQL Editor

INSERT INTO tools (slug, name, tagline, description, logo_url, website_url, affiliate_url, pricing_type, pricing_free_tier, pricing_starting_price, tags, rating, review_count, editor_pick, trending, featured, pros, cons, use_cases)
VALUES

(
  'sora',
  'Sora',
  'OpenAI''s AI video generation model that creates realistic videos from text prompts',
  'Sora is OpenAI''s text-to-video model, available to ChatGPT Plus and Pro subscribers. Describe a scene in plain language and Sora generates a high-fidelity video clip up to 20 seconds long - with coherent motion, realistic lighting, and accurate physical behaviour that earlier video AI models could not produce. The model understands complex prompts: multiple characters, specific camera movements, environmental detail, and temporal consistency across the clip.\n\nFor content creators, marketers, and filmmakers, Sora removes the most expensive part of video production - the gap between concept and footage. Generate B-roll, visualise a script, produce a concept video for client approval, or create social content without a camera or crew. Sora is accessed through ChatGPT''s interface, making it the most accessible entry point to high-quality AI video for users already on a ChatGPT subscription.',
  'https://www.google.com/s2/favicons?domain=openai.com&sz=64',
  'https://openai.com/sora',
  'https://openai.com/sora',
  'paid',
  false,
  20,
  ARRAY['video-ai'],
  4.4,
  890,
  false, false, false,
  ARRAY['Highest video quality of any text-to-video model', 'Integrated into ChatGPT - no separate signup', '20-second clips with coherent motion', 'Strong understanding of complex scene descriptions'],
  ARRAY['Requires ChatGPT Plus or Pro subscription', 'No fine-tuning or custom style training', 'Limited control over output vs. Runway or Kling'],
  ARRAY['Generating concept video for client pitches', 'Creating B-roll for marketing campaigns', 'Visualising scripts before full production', 'Social content without a camera or crew']
),

(
  'avoma',
  'Avoma',
  'AI meeting intelligence platform that records, transcribes, and analyses every conversation',
  'Avoma is an AI meeting intelligence platform built for sales teams, customer success managers, and anyone who runs a high volume of structured conversations. It records and transcribes meetings automatically, then uses AI to generate structured notes, identify action items, score conversations against a defined rubric, and surface coaching insights for managers. The notes are shareable, searchable, and can sync directly to Salesforce, HubSpot, or other CRMs.\n\nWhat separates Avoma from simpler transcription tools is its conversation intelligence layer: it tracks talk-to-listen ratios, identifies competitor mentions, flags objection patterns, and surfaces the topics that correlate with deal wins and losses. For revenue teams, this turns every customer conversation into a coaching asset and a data source. The free plan covers basic transcription and notes; paid plans unlock the analytics and CRM sync features that make Avoma genuinely useful at scale.',
  'https://www.google.com/s2/favicons?domain=avoma.com&sz=64',
  'https://avoma.com',
  'https://avoma.com',
  'freemium',
  true,
  19,
  ARRAY['productivity', 'voice-ai'],
  4.5,
  620,
  false, false, false,
  ARRAY['Conversation intelligence beyond basic transcription', 'CRM sync with Salesforce and HubSpot', 'Coaching scorecard for managers', 'Searchable meeting library across the team'],
  ARRAY['Free plan limits transcription hours per month', 'Analytics features require paid plan', 'Overkill for solo users or infrequent meetings'],
  ARRAY['Sales call coaching and deal analysis', 'Customer success handoff documentation', 'Identifying objection patterns across the team', 'Syncing meeting notes to CRM automatically']
),

(
  'instantly-ai',
  'Instantly',
  'AI-powered cold email outreach platform for sales teams and agencies',
  'Instantly is a cold email automation platform designed for sales teams, recruiters, and agencies running high-volume outreach. It connects unlimited email accounts, warms them automatically to maintain deliverability, and manages sending schedules to avoid spam filters. The AI features personalise emails at scale - generating custom first lines, subject lines, and follow-up sequences based on prospect data - so campaigns feel handwritten even when sent to thousands of contacts.\n\nThe platform''s deliverability infrastructure is its core advantage: dedicated IP warming, inbox rotation, and real-time blacklist monitoring keep reply rates high. The campaign analytics show open rates, reply rates, and meeting booked rates by sequence, allowing rapid testing of messaging. For sales-led companies and agencies that rely on outbound email as a primary growth channel, Instantly removes the technical overhead of email infrastructure and lets teams focus on the message.',
  'https://www.google.com/s2/favicons?domain=instantly.ai&sz=64',
  'https://instantly.ai',
  'https://instantly.ai',
  'paid',
  false,
  37,
  ARRAY['sales', 'marketing'],
  4.6,
  1240,
  false, true, false,
  ARRAY['Unlimited email account connections', 'Automated inbox warming for deliverability', 'AI personalisation at scale', 'Strong analytics and A/B testing'],
  ARRAY['No free plan - paid only', 'Learning curve for campaign setup', 'Best for high-volume outbound - overkill for small lists'],
  ARRAY['Cold outbound prospecting at scale', 'Agency client outreach campaigns', 'Recruiting candidate outreach', 'Testing messaging across audience segments']
),

(
  'recraft-ai',
  'Recraft',
  'AI image and vector art generator built for designers and brand teams',
  'Recraft is an AI image generation platform with a specific focus on brand-consistent output and vector art - the two things that general-purpose image generators like Midjourney handle poorly. It generates SVG vector illustrations, brand icons, UI assets, and product mockups from text prompts, with style controls that let teams lock in a consistent visual language across every generated asset. The brand kit feature stores your colour palette, typography, and style preferences so every generated image matches your existing design system.\n\nFor designers, the vector output is the key differentiator: where other tools generate raster images that require manual tracing, Recraft produces native SVG files that scale perfectly and edit cleanly in Figma or Illustrator. For marketing teams, the style consistency means AI-generated content looks like it came from the same designer, not a collection of unrelated AI outputs. Recraft''s free plan is generous; the paid tier unlocks higher resolution outputs and batch generation.',
  'https://www.google.com/s2/favicons?domain=recraft.ai&sz=64',
  'https://recraft.ai',
  'https://recraft.ai',
  'freemium',
  true,
  12,
  ARRAY['image-ai', 'design-ai'],
  4.5,
  740,
  false, true, false,
  ARRAY['Native SVG vector output - unique among AI image tools', 'Brand kit for style consistency', 'Clean Figma and Illustrator compatibility', 'Strong icon and UI asset generation'],
  ARRAY['Less photorealistic than Midjourney', 'Smaller model variety than Stable Diffusion ecosystem', 'Batch generation requires paid plan'],
  ARRAY['Generating brand-consistent illustrations', 'Creating SVG icons and UI assets', 'Marketing visuals with locked style guidelines', 'Rapid concept exploration for brand projects']
),

(
  'hedra',
  'Hedra',
  'AI video platform that animates portraits and creates talking character videos from audio',
  'Hedra creates talking character videos by animating a still portrait image with a voice - either uploaded audio or AI-generated speech. Upload a photo or AI-generated face, provide the audio, and Hedra produces a realistic video of the character speaking with synchronised mouth movements, natural head motion, and appropriate facial expressions. The output quality is significantly higher than earlier lip-sync tools, and the platform handles a range of source image styles from photographs to illustrated avatars.\n\nThe primary use cases are content creation at scale: educators creating engaging lesson videos without on-camera recording, marketers producing multilingual spokesperson content by re-voicing the same avatar, and creators building a consistent digital presence without filming. Hedra''s free plan allows a meaningful number of credits per month, making it accessible for evaluation before committing to paid usage. For teams producing character-based video content regularly, Hedra''s quality-to-effort ratio is the best available.',
  'https://www.google.com/s2/favicons?domain=hedra.com&sz=64',
  'https://hedra.com',
  'https://hedra.com',
  'freemium',
  true,
  8,
  ARRAY['video-ai'],
  4.2,
  410,
  false, false, false,
  ARRAY['High-quality lip sync and facial animation', 'Works with photos and illustrated avatars', 'Multilingual voice support', 'Free plan with meaningful credits'],
  ARRAY['Limited to portrait-based talking head videos', 'Cannot generate full body motion', 'Best results with clean, front-facing source images'],
  ARRAY['Creating spokesperson videos without on-camera recording', 'Multilingual content from a single avatar', 'Educator course videos with talking character', 'Social content with consistent digital persona']
),

(
  'tana',
  'Tana',
  'AI-native note-taking and knowledge management with super tags and AI assistance',
  'Tana is a note-taking and knowledge management tool built around a novel data model: every piece of information is a node that can be tagged, referenced, and queried like a database entry while still reading like a natural note. Super tags are the core concept - they let you define structured templates for recurring note types (meeting notes, book summaries, project briefs) that automatically organise information and make it queryable across your entire knowledge base.\n\nThe AI layer in Tana integrates tightly with this structure: it can extract entities from unstructured notes and tag them automatically, generate summaries, fill out templates from rough input, and surface relevant nodes when you start a new note on a related topic. For knowledge workers, researchers, and people who have hit the limits of Notion''s flexibility, Tana offers a more powerful data model at the cost of a steeper learning curve. The free plan covers individual use; team plans unlock collaboration.',
  'https://www.google.com/s2/favicons?domain=tana.inc&sz=64',
  'https://tana.inc',
  'https://tana.inc',
  'freemium',
  true,
  16,
  ARRAY['productivity'],
  4.4,
  580,
  false, false, false,
  ARRAY['Super tags create a flexible database-document hybrid', 'AI entity extraction from unstructured notes', 'Highly queryable knowledge base', 'Strong for researchers and knowledge workers'],
  ARRAY['Steep learning curve compared to Notion or Obsidian', 'Less polish than mainstream tools', 'Best for users who invest time in setup'],
  ARRAY['Personal knowledge base with structured templates', 'Research note organisation and querying', 'Meeting notes with automatic entity extraction', 'Project and task management with rich context']
),

(
  'pipio',
  'Pipio',
  'AI video studio with photorealistic digital humans and text-to-video generation',
  'Pipio creates professional video content using photorealistic AI-generated presenters - digital humans that deliver scripts with natural speech, realistic facial expressions, and appropriate gestures. Unlike tools that animate existing photos, Pipio generates its own presenter characters, giving teams full control over appearance, style, and demographic without sourcing stock footage or hiring actors. Scripts are input as text and converted to video with a choice of voice and presenter.\n\nThe use cases are clearest in corporate and educational content: onboarding videos, product explainers, training materials, and marketing videos that need a human face without the cost of video production. Pipio''s presenters cover a range of appearances and languages, making it practical for multilingual content at scale. The platform integrates with common workflows - scripts can be imported, output can be exported directly to editing tools, and the API allows programmatic video generation for teams building content pipelines.',
  'https://www.google.com/s2/favicons?domain=pipio.ai&sz=64',
  'https://pipio.ai',
  'https://pipio.ai',
  'paid',
  false,
  25,
  ARRAY['video-ai'],
  4.1,
  320,
  false, false, false,
  ARRAY['Photorealistic AI presenter generation', 'Multilingual script support', 'No sourcing or hiring of on-screen talent', 'API for programmatic video generation'],
  ARRAY['No free plan', 'Presenters can feel less natural than real video', 'Less creative flexibility than Runway or Sora'],
  ARRAY['Corporate training and onboarding videos', 'Multilingual product explainer content', 'Marketing videos without production budget', 'Scalable e-learning content at volume']
),

(
  'hypercontext',
  'Hypercontext',
  'AI meeting management platform for one-on-ones, team meetings, and performance reviews',
  'Hypercontext is an AI-powered meeting management tool focused specifically on the recurring meetings that drive team performance: one-on-ones, team standups, and performance reviews. It provides shared agendas built from templates, AI-generated talking point suggestions based on role and meeting type, and automatic action item tracking across sessions so nothing falls through the cracks between meetings.\n\nThe platform integrates with Slack and Google Calendar to surface the right agenda at the right time and remind participants to prepare. Managers get a longitudinal view of each direct report''s goals, blockers, and progress across all their one-on-one conversations - making performance reviews a summary of the year rather than a reconstruction of it. For engineering managers and team leads running 5-15 recurring meetings per week, Hypercontext removes the preparation overhead and creates a consistent, documented record of every conversation.',
  'https://www.google.com/s2/favicons?domain=hypercontext.com&sz=64',
  'https://hypercontext.com',
  'https://hypercontext.com',
  'freemium',
  true,
  7,
  ARRAY['productivity'],
  4.3,
  390,
  false, false, false,
  ARRAY['Purpose-built for recurring management meetings', 'Longitudinal view of 1:1 conversation history', 'AI agenda suggestions by meeting type and role', 'Slack and Google Calendar integration'],
  ARRAY['Narrower use case than general meeting tools', 'Less useful for external client meetings', 'Advanced features require paid plan'],
  ARRAY['Running structured one-on-one meetings', 'Preparing for quarterly performance reviews', 'Tracking action items across recurring team standups', 'Onboarding new managers with structured templates']
),

(
  'adobe-podcast',
  'Adobe Podcast',
  'AI-powered audio recording and enhancement tool that makes any microphone sound professional',
  'Adobe Podcast (now Adobe Enhance Speech) applies AI audio processing to recordings made on any microphone - removing background noise, room echo, and audio artefacts to produce broadcast-quality results. Upload a recording made on a laptop microphone, a phone, or a consumer headset, and the AI enhancement makes it sound like a professional studio recording. The difference in quality is significant enough to matter for podcast hosts, video creators, online educators, and anyone who records voice content regularly.\n\nThe recording feature captures clean audio directly in the browser, and the transcription and editing tools let creators edit audio by editing text - deleting filler words, restructuring segments, and tightening timing without touching a timeline editor. For podcasters and course creators who are not audio professionals, Adobe Podcast removes the technical barrier between capturing an idea and publishing polished audio. The basic enhance feature is free to use.',
  'https://www.google.com/s2/favicons?domain=adobe.com&sz=64',
  'https://podcast.adobe.com',
  'https://podcast.adobe.com',
  'freemium',
  true,
  0,
  ARRAY['voice-ai'],
  4.5,
  870,
  false, false, false,
  ARRAY['Dramatic audio quality improvement on any microphone', 'Text-based audio editing', 'Browser-based - no software install', 'Free enhance feature is genuinely useful'],
  ARRAY['Requires Adobe account for full features', 'Processing time for longer files', 'Not a full DAW - limited for complex audio production'],
  ARRAY['Enhancing podcast recordings made on consumer hardware', 'Cleaning up course and tutorial audio', 'Improving video voiceover quality', 'Removing background noise from remote interview recordings']
),

(
  'warp',
  'Warp',
  'AI-powered terminal that makes the command line accessible with natural language commands',
  'Warp is a modern terminal that replaces the traditional command-line interface with a collaborative, AI-assisted environment. The core AI feature is natural language command generation: describe what you want to do in plain English and Warp generates the exact shell command - including complex flags, pipes, and subcommands that most developers look up on Stack Overflow. Warp also provides inline error explanations, suggesting what went wrong and how to fix it when commands fail.\n\nThe interface improvements matter too: outputs are grouped into blocks that can be copied, shared, or re-run individually; command history is searchable; and the editing experience is closer to a code editor than a raw terminal. For developers who spend significant time in the terminal, Warp reduces the cognitive overhead of shell scripting and command construction without requiring a switch to a higher-level tool. The free plan is fully functional for individual use; paid plans add team features like shared runbooks.',
  'https://www.google.com/s2/favicons?domain=warp.dev&sz=64',
  'https://warp.dev',
  'https://warp.dev',
  'freemium',
  true,
  0,
  ARRAY['code-ai'],
  4.6,
  1100,
  false, true, false,
  ARRAY['Natural language to shell command generation', 'Inline error explanations and fix suggestions', 'Grouped, searchable command history', 'Modern editor-like interface in the terminal'],
  ARRAY['macOS-first (Linux in beta, Windows not yet available)', 'Some workflows require learning new interface patterns', 'Team features require paid plan'],
  ARRAY['Generating complex shell commands from descriptions', 'Debugging command failures with AI explanation', 'Sharing reproducible terminal workflows', 'Onboarding developers unfamiliar with specific CLI tools']
)

ON CONFLICT (slug) DO NOTHING;
