-- tools-batch-61.sql
-- Theme: AI HR / People Ops
-- Target: ~589 tools total (579 + 10)
-- All slugs verified fresh against all prior tools-batch-*.sql files:
--   lattice, culture-amp, 15five, leapsome, gusto, hibob, paradox-ai, betterup, pyn, peakon
-- Run after tools-batch-60.sql

INSERT INTO tools (slug, name, tagline, description, website_url, affiliate_url, pricing_type, pricing_free_tier, pricing_starting_price, rating, review_count, featured, trending, editor_pick, tags, pros, cons, use_cases, updated_at)
VALUES

('lattice', 'Lattice', 'AI-powered performance management and employee engagement platform for building high-performance teams',
 E'Lattice is a performance management platform used by over 5,000 companies to run structured performance reviews, continuous feedback cycles, goal setting via OKRs, and employee engagement surveys. The AI layer in 2026, called Lattice Intelligence, analyses performance data across the organisation to surface managers who may need coaching, identify employees at flight risk based on engagement and performance signal patterns, and recommend development opportunities tailored to each individual''s career goals and skill gaps.\n\nThe platform covers the full people management cycle: 1-on-1 meeting agendas and note-taking, continuous feedback collection between peers and managers, structured mid-year and annual reviews, and OKR tracking that connects individual goals to company-level objectives. Lattice''s AI-generated review summaries compress the review writing process - managers can review an AI-drafted performance narrative based on feedback received, goals completed, and 1-on-1 notes rather than writing from memory. This addresses one of the primary sources of review quality variability across large organisations.\n\nFor HR teams, Lattice provides the analytics layer to move beyond gut-feel people decisions. The engagement survey tools measure employee sentiment across key drivers - management quality, growth opportunities, recognition, and work-life balance - with benchmarks against similar companies. AI-driven action recommendations suggest what specific interventions correlate with engagement improvements in companies with similar patterns. Lattice integrates with major HRIS platforms including Workday, BambooHR, and Rippling, and with communication tools including Slack and Microsoft Teams for embedded feedback prompts.',
 'https://lattice.com', 'https://lattice.com',
 'paid', false, 11, 4.7, 4200, false, true, false,
 ARRAY['hr-tech', 'performance-management', 'employee-engagement'],
 ARRAY['AI-generated performance review summaries reduce manager writing time significantly', 'Flight risk detection surfaces at-risk employees before they submit resignations', 'OKR tracking connects individual performance to company-level objectives', 'Engagement survey benchmarks compare sentiment against similar companies in real time'],
 ARRAY['Pricing at $11/user/month adds up quickly for large organisations', 'Full value requires consistent manager adoption - tools only work if managers engage', 'Advanced analytics features require higher-tier plans', 'Implementation and configuration takes 4-6 weeks for mid-market deployments'],
 ARRAY['HR teams replacing annual review cycles with continuous performance management', 'People leaders identifying retention risk in high-value employee segments', 'Managers running structured 1-on-1s and development conversations with their teams'],
 NOW()),

('culture-amp', 'Culture Amp', 'Employee experience platform combining engagement surveys, performance management, and people analytics',
 E'Culture Amp is an employee experience platform that originated as an employee survey tool and has evolved into a full people analytics and performance management suite. The platform serves over 6,000 organisations and is particularly strong in the enterprise and mid-market, where its reputation for survey science and benchmarking data - drawn from its global customer base - gives HR leaders confidence in the validity of their people data.\n\nThe AI features in 2026 include AI-generated survey action recommendations that connect engagement driver scores to specific managerial and organisational interventions with evidence of effectiveness drawn from Culture Amp''s aggregate dataset. The natural language survey comment analysis clusters open-ended employee feedback into themes automatically, surfacing the most common sentiment patterns without requiring HR teams to manually read thousands of free-text responses. Performance review tools include AI-assisted feedback analysis that identifies patterns of bias in review language - helping organisations ensure that feedback quality is consistent across demographic groups.\n\nCulture Amp''s differentiation is its dataset. With over 6,000 customer organisations and hundreds of millions of survey responses, the benchmarking data for engagement scores, turnover intent, and culture driver comparisons is the most statistically reliable in the market. When a CHRO at a 500-person tech company wants to know whether their management effectiveness score is above or below the market median for similar companies, Culture Amp provides that answer with genuine statistical confidence. The platform integrates with leading HRIS systems and SSO providers for single sign-on access across enterprise deployments.',
 'https://cultureamp.com', 'https://cultureamp.com',
 'paid', false, 50, 4.6, 3800, false, true, false,
 ARRAY['hr-tech', 'employee-engagement', 'people-analytics'],
 ARRAY['Industry-leading benchmarking database from 6,000+ organisations for reliable comparisons', 'AI comment analysis clusters thousands of open-text responses into actionable themes', 'Bias detection in performance review language helps organisations ensure review fairness', 'Strong survey science foundation distinguishes data quality from less rigorous alternatives'],
 ARRAY['Pricing starts at approximately $50/user/year - premium positioning for mid-market and enterprise', 'Performance management module is less mature than dedicated tools like Lattice', 'Requires strong HR leadership buy-in to drive survey participation rates above 70%', 'Customisation depth for survey templates can require HR team configuration effort'],
 ARRAY['Enterprise HR teams running annual and pulse engagement surveys with benchmarking needs', 'CHROs reporting people analytics and culture metrics to boards and executive teams', 'Organisations working to identify and eliminate bias in performance review processes'],
 NOW()),

('15five', '15Five', 'Continuous performance management platform built around weekly check-ins, OKRs, and manager effectiveness',
 E'15Five is a continuous performance management platform built on the idea that weekly check-ins between managers and employees - taking approximately 15 minutes to write and 5 minutes to read - surface issues early enough to address them before they become retention or performance problems. The platform has expanded from its check-in origins to include structured 1-on-1 meeting management, OKR and goal tracking, engagement pulse surveys, and a Manager Effectiveness Indicator that gives HR teams visibility into which managers are driving high team engagement and performance.\n\nThe AI features in 2026 include Best-Self Review, an AI-assisted performance review process where the AI synthesises check-in responses, OKR progress, and peer feedback into a draft review narrative for manager review and editing. The Predictive Impact Model analyses engagement data to predict which actions - increasing 1-on-1 frequency, recognising specific employees, adjusting workload distribution - have the highest probability of improving engagement scores in specific teams. The High Five recognition module enables peer-to-peer recognition tied to company values.\n\nFor HR and people operations teams that want to invest in manager development as the lever for engagement and retention improvement, 15Five''s manager effectiveness focus is its clearest differentiator from broader platforms. The platform provides managers with direct feedback on how their teams feel about management quality, coaching prompts tied to specific weak areas, and tracking data showing whether interventions are working over time. 15Five integrates with Slack, Microsoft Teams, Workday, BambooHR, and Rippling for embedded check-in prompts in communication tools and HRIS data sync.',
 'https://15five.com', 'https://15five.com',
 'paid', false, 4, 4.5, 2900, false, true, false,
 ARRAY['hr-tech', 'performance-management', 'employee-engagement'],
 ARRAY['Weekly check-in format surfaces team issues early before they become resignation drivers', 'Manager Effectiveness Indicator gives HR visibility into manager quality across the org', 'AI-assisted review synthesis reduces time to write balanced, evidence-based performance reviews', 'Predictive Impact Model identifies which specific actions are most likely to improve engagement'],
 ARRAY['Weekly check-in habit requires manager and employee adoption to deliver value', 'Less feature depth in advanced analytics compared to Culture Amp', 'Goal and OKR tracking is functional but less sophisticated than dedicated OKR tools', 'Smaller benchmarking dataset than Culture Amp for industry comparisons'],
 ARRAY['HR teams building a continuous performance management culture to replace annual reviews', 'People operations leaders wanting visibility into manager effectiveness across the organisation', 'Fast-growing companies where manager quality is the primary driver of retention outcomes'],
 NOW()),

('leapsome', 'Leapsome', 'Intelligent people enablement platform combining performance reviews, learning, and engagement in one system',
 E'Leapsome is a people enablement platform developed in Europe that combines performance management, learning and development, engagement surveys, and compensation planning in a single integrated system. The platform is used by over 1,500 companies globally, with particular strength in European mid-market and enterprise organisations that need GDPR-compliant people data handling alongside strong HR functionality.\n\nThe AI capabilities in 2026 include Leapsome AI Assist, which helps managers write balanced, specific performance reviews by prompting for concrete examples when feedback is vague and flagging language that may be biased or insufficiently evidenced. The learning recommendation engine surfaces development content - internal courses, external resources, and coaching assignments - based on each employee''s goals, skill gaps identified in reviews, and career trajectory within the organisation. The engagement analytics module uses natural language processing to categorise open-ended survey responses and identify the themes driving the highest and lowest engagement scores across different teams.\n\nLeapsome''s integration of compensation planning into the same platform as performance data is a meaningful differentiator for HR leaders who want to connect pay decisions directly to performance evidence rather than managing the calibration process across disconnected spreadsheets and systems. The compensation review module allows managers to see team member performance history, peer benchmarks, and current compensation in a single view during salary review cycles. Leapsome integrates with major HRIS platforms, payroll systems, and communication tools, and provides a developer API for custom integrations in enterprise deployments.',
 'https://leapsome.com', 'https://leapsome.com',
 'paid', false, 8, 4.6, 1800, false, false, false,
 ARRAY['hr-tech', 'performance-management', 'learning-development'],
 ARRAY['Compensation planning integrated with performance data in a single system', 'GDPR-compliant architecture makes it strong for European organisations', 'AI Assist flags vague or potentially biased review language before submission', 'Learning recommendations connect development resources to individual performance data'],
 ARRAY['Smaller market presence than US-headquartered competitors means fewer third-party integrations', 'Full platform value requires adoption across reviews, surveys, and learning - partial use delivers less ROI', 'Pricing at $8/user/month requires enterprise volume commitments for cost-effectiveness', 'Onboarding complexity for the full platform suite is high for small HR teams'],
 ARRAY['European organisations needing GDPR-compliant performance and engagement management', 'HR leaders wanting to connect compensation decisions directly to performance evidence', 'Companies that want performance management, learning, and engagement in a single integrated system'],
 NOW()),

('gusto', 'Gusto', 'AI-powered payroll, benefits, and HR platform built for small and medium businesses',
 E'Gusto is the dominant payroll, benefits, and HR platform for US-based small and medium businesses, used by over 300,000 companies. The platform handles full-cycle payroll processing including federal, state, and local tax compliance, W-2 and 1099 generation, and benefits administration for health insurance, 401(k), HSA, and commuter benefits. Gusto''s people platform layer extends into onboarding automation, time tracking, offer letter generation, and an employee self-service portal.\n\nThe AI features in 2026 include Gusto Assistant, a conversational AI that answers HR and compliance questions in plain language - handling questions about PTO policies, benefits enrollment deadlines, tax withholding, and state-specific compliance requirements that previously required a call to HR or an employment attorney. The AI hiring tools assist with offer letter drafting, compensation benchmarking against Gusto''s aggregate salary data from 300,000+ companies, and onboarding checklist generation for new roles. Automated compliance monitoring alerts administrators to state law changes, upcoming filing deadlines, and required notices.\n\nFor small businesses that cannot afford a dedicated HR team, Gusto serves as the operational backbone of people management - handling the compliance, paperwork, and administrative overhead that previously required either expensive HR consultants or risked compliance gaps. The product is designed for non-HR specialists: founders, office managers, and accountants who need HR infrastructure without needing to become HR experts. Gusto integrates with QuickBooks, Xero, FreshBooks, and major accounting platforms for automatic payroll expense sync.',
 'https://gusto.com', 'https://gusto.com',
 'paid', false, 40, 4.5, 6500, false, false, false,
 ARRAY['hr-tech', 'payroll', 'small-business'],
 ARRAY['Full-cycle payroll with automated federal, state, and local tax compliance', 'Gusto Assistant answers HR and compliance questions in plain language without needing an HR team', 'Compensation benchmarking uses aggregate data from 300,000+ companies for credible salary insights', 'Benefits administration for health, 401(k), and HSA without a dedicated benefits coordinator'],
 ARRAY['Base price of $40/month plus $6/user/month adds up for companies scaling past 20 employees', 'US-only - not suitable for companies with international payroll requirements', 'Benefits administration is limited to US-based plans - no international benefits support', 'Advanced HR analytics are lighter than dedicated performance platforms like Lattice'],
 ARRAY['Small business owners handling payroll and HR compliance without a dedicated HR department', 'Startups setting up their first formal payroll and benefits infrastructure', 'Accountants and bookkeepers managing payroll for multiple small business clients'],
 NOW()),

('hibob', 'HiBob', 'Modern HRIS platform for fast-growing companies with AI-powered people analytics and workforce planning',
 E'HiBob is a modern HRIS platform designed for mid-market companies experiencing rapid growth, providing the people data infrastructure, compliance tools, and analytics that companies need as they scale from 100 to 1,000+ employees. The platform covers core HR functions - employee records, organisational hierarchy, onboarding and offboarding workflows, time and attendance, document management, and compensation data - with a user experience designed to be navigated by employees and managers without HR training.\n\nThe AI capabilities in 2026 include an intelligent people analytics module that combines HR data with performance and engagement signals to surface workforce trends: headcount growth by department versus plan, compensation equity gaps across demographic groups, attrition risk by role and tenure cohort, and promotion trajectory analysis. Bob''s AI-powered org planning tools help HR and finance teams model headcount scenarios - what happens to department cost structure if 15% of the team turns over in Q3, or what the compensation impact is of promoting five engineers to senior levels simultaneously.\n\nHiBob differentiates on employee experience: the platform is designed to feel like a product employees actually want to use rather than a compliance system they are forced to log into. The Club House module creates a social directory and team culture hub. The Shoutouts feature enables peer recognition tied to company values. This consumer-grade UX focus drives adoption rates that HR leaders report are significantly higher than legacy HRIS platforms, which matters because people data is only as good as the participation rate of the organisation filling it in. HiBob integrates with Greenhouse, Lever, Workday, Slack, and over 100 HR and productivity tools.',
 'https://hibob.com', 'https://hibob.com',
 'paid', false, 10, 4.5, 2100, false, false, false,
 ARRAY['hr-tech', 'hris', 'people-analytics'],
 ARRAY['Modern consumer-grade UX drives high employee adoption compared to legacy HRIS platforms', 'Workforce planning and scenario modelling tools for headcount and compensation forecasting', 'Compensation equity analysis surfaces pay gaps across demographic groups proactively', 'Integrates with over 100 HR and productivity tools for a connected people tech stack'],
 ARRAY['Pricing requires a sales call for quotes - not transparent for budget planning without a demo', 'Payroll processing requires third-party integration - Bob is not a payroll system', 'Setup and configuration for a 200-person company typically takes 6-8 weeks', 'Support response times can be slower for smaller customers on lower-tier plans'],
 ARRAY['Fast-growing mid-market companies scaling from 100 to 1,000+ employees who need a modern HRIS', 'HR leaders who want workforce planning and analytics alongside core people data management', 'Companies replacing legacy HRIS systems where low adoption is degrading data quality'],
 NOW()),

('paradox-ai', 'Paradox', 'Conversational AI recruiting assistant that automates candidate screening, scheduling, and onboarding',
 E'Paradox is a conversational AI platform for talent acquisition built around Olivia, an AI recruiting assistant that handles high-volume candidate interactions through chat, text message, and WhatsApp. Olivia automates the most time-consuming steps in the recruiting funnel: answering candidate questions about the role and company, collecting application information through conversation rather than forms, screening candidates against job requirements, scheduling interviews by checking interviewer availability and proposing times, sending reminders and confirmations, and processing post-hire onboarding paperwork.\n\nFor high-volume hiring environments - retail, logistics, manufacturing, hospitality, and healthcare - the impact of automating candidate communication is material. Companies using Paradox report reducing time-to-offer by 60-80% by eliminating the scheduling and communication back-and-forth that previously required recruiter time on every candidate. Olivia operates 24/7, responding to candidate messages within seconds rather than the 2-3 day response lag that characterises manual recruiting pipelines and causes candidate drop-off.\n\nThe 2026 Paradox platform includes career site AI that surfaces relevant open roles to site visitors through conversational interaction, an interview question bank with AI-generated role-specific questions, and post-hire onboarding automation that walks new hires through paperwork, policy acknowledgments, and first-week scheduling through a conversational interface. Paradox integrates with major ATS platforms including Workday, Greenhouse, iCIMS, and SAP SuccessFactors, fitting into existing recruiting workflows as a candidate-facing automation layer rather than replacing the ATS.',
 'https://paradox.ai', 'https://paradox.ai',
 'paid', false, 0, 4.4, 1500, false, false, false,
 ARRAY['hr-tech', 'recruiting', 'ai-assistants'],
 ARRAY['Olivia AI assistant responds to candidates 24/7 - eliminating the lag that causes drop-off', 'Automates scheduling, screening, and paperwork across high-volume hiring workflows', 'Integrates with major ATS platforms as a conversation layer rather than replacing existing tools', 'Conversational onboarding automation reduces new hire paperwork friction significantly'],
 ARRAY['Enterprise pricing requires a custom sales engagement - not suitable for small companies', 'Best ROI in high-volume hourly hiring - less compelling for low-volume professional roles', 'AI screening quality requires careful threshold configuration to avoid inappropriate filtering', 'Heavy implementation effort for initial ATS integration and Olivia configuration'],
 ARRAY['High-volume retail, logistics, and healthcare hiring operations processing 500+ applications monthly', 'Talent acquisition teams using text and WhatsApp to reach hourly and frontline worker candidates', 'Enterprises reducing recruiter time on scheduling and administrative coordination in large hiring pipelines'],
 NOW()),

('betterup', 'BetterUp', 'AI-powered professional coaching and mental fitness platform for enterprise workforce development',
 E'BetterUp is an enterprise professional coaching platform that pairs employees with certified coaches for personalised development sessions delivered remotely. The platform combines one-on-one coaching with AI-powered insights about workforce mental fitness, resilience, and performance potential - providing HR and L and D leaders with aggregate data on employee readiness and growth trajectory without surfacing individual coaching session content.\n\nThe Whole Person Model underlying BetterUp''s coaching methodology measures 26 dimensions of employee wellbeing and performance potential, from cognitive agility and goal orientation to physical health and social connection. The AI layer uses these measurements to match employees with the coaches most likely to be effective for their specific development needs, track progress over time, and surface aggregate patterns that HR leaders can act on at the organisational level without individual privacy compromise.\n\nBetterUp''s value proposition in 2026 centres on the evidence base. The company has published research with Stanford, Berkeley, and MIT demonstrating measurable improvement in employee performance, retention, and mental fitness outcomes from coaching programs. For enterprise CHROs who need to justify L and D investment to CFOs and boards, the outcome data is the differentiator. Companies including Google, Microsoft, Amazon, and Salesforce have deployed BetterUp at scale for executive development, high-potential employee acceleration, and manager effectiveness programs. The platform is not built for individual consumer use - it is enterprise-only with minimum deployment commitments and custom pricing based on seat volume and coaching hour allocation.',
 'https://betterup.com', 'https://betterup.com',
 'paid', false, 0, 4.6, 2400, false, false, false,
 ARRAY['hr-tech', 'learning-development', 'employee-engagement'],
 ARRAY['Evidence-based coaching with published research outcomes from Stanford and Berkeley partnerships', 'AI matching connects employees with the most effective coach for their specific development profile', 'Aggregate workforce mental fitness analytics give HR leaders actionable data without privacy compromise', 'Used at scale by Google, Microsoft, Amazon - strong signal for enterprise deployment confidence'],
 ARRAY['Enterprise-only pricing with minimum seat commitments - not accessible for companies under 200 employees', 'Custom pricing requires a sales process - budgeting without a demo engagement is difficult', 'ROI realisation typically takes 6-12 months to show up in measurable retention and performance data', 'Coaching availability varies by time zone - some geographies have thinner coach supply'],
 ARRAY['Enterprise HR leaders building executive and high-potential development programs with measurable outcomes', 'L and D teams needing to demonstrate ROI on development investment to CFOs and boards', 'Companies addressing burnout, attrition risk, and manager effectiveness with evidence-based coaching'],
 NOW()),

('pyn', 'Pyn', 'Employee communication automation platform that sends the right message to each employee at the right moment',
 E'Pyn is an employee communication automation platform that solves a fundamental people ops problem: employees receive either too much communication from HR (ignored broadcasts to everyone) or too little (no guidance at critical moments like starting a new role, receiving a promotion, or returning from leave). Pyn automates personalised employee communication that is triggered by HR events in the HRIS - a new hire, a manager change, a performance review cycle opening, a work anniversary - and delivers the right contextual message to the right employee at exactly the right time.\n\nThe content library in 2026 includes over 100 pre-built communication flows covering the full employee lifecycle: pre-boarding for new hires, first-week orientation messages, manager transition communications, promotion celebration and expectation-setting, parental leave preparation, return-to-work support, and offboarding. HR teams can customise these templates for their company culture and policies, or build new flows from scratch using Pyn''s visual workflow builder. AI-assisted content drafting helps HR writers generate personalised, empathetic message text from a brief description of the communication goal.\n\nFor people operations teams managing employee experience at scale, Pyn addresses the gap between HR intent and employee reality. A company may have excellent programs for manager development, mental health support, and career growth - but if employees do not know about them at the moment they are most relevant, participation rates are low and program investment is wasted. Pyn''s event-triggered delivery ensures employees receive relevant guidance from day one through every significant career moment. The platform integrates with BambooHR, Workday, HiBob, Rippling, and Slack.',
 'https://pyn.com', 'https://pyn.com',
 'paid', false, 5, 4.3, 980, false, false, false,
 ARRAY['hr-tech', 'employee-engagement', 'people-analytics'],
 ARRAY['Event-triggered communication ensures employees receive guidance at the exact relevant moment', 'Pre-built library of 100+ lifecycle communication flows reduces HR setup time significantly', 'AI-assisted content drafting helps HR teams write personalised, empathetic messages at scale', 'Integrates with major HRIS platforms for automated trigger-based delivery without manual scheduling'],
 ARRAY['Focused exclusively on communication automation - not a full HR platform', 'Smaller brand recognition than enterprise HR platforms may require more internal selling', 'Return on investment depends on HR team quality of communication templates and flows', 'Limited analytics on downstream employee behaviour changes from improved communication'],
 ARRAY['People ops teams automating onboarding and lifecycle communications across a growing workforce', 'HR teams struggling with low participation rates in development and wellbeing programs', 'Companies improving employee experience without adding headcount to the HR function'],
 NOW()),

('peakon', 'Peakon', 'Real-time employee engagement and retention intelligence platform now part of Workday',
 E'Peakon is an employee engagement and retention intelligence platform that was acquired by Workday in 2021 and continues to serve as Workday''s primary employee listening and engagement analytics product. The platform uses continuous pulse surveys - short weekly or biweekly questionnaires delivered to employees - to measure engagement in real time rather than through annual surveys that capture sentiment too infrequently to drive timely action.\n\nThe AI and machine learning capabilities are the platform''s core differentiator. Peakon''s predictive models identify which employees are at risk of leaving 3-6 months before they submit resignation letters, based on engagement trend analysis, comment sentiment, and benchmark comparisons. The driver analysis identifies which specific factors are most strongly correlated with engagement scores in different teams - so HR leaders can prioritise interventions on the drivers that will move the needle rather than trying to improve everything simultaneously.\n\nFor Workday customers, Peakon''s integration with the broader Workday HCM platform means that engagement data sits alongside performance, compensation, and learning data in a single system - enabling the kind of cross-dimensional people analytics that requires expensive data engineering in multi-system environments. The comment analysis uses NLP to identify recurring themes in employee feedback at scale, surfacing the top issues across hundreds of thousands of open-ended responses without requiring manual review. Peakon''s global customer base of over 700 organisations generates the benchmarking data that allows companies to compare their engagement scores against industry and region peers.',
 'https://peakon.com', 'https://peakon.com',
 'paid', false, 0, 4.4, 2600, false, false, false,
 ARRAY['hr-tech', 'employee-engagement', 'people-analytics'],
 ARRAY['Predictive attrition model identifies flight-risk employees 3-6 months before resignation', 'Native Workday integration enables engagement data alongside performance and compensation in one system', 'Continuous pulse survey model captures real-time sentiment changes rather than annual snapshots', 'NLP comment analysis processes thousands of open-text responses into prioritised themes automatically'],
 ARRAY['Workday acquisition means full value requires Workday HCM licensing - expensive for smaller organisations', 'Pricing is enterprise and requires custom engagement - no transparent public pricing', 'Standalone value without Workday integration is lower than dedicated competitors like Culture Amp', 'Implementation and survey cadence design requires experienced HR analytics leadership to be effective'],
 ARRAY['Workday HCM customers who want employee engagement and retention intelligence in the same system', 'Enterprise HR analytics teams running continuous listening programs at scale', 'CHROs needing statistically benchmarked engagement data for board-level workforce reporting'],
 NOW())

ON CONFLICT (slug) DO NOTHING;
