-- tools-batch-13.sql - 10 new tools (DB: 153 to 163)
-- Run in Supabase SQL Editor
-- All inserts use ON CONFLICT DO NOTHING (idempotent)

INSERT INTO tools (slug, name, tagline, description, logo_url, website_url, affiliate_url, tags, pricing_type, pricing_free_tier, pricing_starting_price, rating, review_count, featured, trending, editor_pick, pros, cons, use_cases, updated_at) VALUES

('taskade', 'Taskade', 'AI-powered project management and team collaboration workspace', 'Taskade is an all-in-one AI productivity platform that combines task management, project planning, mind mapping, and real-time collaboration in a single workspace. Powered by its native AI agent, Taskade can generate project outlines, create tasks from prompts, write content, and automate workflows across your entire team.

Teams use Taskade to plan sprints, manage OKRs, brainstorm ideas, and keep everyone aligned. Its AI can summarize meetings, draft emails, and break down complex projects into actionable steps. With cross-platform support and a generous free tier, Taskade suits startups, remote teams, and solo creators alike.', 'https://www.google.com/s2/favicons?domain=taskade.com&sz=64', 'https://taskade.com', 'https://taskade.com', ARRAY['productivity'], 'freemium', true, 8, 4.4, 312, false, true, false, ARRAY['Native AI agent for task generation and automation', 'Real-time collaboration with unlimited members on free plan', 'Flexible views: list, board, mind map, calendar', 'Cross-platform: web, desktop, mobile apps'], ARRAY['AI features locked behind paid plans', 'Learning curve compared to simpler to-do apps', 'Search functionality needs improvement'], ARRAY['Sprint planning for agile teams', 'Brainstorming and mind mapping sessions', 'Freelance project management with client collaboration'], NOW()),

('sudowrite', 'Sudowrite', 'AI writing partner built specifically for fiction and creative writing', 'Sudowrite is a creative writing AI designed from the ground up for novelists, screenwriters, and storytellers. Unlike general-purpose writing tools, Sudowrite understands narrative structure, character development, and prose style. Its "Describe" feature generates sensory-rich descriptions, "Brainstorm" generates plot ideas, and "Write" helps you push through writer''s block.

Writers use Sudowrite to draft chapters, rewrite scenes in different tones, explore alternative story directions, and develop characters with depth. It learns your writing style to maintain consistency across a manuscript. The tool has become essential for authors working on long-form fiction, where maintaining voice and continuity is critical.', 'https://www.google.com/s2/favicons?domain=sudowrite.com&sz=64', 'https://sudowrite.com', 'https://sudowrite.com', ARRAY['writing-ai'], 'paid', false, 19, 4.5, 428, false, false, false, ARRAY['Purpose-built for fiction and creative writing', 'Maintains authorial voice and style across chapters', 'Unique features: Describe, Brainstorm, Rewrite', 'No word limits per session on paid plans'], ARRAY['Not suitable for business or technical writing', 'Requires a paid subscription to use meaningfully', 'Output quality varies with complex plots'], ARRAY['Drafting novel chapters and overcoming writer''s block', 'Rewriting scenes in different tones or perspectives', 'Developing character backstories and dialogue'], NOW()),

('lex', 'Lex', 'Distraction-free AI writing tool for essays, documents and ideas', 'Lex is a minimalist AI writing tool focused on helping writers think and draft without distraction. Built around a clean, Google Docs-like interface, Lex features an AI that you summon by typing "+++" when you get stuck. It completes your thought, suggests next sentences, or offers alternative phrasings on demand.

Writers and professionals use Lex for essays, blog posts, reports, and long-form content where focus matters. Its commenting and sharing features make it viable for collaborative editing. Lex is intentionally simple: no overwhelming sidebar, no complex menus, just you and your writing with AI available when you need it.', 'https://www.google.com/s2/favicons?domain=lex.page&sz=64', 'https://lex.page', 'https://lex.page', ARRAY['writing-ai'], 'freemium', true, 8, 4.2, 198, false, false, false, ARRAY['Distraction-free, minimal interface for deep work', 'AI available on demand (not forced on every sentence)', 'Fast collaboration and sharing via link', 'Excellent for long-form essays and reports'], ARRAY['Limited formatting options compared to Google Docs', 'AI context window can feel short on very long documents', 'No mobile app yet'], ARRAY['Writing long-form essays and op-eds', 'Drafting blog posts and thought leadership content', 'Collaborative document editing with feedback'], NOW()),

('podcastle', 'Podcastle', 'AI podcast creation platform for recording, editing and publishing', 'Podcastle is an all-in-one podcast production platform that uses AI to simplify every step of the podcasting process. From browser-based recording with remote guests to AI-powered editing, noise removal, and audio restoration, Podcastle handles the technical complexity so creators can focus on content.

Podcasters use Podcastle to record studio-quality audio directly in their browser, automatically remove filler words and silences, and convert recordings into polished episodes ready for distribution. Its AI voice cloning feature lets hosts record voiceovers in their own cloned voice. The platform supports both solo podcasters and multi-host shows with separate audio tracks.', 'https://www.google.com/s2/favicons?domain=podcastle.ai&sz=64', 'https://podcastle.ai', 'https://podcastle.ai', ARRAY['voice-audio'], 'freemium', true, 12, 4.3, 267, false, false, false, ARRAY['Browser-based recording with no software install needed', 'AI noise removal and audio enhancement', 'Filler word and silence removal saves editing time', 'Supports multi-track recording for interview shows'], ARRAY['Free plan has limited export options', 'AI voice cloning requires significant training audio', 'Video recording quality lags behind dedicated tools'], ARRAY['Recording and editing solo podcast episodes', 'Producing interview-style podcasts with remote guests', 'Converting written content into audio episodes'], NOW()),

('castmagic', 'Castmagic', 'AI tool that transforms audio and video recordings into content assets', 'Castmagic is an AI-powered content repurposing platform that turns your audio and video recordings into ready-to-use content. Upload a podcast episode, webinar, or video call and Castmagic generates show notes, blog posts, social media clips, email newsletters, and transcripts automatically.

Content creators, podcasters, and marketers use Castmagic to multiply the value of every recording they produce. Instead of manually writing show notes or pulling quotes for social media, Castmagic analyzes the full recording and produces dozens of content pieces in minutes. It supports multiple output templates and lets you define your own content formats using custom prompts.', 'https://www.google.com/s2/favicons?domain=castmagic.io&sz=64', 'https://castmagic.io', 'https://castmagic.io', ARRAY['writing-ai'], 'paid', false, 23, 4.6, 341, false, true, false, ARRAY['Turns one recording into 10+ content assets automatically', 'Custom content templates with your own prompts', 'High-quality transcription with speaker identification', 'Saves hours of manual content repurposing work'], ARRAY['No free tier - paid plans only', 'Best results with clear audio (struggles with heavy accents)', 'Limited video editing features'], ARRAY['Repurposing podcast episodes into blog posts and newsletters', 'Generating social media content from webinars', 'Creating show notes and episode summaries at scale'], NOW()),

('typeframes', 'Typeframes', 'AI video creation tool that turns text into animated videos', 'Typeframes is an AI video creation tool that converts text, scripts, and ideas into polished animated videos. Designed for product teams and marketers, Typeframes specializes in product demos, explainer videos, and social media content. You paste your script or URL and the AI generates motion graphics, text animations, and transitions.

Teams use Typeframes to create product launch videos, feature announcements, and marketing content without hiring a video editor. The tool integrates brand colors, logos, and fonts to maintain consistency. Export options include vertical formats for TikTok and Instagram Reels, making it useful for social media marketing campaigns.', 'https://www.google.com/s2/favicons?domain=typeframes.com&sz=64', 'https://typeframes.com', 'https://typeframes.com', ARRAY['video-ai'], 'freemium', true, 29, 4.1, 142, false, false, false, ARRAY['Text-to-video in minutes with no design skills needed', 'Product demo and SaaS announcement focus', 'Multiple aspect ratios for social media', 'Brand kit integration for consistent look'], ARRAY['Limited to text-based and screen recording style videos', 'Less suitable for live-action or talking-head content', 'Rendering can be slow on complex animations'], ARRAY['Creating product demo videos for SaaS tools', 'Generating social media video content from blog posts', 'Building feature announcement videos for product launches'], NOW()),

('magicschool-ai', 'MagicSchool AI', 'AI platform designed specifically for teachers and educators', 'MagicSchool AI is the leading AI productivity platform built for educators. Teachers use it to generate lesson plans, rubrics, assignments, quiz questions, email drafts for parents, IEP accommodations, and differentiated materials - all from simple text prompts. The platform has over 60 AI tools tailored to the specific needs of K-12 and higher education.

School districts adopt MagicSchool AI to reduce teacher planning time while maintaining educational quality. Unlike generic AI tools, MagicSchool understands pedagogical frameworks, Common Core standards, and grade-level language. The student version helps learners with reading comprehension and study skills without doing assignments for them.', 'https://www.google.com/s2/favicons?domain=magicschool.ai&sz=64', 'https://magicschool.ai', 'https://magicschool.ai', ARRAY['productivity'], 'freemium', true, 3, 4.7, 892, false, true, false, ARRAY['60+ AI tools built specifically for education workflows', 'Understands grade levels, standards, and pedagogy', 'Student version with guardrails for academic integrity', 'Free tier generous enough for most individual teachers'], ARRAY['Most advanced features require paid school/district plan', 'Primarily focused on K-12, less useful for higher ed', 'Output still needs teacher review for accuracy'], ARRAY['Generating lesson plans and unit outlines in minutes', 'Creating differentiated materials for diverse learners', 'Drafting parent communication and IEP documentation'], NOW()),

('merlin', 'Merlin', 'AI assistant browser extension for instant help on any website', 'Merlin is a browser extension that brings AI assistance to any webpage you visit. Highlight text to get instant explanations, summaries, or translations. Open the sidebar to chat with Claude, GPT-4, or Gemini while browsing. Ask Merlin to summarize YouTube videos, draft replies to emails in Gmail, or explain complex articles as you read them.

Professionals and students use Merlin to accelerate research, understand dense content, and compose messages without switching tabs. The extension supports multiple AI models so you can choose Claude for nuanced writing or GPT-4 for coding tasks. Its YouTube summary feature is particularly popular for quickly extracting key points from long videos.', 'https://www.google.com/s2/favicons?domain=merlin.foyer.work&sz=64', 'https://merlin.foyer.work', 'https://merlin.foyer.work', ARRAY['productivity'], 'freemium', true, 19, 4.4, 567, false, false, false, ARRAY['Works on any webpage without switching tabs', 'Access to multiple AI models in one extension', 'YouTube video summarization saves hours', 'Gmail and LinkedIn integration for quick drafts'], ARRAY['Free plan limits daily queries', 'Context window limited when working with very long pages', 'Quality depends on which AI model is selected'], ARRAY['Summarizing research papers and articles while reading', 'Getting quick explanations of complex content in any tab', 'Drafting professional replies in Gmail without leaving inbox'], NOW()),

('reflect', 'Reflect', 'AI-powered note-taking app with networked thoughts and backlinks', 'Reflect is a note-taking and knowledge management app that uses AI to help you think better and remember more. Built around networked thinking, Reflect automatically creates backlinks between related notes, building a personal knowledge graph over time. Its AI assistant can summarize notes, generate meeting agendas from your calendar, and help you find connections between ideas.

Knowledge workers, writers, and researchers use Reflect to capture fleeting thoughts, organize research, and surface insights from their note archive. The AI can query your entire note collection to answer questions based on your own writing. Daily note templates and calendar integration make it a powerful system for personal knowledge management and journaling.', 'https://www.google.com/s2/favicons?domain=reflect.app&sz=64', 'https://reflect.app', 'https://reflect.app', ARRAY['productivity'], 'paid', false, 10, 4.5, 334, false, false, false, ARRAY['AI that queries your own notes for personalized insights', 'Automatic backlinks build a personal knowledge graph', 'Calendar integration for meeting notes and agendas', 'Fast, native apps for Mac, iOS, and web'], ARRAY['No free plan - requires paid subscription', 'Import from other apps can be limited', 'Less feature-rich than Notion for project management'], ARRAY['Building a personal knowledge management system', 'Capturing and connecting research notes with backlinks', 'Daily journaling with AI-assisted reflection prompts'], NOW()),

('anytype', 'Anytype', 'Local-first, privacy-focused knowledge management with AI', 'Anytype is an open-source, local-first knowledge management platform that stores your data on your device rather than in the cloud. It offers blocks, databases, wikis, and task management similar to Notion, but with end-to-end encryption and offline-first architecture. AI features help you write, summarize, and organize content within your private workspace.

Privacy-conscious users, developers, and researchers choose Anytype because they want the power of Notion without sending data to a third-party cloud. The peer-to-peer sync lets you share workspaces without a central server. Its object-based data model is more flexible than traditional document editors, supporting complex knowledge graphs and custom data types.', 'https://www.google.com/s2/favicons?domain=anytype.io&sz=64', 'https://anytype.io', 'https://anytype.io', ARRAY['productivity'], 'freemium', true, 0, 4.3, 278, false, false, false, ARRAY['Local-first with end-to-end encryption for full privacy', 'Open source with no vendor lock-in', 'Offline mode with peer-to-peer sync', 'Free for personal use with generous storage'], ARRAY['Steeper learning curve than Notion or Obsidian', 'Mobile apps still maturing', 'AI features less developed than cloud-based alternatives'], ARRAY['Building a private, offline-capable knowledge base', 'Managing research and writing projects with full data ownership', 'Replacing Notion for privacy-focused teams and individuals'], NOW())

ON CONFLICT (slug) DO NOTHING;
