-- tools-batch-60.sql
-- Theme: AI Education / EdTech
-- Target: ~579 tools total (569 + 10)
-- Slug collision check: khanmigo, curipod, diffit, brisk-teaching all found in tools-batch-35.sql
-- Swapped with 4 fallback pool slugs: gradescope-ai, kahoot-ai, nearpod-ai, edpuzzle-ai
-- Final 10 slugs verified fresh against all prior tools-batch-*.sql files:
--   coursera-coach, socratic, quizlet-q-chat, photomath, mathgpt,
--   eduaide-ai, gradescope-ai, kahoot-ai, nearpod-ai, edpuzzle-ai

INSERT INTO tools (slug, name, tagline, description, website_url, affiliate_url, pricing_type, pricing_free_tier, pricing_starting_price, rating, review_count, featured, trending, editor_pick, tags, pros, cons, use_cases, updated_at)
VALUES

('coursera-coach', 'Coursera Coach', 'AI-powered learning assistant embedded in Coursera courses for personalised guidance and concept explanation',
 E'Coursera Coach is the AI learning assistant built directly into the Coursera platform, providing learners with on-demand, contextually relevant guidance as they work through courses and specialisations. Rather than being a generic chatbot bolted onto a learning management system, Coursera Coach is trained on course content and understands the specific material a learner is currently studying - allowing it to explain concepts in alternative ways, answer questions tied to the actual lesson, and suggest which parts of the course to revisit when a learner is struggling with a particular idea.\n\nThe coaching capability extends beyond content explanation. Coursera Coach helps learners build structured study plans based on their stated goals and available time, suggests related courses and specialisations that build on completed material, and provides contextual hints for graded assignments without giving away the answers - preserving the integrity of the learning assessment while reducing the frustration that causes learners to abandon courses before completion. For working professionals taking courses in data science, cloud computing, or business strategy, the ability to get an immediate, relevant answer at 11pm rather than waiting for a forum response the next day meaningfully changes the completion dynamics.\n\nCoursera Coach is available to learners on Coursera Plus subscriptions and to learners on individual course purchases that include the AI feature. The integration with Coursera''s catalog of 7,000+ courses from 325+ university and industry partners means that Coach can reference authoritative course content rather than generating generic educational responses. For enterprise customers using Coursera for workforce development, the Coach functionality is available in the Coursera for Business plan and can be configured to the specific learning programs the organisation has deployed.',
 'https://coursera.org', 'https://coursera.org',
 'freemium', true, 59, 4.3, 3200, false, false, false,
 ARRAY['education', 'ai-assistants', 'e-learning'],
 ARRAY['Context-aware coaching tied to actual course content rather than generic educational responses', 'Study plan generation adapts to learner goals and available weekly time', 'Immediate on-demand guidance that reduces the friction causing mid-course abandonment', 'Access to 7,000+ courses from 325+ university and industry partners within the same platform'],
 ARRAY['Full Coach functionality requires Coursera Plus subscription or individual course purchase with AI included', 'Quality of coaching is dependent on how well the underlying course content is structured', 'Less useful for highly specialised or niche course content where AI training depth is thinner', 'Not a substitute for human instructor interaction on complex, ambiguous learning challenges'],
 ARRAY['Working professionals learning data science or cloud skills who need flexible, self-paced guidance', 'Learners working through Coursera specialisations who want conceptual clarification without waiting for forum responses', 'Enterprise L and D teams deploying Coursera for workforce upskilling who want AI coaching alongside curated programs'],
 NOW()),

('socratic', 'Socratic by Google', 'AI homework help app for students that explains concepts using visuals, videos, and step-by-step guidance',
 E'Socratic by Google is a free AI-powered homework help app designed for high school and university students who need help understanding concepts across subjects including mathematics, science, history, literature, and social studies. The core workflow is simple: a student photographs a question or types it into the app, and Socratic returns an explanation of the underlying concept illustrated with visual breakdowns, relevant YouTube video explanations, step-by-step worked examples, and links to additional learning resources - rather than just providing the answer.\n\nThe AI is trained to identify what type of problem the student is facing and route to the most useful explanatory approach for that problem type. A trigonometry question returns a visual diagram of the relevant angle relationships alongside a step-by-step solution process. A historical analysis question returns context about the period, key figures, and thematic frameworks relevant to the question. The emphasis on explanation over answer delivery is intentional - Socratic is designed to build understanding rather than enable answer copying, which is why it has been adopted by educators as a supplemental learning tool as well as by students.\n\nAs a Google product, Socratic benefits from integration with Google''s broader knowledge graph and YouTube''s educational content library, which means the video and visual resources it surfaces are consistently relevant and high-quality. The app is completely free with no subscription required, making it one of the most accessible AI learning tools available to students globally. Socratic covers content appropriate for grades 9 through university level, with the strongest coverage in STEM subjects where the step-by-step explanation format is most naturally suited to the problem structure.',
 'https://socratic.org', 'https://socratic.org',
 'free', true, 0, 4.4, 5600, false, false, false,
 ARRAY['education', 'ai-assistants', 'student-tools'],
 ARRAY['Completely free with no subscription required - accessible to all students globally', 'Visual and video explanations build conceptual understanding rather than just delivering answers', 'Google integration surfaces high-quality YouTube educational content alongside AI explanations', 'Photo capture allows students to photograph textbook questions directly without retyping'],
 ARRAY['Coverage depth varies by subject - strongest in STEM, thinner in humanities and language arts', 'Explanation depth can be insufficient for advanced university-level coursework in complex domains', 'No teacher or parent dashboard for monitoring student learning patterns', 'App-based only - no desktop or browser version for students who prefer non-mobile workflows'],
 ARRAY['High school students getting step-by-step concept explanations for math and science homework', 'Students preparing for standardised tests who need on-demand conceptual review across subjects', 'Self-directed learners who want visual explanations of difficult concepts without enrolling in a course'],
 NOW()),

('quizlet-q-chat', 'Quizlet Q-Chat', 'AI study companion integrated into Quizlet that tutors students through flashcard sets using Socratic questioning',
 E'Quizlet Q-Chat is the AI tutoring feature embedded in the Quizlet learning platform, transforming the traditional flashcard study workflow into an interactive tutoring conversation. Rather than passively cycling through flashcards, students engage with Q-Chat in a dialogue where the AI asks questions, responds to student answers with targeted follow-up, explains concepts when understanding gaps appear, and adjusts the difficulty and pacing based on demonstrated comprehension. The Socratic questioning approach is designed to build durable recall rather than surface familiarity.\n\nQ-Chat is built on top of Quizlet''s existing flashcard infrastructure, which means it has access to the hundreds of millions of study sets created by students and teachers on the platform across every subject and level. A student studying AP Biology can use Q-Chat with a verified, community-built study set for that specific exam, getting an AI tutoring session that understands the exact content scope and terminology of their upcoming test rather than generating generic biology questions. This combination of structured content assets and conversational AI tutoring is the core differentiator from standalone AI tutors that lack the curricular depth of established study sets.\n\nQ-Chat is available on Quizlet''s paid plans. The feature includes practice test generation from study sets, explanation of incorrect answers with the relevant concept taught through additional questioning, and progress tracking that shows which concepts have been mastered and which require more practice. For students using Quizlet as part of an existing study workflow, Q-Chat adds an AI tutoring layer to a tool they are already familiar with rather than requiring adoption of a separate platform. Quizlet is used by over 60 million students globally, making Q-Chat one of the most widely accessible AI tutoring tools by user base.',
 'https://quizlet.com', 'https://quizlet.com',
 'freemium', true, 8, 4.2, 4800, false, false, false,
 ARRAY['education', 'ai-assistants', 'student-tools'],
 ARRAY['Access to hundreds of millions of community-built study sets across every subject and level', 'Socratic questioning builds durable recall rather than passive flashcard familiarity', 'AI tutoring is anchored to specific exam-ready content sets rather than generic subject knowledge', 'Progress tracking identifies mastered versus under-practiced concepts across the study set'],
 ARRAY['Full Q-Chat functionality requires Quizlet paid subscription', 'Study set quality varies - AI tutoring is only as good as the underlying content in the set used', 'Conversational AI tutoring format is less suited to open-ended subjects like essay writing or creative work', 'Some students find Socratic questioning slower than direct answer review for time-pressured exam prep'],
 ARRAY['Students preparing for specific standardised exams using verified, exam-mapped Quizlet study sets', 'High school and university students who want interactive AI tutoring without leaving their existing Quizlet workflow', 'Teachers assigning AI-assisted study practice using class-created or curated Quizlet sets'],
 NOW()),

('photomath', 'Photomath', 'AI math solver that scans handwritten or printed problems and explains step-by-step solutions',
 E'Photomath is the leading AI-powered math problem solver, used by over 220 million students and parents globally. The core capability is simple and immediately useful: a student points their phone camera at a math problem - whether handwritten in a notebook or printed in a textbook - and Photomath scans it, solves it, and returns a detailed step-by-step explanation of the solution process. The explanation does not just show the answer; it breaks down every step with the mathematical reasoning that connects them, which is the critical differentiator from a calculator.\n\nPhotomath covers a wide range of mathematics from basic arithmetic through algebra, geometry, trigonometry, calculus, and statistics. The AI is trained to recognise handwriting variations and non-standard problem formatting, making it practical for students working from physical worksheets and notebook assignments rather than only typed digital content. The multiple solution paths feature shows students when a problem can be solved using different methods - factoring versus the quadratic formula for a polynomial equation, for example - and explains the conditions under which each approach is most efficient.\n\nThe educational design philosophy behind Photomath is explicit: the step-by-step explanation is intended to help students understand why each step follows from the previous one, not just copy a final answer. This is reflected in the app structure, where the answer is not shown until the student has had the opportunity to engage with the solution walkthrough. For parents helping with homework without a strong math background, Photomath serves as a real-time refresher. For students working independently at home, it provides the concept explanation that would otherwise require access to a teacher or tutor. Photomath Plus adds animated tutorials and additional practice problems for deeper concept reinforcement beyond the step-by-step solver.',
 'https://photomath.com', 'https://photomath.com',
 'freemium', true, 12, 4.6, 8900, false, true, false,
 ARRAY['education', 'student-tools', 'ai-assistants'],
 ARRAY['Camera scan of handwritten and printed math problems - works on physical worksheets and textbooks', 'Step-by-step solution explanation builds conceptual understanding, not just answer delivery', 'Multiple solution path options show students different methods and when each is most appropriate', 'Covers arithmetic through calculus and statistics - useful across all school grade levels'],
 ARRAY['Primary strength is mathematics - limited coverage of other STEM subjects', 'Animated tutorials and extra practice require Photomath Plus subscription', 'Handwriting recognition can struggle with very messy or non-standard notation', 'Focus on procedural step-by-step explanation; less helpful for developing mathematical intuition'],
 ARRAY['Students checking their work and understanding mistakes on math homework across grade levels', 'Parents helping children with math assignments without needing subject expertise themselves', 'Students preparing for math exams who want step-by-step breakdowns of practice problem types'],
 NOW()),

('mathgpt', 'MathGPT', 'AI math tutor that solves and explains problems across all levels using conversational step-by-step guidance',
 E'MathGPT is an AI-powered mathematics tutor built specifically for students who need help solving and understanding math problems across a broad range of levels - from middle school arithmetic and algebra through university-level calculus, linear algebra, differential equations, and statistics. Unlike a general-purpose AI assistant applied to math questions, MathGPT is purpose-trained for mathematical reasoning and explanation, with a focus on returning not just correct solutions but pedagogically useful explanations that students can follow and learn from.\n\nThe conversational tutoring model allows students to ask follow-up questions when an explanation is unclear - "Why did you factor it that way?" or "What happens if x is negative?" - and receive contextually relevant responses that continue the mathematical dialogue rather than starting a new explanation from scratch. This back-and-forth dynamic is closer to working with a human tutor than using a solver that returns a static step-by-step output. MathGPT can also check student work when a student types in their own attempted solution, identifying where the reasoning diverged from the correct approach and explaining the specific error.\n\nMathGPT is accessible via web browser without requiring a specific device or operating system, making it practical for students across different hardware environments. The platform offers a free tier with a limited number of problem-solving sessions per day, with paid plans unlocking unlimited usage and additional features including detailed worked example generation and practice problem sets customised to the specific topic a student is working on. For university students taking quantitative courses who need on-demand math tutoring outside of office hours, MathGPT provides a more specialised and mathematically reliable alternative to using a general-purpose AI assistant for problem-solving.',
 'https://mathgpt.com', 'https://mathgpt.com',
 'freemium', true, 15, 4.1, 1200, false, false, false,
 ARRAY['education', 'student-tools', 'ai-assistants'],
 ARRAY['Conversational tutoring allows follow-up questions within the same mathematical dialogue', 'Purpose-trained for math reasoning - more reliable on complex problems than general-purpose AI', 'Student work checking identifies specific reasoning errors rather than just flagging wrong answers', 'Covers a broad math curriculum from middle school through university-level courses'],
 ARRAY['Free tier limits daily problem-solving sessions - heavy users need a paid plan', 'Covers mathematics primarily - not designed for physics, chemistry, or other STEM subjects', 'Explanation depth can be uneven on highly advanced or specialised postgraduate topics', 'Browser-only access - no dedicated mobile app for students who prefer on-the-go study'],
 ARRAY['University students working through calculus or linear algebra problem sets outside of office hours', 'High school students preparing for standardised math exams who need conversational tutoring on specific topics', 'Students checking their own work on complex math assignments and understanding where their reasoning went wrong'],
 NOW()),

('eduaide-ai', 'Eduaide.AI', 'AI lesson planning and teaching resource generation platform for K-12 educators',
 E'Eduaide.AI is an AI productivity platform designed specifically for K-12 teachers, with a focus on reducing the time educators spend creating instructional materials. The platform provides over 100 AI-powered generation tools covering the full range of teacher content needs: lesson plans, unit plans, assessments, rubrics, exit tickets, discussion prompts, parent communication templates, differentiated activity variations, and IEP accommodation suggestions. Teachers enter a topic, grade level, and any relevant context, and Eduaide.AI generates a draft that can be reviewed, edited, and saved to the teacher''s resource library.\n\nThe differentiation tools are a standout feature for teachers working with mixed-ability classrooms. Eduaide.AI can take a base lesson activity and automatically generate modified versions at different reading levels, with additional scaffolding for English language learners, with extension challenges for advanced students, or with accessibility modifications for students with specific learning needs - all from a single input. This is the kind of adaptation work that can take an experienced teacher hours to produce manually and that is frequently skipped under time pressure, to the detriment of students who need it most.\n\nEduaide.AI also includes a feedback generation tool that helps teachers write specific, standards-aligned feedback on student work quickly - a particularly time-consuming task at scale. The platform supports content generation in multiple languages and aligns with Common Core, NGSS, and other major standards frameworks, allowing teachers to specify the standards alignment for generated materials. For individual teachers, the free plan provides access to a meaningful set of tools with usage limits. School and district plans unlock unlimited generation, collaborative resource sharing across a teaching team, and administrative visibility into platform usage.',
 'https://eduaide.ai', 'https://eduaide.ai',
 'freemium', true, 10, 4.4, 1800, false, false, false,
 ARRAY['education', 'productivity', 'teacher-tools'],
 ARRAY['100+ AI tools covering the full range of teacher content creation needs in one platform', 'Differentiation tools generate modified activity versions for different ability levels and learning needs automatically', 'Standards alignment support for Common Core, NGSS, and other major frameworks', 'Multi-language content generation supports teachers in diverse linguistic classroom environments'],
 ARRAY['Free plan has usage limits that power users will exceed quickly', 'AI-generated content requires teacher review for accuracy, grade-level appropriateness, and local curriculum fit', 'Less useful for higher education or vocational training contexts outside of K-12', 'Feedback generation quality depends on how clearly the teacher specifies the assessment criteria'],
 ARRAY['K-12 teachers generating differentiated lesson materials and activity variations for mixed-ability classrooms', 'Teachers creating standards-aligned assessments and rubrics without spending evenings on planning documents', 'Schools and districts looking to reduce teacher administrative burden while maintaining instructional quality'],
 NOW()),

('gradescope-ai', 'Gradescope', 'AI-assisted grading and assessment platform that accelerates feedback delivery for university instructors',
 E'Gradescope is an AI-assisted grading and assessment platform used by universities and colleges to dramatically reduce the time instructors and teaching assistants spend grading student work while improving the consistency and specificity of the feedback students receive. The platform supports grading of paper-based handwritten submissions (scanned), digital uploads, and programming assignments, making it applicable across disciplines from engineering and mathematics to humanities and social sciences.\n\nThe AI-assisted grading workflow groups similar student responses together automatically, allowing instructors to evaluate and comment on a cluster of similar answers at once rather than reviewing each submission individually. When an instructor marks a response correct and adds a comment, Gradescope applies the same mark and comment to all grouped responses that match - dramatically reducing redundant grading work on large class sizes. For university courses with 100+ students, this approach can reduce grading time by 50-70% according to instructor reports while producing more consistent marking than individual manual review.\n\nGradescope also provides rubric-based grading tools that allow instructors to define assessment criteria upfront and apply them consistently across the cohort. The analytics layer shows instructors where the class struggled - which questions had low average scores, which rubric criteria were most commonly missed - providing data for targeted in-class review. For programming assignments, Gradescope''s autograding infrastructure runs automated test suites against student submissions, providing instant feedback on correctness and freeing instructor time for the aspects of code review that require human judgment. Gradescope is now part of the Turnitin family and integrates with major learning management systems including Canvas, Blackboard, and Moodle.',
 'https://gradescope.com', 'https://gradescope.com',
 'freemium', true, 0, 4.5, 3400, false, false, false,
 ARRAY['education', 'teacher-tools', 'ai-assistants'],
 ARRAY['AI response grouping reduces redundant grading work on large class sizes by 50-70%', 'Consistent rubric-based marking improves fairness across large cohorts graded by multiple TAs', 'Analytics identify class-wide knowledge gaps for targeted instructional review', 'Autograding for programming assignments provides instant student feedback on correctness'],
 ARRAY['Most valuable for medium-to-large university classes - lower ROI for small seminars where personal grading is already fast', 'Initial rubric setup and workflow configuration takes time before the efficiency gains become visible', 'Paper submission workflow requires scanning infrastructure that smaller institutions may lack', 'Integration quality varies across LMS platforms - Moodle integration is less mature than Canvas'],
 ARRAY['University instructors grading large cohorts of handwritten or digital submissions faster with consistent rubrics', 'Computer science courses using autograding to provide instant correctness feedback on programming assignments', 'Teaching assistants grading collaboratively with consistent criteria across a team'],
 NOW()),

('kahoot-ai', 'Kahoot! AI', 'AI-powered quiz and game-based learning platform that generates course-aligned questions for engagement and formative assessment',
 E'Kahoot! is the game-based learning platform used by over 350 million users globally, and its AI features represent a meaningful evolution of the platform beyond manually-created quiz content. The Kahoot! AI question generator allows teachers and course creators to input a topic, paste source text, or specify a learning objective, and automatically generate a complete set of quiz questions with answer options - ready to run as a live game in class or assign as self-paced homework without manual question authorship.\n\nThe AI generation capability addresses one of the main friction points in Kahoot! adoption: creating quality question content takes time, and the platform''s game-based format is most effective when the question set is closely aligned to the specific material students are currently studying rather than generic subject questions. With AI generation, a teacher can create a 15-question formative assessment on the specific chapter assigned last night in under two minutes - low enough effort that it becomes a practical tool for daily or weekly lesson closers rather than a special event that requires advance preparation.\n\nKahoot! AI also includes a question improvement feature that reviews manually-written questions for clarity, answer option quality, and difficulty calibration, suggesting revisions that make the questions more pedagogically effective as formative assessment instruments. The Creator AI tool helps course creators on the Kahoot! platform produce structured learning courses with AI-generated content frameworks rather than starting from a blank structure. For businesses using Kahoot! for training and onboarding, the AI generation tools apply equally to corporate learning content as to academic curricula. The AI features are available on Kahoot! paid plans for teachers and businesses.',
 'https://kahoot.com', 'https://kahoot.com',
 'freemium', true, 8, 4.3, 6700, false, false, false,
 ARRAY['education', 'teacher-tools', 'e-learning'],
 ARRAY['AI question generation from topic input or source text creates formative assessments in under two minutes', 'Game-based format increases student engagement compared to traditional quiz formats', '350 million user base means extensive community-created question sets available as starting points', 'Works equally for academic classrooms and corporate training and onboarding programs'],
 ARRAY['Game format prioritises speed over depth - less suitable for complex analytical or open-ended assessment', 'AI question quality requires teacher review - generated questions can be too straightforward or contain errors', 'Full AI generation features require a paid plan - free plan has limitations on AI usage', 'Engagement peaks when used occasionally - frequent use can reduce the novelty effect that drives participation'],
 ARRAY['Teachers creating quick formative assessments aligned to the specific lesson content from that week', 'Corporate trainers building engagement into onboarding and compliance training programs', 'Course creators on the Kahoot! platform generating structured course content frameworks with AI assistance'],
 NOW()),

('nearpod-ai', 'Nearpod AI', 'AI-powered interactive lesson platform that generates engaging, standards-aligned classroom presentations',
 E'Nearpod is an interactive lesson and assessment platform used by K-12 teachers to create and deliver lessons that include student participation tools - polls, open-ended questions, quizzes, virtual reality experiences, and collaborative boards - embedded directly in the lesson flow rather than as separate tools. The Nearpod AI features, launched progressively across the platform, use AI to generate complete interactive lesson drafts from a topic and grade level input, reducing the time a teacher spends building an engaging lesson from hours to minutes.\n\nThe AI lesson generation outputs a structured Nearpod presentation with slides, embedded knowledge checks, discussion prompts, and formative assessment questions already integrated into the lesson flow - not a passive slide deck that a teacher then needs to retrofit with interactivity. For teachers who are new to the platform or who are building lessons in subjects outside their deepest expertise, the AI-generated structure provides a sound pedagogical starting point that can be customised rather than a blank canvas. The generated content aligns to Common Core and state standards when a grade level and subject are specified.\n\nNearpod''s student-facing interactivity is the platform''s core differentiator from general AI lesson generators. Students participate in real time during live teacher-led sessions or work through lessons at their own pace in student-paced mode. The teacher dashboard shows individual student responses as they are submitted, allowing the teacher to adjust the lesson pace and address misconceptions in real time based on actual class data rather than guessing at understanding levels. For schools and districts that have adopted Nearpod as a core classroom technology, the AI generation features meaningfully reduce the planning time required to keep lesson content fresh and interactive without sacrificing the participation elements that drive the platform''s engagement value.',
 'https://nearpod.com', 'https://nearpod.com',
 'freemium', true, 18, 4.3, 2900, false, false, false,
 ARRAY['education', 'teacher-tools', 'e-learning'],
 ARRAY['AI generates complete interactive lessons with embedded polls, quizzes, and discussion prompts - not just slide content', 'Real-time student response dashboard allows teachers to adjust pacing based on actual class comprehension', 'Standards alignment for Common Core and state standards built into AI generation workflow', 'Student-paced mode allows asynchronous delivery for absent students or flipped classroom models'],
 ARRAY['Full AI generation and advanced features require a paid school or district plan', 'AI-generated lesson content requires teacher review for accuracy and local curriculum alignment', 'Most valuable when students are engaged through school-issued devices - BYOD implementation can be inconsistent', 'Content depth on highly specialised topics may require significant manual customisation beyond the AI draft'],
 ARRAY['Teachers creating interactive standards-aligned lessons without spending hours building participation activities manually', 'Schools adopting a consistent interactive lesson format across classrooms with AI-generated starting templates', 'Districts tracking real-time student comprehension data across lessons for instructional decision-making'],
 NOW()),

('edpuzzle-ai', 'Edpuzzle AI', 'AI-powered video lesson platform that embeds questions and comprehension checks into educational videos',
 E'Edpuzzle is a video-based learning platform that allows teachers to take any educational video - from YouTube, Khan Academy, National Geographic, TED-Ed, or any other source - and embed interactive questions, audio notes, and comprehension checks directly into the video timeline. Students cannot skip past embedded questions, ensuring active engagement with the video content rather than passive watching. The Edpuzzle AI features automate the most time-consuming part of this workflow: question creation.\n\nThe AI question generation analyses video content and automatically suggests relevant comprehension and analysis questions at appropriate timestamps throughout the video. For a 10-minute science documentary, Edpuzzle AI might generate eight questions embedded at the moments in the video where the key concepts are introduced, with a mix of multiple choice, true/false, and short answer formats. The teacher reviews, adjusts, and selects from the AI suggestions rather than writing questions from scratch - reducing the lesson preparation time while maintaining teacher control over the specific comprehension points the lesson is assessing.\n\nEdpuzzle also provides a library of pre-made video lessons created by other teachers across all subjects and grade levels, which can be assigned directly or used as a starting point with customisation. The teacher dashboard tracks individual student completion, time spent, and question performance, providing the data teachers need to identify students who are struggling with the video content before the next class session. For teachers implementing flipped classroom models where students watch instructional videos at home before class discussion, Edpuzzle''s accountability and comprehension tracking makes the model operationally practical rather than reliant on students self-reporting their preparation. The platform is used by over 20 million educators globally and supports content delivery in over 60 languages.',
 'https://edpuzzle.com', 'https://edpuzzle.com',
 'freemium', true, 0, 4.4, 4100, false, false, false,
 ARRAY['education', 'teacher-tools', 'e-learning'],
 ARRAY['AI question generation suggests comprehension checks at relevant video timestamps automatically', 'Works with any YouTube, Khan Academy, or uploaded video - no proprietary content library required', 'Student skip prevention ensures active video engagement rather than passive playback', 'Comprehension tracking dashboard identifies struggling students before the next class session'],
 ARRAY['AI question suggestions require teacher review - quality varies by video type and subject complexity', 'Video-centric format is less suitable for subjects where reading or hands-on practice is the primary learning mode', 'Free plan limits the number of videos that can be assigned per teacher per month', 'Embedded question format works best for informational and documentary video types - less effective for demonstration or tutorial videos'],
 ARRAY['Teachers implementing flipped classroom models who need comprehension accountability on assigned video homework', 'K-12 teachers embedding formative assessment into video-based lesson content without manual question authorship', 'Schools tracking student video engagement and comprehension performance at the individual student level'],
 NOW())

ON CONFLICT (slug) DO NOTHING;
