-- tools-batch-41.sql
-- 10 AI cybersecurity and developer security tools
-- Run BEFORE compare-batch-41.sql and session54-flags.sql

INSERT INTO tools (
  slug, name, tagline, description, logo_url, website_url, affiliate_url,
  tags, pricing_type, pricing_free_tier, pricing_starting_price,
  rating, review_count, featured, trending, editor_pick,
  pros, cons, use_cases
) VALUES

(
  'snyk',
  'Snyk',
  'Developer-first security platform for code, dependencies, containers, and IaC',
  'Snyk is a developer security platform that finds and fixes vulnerabilities in code, open source dependencies, container images, and infrastructure as code. It integrates directly into developer workflows - IDE plugins for VS Code and JetBrains, CLI scanning, GitHub and GitLab PR checks, and CI/CD pipeline integration - so security findings surface during development rather than after deployment. The dependency scanning engine maintains a proprietary vulnerability database updated continuously, covering npm, PyPI, Maven, Go modules, and a dozen other package ecosystems. Container scanning identifies vulnerable base images and provides remediation recommendations with specific version upgrades. License compliance scanning identifies open source licenses that may create legal obligations. For development teams, Snyk removes the friction of context-switching to a security tool by embedding security checks where developers already work. The Fix PRs feature automatically opens pull requests with remediation code, reducing the time from vulnerability detection to patch from days to minutes. The free tier covers unlimited tests for open source projects and a generous monthly limit for private repositories.',
  '',
  'https://snyk.io',
  'https://snyk.io',
  ARRAY['security', 'developer-tools'],
  'freemium',
  true,
  0.00,
  4.7,
  1834,
  false,
  false,
  false,
  ARRAY['Integrates into IDEs, GitHub, and CI/CD without disrupting developer workflow', 'Fix PRs automatically generate remediation pull requests', 'Proprietary vulnerability database updated faster than NVD', 'Covers code, dependencies, containers, and IaC in one platform'],
  ARRAY['Free tier limits can be restrictive for larger private codebases', 'Some false positives in static code analysis', 'Enterprise pricing scales up significantly with team size'],
  ARRAY['Scanning npm and PyPI dependencies for known vulnerabilities in CI/CD', 'Identifying vulnerable base images before pushing containers to production', 'Enforcing open source license compliance policies across the codebase']
),

(
  'wiz',
  'Wiz',
  'Agentless cloud security platform connecting risk across code, cloud, and runtime',
  'Wiz is a cloud security platform that scans cloud environments without requiring agents on every resource. It connects to AWS, Azure, Google Cloud, and OCI via API, building a graph of every resource, identity, network connection, and configuration across the environment. The Wiz Security Graph correlates multiple risk factors - a VM that is publicly exposed, running with overprivileged IAM, and containing a critical CVE - to identify the genuinely high-risk attack paths rather than generating thousands of uncontextualized findings. The CNAPP (Cloud-Native Application Protection Platform) capabilities span cloud security posture management (CSPM), workload protection, data security posture management (DSPM), and infrastructure as code scanning from a single platform. For engineering and security teams drowning in alerts, the contextualized risk approach means analysts work on the 10 findings that actually represent breach paths rather than the 10,000 that represent policy violations. Wiz does not publish pricing - contracts are based on cloud resource count and typically start in the six-figure range for enterprise deployments. Used by Morgan Stanley, BMW, LVMH, and Salesforce.',
  '',
  'https://wiz.io',
  'https://wiz.io',
  ARRAY['security', 'cloud'],
  'paid',
  false,
  0.00,
  4.8,
  1247,
  false,
  false,
  false,
  ARRAY['Agentless deployment scans entire cloud environment in hours, not months', 'Security Graph correlates risks to surface real attack paths, not just policy violations', 'Single platform covers CSPM, workload, data security, and IaC', 'Near-zero false positive rate reduces analyst alert fatigue significantly'],
  ARRAY['Enterprise-only pricing with no self-serve or SMB tier', 'Implementation requires cloud admin access which some organizations restrict', 'Deep feature set has a learning curve for security teams new to cloud security'],
  ARRAY['Identifying exploitable attack paths in multi-cloud environments without deploying agents', 'Data security posture management for sensitive data stored in cloud storage and databases', 'Continuous compliance monitoring for SOC 2, PCI DSS, HIPAA, and ISO 27001']
),

(
  'orca-security',
  'Orca Security',
  'Sidescanning cloud security platform with zero performance impact',
  'Orca Security uses SideScanning technology to read cloud workload data directly from the cloud provider API without agents, network scanners, or performance impact on running workloads. The platform detects vulnerabilities, misconfigurations, malware, lateral movement risks, and data exposure across VMs, containers, serverless functions, and managed services in AWS, Azure, and GCP. The Attack Path Analysis engine maps how a threat actor could move from internet exposure to sensitive data, prioritizing the specific combination of findings that constitute a real breach risk over isolated vulnerability counts. Orca integrates with Jira, ServiceNow, and Slack for alert routing, and with CI/CD pipelines for shift-left IaC scanning. The Unified Data Model stores all cloud security findings in a single queryable data lake, enabling custom queries for compliance and risk reporting. For organizations moving to cloud-first infrastructure who need visibility across hybrid and multi-cloud environments, Orca provides a complete inventory of every asset and its security posture without the operational overhead of agent management.',
  '',
  'https://orca.security',
  'https://orca.security',
  ARRAY['security', 'cloud'],
  'paid',
  false,
  0.00,
  4.6,
  892,
  false,
  false,
  false,
  ARRAY['SideScanning eliminates agent deployment and management overhead entirely', 'Attack Path Analysis connects exposure to actual breach risk', 'Full asset inventory includes resources other tools miss like serverless and managed databases', 'Single data model enables custom compliance queries across all cloud resources'],
  ARRAY['No agent means some runtime threat detection capabilities are limited compared to agent-based tools', 'Enterprise pricing without a self-serve SMB option', 'Deeper API integration required for some managed cloud services'],
  ARRAY['Cloud asset inventory and vulnerability management without agent deployment complexity', 'Compliance reporting for CIS benchmarks and regulatory frameworks across multi-cloud', 'Detecting sensitive data exposure in cloud storage buckets and database snapshots']
),

(
  'lacework',
  'Lacework',
  'AI-driven cloud-native application protection platform with behavioral threat detection',
  'Lacework is a cloud-native application protection platform (CNAPP) that uses machine learning to establish behavioral baselines for cloud workloads and detect anomalies that deviate from normal patterns. Rather than relying solely on known vulnerability signatures, the Polygraph behavioral analysis engine learns what normal looks like for each workload and surfaces activity that represents genuine threats - unusual process execution, unexpected network connections, and data access patterns that correlate with attacker behavior. The platform covers cloud security posture management, workload protection, container and Kubernetes security, infrastructure as code scanning, and software supply chain security from a single agent. Lacework integrates with major CI/CD platforms for shift-left scanning and provides runtime protection for cloud workloads with automatic incident investigation that correlates process, network, and file activity into coherent attack timelines. For security operations teams, the AI-driven alert consolidation reduces the noise from thousands of raw findings to dozens of high-confidence incidents requiring investigation.',
  '',
  'https://lacework.com',
  'https://lacework.com',
  ARRAY['security', 'cloud'],
  'paid',
  false,
  0.00,
  4.5,
  743,
  false,
  false,
  false,
  ARRAY['Behavioral ML detects zero-day and novel threats beyond known vulnerability signatures', 'Polygraph data platform correlates activity across host, network, and user for complete attack timelines', 'Single agent covers workload, container, and Kubernetes security', 'Significant alert reduction compared to signature-only tools'],
  ARRAY['Agent-based deployment requires rollout across every protected workload', 'Initial baseline learning period before behavioral detection reaches full accuracy', 'Enterprise-only pricing and sales-driven procurement process'],
  ARRAY['Runtime threat detection for cloud workloads using behavioral ML to catch novel attacks', 'Kubernetes security monitoring across cluster configuration and container runtime behavior', 'Correlating security incidents from infrastructure, identity, and network signals into unified timelines']
),

(
  'tenable-io',
  'Tenable',
  'Vulnerability management platform with exposure-based risk prioritization',
  'Tenable is a vulnerability management platform that scans infrastructure, cloud environments, web applications, and operational technology for known vulnerabilities, then prioritizes them by actual exploitability risk rather than raw CVSS score. The Vulnerability Priority Rating (VPR) system combines CVSS data with real-world threat intelligence - exploit availability, active threat actor usage, and asset criticality - to focus remediation on the vulnerabilities most likely to be exploited in the near term. Tenable.io covers on-premises infrastructure via authenticated and unauthenticated scanning, cloud environments via API connectors, and web application attack surface via DAST scanning. Tenable One extends the platform to an exposure management view connecting assets, identities, and vulnerabilities into a unified risk picture for executive reporting. Nessus, the underlying scanner with a 25-year history, remains the most widely deployed vulnerability scanner in enterprise environments. Organizations in regulated industries use Tenable as the primary evidence source for PCI DSS, HIPAA, and FedRAMP vulnerability management requirements.',
  '',
  'https://tenable.com',
  'https://tenable.com',
  ARRAY['security'],
  'paid',
  false,
  0.00,
  4.6,
  2156,
  false,
  false,
  false,
  ARRAY['VPR prioritization reduces remediation backlog by focusing on exploitable vulnerabilities', 'Nessus scanner has the broadest plugin coverage of any vulnerability scanner', 'Covers infrastructure, cloud, OT, and web applications in one platform', 'Strong compliance reporting for PCI DSS, HIPAA, FedRAMP, and CIS benchmarks'],
  ARRAY['Scanning large environments requires careful scheduling to avoid performance impact', 'Annual licensing is expensive for smaller organizations relative to alternatives', 'Web application scanning capabilities less deep than dedicated DAST tools'],
  ARRAY['Continuous vulnerability management across hybrid on-premises and cloud infrastructure', 'PCI DSS and HIPAA compliance reporting with automated evidence collection', 'OT and ICS security monitoring for industrial environments alongside IT infrastructure']
),

(
  'detectify',
  'Detectify',
  'Web application security scanner powered by an ethical hacker community',
  'Detectify is a web application security scanner that combines automated DAST scanning with a continuous stream of security tests written by a curated community of ethical hackers. The crowdsourced module library is updated within days of new CVE publication and includes attack logic for vulnerabilities that automated scanners miss - business logic flaws, authentication bypasses, and application-specific misconfigurations. Surface Monitoring maps the full external attack surface from a domain name, discovering subdomains, APIs, and exposed applications that teams may not know exist. The scanner authenticates to applications and tests logged-in functionality, covering modern web applications built on JavaScript frameworks and APIs rather than just crawlable static content. For development teams doing continuous deployment, Detectify integrates with CI/CD pipelines to test each deployment against the current vulnerability module library. At $89 per month for the Starter plan, it is positioned between free open source scanners and enterprise DAST platforms.',
  '',
  'https://detectify.com',
  'https://detectify.com',
  ARRAY['security'],
  'paid',
  false,
  89.00,
  4.4,
  567,
  false,
  false,
  false,
  ARRAY['Crowdsourced vulnerability modules updated faster than any single vendor research team', 'Surface Monitoring discovers unknown assets and shadow IT exposure', 'Authenticated scanning covers modern SPA and API surfaces', 'CI/CD integration enables continuous security testing on every deployment'],
  ARRAY['No free tier - minimum $89/month makes it inaccessible for individual developers', 'Crawler can miss complex client-side JavaScript application flows', 'Module library is strong for web vulnerabilities but does not cover infrastructure or code'],
  ARRAY['External attack surface discovery and monitoring for unknown assets and subdomains', 'Continuous DAST testing in CI/CD pipelines for web applications and APIs', 'Pre-launch security testing for new web products before public release']
),

(
  'aikido-security',
  'Aikido Security',
  'Developer-first all-in-one security platform covering code to cloud',
  'Aikido Security is a developer-first platform that consolidates SAST, SCA, container scanning, cloud configuration, and secret detection into a single tool with a clean interface optimized for development teams rather than security operations centers. The platform connects to GitHub, GitLab, or Bitbucket repositories and runs automated scans on every pull request, surfacing findings directly in the PR review workflow. The noise reduction approach is central to the product: Aikido cross-references findings from multiple scanners, deduplicates overlapping results, and applies reachability analysis to filter out vulnerabilities in code that cannot actually be executed in the runtime environment. This approach reduces finding volume by 80 percent compared to running the individual scanners separately. For startups and scale-ups building compliance programs for SOC 2 or ISO 27001 that need security tooling without a dedicated security team, Aikido provides the breadth of coverage in a single tool that previously required four or five separate point solutions. A limited free plan is available for small teams; paid plans start at $59 per month.',
  '',
  'https://aikido.dev',
  'https://aikido.dev',
  ARRAY['security', 'developer-tools'],
  'freemium',
  true,
  59.00,
  4.5,
  412,
  false,
  false,
  false,
  ARRAY['Consolidates SAST, SCA, secrets, containers, and cloud in one tool', 'Reachability analysis filters unreachable vulnerabilities to cut noise by 80 percent', 'Clean developer-focused interface designed for engineering teams, not SOC analysts', 'Competitive pricing for full coverage makes it viable for startups building compliance programs'],
  ARRAY['Newer platform with less enterprise track record than established SAST vendors', 'Some advanced SAST rules are less comprehensive than dedicated static analysis tools', 'Cloud configuration scanning covers major clouds but not all edge cases'],
  ARRAY['Building SOC 2 or ISO 27001 security programs for startups without a dedicated security team', 'PR-level security feedback that keeps findings in the developer workflow without context switching', 'Reducing vulnerability noise by running consolidated scanning instead of multiple separate tools']
),

(
  'socket-dev',
  'Socket',
  'Supply chain security for open source packages that detects malicious code before install',
  'Socket analyzes open source npm, PyPI, and Go packages for supply chain security risks before they are installed into a codebase. Where vulnerability scanners detect known CVEs after the fact, Socket reads actual package source code to detect malicious behavior: unexpected network connections, file system writes outside the package scope, obfuscated code, and install scripts that execute code at install time. The GitHub app blocks pull requests that introduce packages with supply chain risk signals, with explanations of exactly what behavior triggered the block. The package health scoring covers maintenance activity, contributor count, dependency tree depth, and typosquatting risk - factors that predict future vulnerability risk even for packages with no current CVEs. For engineering teams, Socket answers the question vulnerability scanners do not: is this package itself trustworthy, independent of whether it has a known CVE today. A free plan covers unlimited public repositories; paid plans start at $19 per developer per month.',
  '',
  'https://socket.dev',
  'https://socket.dev',
  ARRAY['security', 'developer-tools'],
  'freemium',
  true,
  19.00,
  4.5,
  389,
  false,
  false,
  false,
  ARRAY['Detects malicious packages from source code analysis, not just CVE matching', 'GitHub PR blocking prevents supply chain attacks before code merges', 'Package health scoring predicts future risk beyond current vulnerability status', 'Free tier for public repositories makes it accessible for open source maintainers'],
  ARRAY['Coverage limited to npm, PyPI, and Go - Maven, NuGet, and other ecosystems are roadmap', 'Some legitimate packages trigger warnings due to install scripts that require allowlisting', 'Complementary to but does not replace SCA tools for known vulnerability scanning'],
  ARRAY['Detecting malicious open source packages in the npm registry before they reach production', 'Enforcing supply chain security policies across engineering teams via GitHub PR checks', 'Auditing dependency trees for packages with characteristics that predict future compromise']
),

(
  'vulcan-cyber',
  'Vulcan Cyber',
  'Vulnerability remediation orchestration platform connecting security findings to engineering workflows',
  'Vulcan Cyber aggregates vulnerability findings from across the security tool stack - Tenable, Qualys, Snyk, Wiz, and 100 other scanners - into a unified risk view with context-aware prioritization and automated remediation workflow management. The platform addresses the gap between security teams that find vulnerabilities and engineering teams that fix them: findings are automatically mapped to asset owners, enriched with business context and SLA requirements, and tracked through Jira or ServiceNow tickets to resolution. The risk-based prioritization engine combines CVSS scores, exploit availability, asset criticality, and compensating control context to generate a remediation priority score that reflects actual business risk rather than raw vulnerability count. For large organizations running multiple security scanners across hybrid infrastructure, Vulcan provides the single view of remediation status that previously required manual aggregation across tool dashboards. Pricing is enterprise with no public list price.',
  '',
  'https://vulcan.io',
  'https://vulcan.io',
  ARRAY['security'],
  'paid',
  false,
  0.00,
  4.3,
  298,
  false,
  false,
  false,
  ARRAY['Aggregates findings from 100+ security tools into a single prioritized remediation queue', 'Automated ticket creation maps findings to asset owners without manual triage', 'Risk-based prioritization factors in business context beyond raw CVSS scores', 'SLA tracking provides accountability for remediation timelines across engineering teams'],
  ARRAY['Requires integration setup with each existing security tool in the stack', 'Enterprise-only pricing is not suitable for smaller organizations', 'Value is proportional to number of integrated tools - limited benefit for organizations using few scanners'],
  ARRAY['Consolidating vulnerability findings from multiple scanners into a single prioritized remediation backlog', 'Automating Jira ticket creation and routing to the right engineering team for each finding', 'SLA-based reporting on remediation velocity for executive and compliance reporting']
),

(
  'cycode',
  'Cycode',
  'Complete Application Security Posture Management platform from code to deployment',
  'Cycode is an Application Security Posture Management (ASPM) platform that provides unified visibility into the security posture of every phase of the software development lifecycle. The platform covers secret detection in code and git history, SAST for code vulnerabilities, SCA for dependency risks, IaC scanning for misconfigurations, and container security - all correlated in a single risk graph that maps how a code-level issue becomes a production risk. The ASPM layer aggregates findings from Cycode native scanners and third-party tools, normalizes them into a common data model, and applies AI-driven correlation to surface attack paths that span multiple tools and phases. The developer portal presents each developer with the security findings relevant to their code and the remediation guidance to fix them without requiring a security team intermediary. For engineering organizations mature enough to run multiple security tools but struggling with finding correlation and remediation prioritization, Cycode provides the unifying layer. A free plan is available for small teams; enterprise contracts for full ASPM capabilities.',
  '',
  'https://cycode.com',
  'https://cycode.com',
  ARRAY['security', 'developer-tools'],
  'freemium',
  true,
  0.00,
  4.4,
  334,
  false,
  false,
  false,
  ARRAY['ASPM approach correlates findings across all SDLC phases in a single risk graph', 'Covers secrets, SAST, SCA, IaC, and containers in one platform', 'Developer portal delivers personalized finding queues without security team bottleneck', 'AI-driven attack path analysis surfaces multi-tool risk chains'],
  ARRAY['Full ASPM capabilities require enterprise contract - free plan is limited to basic scanning', 'Newer category means some integrations with legacy tools are still maturing', 'ASPM value proposition requires organizational buy-in across security and engineering leadership'],
  ARRAY['Unifying security findings across multiple existing tools into a single SDLC risk view', 'Secret detection and remediation in git history before credentials reach production', 'Measuring application security posture across engineering teams for security program reporting']
)

ON CONFLICT (slug) DO NOTHING;
