-- tools-batch-39.sql
-- 10 AI recruitment and HR tech tools
-- Run AFTER tools-batch-38.sql is confirmed in DB
-- All slugs verified absent from tools-batch-1 through tools-batch-38

INSERT INTO tools (
  slug, name, tagline, description,
  logo_url, website_url, affiliate_url,
  tags, pricing_type, pricing_free_tier, pricing_starting_price,
  rating, review_count, featured, trending, editor_pick,
  pros, cons, use_cases,
  created_at
) VALUES

('greenhouse', 'Greenhouse', 'Structured hiring software that builds fairer, more predictable recruiting pipelines',
 'Greenhouse is a recruiting platform designed around structured hiring - the practice of defining evaluation criteria before sourcing begins, applying them consistently to every candidate, and removing bias from hiring decisions through process design rather than willpower. Every job opening in Greenhouse starts with a defined scorecard listing the competencies and skills required. Interviewers score candidates against the same criteria using the same scale. The result is a dataset that predicts which attributes correlate with high performance at your company over time. Greenhouse integrations connect to 450+ HR tools including Slack, LinkedIn, Workday, and BambooHR, making it the center of gravity for most enterprise recruiting stacks. The CRM features let recruiting teams nurture passive candidates with targeted content, tracking engagement before a role opens. Greenhouse is used by companies including HubSpot, Squarespace, and Airbnb. For teams that are serious about reducing bias, improving offer acceptance rates, and building a predictable hiring engine, Greenhouse is the most mature platform in the category.',
 'https://www.google.com/s2/favicons?domain=greenhouse.io&sz=64',
 'https://greenhouse.io', 'https://greenhouse.io',
 ARRAY['recruiting', 'hr-tech'],
 'paid', false, 0.00,
 4.5, 2841, false, false, false,
 ARRAY['Structured hiring scorecards reduce interview bias', 'Rich integration ecosystem - 450+ HR tools', 'CRM features for passive candidate nurturing', 'Strong analytics on pipeline conversion and source quality'],
 ARRAY['Enterprise pricing - not suitable for early-stage startups', 'Setup and configuration requires dedicated TA ops time', 'Reporting customization has a learning curve'],
 ARRAY['Running structured hiring at mid-market and enterprise scale', 'Building candidate pipelines before roles open via CRM', 'Tracking source quality and time-to-hire analytics'],
 NOW()),

('lever', 'Lever', 'Applicant tracking and CRM combined for relationship-first recruiting',
 'Lever combines an applicant tracking system and candidate relationship management into a single platform, built on the premise that every candidate is a future hire or future customer. The unified database means a candidate rejected for one role is automatically considered for future openings rather than lost in a folder. Lever Nurture runs automated email sequences to keep passive candidates warm over months - a critical capability in competitive hiring markets where the best candidates are rarely actively looking. The visual pipeline is clean and intuitive, making it accessible to hiring managers who interact with Lever occasionally rather than daily. AI features include automated job description writing, candidate fit scoring, and resume parsing that populates candidate profiles without manual data entry. Analytics dashboards track EEOC data, pipeline conversion by stage, and interviewer-specific pass-through rates. Lever is particularly popular at growth-stage tech companies and scale-ups that are hiring across multiple roles simultaneously and need recruiting to operate as a revenue function rather than an administrative one.',
 'https://www.google.com/s2/favicons?domain=lever.co&sz=64',
 'https://lever.co', 'https://lever.co',
 ARRAY['recruiting', 'hr-tech'],
 'paid', false, 0.00,
 4.4, 1938, false, false, false,
 ARRAY['CRM and ATS in one platform - no separate tools needed', 'Lever Nurture automates passive candidate engagement', 'Clean visual pipeline accessible to non-recruiters', 'Strong EEOC and DEI reporting'],
 ARRAY['Custom enterprise pricing - no self-serve plan', 'Some reporting requires help from Lever support to configure', 'Mobile app less capable than desktop'],
 ARRAY['Managing high-volume hiring across 20+ open roles simultaneously', 'Running passive candidate nurture campaigns for hard-to-fill roles', 'Tracking DEI metrics and EEOC compliance data'],
 NOW()),

('ashby', 'Ashby', 'All-in-one hiring platform with the best analytics in the category',
 'Ashby is a modern all-in-one recruiting platform that combines ATS, CRM, scheduling, and analytics in a single product. Where it stands out is analytics: Ashby tracks recruiting metrics at a depth that legacy platforms cannot match, including interviewer-level throughput, source-of-hire attribution down to campaign level, and offer acceptance rates segmented by role, team, and salary band. The scheduling module handles complex interview loops automatically - sending availability requests, coordinating panel schedules, and sending confirmation emails without recruiter coordination. The AI writing assistant generates job descriptions, candidate outreach emails, and interview plans from a brief. Ashby is a favorite at high-growth startups that need enterprise-grade data without the enterprise price tag or implementation complexity of Greenhouse or Workday Recruiting. Companies like Notion, Linear, Vercel, and Brex use Ashby. For recruiting operations teams that run on data and want to improve hiring quality through measurement rather than intuition, Ashby is the most powerful option currently available.',
 'https://www.google.com/s2/favicons?domain=ashbyhq.com&sz=64',
 'https://ashbyhq.com', 'https://ashbyhq.com',
 ARRAY['recruiting', 'hr-tech'],
 'paid', false, 0.00,
 4.7, 847, true, true, false,
 ARRAY['Best recruiting analytics in the market by a significant margin', 'Automated interview scheduling that handles complex panel loops', 'All-in-one: ATS, CRM, scheduling, analytics in one product', 'Favored by high-growth tech companies for data-driven hiring'],
 ARRAY['Newer platform - fewer integrations than Greenhouse', 'Pricing is competitive but not cheap for small teams', 'Some advanced features require onboarding support'],
 ARRAY['Building data-driven recruiting operations at high-growth startups', 'Automating complex multi-stage interview scheduling loops', 'Tracking source ROI and interviewer performance at depth'],
 NOW()),

('rippling', 'Rippling', 'HR, IT, and Finance unified in one workforce platform',
 'Rippling is a workforce management platform that unifies HR, IT, and Finance in a single system. When a new hire is added in Rippling, the platform automatically provisions their laptop software, email account, Slack access, and payroll - without any manual coordination between HR and IT. This automated provisioning and deprovisioning is the defining differentiator: when an employee leaves, Rippling deactivates all their access simultaneously with their last day. The PEO option allows small companies to offer Fortune 500 benefits by pooling with Rippling employees. Global payroll runs in 50+ countries from the same interface as US payroll. The ATS module handles recruiting, and an LMS handles onboarding and compliance training. For startups scaling from 10 to 500 employees where HR processes are being built for the first time, Rippling reduces the administrative overhead of managing multiple disconnected HR, payroll, and IT systems. Rippling is priced per employee per month and scales with headcount.',
 'https://www.google.com/s2/favicons?domain=rippling.com&sz=64',
 'https://rippling.com', 'https://rippling.com',
 ARRAY['hr-tech', 'productivity'],
 'paid', false, 8.00,
 4.6, 3124, false, true, false,
 ARRAY['Automatic software provisioning when new hires are onboarded', 'Unified HR, IT, and Finance in one platform', 'Global payroll in 50+ countries', 'PEO option for competitive benefits at small company scale'],
 ARRAY['Can be complex to configure for non-standard workflows', 'Customer support response times vary', 'Full value requires using HR, IT, and Finance modules together'],
 ARRAY['Automating IT provisioning and deprovisioning for growing teams', 'Running global payroll and benefits from a single system', 'Building HR infrastructure at startups scaling from 10 to 500 people'],
 NOW()),

('bamboohr', 'BambooHR', 'HR software built specifically for small and medium businesses',
 'BambooHR is an HR information system designed for the 10-to-500 employee range, covering employee records, onboarding, time tracking, performance management, and basic payroll. Where enterprise platforms like Workday or SAP SuccessFactors are overkill for SMBs, BambooHR provides the core HR capabilities a growing company needs without the implementation complexity or per-module pricing. The self-service portal lets employees update their own information, request time off, and complete onboarding checklists - reducing routine HR administrative tasks. Performance management features include goal setting, 360-degree feedback, and automated review scheduling. The ATS handles basic recruiting workflows for companies hiring at a moderate pace. Reporting covers headcount, turnover, time-to-hire, and compensation analysis with export to Excel or direct visualization. BambooHR is not the most feature-rich HR platform, but it is consistently rated the highest for ease of use and customer support in the SMB segment, making it the default choice for first-time HR software buyers.',
 'https://www.google.com/s2/favicons?domain=bamboohr.com&sz=64',
 'https://bamboohr.com', 'https://bamboohr.com',
 ARRAY['hr-tech', 'productivity'],
 'paid', false, 0.00,
 4.5, 2673, false, false, false,
 ARRAY['Purpose-built for SMB - not a stripped-down enterprise tool', 'Consistently top-rated for ease of use and customer support', 'Employee self-service reduces routine HR admin work', 'Strong onboarding checklists and e-signature for new hire paperwork'],
 ARRAY['Payroll is a paid add-on, not included in base price', 'Limited customization compared to enterprise HRIS platforms', 'ATS is basic - not suitable for high-volume or complex hiring'],
 ARRAY['Centralizing employee records for companies with 10-500 employees', 'Automating onboarding paperwork and checklists for new hires', 'Running performance reviews and goal tracking without spreadsheets'],
 NOW()),

('goodtime', 'GoodTime', 'AI-powered interview scheduling that eliminates recruiter coordination overhead',
 'GoodTime automates the most time-consuming part of recruiting: interview scheduling. For a candidate moving through a 4-stage loop with a panel of 6 interviewers, scheduling can consume hours of recruiter time per candidate across email chains, calendar conflicts, and rescheduling requests. GoodTime replaces this entirely by reading interviewer availability, applying scheduling preferences (no back-to-back, no early morning), and sending candidates a self-scheduling link that respects all constraints automatically. When a candidate reschedules, GoodTime recalculates the entire loop. Interviewer pools ensure that no single interviewer is overburdened and that diversity of perspective is maintained across panels. Hiring velocity analytics show which interview stages cause the most drop-off and delay, giving recruiting teams data to optimize their processes. Companies using GoodTime report significant reductions in time-to-schedule and scheduler workload. For recruiting operations at companies hiring 50+ people per quarter, the time savings justify the cost immediately.',
 'https://www.google.com/s2/favicons?domain=goodtime.io&sz=64',
 'https://goodtime.io', 'https://goodtime.io',
 ARRAY['recruiting', 'scheduling'],
 'paid', false, 0.00,
 4.6, 412, false, true, false,
 ARRAY['Eliminates manual interview scheduling across complex panel loops', 'Interviewer pool management prevents overburdening top interviewers', 'Candidate self-scheduling with real-time calendar sync', 'Hiring velocity analytics pinpoint scheduling bottlenecks'],
 ARRAY['Enterprise pricing - not cost-effective for low-volume hiring', 'Setup requires integration with your ATS and calendar systems', 'Most value at 50+ hires per quarter scale'],
 ARRAY['Automating panel interview scheduling for high-volume tech recruiting', 'Reducing coordinator workload when scheduling complex multi-stage loops', 'Tracking interviewer load balance and scheduling SLA metrics'],
 NOW()),

('beamery', 'Beamery', 'Talent lifecycle platform for strategic workforce planning',
 'Beamery is a talent lifecycle platform that covers three interconnected problems: talent acquisition, talent management, and workforce planning. The AI layer - called TalentGPT - powers skills inference, career pathing recommendations, and talent intelligence that connects internal mobility with external recruiting. When a role opens, Beamery can identify internal candidates likely to succeed before going external. When a candidate applies, it surfaces historical engagement data from previous interactions. The skills taxonomy engine maps every employee and candidate to a standardized skills ontology, enabling workforce planning based on skill gaps rather than headcount spreadsheets. Beamery is built for large enterprises - companies with thousands of employees and complex internal mobility needs where the cost of external hiring versus internal development is a strategic CFO-level question. Clients include Spotify, American Airlines, and EY. For mid-market companies or straightforward ATS needs, Beamery is overkill. For enterprises treating talent as strategic infrastructure, it is one of the most sophisticated platforms available.',
 'https://www.google.com/s2/favicons?domain=beamery.com&sz=64',
 'https://beamery.com', 'https://beamery.com',
 ARRAY['recruiting', 'hr-tech'],
 'paid', false, 0.00,
 4.3, 287, false, false, false,
 ARRAY['TalentGPT connects internal mobility with external recruiting', 'Skills taxonomy enables workforce planning by skill gap', 'Covers full talent lifecycle from acquisition to development', 'Purpose-built for large enterprise complexity'],
 ARRAY['Enterprise-only pricing and implementation timeline', 'Significant configuration required to match skills taxonomy to your organization', 'ROI requires sustained program management investment'],
 ARRAY['Strategic workforce planning based on skills gap analysis', 'Connecting internal mobility to external recruiting to reduce cost-per-hire', 'Building a talent intelligence layer across a large enterprise'],
 NOW()),

('eightfold', 'Eightfold AI', 'Deep learning talent intelligence for skills-based hiring and retention',
 'Eightfold AI is a talent intelligence platform built on a deep learning model trained on hundreds of millions of career trajectories. The core insight is skills inference: Eightfold can determine what skills a person likely has based on their career path, even if those skills are not listed on their resume, and match them to roles requiring those skills. For hiring, this means surfacing candidates who would succeed in a role but might not apply because the job description does not match their self-description. For retention, it identifies employees at risk of leaving based on career trajectory patterns and surfaces internal opportunities before they look elsewhere. The platform integrates with most major ATS systems as an intelligence layer on top of existing workflows. Eightfold is particularly effective for companies that want to implement skills-based hiring - removing degree requirements and focusing on demonstrated capability - and need AI to make that operationally viable at scale. Used by major enterprises across financial services, healthcare, and technology.',
 'https://www.google.com/s2/favicons?domain=eightfold.ai&sz=64',
 'https://eightfold.ai', 'https://eightfold.ai',
 ARRAY['recruiting', 'hr-tech'],
 'paid', false, 0.00,
 4.4, 531, false, true, false,
 ARRAY['Skills inference from career trajectories - not just listed skills', 'Identifies at-risk employees and surfaces internal opportunities', 'Enables skills-based hiring by removing reliance on credentials', 'Deep learning trained on hundreds of millions of career paths'],
 ARRAY['Enterprise platform - complex implementation and significant investment', 'Effectiveness depends on data quality and integration depth', 'Benefits compound over time - slower ROI for recent adopters'],
 ARRAY['Implementing skills-based hiring to reduce credential bias', 'Predicting employee flight risk and enabling proactive retention', 'Building internal mobility programs at large enterprises'],
 NOW()),

('seekout', 'SeekOut', 'AI talent search for finding diverse and hard-to-find candidates',
 'SeekOut is a talent search platform that helps recruiters find and engage candidates who are difficult to reach through standard job boards. Its database indexes over 800 million professional profiles from GitHub, LinkedIn, medical databases, patent filings, and academic publications - making it particularly effective for technical and scientific roles. Diversity filters allow recruiters to build pipelines with targeted representation goals, with gender and ethnicity signals derived from public profile data and name analysis. GitHub profile analysis identifies software engineers by their actual code contributions, open-source projects, and programming language expertise - more accurate signals for technical hiring than a resume. SeekOut Grow adds internal talent management features for retention and internal mobility. The platform competes directly with LinkedIn Recruiter on sourcing but differentiates through diversity data, technical signals, and niche talent pools that LinkedIn does not cover (researchers, physicians, patent holders). Pricing is competitive for the data quality delivered.',
 'https://www.google.com/s2/favicons?domain=seekout.io&sz=64',
 'https://seekout.io', 'https://seekout.io',
 ARRAY['recruiting', 'hr-tech'],
 'paid', false, 0.00,
 4.5, 619, false, false, false,
 ARRAY['800M+ profiles including GitHub, academic, and medical databases', 'Diversity filters with gender and ethnicity signals', 'GitHub analysis identifies engineers by actual code contributions', 'Covers talent pools LinkedIn Recruiter does not reach'],
 ARRAY['Pricing comparable to LinkedIn Recruiter - not a budget option', 'Diversity signal accuracy depends on inference from limited data points', 'Contact information quality varies by candidate type'],
 ARRAY['Sourcing software engineers through GitHub contribution analysis', 'Building diverse candidate pipelines with measurable representation targets', 'Finding niche talent - researchers, physicians, patent holders - outside LinkedIn'],
 NOW()),

('metaview', 'Metaview', 'AI interview notes that let interviewers focus on the candidate',
 'Metaview records and transcribes interviews, then uses AI to generate structured interview notes automatically - aligned to the scorecard criteria defined in your ATS. Rather than interviewers taking notes during a conversation (which splits attention and degrades interview quality), Metaview captures everything and presents a summary: candidate answers to each scorecard question, key quotes, and a structured evaluation the interviewer can approve or edit. The AI does not score candidates - it organizes evidence so the interviewer can score with full context rather than reconstructed memory. Integrations with Greenhouse, Lever, and Ashby push notes directly to the candidate record, reducing post-interview admin from 20 minutes to under 2 minutes. For recruiting teams that care about interview quality, Metaview addresses a real problem: interviewers who take notes miss non-verbal signals; those who do not forget details by debrief. The result is more consistent hiring decisions based on actual evidence rather than recency bias.',
 'https://www.google.com/s2/favicons?domain=metaview.ai&sz=64',
 'https://metaview.ai', 'https://metaview.ai',
 ARRAY['recruiting', 'ai-assistants'],
 'paid', false, 0.00,
 4.6, 284, false, true, false,
 ARRAY['AI-generated interview notes aligned to scorecard criteria', 'Interviewers stay present in conversation instead of typing notes', 'Direct ATS integration - notes push to Greenhouse, Lever, Ashby', 'Reduces post-interview admin from 20 minutes to under 2 minutes'],
 ARRAY['Candidate consent and recording disclosure required (varies by jurisdiction)', 'Value depends on structured hiring process being in place', 'AI note quality varies with audio clarity and interview format'],
 ARRAY['Improving interview quality by letting interviewers focus on candidates', 'Reducing post-interview admin for high-volume recruiting teams', 'Standardizing interview evidence capture for structured hiring programs'],
 NOW())

ON CONFLICT (slug) DO NOTHING;
