-- tools-batch-14.sql - 10 new tools (DB: 162 to 172)
-- Run in Supabase SQL Editor
-- All inserts use ON CONFLICT DO NOTHING (idempotent)

INSERT INTO tools (slug, name, tagline, description, logo_url, website_url, affiliate_url, tags, pricing_type, pricing_free_tier, pricing_starting_price, rating, review_count, featured, trending, editor_pick, pros, cons, use_cases, updated_at) VALUES

('superhuman', 'Superhuman', 'The fastest AI-powered email client for high-volume inboxes', 'Superhuman is an AI-powered email client that rebuilds the inbox experience from the ground up for speed and focus. Built on keyboard shortcuts, instant performance, and AI-assisted triage, it processes email faster than any native app. The AI Triage feature surfaces important messages, auto-summarizes long threads, and drafts replies in your writing style - cutting inbox time by an average of four hours per week for most users.

The tool is designed for executives, founders, and professionals who treat inbox zero as a productivity discipline. Superhuman integrates with Gmail and Outlook, preserving your existing email address while replacing the interface entirely. Features like Snippets (saved reply templates), Read Statuses (open tracking), and Follow-up Reminders give power users granular control over their communication workflow. At $30 per month, it is a premium product aimed at users for whom reclaimed hours justify the cost.',
'https://www.google.com/s2/favicons?domain=superhuman.com&sz=64', 'https://superhuman.com', 'https://superhuman.com', ARRAY['productivity'], 'paid', false, 30, 4.4, 423, false, false, false, ARRAY['AI triage surfaces high-priority emails automatically', 'Keyboard-first design is significantly faster than Gmail', 'Read Statuses show when recipients open your emails', 'AI drafts replies in your personal writing style'], ARRAY['No free plan - $30/month minimum', 'Gmail and Outlook only - no IMAP support for other providers', 'Steep learning curve for keyboard-shortcut workflow'], ARRAY['Executives managing 200+ emails per day', 'Sales professionals tracking outreach response rates', 'Founders and operators who batch email as a single daily workflow'], NOW()),

('klap', 'Klap', 'AI video clipper that turns long videos into short-form content', 'Klap is an AI video repurposing tool that automatically clips long-form video content into short, platform-ready segments for TikTok, Instagram Reels, and YouTube Shorts. Upload a video or paste a YouTube URL and Klap analyzes the transcript, identifies the most engaging moments, adds animated captions, and exports multiple clips in the correct vertical format. The process takes minutes rather than the hours required to manually clip and caption content.

Content creators, podcasters, and social media managers use Klap to multiply the reach of every video they produce without extra production time. The AI understands hook quality, pacing, and viewer retention patterns to prioritize clips most likely to perform on short-form platforms. Klap supports podcast recordings, webinars, YouTube videos, and course content as input. For creators already producing long-form video who want a short-form presence without a separate editing workflow, Klap is one of the most practical repurposing tools available.',
'https://www.google.com/s2/favicons?domain=klap.app&sz=64', 'https://klap.app', 'https://klap.app', ARRAY['video-ai'], 'freemium', true, 29, 4.3, 287, false, true, false, ARRAY['Fully automated clip selection from long videos', 'Animated captions added automatically in vertical format', 'Processes hours of video in minutes', 'Works with YouTube URLs - no upload required'], ARRAY['Free plan limits monthly video minutes', 'AI clip selection sometimes misses best moments', 'Caption styling options are limited on lower plans'], ARRAY['Repurposing podcast episodes into TikTok and Reels clips', 'Creating YouTube Shorts from long-form YouTube content', 'Generating social content from webinars and online events'], NOW()),

('d-id', 'D-ID', 'AI talking avatar videos from photos and scripts', 'D-ID is an AI video generation platform specializing in realistic talking avatar videos from a still image and audio or text input. Users upload a portrait photo, provide a script or select a text-to-speech voice, and D-ID generates a video of the subject speaking with natural lip sync, facial animation, and head movement. The technology is used for AI-generated presenters, digital twins, customer service avatars, and multilingual video content at scale.

Creative Reality Studio, D-ID''s main product, targets marketing teams, e-learning developers, and enterprise organizations that need talking-head videos without on-camera talent. The platform supports over 100 languages and can generate videos from AI-generated characters, brand mascots, or real people with consent. For content teams that produce training materials, product explainers, or customer-facing video at high volume, D-ID offers a practical path to production-quality talking-head video without scheduling a film crew.',
'https://www.google.com/s2/favicons?domain=d-id.com&sz=64', 'https://www.d-id.com', 'https://www.d-id.com', ARRAY['video-ai'], 'freemium', true, 6, 4.2, 334, false, false, false, ARRAY['Realistic lip sync with natural facial animation', 'Supports 100+ languages for multilingual content', 'Works from any portrait photo - no live recording needed', 'API available for enterprise-scale video generation'], ARRAY['Free tier has strict per-month credit limits', 'Output quality drops with low-resolution input photos', 'Less control over avatar emotion and expression vs. competitors'], ARRAY['Creating multilingual explainer videos without re-recording', 'Producing training and onboarding videos at scale', 'Building AI-generated spokesperson content for marketing'], NOW()),

('readwise', 'Readwise', 'AI-powered reader that helps you retain everything you read', 'Readwise is an AI-powered reading tool that helps you retain and reconnect with everything you read across books, articles, newsletters, podcasts, and PDFs. It aggregates highlights from Kindle, Instapaper, Pocket, and web articles into a single library, then resurfaces them via daily digests and a spaced repetition review system. The Readwise Reader app adds full-featured read-it-later functionality with AI summarization, note-taking, and document-level chat directly in the reading view.

Knowledge workers, researchers, and avid readers use Readwise to build a searchable, annotated library of everything they consume online. The AI can summarize documents, answer questions about a book based on your highlights, and surface related notes across your entire reading history. For professionals who read extensively but struggle to act on what they learn, Readwise bridges the gap between passive reading and active knowledge retention. The tool pairs well with note-taking systems like Obsidian, Notion, and Roam Research via native export integrations.',
'https://www.google.com/s2/favicons?domain=readwise.io&sz=64', 'https://readwise.io', 'https://readwise.io', ARRAY['productivity'], 'freemium', true, 8, 4.6, 512, false, false, false, ARRAY['Aggregates highlights from Kindle, Pocket, Instapaper in one place', 'Spaced repetition resurfaces key ideas you have already read', 'AI Reader app with document chat and summarization', 'Integrates with Obsidian, Notion, and Roam for PKM workflows'], ARRAY['Reader app is separate from the core highlights product', 'Free plan is limited - full value requires paid subscription', 'Mobile app for reading can feel slower than native apps'], ARRAY['Building a searchable library of highlights across all reading', 'Retaining key insights from books and research papers', 'AI-assisted reading of PDFs and research documents'], NOW()),

('vizard', 'Vizard', 'AI video repurposing platform for short-form social content', 'Vizard is an AI video repurposing platform that transforms long-form recordings into multiple short-form clips optimized for social media. Upload a video or import from YouTube and Vizard automatically identifies key moments, generates captions, resizes for vertical formats, and produces clips ready for TikTok, Instagram, LinkedIn, and YouTube Shorts. The platform processes video faster than real-time and lets users refine selections or manually clip sections using a browser-based editor.

Marketing teams, course creators, and content agencies use Vizard to scale video repurposing across multiple clients and platforms. The AI analyzes speaker segments, topic transitions, and engagement patterns to select clips most likely to retain viewers. Vizard supports pre-recorded content and live stream recordings from Zoom and StreamYard. For organizations publishing regular video content who want consistent short-form output without a dedicated editor, Vizard offers batch processing and team collaboration features at a per-minute pricing model.',
'https://www.google.com/s2/favicons?domain=vizard.ai&sz=64', 'https://vizard.ai', 'https://vizard.ai', ARRAY['video-ai'], 'freemium', true, 19, 4.2, 198, false, false, false, ARRAY['Batch processes multiple videos simultaneously', 'Auto-generates captions and resizes for all social formats', 'Team collaboration features for agency workflows', 'Imports directly from YouTube and Zoom recordings'], ARRAY['Free plan has tight minute limits per month', 'AI clip selection can miss context-dependent highlights', 'Export quality limited on lower pricing tiers'], ARRAY['Repurposing webinar recordings into social clips', 'Creating LinkedIn video content from long-form interviews', 'Scaling short-form video output for marketing agencies'], NOW()),

('chatpdf', 'ChatPDF', 'Chat with any PDF using AI - summaries, questions, citations', 'ChatPDF is a tool that lets you upload any PDF and have a conversation with it using AI. Ask questions, request summaries, extract specific data points, and get citations linked to the source page in the document. The tool works with research papers, contracts, textbooks, and financial reports, returning answers grounded in the document rather than general AI knowledge. Claims are referenced to specific passages, making it useful for fact-checking and document review.

Students, researchers, and professionals use ChatPDF to process large documents faster than manual reading allows. A 200-page annual report can be summarized in minutes, and specific clauses in a legal contract can be located by asking plain-language questions. The free tier allows a limited number of PDFs and pages per day, with paid plans removing limits and enabling larger files. For users who regularly process dense professional or academic documents, ChatPDF reduces document review time by replacing keyword search with conversational retrieval.',
'https://www.google.com/s2/favicons?domain=chatpdf.com&sz=64', 'https://www.chatpdf.com', 'https://www.chatpdf.com', ARRAY['productivity'], 'freemium', true, 5, 4.1, 423, false, false, false, ARRAY['Answers questions with citations linked to source pages', 'Works immediately - no setup or account required on free plan', 'Handles research papers, contracts, reports, and textbooks', 'Multi-language support for non-English documents'], ARRAY['Free plan limits PDF size and daily uploads', 'Accuracy drops on scanned or image-based PDFs', 'No persistent document library on free plan'], ARRAY['Reviewing and summarizing long research papers quickly', 'Extracting specific clauses from legal or compliance documents', 'Studying textbooks by asking questions about chapter content'], NOW()),

('remove-bg', 'Remove.bg', 'AI background removal tool with pixel-precise accuracy', 'Remove.bg is an AI-powered background removal tool that processes images in seconds using computer vision to separate subjects from their backgrounds with pixel-precise accuracy. It handles complex edges including hair strands, fur, and transparent objects that traditional manual cutout tools struggle with. The tool is available as a web app, API, integrations for Photoshop and other design tools, and desktop apps for batch processing.

Photographers, e-commerce teams, and designers use Remove.bg to automate background removal at scale. An e-commerce company can process thousands of product photos in minutes rather than hours of manual retouching. The API makes it practical to integrate into existing photo workflows, content management systems, and automated publishing pipelines. For teams with high volumes of product photography or portrait editing, Remove.bg eliminates one of the most time-consuming manual post-production tasks while maintaining quality that rivals manual cutouts on most subjects.',
'https://www.google.com/s2/favicons?domain=remove.bg&sz=64', 'https://www.remove.bg', 'https://www.remove.bg', ARRAY['image-ai'], 'freemium', true, 9, 4.5, 876, false, false, false, ARRAY['Processes complex edges like hair and fur accurately', 'API available for automated batch processing at scale', 'Photoshop and Figma plugins for direct workflow integration', 'Free tier available with watermarked preview downloads'], ARRAY['Paid credits required for high-resolution output without watermark', 'Struggles with very busy or textured backgrounds', 'No editing tools built in - outputs the removed background only'], ARRAY['E-commerce product photography background removal at scale', 'Creating transparent PNG assets for design and marketing', 'Automating background removal in photo editing pipelines'], NOW()),

('fliki', 'Fliki', 'Turn text and blog posts into AI-narrated videos', 'Fliki is an AI video creation tool that generates videos from text scripts, articles, or blog posts using AI-generated voiceovers and a library of stock visuals. Users input a text prompt or paste existing content, select a voice from over 1,900 AI voices across 75+ languages, and Fliki generates a narrated video with matched visuals automatically. The tool targets content creators and marketers who want to produce voiceover videos without recording equipment or video editing experience.

Teams use Fliki to convert written content - blog posts, newsletters, and scripts - into video format for YouTube, LinkedIn, and social media. The AI voice quality is among the better text-to-speech options available, with realistic pacing and intonation. Fliki also supports AI avatars for talking-head videos and custom voice cloning for a consistent branded voice across all content. For marketing teams already producing written content at scale who want a video presence without additional production overhead, Fliki bridges the gap between text-first and video-first content strategies.',
'https://www.google.com/s2/favicons?domain=fliki.ai&sz=64', 'https://fliki.ai', 'https://fliki.ai', ARRAY['video-ai'], 'freemium', true, 28, 4.3, 312, false, false, false, ARRAY['1,900+ AI voices across 75+ languages for global content', 'Converts blog posts and articles into video with one click', 'Custom voice cloning for consistent branded narration', 'AI avatar support for talking-head video style'], ARRAY['Free plan has strict monthly minute limits', 'Stock visuals can feel generic without custom media uploads', 'Voice cloning requires significant audio training samples'], ARRAY['Converting blog posts into YouTube videos automatically', 'Producing multilingual voiceover content for global markets', 'Building a social video presence from existing written content'], NOW()),

('decktopus', 'Decktopus', 'AI presentation builder that generates complete slide decks', 'Decktopus is an AI presentation builder that generates complete slide decks from a topic description or outline prompt. Users describe the presentation topic and audience, and the AI produces a structured deck with suggested content, appropriate layouts, and visual design applied automatically. Decktopus handles the structure and formatting decisions that slow down most presentation workflows, letting users focus on refining content rather than building slides from scratch.

Teams and individuals use Decktopus for pitch decks, educational presentations, client reports, and internal business updates where a clean, professional-looking result is needed without a full design process. The tool includes a template library for common presentation types and allows customization of branding, colors, and fonts. Built-in form and response collection features let presenters gather audience feedback directly within the presentation. For professionals who need to produce a large number of presentations quickly and lack dedicated design resources, Decktopus provides a faster alternative to PowerPoint or Google Slides without requiring design skills.',
'https://www.google.com/s2/favicons?domain=decktopus.com&sz=64', 'https://decktopus.com', 'https://decktopus.com', ARRAY['productivity'], 'freemium', true, 7, 4.0, 198, false, false, false, ARRAY['Generates complete decks from a single prompt in minutes', 'Built-in audience Q&A and form collection features', 'Brand kit customization for consistent visual identity', 'Extensive template library for common presentation types'], ARRAY['Less design flexibility than PowerPoint or Google Slides', 'AI content generation can be generic without a detailed prompt', 'Limited advanced animation and transition options'], ARRAY['Creating pitch decks and business proposals quickly', 'Building educational course presentations and lecture materials', 'Generating client-facing reports without a designer'], NOW()),

('groq', 'Groq', 'The fastest AI inference platform - chat at 500+ tokens per second', 'Groq is an AI inference company that built custom Language Processing Units (LPUs) designed to run large language models significantly faster than GPU-based alternatives. The practical result for end users is chat.groq.com, a free web interface that lets anyone interact with models like Llama 3, Mixtral, and Gemma at speeds reaching 500+ tokens per second - noticeably faster than any other publicly accessible AI chat interface. This speed difference is perceptible in real-time conversations and makes Groq practical for tasks where rapid iteration matters.

Developers and power users use Groq''s API to build applications requiring low-latency AI responses, including real-time transcription, live coding assistance, and customer-facing products where speed affects user experience. The free tier includes generous API limits that cover most experimental and personal use cases. Groq runs open-source and partner models with optimized inference, making it a neutral infrastructure layer rather than a model vendor. For users who want the fastest available AI responses with access to competitive open-source models at minimal cost, Groq is one of the most technically differentiated options available.',
'https://www.google.com/s2/favicons?domain=groq.com&sz=64', 'https://groq.com', 'https://groq.com', ARRAY['ai-assistant'], 'freemium', true, 0, 4.5, 234, false, true, false, ARRAY['500+ tokens/second - fastest publicly available AI inference', 'Access to Llama 3, Mixtral, Gemma and other top open models', 'Generous free tier with no credit card required', 'Low-latency API for building speed-critical AI applications'], ARRAY['No proprietary models - relies on open-source model providers', 'Less suitable for users who need Claude or GPT-4 specifically', 'API rate limits on free tier for high-volume applications'], ARRAY['Real-time AI chat where speed is a priority', 'Building low-latency AI features in production applications', 'Experimenting with open-source models via a fast API'], NOW())

ON CONFLICT (slug) DO NOTHING;
