-- tools-batch-18.sql
-- 10 new tools: DB 202 → 212
-- ON CONFLICT (slug) DO NOTHING (idempotent)

INSERT INTO tools (slug, name, tagline, description, logo_url, website_url, affiliate_url, tags, pricing_type, pricing_free_tier, pricing_starting_price, rating, review_count, featured, trending, editor_pick, pros, cons, use_cases)
VALUES

-- 1. Adobe Express (upgraded entry, replaces stub if exists)
('adobe-express-video', 'Adobe Express Video', 'Create short social videos with AI templates and voiceover in minutes', 'Adobe Express Video brings professional video creation to non-designers through AI-powered templates, text-to-video features, and automated voiceover generation. Built on Adobe''s creative infrastructure, it connects to the broader Creative Cloud ecosystem while remaining accessible enough for marketers and social media managers with no video editing background. Users can animate graphics, add branded overlays, sync music to video clips, and export in platform-optimised formats for Instagram, TikTok, YouTube Shorts, and LinkedIn. The AI scene generator can transform a text prompt into a short video draft, making it useful for teams that need to produce a high volume of short-form content quickly. For organisations already using Adobe products, Express Video integrates directly with existing brand kits, stock libraries, and team storage. It is the fastest path to branded social video without hiring a video editor.', 'https://www.google.com/s2/favicons?domain=adobe.com&sz=64', 'https://www.adobe.com/express/feature/video', 'https://www.adobe.com/express/feature/video', ARRAY['video-ai', 'design'], 'freemium', true, 9.99, 4.2, 890, false, true, false, ARRAY['Integrates with Adobe Creative Cloud and brand kits', 'AI voiceover and text animation built in', 'Exports in all major social media formats', 'No video editing experience required'], ARRAY['Limited advanced editing vs Premiere Pro', 'Free tier watermarks output', 'Template selection smaller than Canva'], ARRAY['Short-form social video content', 'Branded video templates for marketing teams', 'Animated infographics and explainer clips']),

-- 2. Udio
('udio', 'Udio', 'Generate full songs from a text prompt - vocals, instruments, and lyrics included', 'Udio is an AI music generation platform that creates complete songs from text descriptions, including vocals, instrumentation, and original lyrics. Unlike tools that produce short background clips, Udio generates full-length tracks with coherent structure - verses, choruses, bridges - making it suitable for content creators, game developers, and producers looking for original music without licensing costs. Users can specify genre, mood, tempo, vocal style, and lyrical theme through natural language prompts. The model handles genre blending naturally, producing credible output across hip-hop, pop, folk, electronic, jazz, and classical styles. Generated tracks can be extended, remixed, and iterated on directly within the platform. For content creators who need royalty-free original music rather than stock library tracks, Udio offers a genuinely compelling alternative. The service is available on a subscription basis with free credits to try before committing.', 'https://www.google.com/s2/favicons?domain=udio.com&sz=64', 'https://www.udio.com', 'https://www.udio.com', ARRAY['audio-ai', 'creative'], 'freemium', true, 9.99, 4.3, 1240, false, true, false, ARRAY['Generates full songs with vocals and lyrics, not just instrumentals', 'Strong genre versatility from hip-hop to classical', 'Tracks can be extended and iterated in-platform', 'Royalty-free output for commercial use'], ARRAY['Lyric quality varies significantly by genre', 'No fine-grained control over individual instruments', 'Audio artifacts occasionally appear in complex arrangements'], ARRAY['Original background music for YouTube and podcast content', 'Game soundtrack prototyping', 'Royalty-free music for commercial projects']),

-- 3. Gamma (additional description update via SQL)
('gamma-app', 'Gamma', 'Build presentations, docs, and websites from a prompt in under a minute', 'Gamma is an AI-powered presentation and document builder that generates fully designed slides, web pages, and long-form documents from a text prompt or outline. Unlike tools that require assembling slides manually, Gamma handles layout, design, formatting, and content generation in a single workflow. Users provide a topic or paste in notes, and Gamma produces a complete, on-brand presentation within seconds. The design system adapts automatically to the content, ensuring visual hierarchy and readability without manual adjustment. Gamma supports nested cards, interactive embeds, data charts, and GIF/video insertion, making it more versatile than standard slide-based tools for product demos and internal documents. Export options include PDF, PowerPoint, and shareable web links that render beautifully on any device. Gamma is particularly popular with consultants, startup founders, and educators who need to produce polished decks quickly without design skills. Its free tier is genuinely useful, making it one of the most accessible AI presentation tools available.', 'https://www.google.com/s2/favicons?domain=gamma.app&sz=64', 'https://gamma.app', 'https://gamma.app', ARRAY['productivity', 'design'], 'freemium', true, 10.00, 4.5, 3200, false, true, false, ARRAY['Generates complete presentations from a prompt in seconds', 'Handles layout and design automatically', 'Supports interactive elements, charts, and video embeds', 'Free tier is genuinely useful for most users'], ARRAY['Less control over pixel-perfect design than PowerPoint', 'Brand customisation limited on free tier', 'Template variety smaller than Canva'], ARRAY['Pitch decks and investor presentations', 'Internal reports and product updates', 'Educational materials and course content']),

-- 4. Scribe
('scribe', 'Scribe', 'Automatically generate step-by-step process documentation as you work', 'Scribe is a process documentation tool that captures your screen actions and converts them into step-by-step guides automatically. Install the browser extension, click record, complete a workflow, and Scribe generates a fully formatted guide with annotated screenshots, numbered steps, and explanatory text - all without writing a single word. The AI layer adds context, identifies key actions, and writes clear instructions for each step. Teams use Scribe to document SOPs, onboarding flows, software tutorials, and troubleshooting guides at a fraction of the time required by manual documentation methods. Scribe integrates with Notion, Confluence, Google Docs, and Slack, so guides can be embedded directly into existing knowledge bases. For teams spending hours documenting processes that change frequently, Scribe eliminates the maintenance burden by making re-recording faster than editing old documentation. Basic plans are free; team plans from $23/user/mo.', 'https://www.google.com/s2/favicons?domain=scribehow.com&sz=64', 'https://scribehow.com', 'https://scribehow.com', ARRAY['productivity', 'automation'], 'freemium', true, 23.00, 4.4, 1780, false, false, false, ARRAY['Auto-generates guides from screen recordings without manual writing', 'Integrates with Notion, Confluence, and Slack', 'Re-recording is faster than editing old documentation', 'Annotated screenshots included automatically'], ARRAY['Limited to web browser workflows on free tier', 'Desktop app required for full screen recording', 'AI-generated text occasionally needs manual cleanup'], ARRAY['SOP and process documentation', 'Software onboarding guides for new employees', 'Customer-facing how-to tutorials']),

-- 5. Loom AI
('loom', 'Loom', 'Record and share video messages with AI summaries and automatic transcripts', 'Loom is the leading asynchronous video communication tool, allowing teams to record short video messages instead of writing long emails or scheduling unnecessary meetings. The AI layer adds automatic transcription, chapter summaries, action item extraction, and message threading on top of video recordings. Loom AI can generate a written summary of any recording in seconds, making it easy to skim video content without watching the full clip. Teams use Loom for async standups, product demos, feedback on designs, onboarding walkthroughs, and sales outreach videos. Integrations with Slack, Notion, Linear, and GitHub make it easy to attach video context directly to tasks and tickets. The free tier allows unlimited recordings up to 5 minutes each. Paid plans from $15/user/mo unlock longer recordings, custom branding, and advanced analytics showing who watched and how far they got. Loom is particularly effective for remote and hybrid teams where written context is frequently lost in translation.', 'https://www.google.com/s2/favicons?domain=loom.com&sz=64', 'https://www.loom.com', 'https://www.loom.com', ARRAY['productivity', 'video-ai'], 'freemium', true, 15.00, 4.5, 4100, false, false, false, ARRAY['AI summaries and transcripts generated automatically', 'Free tier covers most individual use cases', 'Integrates with Slack, Notion, and Linear', 'Analytics show viewer engagement per recording'], ARRAY['Video quality dependent on local internet speed', 'Not ideal for polished external marketing videos', 'Paid team features are expensive at scale'], ARRAY['Async team updates and standups', 'Sales outreach and product demos', 'Onboarding walkthroughs and training videos']),

-- 6. Magnific AI
('magnific', 'Magnific AI', 'AI image upscaler that adds detail and texture at 4x-16x resolution', 'Magnific AI is an image enhancement tool that upscales images while adding photorealistic detail - not just enlarging pixels, but generating new texture, skin pores, fabric weave, and fine detail that did not exist in the original image. The result is high-resolution output that looks like it was originally captured at that resolution, rather than a blurry enlargement. Photographers, digital artists, and print designers use Magnific to enhance AI-generated images, improve stock photos, and restore detail to compressed or low-resolution source material. The tool offers control over enhancement intensity, allowing users to choose between subtle upscaling and aggressive hallucination of new detail. Output can be exported at up to 8K resolution for large-format print or high-resolution digital display. Pricing is usage-based, starting at $39/mo for a monthly credit allocation.', 'https://www.google.com/s2/favicons?domain=magnific.ai&sz=64', 'https://magnific.ai', 'https://magnific.ai', ARRAY['image-ai', 'design'], 'paid', false, 39.00, 4.4, 980, false, true, false, ARRAY['Generates new photorealistic detail rather than just enlarging pixels', 'Output up to 8K resolution for large-format print', 'Works on AI-generated images and real photography', 'Fine control over enhancement intensity'], ARRAY['No free tier - requires paid subscription to try', 'Enhancement can over-hallucinate detail on low-quality sources', 'Processing time longer than basic upscalers'], ARRAY['Upscaling AI-generated images for print use', 'Enhancing low-resolution stock photography', 'Restoring detail in compressed or archival images']),

-- 7. Adobe Podcast
('adobe-podcast', 'Adobe Podcast', 'AI audio enhancement that removes noise and makes any microphone sound studio-quality', 'Adobe Podcast is a browser-based audio enhancement tool powered by AI that removes background noise, eliminates echo, and normalises audio levels to produce studio-quality sound from any microphone, including built-in laptop microphones. The Enhance Speech feature processes audio files by analysing and removing unwanted frequencies, making it valuable for podcasters, educators recording course content, and remote workers who need clear audio for meetings and video calls. Users upload an audio or video file and receive a cleaned version within minutes - no audio engineering knowledge required. Adobe Podcast also includes a web-based recorder with real-time enhancement for direct recording sessions. For creators who cannot afford professional recording equipment or acoustic treatment, Adobe Podcast delivers a measurable improvement in audio quality at no cost. The core Enhance Speech feature is available free with an Adobe ID.', 'https://www.google.com/s2/favicons?domain=adobe.com&sz=64', 'https://podcast.adobe.com', 'https://podcast.adobe.com', ARRAY['audio-ai', 'productivity'], 'freemium', true, 0.00, 4.6, 2340, false, false, false, ARRAY['Free Enhance Speech feature requires only an Adobe ID', 'Works on any microphone including built-in laptop mics', 'No audio engineering knowledge needed', 'Significant quality improvement on voice recordings'], ARRAY['Limited to voice audio enhancement, not music or sound design', 'File size limits on free tier', 'Requires internet connection - no offline processing'], ARRAY['Podcast episode cleanup and noise removal', 'Online course audio quality improvement', 'Remote meeting and webinar audio enhancement']),

-- 8. Perplexity Pages
('perplexity-pages', 'Perplexity Pages', 'AI-powered long-form content creation with citations and real-time research', 'Perplexity Pages is a content creation feature within Perplexity AI that generates structured, cited long-form articles and reports by pulling from real-time web sources. Unlike standard AI writing tools that generate text from training data alone, Pages continuously cites its sources inline, allowing readers to verify claims and explore primary sources. The tool is designed for researchers, analysts, and content teams who need well-sourced reference documents, not just fluent prose. Users provide a topic and Perplexity Pages generates a structured document with an introduction, multiple sections, and inline citations to recent sources. The output can be published as a shareable web page or exported for further editing. Pages works particularly well for competitive research reports, industry overviews, and trend analysis where source credibility matters. Available to Perplexity Pro subscribers at $20/mo.', 'https://www.google.com/s2/favicons?domain=perplexity.ai&sz=64', 'https://www.perplexity.ai/pages', 'https://www.perplexity.ai/pro', ARRAY['research-ai', 'productivity'], 'paid', false, 20.00, 4.4, 760, false, false, false, ARRAY['Cites real-time sources inline for every factual claim', 'Output is a shareable web page, not just a document', 'Strong for research reports and competitive analysis', 'Sources are current, not limited to training cutoff'], ARRAY['Requires Perplexity Pro subscription', 'Less control over structure than manual writing tools', 'Citation quality varies by topic depth'], ARRAY['Competitive research and industry reports', 'Well-sourced reference documents for content teams', 'Trend analysis with real-time citation support']),

-- 9. Ideogram
('ideogram', 'Ideogram', 'AI image generator that excels at text rendering inside images', 'Ideogram is an AI image generation tool with a specific strength that most competitors lack: accurate text rendering within generated images. Where Midjourney and Stable Diffusion frequently produce garbled or misspelled text in images, Ideogram renders logos, signs, labels, product names, and typographic elements legibly and correctly. This makes it particularly useful for marketers generating ad concepts, designers creating logo mockups, and social media managers producing text-heavy graphics. Ideogram supports photorealistic, illustration, and design styles with strong prompt adherence across all modes. The free tier offers 10 images per day - generous enough for daily creative work. Paid plans from $7/mo unlock higher resolution, priority generation, and private image storage. For any workflow that requires text to appear accurately in AI-generated images, Ideogram is the most reliable tool available in 2026.', 'https://www.google.com/s2/favicons?domain=ideogram.ai&sz=64', 'https://ideogram.ai', 'https://ideogram.ai', ARRAY['image-ai', 'design'], 'freemium', true, 7.00, 4.5, 2180, false, true, false, ARRAY['Best-in-class text rendering within generated images', 'Free tier with 10 images per day', 'Strong across photorealistic, illustration, and design styles', 'Paid plans from $7/mo - most affordable premium tier'], ARRAY['Less photorealistic than Midjourney for non-text images', 'Style range narrower than Stable Diffusion ecosystem', 'Batch generation limited on free tier'], ARRAY['Ad concepts and marketing graphics with text overlays', 'Logo and brand mockups using AI generation', 'Social media graphics requiring accurate text']),

-- 10. Warp
('warp', 'Warp', 'AI-powered terminal that understands natural language commands and explains errors', 'Warp is a modern terminal application with AI built natively into the command-line interface. Instead of memorising obscure flag syntax or hunting Stack Overflow for the right command, users can describe what they want to accomplish in plain English and Warp generates the correct command. The AI assistant explains errors in plain language, suggests fixes, and provides context for why a command failed. Warp also introduces blocks - grouped command input and output units that are individually shareable and searchable, making it easier to navigate long terminal sessions. The Warp Drive feature allows teams to share frequently used commands and scripts as a shared library. For developers who spend significant time in the terminal, Warp reduces the cognitive load of command recall and error debugging. The core application is free; Warp for Teams plans start at $15/user/mo.', 'https://www.google.com/s2/favicons?domain=warp.dev&sz=64', 'https://www.warp.dev', 'https://www.warp.dev', ARRAY['code-ai', 'developer-tools'], 'freemium', true, 15.00, 4.5, 1890, false, true, false, ARRAY['Natural language command generation directly in terminal', 'Error explanation in plain English', 'Shareable command blocks and team script library', 'Free core application for individual use'], ARRAY['macOS and Linux only - no Windows support yet', 'AI features require internet connection', 'Some users prefer traditional terminal muscle memory'], ARRAY['Generating complex shell commands from natural language', 'Debugging terminal errors without Stack Overflow', 'Sharing command scripts across development teams'])

ON CONFLICT (slug) DO NOTHING;
