-- tools-batch-58.sql
-- Theme: AI Real Estate / Proptech
-- Target: ~559 tools total (549 + 10)
-- All 10 slugs verified fresh - not found in any prior tools-batch-*.sql file
-- matterport: confirmed NOT in any batch file (no seed collision found)
-- No swaps needed - all original candidate slugs are fresh

INSERT INTO tools (slug, name, tagline, description, website_url, affiliate_url, pricing_type, pricing_free_tier, pricing_starting_price, rating, review_count, featured, trending, editor_pick, tags, pros, cons, use_cases, updated_at)
VALUES

('compass', 'Compass', 'AI-powered real estate brokerage platform for agents and buyers',
 E'Compass is a technology-driven real estate brokerage that has built one of the most sophisticated AI platforms in residential real estate. The platform combines CRM, listing management, marketing automation, and AI-powered market intelligence in a single suite built specifically for real estate agents and their clients. Compass agents access predictive analytics that identify likely sellers in their target neighbourhoods before those homeowners list, enabling proactive outreach campaigns that generate listing opportunities rather than waiting for inbound leads.\n\nThe AI market insights engine analyses comparable sales, days on market, price reduction patterns, and buyer demand signals to recommend optimal listing prices with confidence intervals. The Collections feature allows buyers and agents to collaborate on home search in a shared digital workspace, with AI recommendations surfacing properties that match stated preferences even when those preferences are not yet fully articulated. Agent performance analytics help brokerage managers identify coaching opportunities and replicate the behaviours of top-performing agents across the team.\n\nCompass has expanded its AI capabilities to include AI-assisted listing descriptions, automated social media content for new listings, and AI-generated neighbourhood market reports that agents can brand and distribute to their client base. For agents competing in a market where speed and data advantage matter, the Compass platform provides capabilities that were previously available only to large institutional brokerages. The platform is available exclusively to agents who join the Compass brokerage.',
 'https://compass.com', 'https://compass.com',
 'paid', false, NULL, 4.2, 2800, false, true, false,
 ARRAY['real-estate', 'ai-analytics', 'crm'],
 ARRAY['Predictive seller identification enables proactive listing generation', 'AI pricing recommendations include confidence intervals based on comparable data', 'Collaborative Collections workspace improves buyer-agent communication', 'Integrated marketing automation handles listing content and social distribution'],
 ARRAY['Platform access requires joining Compass as a brokerage - not available to independent agents', 'Market coverage is strongest in major metros - less depth in rural or small markets', 'Agent performance metrics can create pressure in high-accountability environments', 'Platform lock-in means switching brokerages requires migrating all client data'],
 ARRAY['Real estate agents wanting AI-assisted lead generation and market intelligence', 'Buyers seeking a collaborative digital workspace for property search', 'Brokerage managers using performance analytics to coach agent teams'],
 NOW()),

('reonomy', 'Reonomy', 'Commercial real estate data and AI intelligence platform for CRE professionals',
 E'Reonomy is a commercial real estate data and intelligence platform that aggregates and analyses property data, ownership records, transaction history, debt information, and tenant data across millions of commercial properties in the United States. The platform uses AI to surface actionable insights from this aggregated data - identifying properties likely to transact, debt that is approaching maturity and creating refinancing or sale pressure, and ownership structures that indicate motivated sellers in specific markets and asset classes.\n\nThe property search experience is built around intent: rather than simple address lookup, Reonomy allows CRE brokers, lenders, and investors to filter properties by ownership type, debt maturity, occupancy rate, building age, and transaction recency - then combine those filters to identify the properties most likely to match a specific investment or lending thesis. The ownership graph connects individual properties to their ultimate beneficial owners, revealing portfolio concentration and enabling outreach to the right decision-maker rather than a registered LLC entity.\n\nReonomy''s AI prospecting tools generate lists of properties and owners matching a specific target profile, with contact information and outreach history tracked through the platform''s CRM features. For CRE brokers building off-market deal flow, lenders prospecting for refinancing opportunities, and institutional investors sourcing acquisition targets, Reonomy provides the data depth and AI intelligence that manual property research cannot match at scale. Reonomy was acquired by CoStar Group in 2021 and continues to operate as a standalone platform.',
 'https://reonomy.com', 'https://reonomy.com',
 'paid', false, 5000, 4.3, 1900, false, true, false,
 ARRAY['real-estate', 'ai-analytics', 'commercial-real-estate'],
 ARRAY['Aggregates ownership, debt, and tenant data into a single commercial property intelligence layer', 'Ownership graph reveals ultimate beneficial owners behind LLC-held properties', 'AI prospecting filters by debt maturity, occupancy, and transaction signals to identify motivated sellers', 'CoStar acquisition has deepened data coverage and integration options'],
 ARRAY['US market only - international CRE data not available', 'Annual subscription cost is significant for smaller brokerages or individual brokers', 'Data freshness varies by market - some smaller metros have less current transaction data', 'CRM features are functional but less sophisticated than dedicated CRE CRM platforms'],
 ARRAY['CRE brokers building off-market deal flow through motivated seller identification', 'Commercial lenders prospecting for refinancing opportunities as debt matures', 'Institutional investors sourcing acquisition targets matching specific portfolio criteria'],
 NOW()),

('cherre', 'Cherre', 'Real estate data unification and AI analytics for institutional investors',
 E'Cherre is an enterprise real estate data platform that solves the fragmentation problem facing institutional real estate investors: property data lives across dozens of sources - public records, data vendors, proprietary databases, internal deal management systems - and connecting those sources into a coherent analytical foundation has historically required expensive data engineering. Cherre acts as a unified data layer that ingests, normalises, and links real estate data from multiple sources around a property identifier, giving investment teams a single view of each asset across all the data they own and license.\n\nThe AI analytics capabilities built on top of this unified data layer include automated valuation models (AVMs) calibrated to specific asset classes and markets, predictive analytics for rent growth, occupancy trends, and cap rate movements, and anomaly detection that flags individual assets whose performance diverges from market trends. Portfolio management teams use Cherre to monitor asset performance at scale without manual data aggregation from property management software, market data vendors, and internal reporting systems.\n\nCherre''s data marketplace allows institutional clients to access curated third-party datasets - demographics, economic indicators, satellite imagery, foot traffic data - that can be layered onto the unified property foundation for more sophisticated analytics. The platform is deployed by some of the largest real estate investment managers, pension funds, and REITs in the market. Pricing is enterprise-tier, with implementation support from Cherre''s data engineering team to manage the initial integration of client data sources.',
 'https://cherre.com', 'https://cherre.com',
 'paid', false, NULL, 4.2, 680, false, false, false,
 ARRAY['real-estate', 'ai-analytics', 'data-platform'],
 ARRAY['Unifies fragmented real estate data from public records, vendors, and internal systems around a property ID', 'Automated valuation models calibrated per asset class and market reduce manual underwriting effort', 'Data marketplace provides access to curated third-party datasets without separate vendor contracts', 'Anomaly detection flags underperforming assets before performance deterioration compounds'],
 ARRAY['Enterprise-only pricing requires significant investment and multi-month implementation', 'Value scales with data volume - less compelling for smaller portfolios', 'Initial data integration requires dedicated data engineering resources', 'Less accessible for CRE brokers or smaller investment firms without data infrastructure'],
 ARRAY['Institutional real estate investors unifying fragmented property data for portfolio analytics', 'REITs and real estate investment managers tracking asset performance against market benchmarks', 'Real estate data science teams building predictive models on top of a unified property data foundation'],
 NOW()),

('leverton', 'Leverton', 'AI lease abstraction and contract intelligence for commercial real estate',
 E'Leverton is an AI-powered lease abstraction platform that extracts structured data from commercial lease agreements at scale. Commercial real estate portfolios routinely contain thousands of leases - office, retail, industrial, multifamily - each with dozens of critical data points: rent commencement dates, rent escalation clauses, CAM reconciliation terms, renewal options, termination rights, tenant improvement allowances, and subletting restrictions. Manually abstracting these terms from lease documents is one of the most labour-intensive and error-prone tasks in CRE asset management. Leverton automates that extraction using AI trained on commercial lease language.\n\nThe platform supports lease abstraction for IFRS 16 and ASC 842 compliance, which require companies to recognise operating leases on the balance sheet with precise term and payment data. Leverton''s structured output feeds directly into lease accounting systems and ERP platforms, reducing the manual data entry that creates errors in financial reporting. The abstraction accuracy is validated through a human review workflow where trained reviewers check and correct AI extractions, creating an auditable record of the abstraction process that satisfies accounting standards.\n\nLeverton''s use cases extend beyond asset management and accounting compliance to lease portfolio analytics: which leases expire in the next 24 months, which tenants have renewal options they have not yet exercised, and where is rent exposure concentrated by market or asset class. For corporate real estate teams managing large office or retail portfolios, Leverton provides the data foundation that makes lease portfolio strategy a data-driven exercise rather than an asset-by-asset manual review.',
 'https://leverton.ai', 'https://leverton.ai',
 'paid', false, NULL, 4.3, 820, false, false, false,
 ARRAY['real-estate', 'legal-ops', 'ai-analytics'],
 ARRAY['AI extraction covers non-standard lease clauses and deal-specific terms, not just standard fields', 'IFRS 16 and ASC 842 structured output feeds lease accounting systems directly', 'Human review validation workflow creates auditable extraction record for accounting compliance', 'Portfolio analytics surface expiration risk, renewal options, and rent concentration by market'],
 ARRAY['Enterprise pricing requires sales engagement - no self-serve option', 'Initial AI training requires sample leases from the client portfolio for calibration', 'Best for portfolios of 100+ leases - less compelling for small portfolios', 'Less specialised for residential lease management; built for commercial asset classes'],
 ARRAY['CRE asset managers abstracting lease portfolios for IFRS 16 or ASC 842 accounting compliance', 'Corporate real estate teams gaining structured visibility across large office and retail lease portfolios', 'M&A and due diligence teams conducting rapid lease review across acquisition targets'],
 NOW()),

('rex-real-estate', 'REX Real Estate', 'AI-powered homebuying and selling platform that bypasses traditional agent commissions',
 E'REX Real Estate is an AI-driven residential real estate platform built on the premise that traditional 5-6% agent commission structures are inefficient for home sellers in an era of digital property search. REX uses machine learning to target potential buyers for a listed property through digital advertising - Facebook, Google, and programmatic display - using audience models built from real estate search behaviour, life event data, and demographic signals. The goal is to find the right buyer directly rather than relying on the MLS and buyer''s agent network as the primary discovery channel.\n\nFor sellers, REX charges a reduced commission compared to the traditional dual-agent model because REX represents both sides of the transaction without a separate buyer''s agent. The AI valuation tool analyses comparable sales, market trends, and property-specific features to recommend listing prices. The digital marketing platform generates professional listing photos, virtual tours, and targeted advertising campaigns automatically from the property data entered into the system.\n\nFor buyers, REX provides a search experience that surfaces both REX listings and MLS listings, with AI recommendations based on stated and inferred preferences. The transaction management platform handles offer submission, negotiation support, and closing document management. REX has faced regulatory challenges from traditional real estate industry groups concerned about its model of operating without buyer''s agent commissions, but continues to operate in its active markets. The platform is an example of how AI is being used to rethink fundamental economics in industries with historically high transaction costs.',
 'https://rexhomes.com', 'https://rexhomes.com',
 'paid', false, NULL, 3.9, 1200, false, false, false,
 ARRAY['real-estate', 'homebuying', 'ai-analytics'],
 ARRAY['Reduced commission model saves sellers money compared to traditional dual-agent transactions', 'AI-targeted digital advertising reaches potential buyers directly across social and programmatic channels', 'Automated listing content generation handles photos, virtual tours, and ad copy', 'Transaction management platform handles the full closing process end-to-end'],
 ARRAY['Limited market coverage - not available in all US markets', 'Bypassing MLS means fewer buyer eyeballs in markets where MLS is dominant', 'Regulatory friction in some markets from traditional real estate industry groups', 'Less experienced with complex transactions that require significant negotiation or legal coordination'],
 ARRAY['Home sellers wanting to reduce commission costs while maintaining professional marketing support', 'Buyers searching for homes outside the traditional MLS-only search model', 'Real estate investors looking for off-market or efficiently transacted residential deals'],
 NOW()),

('rentlytics', 'Rentlytics', 'Multifamily analytics platform powered by AI for property performance intelligence',
 E'Rentlytics is a data analytics and business intelligence platform built specifically for multifamily real estate operators - apartment owners, property management companies, and real estate investment trusts with residential portfolios. The platform aggregates operational data from property management systems (Yardi, RealPage, Entrata) and combines it with market data to give asset managers and operators a real-time view of portfolio performance across occupancy, rent trends, leasing velocity, renewals, and maintenance costs.\n\nThe AI analytics layer identifies performance anomalies and surfaces actionable insights that would be missed in standard property management system reports. The occupancy prediction model forecasts 30, 60, and 90-day occupancy exposure by property, enabling leasing teams to adjust pricing and promotion strategies before occupancy declines materialise. The rent benchmarking module compares each property''s effective rents against market comps in real time, flagging properties where the gap between asking rent and market rent represents either unrealised revenue potential or elevated churn risk.\n\nRentlytics''s portfolio dashboards consolidate key performance indicators across hundreds of properties into a single view that asset managers can monitor in real time without pulling individual property reports from the PMS. The variance analysis feature compares actual NOI performance against underwriting projections and budgets, with AI-generated explanations of variances that identify whether underperformance is driven by occupancy, rent, or expense factors. For multifamily operators managing large portfolios, Rentlytics provides the analytical layer that turns raw PMS data into portfolio intelligence.',
 'https://rentlytics.com', 'https://rentlytics.com',
 'paid', false, NULL, 4.2, 560, false, false, false,
 ARRAY['real-estate', 'ai-analytics', 'multifamily'],
 ARRAY['Aggregates data from Yardi, RealPage, and Entrata into a unified portfolio view', 'Occupancy prediction model enables proactive leasing strategy before vacancy materialises', 'Rent benchmarking against live market data flags unrealised revenue and churn risk simultaneously', 'AI-generated variance explanations replace manual NOI report analysis'],
 ARRAY['Best suited for portfolios of 1,000+ units - less compelling for smaller operators', 'Implementation requires PMS data integration that takes 4-8 weeks to configure', 'Limited applicability outside multifamily - not designed for commercial or retail asset classes', 'Market data coverage depth varies by metro - strongest in major multifamily markets'],
 ARRAY['Multifamily asset managers monitoring portfolio performance across Yardi or RealPage-managed properties', 'Property management companies benchmarking rent performance against market comps in real time', 'Institutional multifamily investors tracking NOI variance against underwriting projections at scale'],
 NOW()),

('reggora', 'Reggora', 'AI appraisal management platform for faster, more accurate residential valuations',
 E'Reggora is an appraisal management technology platform that uses AI to modernise the residential real estate appraisal process - one of the last major manual bottlenecks in residential mortgage origination. Traditional appraisals take 10-14 days and are ordered, assigned, and reviewed through disconnected processes involving lender appraisal departments, appraisal management companies (AMCs), and individual appraisers. Reggora automates the order management, appraiser assignment, quality review, and delivery workflow, reducing average appraisal cycle times significantly.\n\nThe AI quality control layer analyses completed appraisal reports for UAD compliance errors, missing comparable sales adjustments, inconsistent value conclusions, and USPAP guideline violations before the report is delivered to the lender. The model flags high-risk appraisal reports for human reviewer attention while allowing clean reports to flow through automatically - concentrating human review effort where it adds the most value. The comparable selection AI identifies the most defensible comparables from the available sales database for appraisers to consider, reducing the time appraisers spend on comp research.\n\nFor mortgage lenders, Reggora provides an appraisal management dashboard that gives real-time visibility into the status, timeline, and quality risk of every appraisal in the pipeline - eliminating the phone calls and email threads that traditionally characterise lender-appraiser communication. The integration with major loan origination systems allows appraisal orders to be triggered automatically from the LOS and appraisal reports to be delivered directly into the loan file. Reggora is used by mortgage lenders ranging from community banks to top-20 national lenders.',
 'https://reggora.com', 'https://reggora.com',
 'paid', false, NULL, 4.3, 740, false, false, false,
 ARRAY['real-estate', 'mortgage-tech', 'ai-analytics'],
 ARRAY['AI quality control catches UAD compliance errors and USPAP violations before delivery to lender', 'Automated order management and appraiser assignment reduces manual coordination overhead', 'Real-time pipeline dashboard eliminates phone and email status tracking for appraisal orders', 'LOS integration allows automated order triggers and report delivery into the loan file'],
 ARRAY['Not an appraiser-facing tool - serves lenders and AMCs rather than individual appraisers', 'Value concentrated in high-volume originators - lower ROI for lenders with few monthly appraisals', 'AI QC catches compliance errors but does not replace human review for high-risk value conclusions', 'Implementation requires LOS integration setup that adds to onboarding timeline'],
 ARRAY['Mortgage lenders reducing appraisal cycle time and manual coordination in high-volume origination', 'Appraisal management companies automating quality control review across high report volumes', 'Community banks and credit unions modernising appraisal ordering workflows without building internal AMC teams'],
 NOW()),

('matterport', 'Matterport', 'AI-powered 3D property capture and virtual tour platform for real estate',
 E'Matterport is the leading platform for 3D property capture, virtual tours, and AI-powered spatial data intelligence in real estate and related industries. The core product is the Matterport 3D camera and processing software that creates photorealistic, navigable 3D models of physical spaces - the "digital twin" of a property. Real estate agents, property managers, architects, and facility managers use Matterport digital twins to allow remote viewers to navigate a space interactively, measuring rooms, viewing from any angle, and experiencing the spatial layout without visiting in person.\n\nThe AI capabilities layer on top of the 3D capture infrastructure provide automated property data extraction: room dimensions, floor plan generation, area calculations, and material identification. The AI floor plan generation feature produces accurate, dimensioned floor plans automatically from the 3D scan data, eliminating the need for separate floor plan drafting. Property data extracted from Matterport scans can be exported in formats compatible with MLS listing systems, building information modelling (BIM) software, and facility management platforms.\n\nMatterport''s platform has expanded beyond residential real estate to commercial real estate, construction progress documentation, insurance loss assessment, and cultural heritage preservation. The Cortex AI engine processes uploaded scans to identify and categorise property features, flag potential insurance risks, and generate structured property data for automated valuation models. Matterport went public via SPAC in 2021 and serves over 700,000 subscribers globally. The platform is available on subscription tiers from individual agents to enterprise real estate operators and insurance companies.',
 'https://matterport.com', 'https://matterport.com',
 'freemium', true, 69, 4.4, 4200, false, true, false,
 ARRAY['real-estate', 'virtual-tours', 'ai-analytics'],
 ARRAY['Industry-standard 3D tour format recognised by MLS and major real estate portals', 'AI floor plan generation from 3D scan eliminates separate drafting workflow', 'Cortex AI extracts structured property data for AVM and insurance applications', 'Multi-industry platform covers residential, commercial, construction, and insurance use cases'],
 ARRAY['Hardware cost for Matterport camera (Pro2 or Pro3) is $3,000-$6,500 - significant for individual agents', 'Scan processing time and upload bandwidth requirements are high for large commercial properties', 'Free and entry-level plans have limited scan hosting - active portfolio management requires paid tier', 'Competing 360-degree tour platforms have closed some quality gap at lower price points'],
 ARRAY['Real estate agents adding professional 3D virtual tours to residential listings', 'Commercial real estate operators creating digital twins of office and retail assets for remote leasing', 'Construction teams using Matterport for progress documentation and as-built verification'],
 NOW()),

('skyline-ai', 'Skyline AI', 'Institutional-grade AI investment analytics for commercial real estate',
 E'Skyline AI is an AI-powered real estate investment analytics platform that applies machine learning to commercial real estate investment decision-making. The platform aggregates data from hundreds of public and proprietary sources - transaction records, tax assessments, demographic trends, economic indicators, satellite imagery, foot traffic data - and uses AI models to generate investment quality scores, risk assessments, and return projections for commercial real estate assets across asset classes including multifamily, office, retail, and industrial.\n\nThe investment screening module allows institutional real estate investment teams to filter available assets by AI-generated metrics rather than only by traditional broker-provided information - identifying properties where the AI model projects above-market returns given current pricing, or flagging assets where risk factors not visible in standard due diligence data suggest potential underperformance. The underwriting assistance tools pre-populate financial models with AI-derived rent growth, cap rate, and expense assumptions calibrated to the specific asset, market, and vintage, reducing the time from initial screening to investment committee presentation.\n\nSkyline AI was acquired by JLL (Jones Lang LaSalle) in 2019 and its capabilities are now integrated into JLL''s investment management and advisory services. The technology remains available to JLL clients and is being expanded as part of JLL''s broader AI investment in real estate intelligence. For institutional investors and investment managers who work with JLL, Skyline AI''s capabilities represent a significant AI-driven enhancement to commercial real estate underwriting and portfolio analytics.',
 'https://skyline.ai', 'https://skyline.ai',
 'paid', false, NULL, 4.1, 420, false, false, false,
 ARRAY['real-estate', 'ai-analytics', 'investment'],
 ARRAY['AI investment scores aggregate hundreds of data sources beyond standard due diligence data', 'Underwriting pre-population with AI assumptions reduces time to investment committee presentation', 'Asset class coverage spans multifamily, office, retail, and industrial in a single platform', 'JLL acquisition provides access to proprietary transaction and market data at institutional scale'],
 ARRAY['Now primarily available as part of JLL advisory services rather than as a standalone product', 'Less accessible to smaller investment managers outside the JLL client ecosystem', 'AI projections require validation against local market knowledge - not a standalone underwriting replacement', 'Limited self-serve access - most value delivered through JLL advisory engagement'],
 ARRAY['Institutional real estate investment managers screening acquisition opportunities with AI-driven risk scoring', 'JLL advisory clients using AI underwriting assistance to accelerate investment decision timelines', 'REIT and pension fund investment teams applying machine learning to portfolio performance benchmarking'],
 NOW()),

('immoviewer', 'iMMOVIEWER', 'AI virtual tour and 3D property presentation platform for real estate professionals',
 E'iMMOVIEWER is a real estate virtual tour and digital property presentation platform that uses AI to help real estate agents and property managers create professional virtual tours and 3D property presentations without specialised hardware or technical expertise. The platform supports 360-degree camera integration from consumer-grade cameras, processes the captured images into navigable virtual tours, and generates AI-enhanced presentation materials including floor plan overlays, branded tour pages, and automated social media content for property listings.\n\nThe AI enhancement layer improves the visual quality of uploaded 360-degree images - correcting lighting imbalances, reducing image noise, and producing more accurate colour rendition than the source camera hardware alone achieves. The floor plan AI generates dimensioned layout plans from the 360-degree image set without requiring a separate scanning device or measurement session. The branded tour player generates shareable listing links, QR codes for physical marketing materials, and embed codes for real estate portals and agency websites.\n\niMMOVIEWER targets the large segment of real estate agents who want professional virtual tour capabilities without the capital cost of a Matterport Pro camera system. The subscription model is accessible for individual agents and small agencies. The platform integrates with major real estate portals in Europe and Latin America, where iMMOVIEWER has strong market presence. For agents in markets where 360-degree virtual tours are an expected component of professional property marketing, iMMOVIEWER provides a cost-effective path to that capability without enterprise-level hardware investment.',
 'https://immoviewer.com', 'https://immoviewer.com',
 'freemium', true, 29, 4.0, 1100, false, false, false,
 ARRAY['real-estate', 'virtual-tours', 'marketing'],
 ARRAY['Consumer-grade 360-degree camera support lowers hardware cost compared to Matterport', 'AI image enhancement improves virtual tour quality without specialist photography skills', 'Floor plan generation from 360-degree capture without separate measurement session', 'Strong real estate portal integration in European and Latin American markets'],
 ARRAY['3D model fidelity is lower than Matterport Pro capture for luxury property marketing', 'Floor plan accuracy from 360-degree images is less precise than dedicated scan hardware', 'Market portal integration is strongest in Europe - fewer integrations for US-focused agents', 'Advanced branding and customisation features require higher subscription tiers'],
 ARRAY['Real estate agents in Europe and Latin America adding virtual tours to property listings', 'Small agencies creating professional 360-degree marketing materials without Matterport hardware costs', 'Property managers creating virtual move-in documentation and remote property inspection tours'],
 NOW())

ON CONFLICT (slug) DO NOTHING;
