-- tools-batch-19.sql
-- 10 new tools: DB 212 → 222
-- ON CONFLICT (slug) DO NOTHING (idempotent)

INSERT INTO tools (slug, name, tagline, description, logo_url, website_url, affiliate_url, tags, pricing_type, pricing_free_tier, pricing_starting_price, rating, review_count, featured, trending, editor_pick, pros, cons, use_cases)
VALUES

-- 1. Soundraw
('soundraw', 'Soundraw', 'AI music generator for creators who need royalty-free tracks with full mood control', 'Soundraw is an AI music generation tool designed specifically for video creators, marketers, and game developers who need royalty-free background music that matches their content''s mood and pacing. Unlike tools that generate a fixed track from a prompt, Soundraw lets users select genre, mood, theme, tempo, and length before generation, then adjust individual instrument layers, energy levels, and timing after the track is created. This combination of generation and fine-tuning makes it more controllable than pure text-to-music tools. All generated tracks are royalty-free for commercial use with any Soundraw subscription, resolving the licensing complexity that comes with stock music libraries. The tool is particularly popular with YouTube creators, video editors, and podcast producers who need a steady supply of original background music without per-track licensing fees. Plans start at $16.99/mo.', 'https://www.google.com/s2/favicons?domain=soundraw.io&sz=64', 'https://soundraw.io', 'https://soundraw.io', ARRAY['audio-ai', 'creative'], 'paid', false, 16.99, 4.3, 1560, false, true, false, ARRAY['Full control over mood, genre, tempo, and instrument layers', 'Royalty-free commercial license included in subscription', 'Tracks adjustable after generation - not just a one-shot output', 'Purpose-built for video and content creators'], ARRAY['No free tier - requires subscription to generate', 'Vocal tracks not supported - instrumental only', 'Less genre diversity than Udio for experimental music'], ARRAY['Background music for YouTube videos and ads', 'Podcast intro and outro tracks', 'Video game and app ambient audio']),

-- 2. Mubert
('mubert', 'Mubert', 'AI music streaming API for developers and creators needing continuous generative audio', 'Mubert is an AI-powered music platform with two distinct use cases: a consumer app for personal listening and a developer API for integrating AI-generated music into applications, games, and interactive experiences. The generative engine produces continuous, adaptive music that adjusts in real time to user inputs, making it particularly valuable for gaming, meditation apps, focus tools, and interactive experiences where a fixed track would loop awkwardly. The API allows developers to specify mood, energy, activity, and duration to generate a unique track programmatically. For content creators, Mubert Render generates downloadable tracks for video projects with commercial licensing included. The platform covers over 50 music genres and produces audio that genuinely sounds like live production rather than algorithmic output. Mubert Studio plans from $14/mo.', 'https://www.google.com/s2/favicons?domain=mubert.com&sz=64', 'https://mubert.com', 'https://mubert.com', ARRAY['audio-ai', 'developer-tools'], 'freemium', true, 14.00, 4.2, 980, false, false, false, ARRAY['Real-time adaptive music generation via API', 'Continuous playback without repetitive loops', 'Commercial license included for creators', 'Strong developer API for app integration'], ARRAY['Less manual control than Soundraw for fine-tuning tracks', 'Consumer app experience is secondary to API use case', 'Higher API costs at scale for developers'], ARRAY['Generative background music for apps and games', 'Adaptive audio for focus and meditation tools', 'Royalty-free track generation for video content']),

-- 3. Pika
('pika', 'Pika', 'AI video generator that transforms images and text into short cinematic clips', 'Pika is an AI video generation platform that converts text descriptions and still images into short animated video clips with cinematic quality. Its core strength is consistency and controllability - users can specify camera motion, aspect ratio, and visual style alongside their prompt, giving more directional control than most comparable tools. Pika 2.0 introduced significant improvements in motion realism, scene coherence, and the ability to add elements to existing video footage through its Modify Region feature. For social media creators, marketers, and designers who need high-quality short video content without a film crew, Pika provides a fast path from concept to visual output. The platform operates on a credit-based system with a free tier that covers initial experimentation before committing to a paid plan. Paid plans from $8/mo.', 'https://www.google.com/s2/favicons?domain=pika.art&sz=64', 'https://pika.art', 'https://pika.art', ARRAY['video-ai', 'creative'], 'freemium', true, 8.00, 4.4, 3210, false, true, false, ARRAY['Strong camera motion and style controls beyond basic text prompts', 'Modify Region lets users edit specific parts of generated video', 'Free tier with monthly credits for experimentation', 'Competitive pricing starting at $8/mo'], ARRAY['Clip duration limited to seconds on standard plans', 'Motion realism still behind Runway for complex scenes', 'Credit consumption varies widely by generation complexity'], ARRAY['Short-form social video and animated content', 'Product visualisation and concept animation', 'Image-to-video transformation for marketing']),

-- 4. Suno
('suno', 'Suno', 'AI song generator that creates complete songs with lyrics and vocals from a text prompt', 'Suno is an AI music generation platform that produces complete songs with vocals, instrumentation, and original lyrics from a short text description. Users can specify genre, mood, lyrical theme, or even provide their own lyrics for the AI to set to music. Suno''s vocal synthesis is among the most convincing available, with the model producing credible performances across pop, hip-hop, folk, rock, and electronic genres. The free tier offers a generous daily credit allowance, making Suno one of the most accessible AI music tools for experimentation without payment. Paid plans from $8/mo unlock longer tracks, commercial licensing, and higher generation limits. Suno is best understood as a complete song production tool - users provide a direction and receive a finished track, as opposed to tools like Soundraw that focus on instrumental background music with more manual control.', 'https://www.google.com/s2/favicons?domain=suno.ai&sz=64', 'https://suno.ai', 'https://suno.ai', ARRAY['audio-ai', 'creative'], 'freemium', true, 8.00, 4.5, 4200, false, true, false, ARRAY['Complete songs with convincing vocals and lyrics from a prompt', 'Generous free tier with daily credits', 'Covers wide genre range including complex vocal styles', 'Custom lyrics input supported'], ARRAY['Less control over individual musical elements than Soundraw', 'Commercial license requires paid plan', 'Vocal style not fully controllable - AI chooses delivery'], ARRAY['Rapid song concept and demo creation', 'Custom jingles and brand audio', 'Royalty-free original music for content creators']),

-- 5. Stable Audio
('stable-audio', 'Stable Audio', 'High-quality AI audio generation for sound design, music, and audio effects', 'Stable Audio is Stability AI''s text-to-audio model that generates music, sound effects, and audio atmospheres from text prompts. Unlike song-focused tools, Stable Audio covers the full spectrum of audio content: background music, ambient sound, cinematic sound design, foley effects, and instrumental compositions. The model produces high-fidelity stereo output up to 44.1kHz, matching the quality expected for professional audio production. Sound designers, film composers, and game developers use Stable Audio to prototype audio concepts quickly and generate unique sound effects that are not available in standard libraries. The free tier allows a limited number of generations per day. The API access makes Stable Audio usable within production pipelines for teams building audio-generation features into their own applications. Paid plans from $11.99/mo.', 'https://www.google.com/s2/favicons?domain=stability.ai&sz=64', 'https://www.stableaudio.com', 'https://www.stableaudio.com', ARRAY['audio-ai', 'developer-tools'], 'freemium', true, 11.99, 4.2, 870, false, false, false, ARRAY['Covers music, sound effects, and ambient audio in one tool', 'High-fidelity 44.1kHz stereo output for professional use', 'API access for integration into production pipelines', 'Strong for cinematic and sound design use cases'], ARRAY['Less polished for full song production than Suno', 'Interface less intuitive than consumer-focused competitors', 'Generation credits consumed quickly on complex audio'], ARRAY['Sound design and foley for video and games', 'Ambient and atmospheric audio for experiences', 'Prototype music compositions for film and media']),

-- 6. Fireflies AI
('fireflies-ai', 'Fireflies.ai', 'AI meeting assistant that records, transcribes, and summarises every conversation', 'Fireflies.ai is an AI meeting assistant that automatically joins video calls, records the audio, produces a transcript, and generates a summary with action items, key decisions, and topic breakdowns. It integrates natively with Zoom, Google Meet, Microsoft Teams, and Webex, joining as a bot participant without requiring the host to set up recording manually. The search feature allows users to search across all past meeting transcripts for specific topics, decisions, or mentions, making it useful for reviewing what was agreed in previous conversations. Fireflies also generates email-ready meeting summaries and CRM integration to log call notes automatically in Salesforce or HubSpot. The free tier covers limited transcription minutes per month; paid plans from $10/user/mo offer unlimited transcription and full search history. For teams that have multiple client or internal calls per day, Fireflies removes the administrative burden of manual note-taking entirely.', 'https://www.google.com/s2/favicons?domain=fireflies.ai&sz=64', 'https://fireflies.ai', 'https://fireflies.ai', ARRAY['productivity', 'voice-audio'], 'freemium', true, 10.00, 4.4, 3800, false, false, false, ARRAY['Auto-joins calls without host action - fully passive recording', 'Search across all past meeting transcripts', 'CRM integration with Salesforce and HubSpot', 'Email-ready meeting summaries generated automatically'], ARRAY['Bot participant visible to all attendees - some clients object', 'Free tier transcription minutes limited', 'Transcript accuracy drops with heavy accents or crosstalk'], ARRAY['Sales call recording and CRM logging', 'Team meeting documentation and action item tracking', 'Client conversation search and recall']),

-- 7. Reflect
('reflect', 'Reflect', 'AI-powered note-taking app with networked thinking and automatic backlinking', 'Reflect is a note-taking application built around the concept of networked thinking - notes automatically link to related notes, creating a personal knowledge graph that surfaces connections the user did not explicitly make. The AI layer adds meeting transcription, automatic note summarisation, and a writing assistant that can help develop ideas within the note-taking workflow. Unlike Notion, which is a flexible team workspace, Reflect is optimised for individual knowledge management and thinking rather than project collaboration. The backlinking system is inspired by Roam Research but with a cleaner interface and stronger AI integration. Reflect syncs across all devices with end-to-end encryption, making it suitable for personal and professional notes that require privacy. Plans start at $10/mo with no free tier. For professionals who think in notes and need their information to connect across topics, Reflect is a more opinionated and AI-forward alternative to standard note tools.', 'https://www.google.com/s2/favicons?domain=reflect.app&sz=64', 'https://reflect.app', 'https://reflect.app', ARRAY['productivity', 'research-ai'], 'paid', false, 10.00, 4.3, 1120, false, false, false, ARRAY['Automatic backlinks surface connections across notes', 'End-to-end encryption for personal and professional notes', 'AI writing assistant integrated into note workflow', 'Cleaner interface than Roam Research for most users'], ARRAY['No free tier - paid from first use', 'Less collaborative than Notion for team use', 'Learning curve for networked note-taking methodology'], ARRAY['Personal knowledge management and research notes', 'Meeting notes with automatic connection to related topics', 'Long-term thinking and idea development']),

-- 8. Mem AI
('mem-ai', 'Mem', 'AI-powered workspace that automatically organises notes and surfaces relevant information', 'Mem is an AI note-taking and workspace tool that removes the need for manual organisation. Instead of creating folders and tags, users capture notes freely and Mem''s AI automatically identifies connections, surfaces related notes when you need them, and builds a semantic understanding of your knowledge base. The Smart Search feature retrieves notes based on meaning rather than exact keyword matches - searching for "the Q3 revenue discussion" finds the relevant note even if those exact words were not used. Mem also offers an AI writing assistant and integration with email and calendar to automatically surface relevant notes before meetings. The always-available AI chat lets users ask questions about their own notes, effectively making their note archive conversational. Mem is best suited to individuals and small teams who want intelligence built into their knowledge management rather than a rigid system they maintain manually. Plans from $14.99/mo.', 'https://www.google.com/s2/favicons?domain=mem.ai&sz=64', 'https://mem.ai', 'https://mem.ai', ARRAY['productivity', 'research-ai'], 'freemium', true, 14.99, 4.2, 890, false, false, false, ARRAY['No manual organisation required - AI handles connections', 'Semantic search retrieves notes by meaning not exact words', 'AI chat lets users query their own knowledge base', 'Calendar integration surfaces relevant notes before meetings'], ARRAY['AI organisation less predictable than manual tagging', 'Less suitable for team collaboration than Notion', 'Free tier is very limited in practice'], ARRAY['Personal knowledge base with zero-maintenance organisation', 'Research and reference note management', 'Meeting preparation using historical note context']),

-- 9. Taskade
('taskade', 'Taskade', 'AI-powered project management with built-in agents for task automation and research', 'Taskade combines project management, document editing, and AI agents into a single workspace. Teams can create projects, assign tasks, and build knowledge bases, while AI agents can be configured to research topics, generate content, analyse data, and complete tasks within the workflow automatically. The agent system is what distinguishes Taskade from standard project management tools - rather than just tracking work, it can do work on behalf of the team. Task hierarchies, mind maps, kanban boards, and list views are all supported within the same project structure, allowing teams to visualise work in whatever format suits the task type. Taskade is particularly popular with content teams, agencies, and research teams who benefit from AI automation within their project structure. Free tier available; paid plans from $8/mo.', 'https://www.google.com/s2/favicons?domain=taskade.com&sz=64', 'https://www.taskade.com', 'https://www.taskade.com', ARRAY['productivity', 'ai-assistants'], 'freemium', true, 8.00, 4.3, 1340, false, true, false, ARRAY['AI agents can complete tasks, not just track them', 'Multiple view types: kanban, list, mind map, calendar', 'Combines project management, documents, and AI in one tool', 'Generous free tier for individuals and small teams'], ARRAY['Agent configuration requires learning the system', 'Less mature than Linear or Asana for pure project management', 'Real-time collaboration less polished than Notion'], ARRAY['AI-assisted project and content workflows', 'Research and analysis with automated agent tasks', 'Team knowledge base with linked task management']),

-- 10. Perplexity Pro
('perplexity', 'Perplexity', 'AI search engine that answers questions with cited real-time sources', 'Perplexity is an AI-powered search engine that provides direct answers to questions by synthesising information from real-time web sources, with inline citations so users can verify every claim. Unlike standard search engines that return a list of links, Perplexity reads the sources and produces a conversational answer with supporting evidence. The result is faster than reading multiple articles but more reliable than asking an AI model with a training cutoff. Perplexity handles follow-up questions conversationally, maintaining context across a research session. The Pro version adds access to the most capable AI models (GPT-4o, Claude Sonnet, Gemini Pro) for complex reasoning tasks, image generation, and higher daily usage limits. For researchers, analysts, and knowledge workers who need current, verifiable information quickly, Perplexity is the most practical search replacement available. Free tier available; Pro at $20/mo.', 'https://www.google.com/s2/favicons?domain=perplexity.ai&sz=64', 'https://www.perplexity.ai', 'https://www.perplexity.ai/pro', ARRAY['ai-assistants', 'research-ai'], 'freemium', true, 20.00, 4.7, 8900, true, true, false, ARRAY['Real-time web sources with inline citations on every answer', 'Conversational follow-up maintains research context', 'Pro access to GPT-4o, Claude, and Gemini models', 'Faster than reading multiple articles for research'], ARRAY['Less capable than Claude for complex reasoning and long documents', 'Answer quality limited by source quality for niche topics', 'Not suitable for tasks requiring deep analysis or generation'], ARRAY['Real-time research on current events and recent data', 'Fact-checking with source verification', 'Quick literature review across multiple sources'])

ON CONFLICT (slug) DO NOTHING;
