-- tools-batch-51.sql
-- 10 AI Workflow Automation tools
-- Run AFTER tools-batch-50.sql confirmed in Supabase

INSERT INTO tools (slug, name, tagline, description, logo_url, website_url, affiliate_url, tags, pricing_type, pricing_free_tier, pricing_starting_price, rating, review_count, featured, trending, editor_pick, pros, cons, use_cases)
VALUES
('zapier',
 'Zapier',
 'Connect your apps and automate workflows without writing code',
 'Zapier is the world''s most widely used workflow automation platform, connecting more than 6,000 apps so non-technical users can build automated workflows called Zaps without writing a single line of code. The platform''s AI features include a natural-language Zap builder where you describe what you want to automate and Zapier generates the workflow, suggested Zaps based on your connected apps, and an AI-powered troubleshooting assistant that diagnoses broken workflows and suggests fixes. Zapier supports multi-step Zaps with conditional logic, filters, and formatters that transform data between apps - enabling complex automation sequences that would otherwise require a developer. Integrations span CRM, email, project management, communication, e-commerce, and virtually every SaaS category. For small businesses, marketing teams, and operations teams that need to eliminate repetitive manual work across their tool stack without technical expertise, Zapier remains the default starting point for workflow automation.',
 'https://www.google.com/s2/favicons?domain=zapier.com&sz=64',
 'https://zapier.com',
 'https://zapier.com',
 ARRAY['automation', 'workflow', 'integration', 'no-code', 'zapier', 'productivity'],
 'freemium', true, 19.99, 4.5, 14200, true, true, false,
 ARRAY['6,000+ app integrations covering every major SaaS category', 'AI Zap builder creates workflows from natural language descriptions', 'No-code interface accessible to non-technical users', 'Multi-step Zaps with filters, conditions, and data formatters', 'Extensive documentation and community with pre-built Zap templates'],
 ARRAY['Pricing scales quickly with task volume - high usage gets expensive', 'Complex multi-step workflows require Zapier-specific logic that is hard to migrate', 'Free plan limited to 100 tasks per month and single-step Zaps only', 'Slower execution than direct API integrations or developer-built solutions'],
 ARRAY['Sync CRM leads to email marketing lists automatically', 'Create project tasks from form submissions without manual entry', 'Post Slack notifications when new deals close in your CRM']),

('make-com',
 'Make',
 'Visual automation platform for building powerful multi-step workflows',
 'Make (formerly Integromat) is the visual workflow automation platform built for users who need more power and flexibility than Zapier''s linear workflow model. Make''s canvas-based builder lets you construct complex multi-step workflows with branches, iterators, aggregators, and error handling paths that can process thousands of records in a single execution. The platform connects to 1,500+ apps and supports direct HTTP/API calls for any service without a native integration. Make''s AI capabilities include a scenario assistant that generates workflow blueprints from text descriptions, AI modules for calling OpenAI and other LLMs directly within workflows, and smart data transformation suggestions. For technical users, marketers, and operations teams who need automation that can handle complex data manipulation, conditional branching, and large volume processing at a fraction of Zapier''s cost, Make is the leading alternative.',
 'https://www.google.com/s2/favicons?domain=make.com&sz=64',
 'https://make.com',
 'https://make.com',
 ARRAY['automation', 'workflow', 'visual-builder', 'integration', 'make', 'no-code'],
 'freemium', true, 9.00, 4.6, 9800, true, true, false,
 ARRAY['Visual canvas builder handles complex branching workflows Zapier cannot', 'Significantly more affordable than Zapier for high-volume automation', 'HTTP module enables integration with any API without a native connector', 'Built-in AI modules for calling LLMs directly within workflows', 'Detailed execution logs and error handling built into the platform'],
 ARRAY['Steeper learning curve than Zapier for non-technical users', 'Fewer native integrations than Zapier (1,500 vs 6,000+)', 'Complex scenarios require understanding of data structures and iterators', 'Support response times can be slow on lower-tier plans'],
 ARRAY['Process large datasets from spreadsheets through multi-step transformation workflows', 'Build complex order fulfillment automation with conditional routing', 'Connect APIs without native integrations using HTTP modules']),

('activepieces',
 'Activepieces',
 'Open-source workflow automation with self-hosting and AI-native design',
 'Activepieces is the open-source automation platform built as a modern, AI-native alternative to Zapier and Make. The platform offers a no-code flow builder with a growing library of 200+ integrations, along with the ability to self-host the entire platform on your own infrastructure - a critical advantage for teams with data residency requirements, regulated industries, or companies that want full control over their automation without vendor lock-in. Activepieces includes native AI pieces for calling OpenAI, Anthropic, and other LLMs within automation flows, enabling AI-augmented workflows without external AI middleware. The open-source codebase means teams with developers can extend the platform with custom pieces for any internal tool or API. For startups, technical teams, and organizations that prioritize data control and want a cost-effective automation platform that can grow with them, Activepieces offers a compelling alternative to closed-source platforms.',
 'https://www.google.com/s2/favicons?domain=activepieces.com&sz=64',
 'https://activepieces.com',
 'https://activepieces.com',
 ARRAY['automation', 'open-source', 'workflow', 'no-code', 'self-hosted', 'AI'],
 'freemium', true, 0.00, 4.3, 1400, false, true, false,
 ARRAY['Fully open-source with self-hosting option for complete data control', 'Native AI pieces for OpenAI and Anthropic without external middleware', 'No vendor lock-in - extend with custom pieces using the open SDK', 'Cloud version free tier available with no credit card required', 'Active development with rapid integration library growth'],
 ARRAY['Smaller integration library than Zapier or Make (200+ vs 1,500-6,000+)', 'Community and support less mature than established platforms', 'Self-hosting requires technical knowledge to set up and maintain', 'Fewer pre-built templates for common automation scenarios'],
 ARRAY['Self-host automation workflows to keep sensitive business data on-premises', 'Build AI-augmented workflows combining automation with LLM calls', 'Automate internal tool integrations with custom-built pieces']),

('pipedream',
 'Pipedream',
 'Developer-first workflow automation with code and no-code in one platform',
 'Pipedream is the automation platform built for developers who want the power of code within a workflow tool. Unlike pure no-code platforms, Pipedream lets you write Node.js, Python, Go, or Bash code directly within workflow steps alongside pre-built connectors - bridging the gap between low-code automation and custom development. The platform connects to 2,000+ APIs with built-in auth handling, so developers don''t need to manage OAuth flows and API credentials manually. Pipedream''s AI code generation writes workflow steps from natural language prompts, dramatically reducing development time for common automation patterns. Event-driven architecture means workflows trigger in real time from webhooks, schedules, app events, and database changes. For engineering teams, technical founders, and developers who want automation that can do anything but without the overhead of building and hosting a custom integration server, Pipedream occupies a unique position between no-code tools and full custom development.',
 'https://www.google.com/s2/favicons?domain=pipedream.com&sz=64',
 'https://pipedream.com',
 'https://pipedream.com',
 ARRAY['automation', 'developer-tools', 'API', 'workflow', 'integration', 'code'],
 'freemium', true, 19.00, 4.4, 3800, false, true, false,
 ARRAY['Write Node.js, Python, Go, or Bash code directly within workflow steps', 'AI code generation writes steps from natural language descriptions', '2,000+ pre-built app connectors with built-in auth management', 'Real-time event-driven triggers from webhooks and app events', 'Free tier generous enough for personal and small team use'],
 ARRAY['Requires programming knowledge to unlock full power - not truly no-code', 'Pricing jumps significantly when moving beyond free tier limits', 'Less suitable for non-technical business users compared to Zapier', 'Fewer pre-built workflow templates for common business use cases'],
 ARRAY['Build custom API integrations without managing OAuth and auth infrastructure', 'Process webhook events with custom transformation logic in code', 'Automate developer workflows connecting GitHub, CI/CD, and deployment tools']),

('bardeen',
 'Bardeen',
 'AI-powered browser automation for web tasks and data collection',
 'Bardeen is the AI automation tool built specifically for browser-based tasks - web scraping, form filling, data collection from websites, and automating repetitive actions inside web apps that don''t have APIs. The Chrome extension installs in seconds and gives users access to an AI agent that can navigate websites, extract data, and perform actions based on natural language instructions. Bardeen''s Scraper feature extracts structured data from any website without writing CSS selectors or XPath - describe what you want and the AI identifies the right data. The platform also integrates with 100+ apps for sending extracted data directly to CRMs, spreadsheets, and databases. For sales teams doing prospecting research, recruiters sourcing candidates, and operations teams that need data from websites without developer support, Bardeen eliminates hours of manual copy-paste work.',
 'https://www.google.com/s2/favicons?domain=bardeen.ai&sz=64',
 'https://bardeen.ai',
 'https://bardeen.ai',
 ARRAY['automation', 'browser', 'AI', 'web-scraping', 'productivity', 'no-code'],
 'freemium', true, 10.00, 4.2, 2400, false, true, false,
 ARRAY['AI agent automates browser tasks from natural language instructions', 'No-code web scraping extracts data from any website without selectors', 'Chrome extension installs in seconds with no technical setup', 'Integrates with 100+ apps to route extracted data automatically', 'Ideal for sales prospecting and research workflows'],
 ARRAY['Browser-only automation - cannot automate server-side or API-based tasks', 'AI agents can break when websites update their structure', 'Limited to Chrome browser - no Firefox or Safari support', 'More expensive than expected for high-volume scraping use cases'],
 ARRAY['Extract contact information from LinkedIn profiles into your CRM automatically', 'Scrape product prices and availability from competitor websites', 'Automate repetitive data entry tasks inside web apps without APIs']),

('integrately',
 'Integrately',
 'One-click automation platform with 1200+ app integrations',
 'Integrately is the automation platform built around a single promise: get your first automation running in under a minute. Its library of 20+ million pre-built automation templates covers the most common use cases across 1,200+ apps, so most users can find, activate, and customize an automation without building from scratch. The platform''s AI automation assistant generates complete automation workflows from natural language descriptions of what you want to achieve. For small businesses, solopreneurs, and teams new to automation who want proven templates rather than building workflows from zero, Integrately''s template-first approach dramatically reduces the learning curve compared to Zapier or Make. Pricing is also more accessible - annual plans are significantly cheaper than Zapier for similar task volumes.',
 'https://www.google.com/s2/favicons?domain=integrately.com&sz=64',
 'https://integrately.com',
 'https://integrately.com',
 ARRAY['automation', 'integration', 'no-code', 'workflow', 'templates', 'small-business'],
 'freemium', true, 19.99, 4.1, 2100, false, false, false,
 ARRAY['20+ million pre-built automation templates reduce setup time to minutes', 'AI automation builder generates workflows from natural language', '1,200+ app integrations covering major SaaS categories', 'More affordable annual pricing than Zapier for comparable task volumes', 'Beginner-friendly interface with template browsing as the primary flow'],
 ARRAY['Less flexible than Zapier or Make for complex custom workflows', 'Smaller integration library than Zapier despite 1,200+ apps', 'Advanced features like multi-step logic require higher-tier plans', 'Support and documentation less comprehensive than major platforms'],
 ARRAY['Connect your lead generation forms to CRM and email marketing in one click', 'Automate e-commerce order notifications across multiple channels', 'Sync calendar events to project management tools automatically']),

('albato',
 'Albato',
 'European workflow automation platform with GDPR compliance and 600+ integrations',
 'Albato is the European-based workflow automation platform that positions itself as the GDPR-compliant alternative to US-based automation tools like Zapier and Make. All data processing occurs on European servers, making it the preferred choice for EU-based businesses, regulated industries, and companies with strict data residency requirements under GDPR. The platform connects 600+ apps with a visual workflow builder that supports multi-step automation, conditional logic, and data transformation. Albato''s pricing is competitive for European teams - plans are structured for small to medium businesses without the task-count pricing that makes Zapier expensive at scale. For EU companies that want workflow automation without the compliance complexity of routing business data through US-based services, Albato removes the legal friction.',
 'https://www.google.com/s2/favicons?domain=albato.com&sz=64',
 'https://albato.com',
 'https://albato.com',
 ARRAY['automation', 'GDPR', 'European', 'integration', 'workflow', 'compliance'],
 'paid', false, 13.00, 4.0, 960, false, false, false,
 ARRAY['EU-based data processing for GDPR compliance without additional configuration', 'Competitive pricing for European teams compared to US platforms', '600+ app integrations covering major business tools', 'Visual workflow builder with conditional logic and data transformation', 'No task-count pricing traps - flat monthly plans'],
 ARRAY['Smaller integration library than Zapier or Make', 'Less community content and third-party tutorials available', 'AI features less developed than US-based competitors', 'Best suited for EU market - limited focus on US-specific SaaS tools'],
 ARRAY['Automate EU business workflows while keeping data on European servers', 'Connect GDPR-regulated customer data between CRM and marketing tools', 'Build compliance-safe automation for regulated industries in Europe']),

('workato',
 'Workato',
 'Enterprise automation and integration platform for IT and business teams',
 'Workato is the enterprise integration and automation platform used by IT teams and business operations groups to connect enterprise systems - ERP, HRIS, CRM, databases - with the speed of no-code automation and the reliability of enterprise-grade infrastructure. The platform''s Copilot AI generates automation recipes from natural language, helps debug workflow issues, and suggests optimizations for complex integration logic. Workato''s strength is its data handling - it processes millions of records with transformation, deduplication, and error recovery built in, not bolted on. Governance features including audit logs, role-based access control, and environment management (dev/staging/prod) make it suitable for enterprise IT teams that need to manage hundreds of automations at scale. For companies that have outgrown Zapier and Make and need enterprise-grade reliability, compliance, and data volume handling, Workato is the standard choice.',
 'https://www.google.com/s2/favicons?domain=workato.com&sz=64',
 'https://workato.com',
 'https://workato.com',
 ARRAY['automation', 'enterprise', 'integration', 'iPaaS', 'workflow', 'IT'],
 'paid', false, 0.00, 4.5, 4800, false, true, false,
 ARRAY['Enterprise-grade reliability and data handling for high-volume integration', 'AI Copilot generates automation recipes from natural language descriptions', 'Dev/staging/prod environment management for enterprise governance', 'Connects ERP, HRIS, and enterprise systems alongside SaaS apps', 'Role-based access control and audit logs for compliance teams'],
 ARRAY['Enterprise pricing with no self-serve - requires sales engagement', 'Significant investment compared to Zapier or Make for SMB use cases', 'Learning curve for non-technical business users despite no-code interface', 'Minimum commitment typically starts at $10,000+ per year'],
 ARRAY['Automate HR onboarding workflows across HRIS, IT provisioning, and communication tools', 'Integrate ERP systems with e-commerce platforms for order processing', 'Build enterprise data sync workflows with governance and audit trails']),

('tray-io',
 'Tray.ai',
 'Enterprise AI automation platform with workflow generation and deep integrations',
 'Tray.ai (formerly Tray.io) is the enterprise automation platform that combines AI-generated workflow creation with deep integration capabilities for complex enterprise environments. The platform''s Merlin AI agent generates complete automation workflows from natural language descriptions of business processes, handles multi-step logic generation, and can autonomously identify and connect the right APIs to accomplish tasks. Tray.ai''s connector library emphasizes deep, reliable integrations with enterprise systems - Salesforce, ServiceNow, Workday, and NetSuite alongside the standard SaaS stack. The platform targets revenue operations, IT teams, and business operations groups at mid-market and enterprise companies that need automation at scale with AI-accelerated workflow creation. For organizations evaluating enterprise iPaaS platforms, Tray.ai competes directly with Workato and Mulesoft but with a stronger AI-first positioning.',
 'https://www.google.com/s2/favicons?domain=tray.io&sz=64',
 'https://tray.io',
 'https://tray.io',
 ARRAY['automation', 'enterprise', 'AI', 'integration', 'iPaaS', 'workflow'],
 'paid', false, 0.00, 4.3, 3200, false, false, false,
 ARRAY['Merlin AI agent generates complete workflows from natural language', 'Deep enterprise system integrations with Salesforce, ServiceNow, and Workday', 'AI-first positioning with autonomous workflow creation capabilities', 'Handles complex multi-step enterprise integration scenarios', 'Strong security and governance features for enterprise compliance'],
 ARRAY['Enterprise-only pricing requiring sales engagement', 'Not suitable for small teams or simple automation use cases', 'Complex platform with steep learning curve despite AI assistance', 'Limited self-serve resources compared to Zapier or Make'],
 ARRAY['Automate complex RevOps workflows connecting CRM, billing, and customer success tools', 'Build ServiceNow IT automation workflows with AI-generated logic', 'Integrate enterprise data systems with cloud SaaS applications at scale']),

('pabbly-connect',
 'Pabbly Connect',
 'Affordable automation platform with unlimited workflows and lifetime deal pricing',
 'Pabbly Connect is the workflow automation platform built for budget-conscious teams and small businesses that need solid automation without the per-task pricing that makes Zapier expensive at scale. The platform connects 1,000+ apps with multi-step automation support, conditional routing, and data formatting - covering most common business automation use cases. Pabbly Connect''s pricing model is its defining feature: plans are based on the number of workflow executions per month rather than individual tasks within a workflow, which makes multi-step automations dramatically cheaper than Zapier for the same volume. The platform also offers lifetime deal pricing through AppSumo and similar marketplaces, making it a popular choice for solopreneurs and small teams that want a one-time investment in automation infrastructure. For cost-sensitive teams running high volumes of multi-step automations, Pabbly Connect delivers strong value at a fraction of Zapier pricing.',
 'https://www.google.com/s2/favicons?domain=pabbly.com&sz=64',
 'https://pabbly.com/connect',
 'https://pabbly.com/connect',
 ARRAY['automation', 'integration', 'workflow', 'lifetime-deal', 'no-code', 'small-business'],
 'paid', false, 17.00, 4.2, 4100, false, false, false,
 ARRAY['Per-execution pricing makes multi-step automations cheaper than Zapier', 'Lifetime deal pricing available for one-time investment', '1,000+ app integrations covering major business and marketing tools', 'Unlimited workflow steps - no per-step charges like Zapier', 'Good value for solopreneurs and small teams running high automation volumes'],
 ARRAY['Less polished interface compared to Zapier or Make', 'AI features significantly less developed than competitors', 'Fewer integration templates - more manual workflow setup required', 'Customer support and documentation less comprehensive than major platforms'],
 ARRAY['Run high-volume lead gen automation without per-task cost penalties', 'Automate e-commerce workflows with unlimited steps at a flat monthly rate', 'Replace Zapier for cost savings on multi-step automation use cases'])
ON CONFLICT (slug) DO NOTHING;
