-- tools-batch-49.sql
-- 10 AI Customer Success tools
-- All slugs verified NOT present in any prior tools-batch file
-- glean (batch-11) and pendo (batch-29) excluded - already in DB
-- Run after tools-batch-48.sql confirmed in DB

INSERT INTO tools (slug, name, tagline, description, logo_url, website_url, affiliate_url, tags, pricing_type, pricing_free_tier, pricing_starting_price, rating, review_count, featured, trending, editor_pick, pros, cons, use_cases)
VALUES

('gainsight',
 'Gainsight',
 'Enterprise customer success platform for reducing churn, driving expansion, and scaling CS operations',
 'Gainsight is the market-leading customer success platform used by enterprise SaaS companies to manage customer health, reduce churn, and systematically drive expansion revenue. The platform centralises all customer data - product usage signals, support tickets, NPS scores, CRM activity, and contract data - into a unified customer health score that gives CS teams a real-time view of which accounts are at risk and which are ready for expansion. Gainsight CS uses rules-based and AI-driven playbooks that trigger automated tasks for CS managers when a customer health score drops below a threshold, when a key feature goes unused for 30 days, or when renewal is approaching. These playbooks standardise the CS motion across a team, ensuring every account receives consistent touchpoints regardless of which manager owns it. The Journey Orchestrator module enables automated lifecycle programmes - onboarding sequences, adoption check-ins, renewal campaigns, and executive business review scheduling - sent through email, in-app messaging, or Slack. Gainsight PX adds a product experience layer with in-app guides, feature announcements, and contextual help that drive feature adoption without requiring engineering resources. Gainsight integrates with Salesforce, Hubspot, Zendesk, Jira, and most major data warehouses. It is the platform of choice for enterprise CS teams at companies like Box, Workday, and Tableau managing hundreds or thousands of accounts where manual relationship management is not scalable.',
 NULL,
 'https://gainsight.com',
 'https://gainsight.com',
 ARRAY['customer-success', 'churn-reduction', 'saas', 'enterprise', 'product-adoption'],
 'paid',
 false,
 0.00,
 4.4, 3210,
 false, false, false,
 ARRAY['Unified customer health scoring across product usage, support, and CRM data', 'AI and rules-based playbooks standardise CS motions across large teams', 'Journey Orchestrator automates lifecycle touchpoints at scale without manual effort', 'Gainsight PX drives in-app feature adoption without engineering dependency'],
 ARRAY['Enterprise pricing and complexity make it overkill for teams under 50 accounts', 'Implementation requires significant time investment and often professional services support', 'Reporting customisation requires familiarity with the platform - steep learning curve initially'],
 ARRAY['Managing churn risk across hundreds of enterprise accounts with automated health scoring', 'Standardising CS playbooks so every account receives consistent lifecycle touchpoints', 'Running automated onboarding and adoption programmes across a large customer base']),

('totango',
 'Totango',
 'Modular customer success platform with SuccessBLOCs for fast CS programme deployment',
 'Totango is a customer success platform built around a modular architecture that lets CS teams deploy and activate specific customer success programmes - called SuccessBLOCs - without building workflows from scratch. Each SuccessBLOC is a pre-built, best-practice programme covering a specific CS motion: onboarding, adoption, renewal, expansion, or executive engagement. Teams activate a SuccessBLOC, customise the tasks and messaging for their customer base, and begin running a structured CS programme within days rather than the months typically required to configure enterprise CS platforms. Totango Spark is the core product for mid-market SaaS companies, combining customer health scoring, task management, email automation, and reporting in a package accessible to CS teams without dedicated operations support. The platform ingests customer data from Salesforce, Hubspot, data warehouses, and product analytics tools to build health scores and trigger engagement. The Spark AI layer analyses customer engagement patterns and proactively flags accounts showing early churn signals before they become urgent. Totango integrates with Salesforce, Hubspot, Mixpanel, Segment, and Slack. The SuccessBLOC marketplace includes pre-built programmes contributed by the Totango community and professional services team, significantly reducing the time required to launch a new CS initiative for any standard use case.',
 NULL,
 'https://totango.com',
 'https://totango.com',
 ARRAY['customer-success', 'churn-reduction', 'saas', 'mid-market', 'onboarding'],
 'freemium',
 true,
 0.00,
 4.2, 1680,
 false, false, false,
 ARRAY['SuccessBLOC pre-built programmes reduce CS implementation time from months to days', 'Modular architecture lets teams activate specific programmes without full platform configuration', 'Free plan available for early-stage CS teams with limited account volumes', 'AI flags early churn signals before accounts become urgent risk cases'],
 ARRAY['SuccessBLOC library is most valuable for standard SaaS use cases - complex custom models require more configuration', 'Reporting depth is less advanced than Gainsight for enterprise analytics requirements', 'Health score customisation requires understanding of the weighting system'],
 ARRAY['Deploying a structured onboarding programme for new customers within a week', 'Building a renewal playbook that triggers tasks 90, 60, and 30 days before contract end', 'Running expansion plays targeted at accounts showing high product adoption scores']),

('churnzero',
 'ChurnZero',
 'Real-time customer success platform for SaaS companies focused on reducing churn and increasing net revenue retention',
 'ChurnZero is a customer success platform built specifically for subscription SaaS businesses, with a focus on real-time signals and immediate action. The platform aggregates product usage data, support activity, NPS responses, and CRM information to build dynamic customer health scores that update continuously as customer behaviour changes - not just nightly or weekly. This real-time approach means CS managers receive alerts when a customer''s engagement drops sharply, when a power user goes inactive, or when a support spike suggests a problem, enabling intervention while there is still time to turn the account around. ChurnZero Journeys automates personalised touchpoints across the customer lifecycle - welcome sequences, feature adoption nudges, renewal communications, and win-back campaigns - triggered by customer behaviour rather than fixed calendar dates. The in-app notification system lets CS and product teams push contextual messages, surveys, and feature announcements directly within the customer''s product session. ChurnZero AI analyses churn risk across the customer base and provides predictive scores and recommended interventions. The platform integrates with Salesforce, Hubspot, Zendesk, Intercom, and major billing systems including Stripe and Chargebee. Used by mid-market and growth-stage SaaS companies including Shutterstock, Netsol, and Recurly to systematically improve net revenue retention across their customer base.',
 NULL,
 'https://churnzero.com',
 'https://churnzero.com',
 ARRAY['customer-success', 'churn-reduction', 'saas', 'net-revenue-retention', 'real-time'],
 'paid',
 false,
 0.00,
 4.3, 1470,
 false, false, false,
 ARRAY['Real-time health scores update as customer behaviour changes, not overnight', 'In-app notification system delivers messages without requiring email open rates', 'AI predictive churn scoring identifies at-risk accounts before manual review', 'Journeys automate personalised lifecycle communications triggered by actual behaviour'],
 ARRAY['Pricing is not publicly listed - requires a sales conversation to get started', 'Implementation complexity increases significantly for multi-product or multi-segment customer bases', 'Reporting exports require manual configuration for custom data needs'],
 ARRAY['Reducing time-to-value for new customers with automated onboarding journeys', 'Identifying accounts with declining usage before they submit a cancellation request', 'Running automated expansion campaigns targeted at accounts with high adoption scores']),

('planhat',
 'Planhat',
 'Modern customer success platform combining health scoring, revenue analytics, and team collaboration',
 'Planhat is a customer success platform designed for modern SaaS CS teams, combining customer health management, revenue analytics, task management, and team playbooks in a clean, intuitive interface that requires less configuration overhead than traditional CS enterprise platforms. The platform ingests data from CRM, billing, product analytics, and support systems to build a multi-dimensional view of each customer account - usage trends, contract value, expansion potential, support health, and engagement with the CS team. Planhat''s revenue analytics layer makes it the tool of choice for CS teams with clear ownership of net revenue retention - the platform tracks expansion MRR, contraction, and churn contribution by CS manager, segment, and cohort, connecting CS activity to the revenue metrics that matter to the business. Collaboration features including shared timelines, internal notes, and stakeholder relationship maps enable cross-functional coordination on strategic accounts without relying on email chains. Planhat AI suggests optimal outreach timing and next best actions based on each customer''s engagement pattern. The platform integrates with Salesforce, Hubspot, Stripe, Chargebee, Segment, and Mixpanel. Used by CS teams at Vend, Teamwork, and Factorial for clear visibility into how customer health connects to revenue outcomes, and for giving individual CS managers an intuitive daily workspace that surfaces the accounts needing attention.',
 NULL,
 'https://planhat.com',
 'https://planhat.com',
 ARRAY['customer-success', 'revenue-analytics', 'net-revenue-retention', 'saas', 'collaboration'],
 'paid',
 false,
 0.00,
 4.4, 920,
 false, false, false,
 ARRAY['Revenue analytics connects CS health signals to NRR, churn, and expansion outcomes', 'Clean modern interface requires less configuration overhead than legacy CS platforms', 'Collaboration timeline and relationship maps support cross-functional account coordination', 'AI suggests next best actions and optimal outreach timing per account'],
 ARRAY['Pricing requires a sales conversation - not self-serve onboarding', 'Automation capabilities are less mature than Gainsight or ChurnZero for complex lifecycle orchestration', 'Custom health score configuration requires understanding of weighting and data mapping'],
 ARRAY['Tracking NRR contribution by CS manager and customer segment with revenue attribution', 'Building a shared account timeline that sales, CS, and support all contribute to', 'Identifying expansion opportunities in high-health accounts with strong usage patterns']),

('vitally',
 'Vitally',
 'Customer success platform built for fast-growing SaaS companies with powerful reporting and Salesforce-level customisation',
 'Vitally is a customer success platform built for growth-stage SaaS companies that need the power of enterprise CS tools without the implementation complexity and cost. The platform is notable for its reporting depth and customisation - CS teams can build custom dashboards, segment cohorts by any attribute, and create bespoke health score models without needing professional services support. Vitally ingests data from product analytics, CRM, billing, and support systems and allows teams to define their own health metric weightings and threshold triggers. The Docs feature within Vitally enables CS managers to create structured account plans, success plans, and QBR templates that live alongside customer data rather than in a separate document tool. Project management features track onboarding milestones, implementation tasks, and strategic initiatives within the account, giving both the CS team and the customer visibility into progress. Vitally AI analyses account data to surface expansion signals and churn indicators with plain-language explanations of what the signals indicate and what action to take. The platform integrates with Salesforce, Hubspot, Segment, Intercom, Zendesk, Mixpanel, and Stripe. Vitally is the platform of choice for growth-stage SaaS companies including Productboard, Delighted, and Benchling that want Gainsight-level functionality at a price and implementation speed appropriate for a scaling team.',
 NULL,
 'https://vitally.io',
 'https://vitally.io',
 ARRAY['customer-success', 'reporting', 'saas', 'growth-stage', 'account-management'],
 'paid',
 false,
 0.00,
 4.5, 740,
 false, false, false,
 ARRAY['Reporting depth and custom dashboards match enterprise platforms without professional services', 'Docs feature brings structured success plans and account plans into the CS workflow', 'Health score customisation is fully self-serve with no implementation dependency', 'AI surfaces expansion signals and churn indicators with plain-language explanations'],
 ARRAY['Less mature automation and journey capabilities than Gainsight or ChurnZero', 'Smaller ecosystem of native integrations than the most established CS platforms', 'Pricing scales with customer accounts - can become expensive at high account volumes'],
 ARRAY['Building custom health score models that reflect the specific usage signals relevant to your product', 'Managing onboarding and implementation projects within the CS platform alongside health data', 'Generating segment-level reporting on NRR and churn by cohort for quarterly business reviews']),

('catalyst',
 'Catalyst',
 'Customer success platform with deep Salesforce integration and revenue-first CS programme management',
 'Catalyst is a customer success platform built for CS teams that operate within a Salesforce-centric revenue stack and need their CS data to live natively alongside CRM data rather than in a disconnected system. The platform is built on top of Salesforce infrastructure, which means customer health scores, CS tasks, playbooks, and account intelligence appear directly within Salesforce records without requiring a data sync or integration layer. This architecture eliminates the data discrepancy problems that arise when CRM and CS platforms operate separately - a customer renewal date changed in Salesforce immediately reflects in the CS health scoring, and CS activity logged in Catalyst is immediately visible to account executives in their CRM workflow. Catalyst tracks customer health across product adoption, support engagement, executive sponsorship, and NPS data, with automated playbooks that trigger tasks based on health threshold breaches. The platform includes revenue forecasting for CS teams - projecting renewal probability and expansion pipeline from health data, giving CS leadership a data-driven view of net revenue retention. Catalyst integrates natively with Salesforce and connects to Segment, Amplitude, Mixpanel, and Zendesk for product and support data ingestion. Used by CS teams at Outreach, Salesloft, and Yext where Salesforce is the system of record and CS data needs to be accessible to the entire revenue team without platform switching.',
 NULL,
 'https://catalyst.io',
 'https://catalyst.io',
 ARRAY['customer-success', 'salesforce', 'revenue-operations', 'saas', 'churn-reduction'],
 'paid',
 false,
 0.00,
 4.3, 580,
 false, false, false,
 ARRAY['Native Salesforce architecture eliminates data sync issues between CRM and CS platform', 'Revenue forecasting from CS health data connects CS to NRR pipeline visibility', 'CS activity visible directly in Salesforce records without platform switching for sales', 'Automated playbooks trigger from health threshold breaches without manual monitoring'],
 ARRAY['Deep Salesforce dependency makes it less suitable for teams on Hubspot or other CRMs', 'Pricing requires a sales conversation - not self-serve for smaller teams', 'Implementation complexity scales with Salesforce configuration complexity'],
 ARRAY['CS teams operating within a Salesforce revenue stack where CRM is the system of record', 'Giving account executives visibility into customer health within their existing Salesforce workflow', 'Forecasting renewal and expansion revenue from CS health signals for quarterly planning']),

('client-success',
 'ClientSuccess',
 'Mid-market customer success platform for managing client relationships, health scoring, and CS team performance',
 'ClientSuccess is a customer success platform designed for mid-market SaaS companies that need a complete CS system without enterprise complexity. The platform manages the full customer lifecycle from onboarding through renewal, with health scoring, automated task management, success plan tracking, and CS team performance reporting in a package that smaller CS teams can configure and operate independently. ClientSuccess SuccessScore aggregates product usage, support history, relationship engagement, and financial metrics into a composite health indicator for every account. The platform tracks relationship engagement at the contact level - logging every call, email, and meeting with customer stakeholders and flagging accounts where executive relationships have gone cold or where a champion has not been reached in a defined period. SuccessPlans within ClientSuccess provide a structured framework for collaborative goal-setting with customers, creating a shared view of what success looks like and tracking progress against milestones that both the CS team and the customer can see. The reporting suite shows CS team performance metrics - tasks completed, playbook adherence, NPS trends, and renewal forecast accuracy - giving CS leaders data to coach and manage team performance. ClientSuccess integrates with Salesforce, Hubspot, Zendesk, and product analytics tools via native connectors and Zapier. Used by CS teams at companies including iQSTEL and Linksquares for client relationship management across a portfolio of accounts.',
 NULL,
 'https://clientsuccess.com',
 'https://clientsuccess.com',
 ARRAY['customer-success', 'mid-market', 'saas', 'client-management', 'health-scoring'],
 'paid',
 false,
 0.00,
 4.0, 620,
 false, false, false,
 ARRAY['Contact-level relationship tracking flags when champion engagement goes cold', 'SuccessPlans create shared customer-facing goal tracking visible to both sides', 'CS team performance reporting supports coaching and accountability at the manager level', 'Mid-market pricing and implementation complexity is manageable for smaller CS teams'],
 ARRAY['Product usage data ingestion requires more configuration effort than modern alternatives', 'Interface feels less modern than Vitally or Planhat for daily CS workflows', 'Automation capabilities are more limited than enterprise platforms for complex lifecycle orchestration'],
 ARRAY['Tracking multi-stakeholder relationships and ensuring regular engagement across all contacts', 'Creating shared success plans that customers actively reference to track their own goals', 'Managing CS team KPIs and playbook adherence across a growing CS organisation']),

('userpilot',
 'Userpilot',
 'Product growth and customer success platform for user onboarding, feature adoption, and in-app engagement',
 'Userpilot is a product growth platform that gives product and customer success teams the ability to build in-app onboarding experiences, feature announcements, tooltips, and surveys without engineering resources. The platform targets the adoption gap that exists between a user signing up and actually achieving value from the product - the period where most SaaS churn originates. CS and product teams use Userpilot to build guided onboarding flows that walk new users through key setup steps, contextual tooltips that explain unfamiliar features when users encounter them, and NPS surveys triggered after meaningful product events. The segmentation engine lets teams target different onboarding tracks to different user personas - an admin user gets a different onboarding flow than an end user, and an enterprise customer sees different feature announcements than a self-serve SMB. Userpilot Analytics tracks feature adoption rates, funnel completion, and user engagement patterns across segments, giving CS and product teams data on which onboarding flows drive activation and which leave users stuck. The platform requires no code to build or update in-app experiences after an initial lightweight installation. Userpilot integrates with Amplitude, Mixpanel, Segment, Hubspot, Salesforce, and Intercom. Used by product and CS teams at Attest, Kontentino, and Bynder to accelerate time-to-value and drive feature adoption across their active user base.',
 NULL,
 'https://userpilot.com',
 'https://userpilot.com',
 ARRAY['product-adoption', 'onboarding', 'customer-success', 'in-app', 'feature-adoption'],
 'freemium',
 true,
 0.00,
 4.4, 1130,
 false, false, false,
 ARRAY['No-code in-app experience builder requires no engineering resources after initial installation', 'Segmentation engine delivers different onboarding tracks to different user personas', 'Analytics tracks feature adoption and funnel completion to identify where users drop off', 'Covers onboarding, adoption tooltips, NPS surveys, and feature announcements in one platform'],
 ARRAY['Free plan is limited to a small number of monthly active users', 'Best suited for web-based SaaS products - mobile in-app capabilities are more limited', 'Advanced analytics features require the higher-tier plans'],
 ARRAY['Building personalised onboarding flows for different user roles without involving engineering', 'Driving adoption of an underused feature with contextual tooltips triggered on first encounter', 'Collecting in-app NPS feedback triggered after a user completes a key product milestone']),

('custify',
 'Custify',
 'Customer success platform for B2B SaaS with automated lifecycle management and 360-degree health scoring',
 'Custify is a customer success platform designed for B2B SaaS companies that need a complete view of account health combined with automated lifecycle management. The platform aggregates customer data from CRM, product usage, billing, support, and email engagement into 360-degree health profiles for every account, giving CS managers a single screen view of everything happening in an account without switching between tools. Custify''s lifecycle automation engine triggers personalised customer interactions based on health events - a welcome sequence when a new customer is created, an adoption nudge when a key feature has not been used after two weeks, or an urgent intervention task when a health score drops below a defined threshold. The no-code automation builder lets CS teams configure these triggers and actions without technical support. Customer timelines within Custify log every interaction with an account - emails, calls, meetings, support tickets, and NPS responses - creating an auditable history that survives CS manager turnover. The reporting suite tracks NRR, churn rate, expansion MRR, and CS team activity metrics across the customer base with segmentation by plan, industry, or any custom attribute. Custify integrates with Stripe, Chargebee, Salesforce, Hubspot, Intercom, and Zendesk through native connectors. Used by B2B SaaS CS teams in Europe and internationally where a comprehensive CS platform is needed without the implementation complexity and cost of Gainsight.',
 NULL,
 'https://custify.com',
 'https://custify.com',
 ARRAY['customer-success', 'b2b-saas', 'lifecycle-automation', 'health-scoring', 'churn-reduction'],
 'paid',
 false,
 0.00,
 4.3, 430,
 false, false, false,
 ARRAY['360-degree account health view aggregates all data sources in one profile', 'No-code automation builder for lifecycle triggers requires no technical resources', 'Customer timeline creates an auditable interaction history that survives team changes', 'European-based platform with strong GDPR compliance and data residency options'],
 ARRAY['Smaller customer success community and ecosystem than US-based market leaders', 'Native integration library is more limited than Gainsight or ChurnZero', 'Reporting customisation requires manual configuration for complex segmentation needs'],
 ARRAY['Building automated lifecycle journeys for new customers without engineering involvement', 'Maintaining customer history and relationship context through CS team changes', 'Tracking NRR and churn contribution by segment with GDPR-compliant data handling']),

('akita',
 'Akita',
 'Customer success platform for SaaS teams focused on data integration, health scoring, and account management',
 'Akita is a customer success platform that prioritises data integration flexibility and health score transparency, making it the choice for CS teams whose customer health is driven by complex, multi-source product usage data. The platform connects to an unusually wide range of data sources - product analytics tools, CRM, billing, support, email, and custom data via API - and lets CS teams define health score logic using any combination of these signals with full visibility into how each metric contributes to the overall score. Unlike opaque health scoring black boxes, Akita shows CS managers exactly why a score changed and which underlying metric drove the movement. Task management and playbook automation within Akita trigger CS activities based on health score thresholds, usage events, or calendar triggers. The platform includes customer-facing success plans that create a shared view of goals and milestones between the CS team and the customer. Account pulse reports provide a weekly digest of significant health changes across the portfolio, reducing the manual scanning required to identify which accounts need attention. Akita integrates with Stripe, Salesforce, Hubspot, Intercom, Zendesk, Amplitude, Mixpanel, Segment, and via Zapier for custom connections. Positioned for mid-market SaaS CS teams that need data integration depth and health score transparency above the level that simpler tools provide.',
 NULL,
 'https://akitaapp.com',
 'https://akitaapp.com',
 ARRAY['customer-success', 'health-scoring', 'data-integration', 'saas', 'account-management'],
 'paid',
 false,
 0.00,
 4.1, 280,
 false, false, false,
 ARRAY['Transparent health scoring shows exactly which metrics drove each score change', 'Wide data integration range connects product, billing, support, CRM, and custom sources', 'Weekly account pulse digest reduces manual portfolio scanning for CS managers', 'Customer-facing success plans create shared milestone visibility with accounts'],
 ARRAY['Smaller user community and fewer publicly available resources than market leaders', 'Automation capabilities are less mature than Gainsight or ChurnZero for complex lifecycle orchestration', 'Pricing requires a sales conversation for teams above a basic account threshold'],
 ARRAY['Teams with complex health scoring needs driven by multiple product usage dimensions', 'Identifying which specific health metrics changed and why an account moved from healthy to at-risk', 'Mid-market CS teams that need more data transparency than simpler tools provide without enterprise costs'])

ON CONFLICT (slug) DO NOTHING;
