-- tools-batch-52.sql
-- 10 AI Social Media tools
-- Run after tools-batch-51.sql is confirmed in Supabase

INSERT INTO tools (slug, name, tagline, description, website_url, affiliate_url, pricing_type, pricing_free_tier, pricing_starting_price, rating, review_count, featured, trending, editor_pick, tags, pros, cons, use_cases, updated_at)
VALUES

('predis-ai', 'Predis.ai', 'AI-powered social media content generator and scheduler',
 'Predis.ai uses artificial intelligence to generate social media posts, captions, and visuals from a single prompt. Enter your product description or URL and Predis generates ready-to-publish content for Instagram, Facebook, LinkedIn, and Twitter. The platform includes a built-in image editor, competitor analysis, and scheduling features. Content teams use Predis to cut social media production time by 70% without sacrificing brand consistency. The AI learns your brand voice over time and improves output quality with each use. Competitor analysis shows what is working in your niche so you can benchmark your content strategy against rivals. The scheduling calendar provides a week-at-a-glance view of your planned content across all platforms.',
 'https://predis.ai', 'https://predis.ai', 'freemium', true, 29, 4.5, 1842,
 false, true, false,
 ARRAY['social-media', 'ai-assistants', 'writing-ai'],
 ARRAY['Generates text and visuals together', 'Competitor content analysis', 'Multi-platform scheduling', 'Brand voice customization over time'],
 ARRAY['Limited posts on free plan', 'Image quality varies by prompt', 'Analytics are basic compared to dedicated tools'],
 ARRAY['Social media content creation for brands', 'Competitor content monitoring', 'Visual brand consistency across platforms'],
 NOW()),

('taplio', 'Taplio', 'AI LinkedIn content tool to grow your personal brand and audience',
 'Taplio is designed specifically for LinkedIn content creators and personal branding. The AI generates post ideas, writes full posts based on your writing style, and schedules content at optimal times. The viral post library shows you what is working in your niche so you can replicate successful formats. Taplio also tracks engagement analytics, manages direct messages, and suggests people to engage with to grow your network. Used by consultants, coaches, founders, and B2B marketers who rely on LinkedIn for lead generation. The relationship management feature tracks which connections you have been engaging with, helping you stay top of mind with key prospects without a separate CRM.',
 'https://taplio.com', 'https://taplio.com', 'paid', false, 39, 4.4, 2156,
 false, true, false,
 ARRAY['social-media', 'writing-ai', 'seo-marketing'],
 ARRAY['LinkedIn-specific AI content generation', 'Viral post inspiration library', 'Smart scheduling and DM manager', 'Engagement network suggestions'],
 ARRAY['LinkedIn only - no other platforms', 'No free tier', 'Learning curve for relationship analytics'],
 ARRAY['LinkedIn personal branding', 'B2B content marketing', 'Thought leadership and lead generation'],
 NOW()),

('supergrow', 'Supergrow', 'LinkedIn growth tool powered by AI for founders and creators',
 'Supergrow combines AI content generation with LinkedIn growth strategies in one platform. It analyzes your profile, benchmarks against top creators in your niche, and generates personalized post templates proven to drive engagement. The AI repurposes your existing content - blog posts, videos, tweets - into LinkedIn-native formats automatically. A built-in carousel maker converts text into swipeable visual slides. Supergrow also tracks your follower growth, post performance, and suggests optimal posting times based on your audience behavior. The hook analyzer scores your post openings and suggests improvements to stop the scroll before readers see the rest of your content.',
 'https://supergrow.ai', 'https://supergrow.ai', 'freemium', true, 19, 4.3, 987,
 false, false, false,
 ARRAY['social-media', 'writing-ai', 'seo-marketing'],
 ARRAY['Content repurposing from any format', 'LinkedIn carousel maker', 'Profile analysis and niche benchmarking', 'Free tier available'],
 ARRAY['LinkedIn focused only', 'Smaller template library than Taplio', 'Limited scheduling slots on free plan'],
 ARRAY['LinkedIn content creation and scheduling', 'Personal brand growth strategy', 'Content repurposing from blogs and videos'],
 NOW()),

('postwise', 'Postwise', 'AI-powered Twitter/X content writing and audience growth tool',
 'Postwise helps Twitter/X creators write better posts, grow their audience, and schedule content at optimal times. The AI analyzes your existing posts to match your voice, then generates new content based on topics you specify. The viral post library contains thousands of high-performing formats you can adapt instantly. Postwise includes a thread writer, tweet-to-LinkedIn repurposing, and an auto-plug feature that adds your product link to posts that gain traction automatically. Designed for creators, solopreneurs, and marketers building a following on Twitter/X. The ghost-writing mode lets you define multiple personas and generate content for each separately, useful for agencies managing multiple client accounts.',
 'https://postwise.ai', 'https://postwise.ai', 'paid', false, 29, 4.2, 1234,
 false, false, false,
 ARRAY['social-media', 'writing-ai'],
 ARRAY['Twitter/X-specific AI writing', 'Viral post inspiration library', 'Thread writer and scheduler', 'Auto-plug monetization feature'],
 ARRAY['Twitter/X only', 'No free tier', 'Analytics less detailed than competitors'],
 ARRAY['Twitter/X audience growth', 'Thread content creation', 'Personal brand monetization on X'],
 NOW()),

('hypefury', 'Hypefury', 'Grow your Twitter/X audience with AI scheduling and smart automation',
 'Hypefury is a Twitter/X growth tool that combines smart scheduling with AI-assisted content creation. It automatically reposts your best-performing content to reach followers who missed them, schedules posts in time slots that maximize reach, and auto-DMs new followers with a welcome message. The inspiration feature shows you successful posts from your niche to spark ideas. Hypefury also cross-posts to Instagram, Facebook, and LinkedIn from a single dashboard, making it a light social media manager for Twitter-first creators. The evergreen queue resurfaces your best content automatically on a rotation, keeping your profile active even during creative dry spells.',
 'https://hypefury.com', 'https://hypefury.com', 'freemium', true, 19, 4.3, 2891,
 false, false, false,
 ARRAY['social-media', 'automation'],
 ARRAY['Auto-repost your best content', 'Cross-platform publishing to 4 networks', 'Free tier available', 'Auto-DM new followers'],
 ARRAY['Twitter/X focused primarily', 'AI writing less powerful than dedicated tools', 'Limited analytics depth'],
 ARRAY['Twitter/X growth automation', 'Cross-platform content distribution', 'Evergreen content recycling'],
 NOW()),

('publer', 'Publer', 'AI-assisted social media scheduler for agencies and small teams',
 'Publer is a social media management tool with AI-powered content features built for agencies and small businesses. The AI assistant generates captions, suggests hashtags, and creates post variations from a brief description. Publer supports 13 social networks including TikTok, Pinterest, YouTube, and Google Business Profile - more platforms than most competitors at this price point. The workspace system lets agencies manage multiple client accounts from one dashboard with separate logins and approval workflows. A built-in link shortener, UTM tracking, and analytics dashboard round out the feature set. The content recycling feature automatically reschedules your best-performing posts at regular intervals to maximize their reach over time.',
 'https://publer.com', 'https://publer.com', 'freemium', true, 12, 4.6, 3412,
 false, false, false,
 ARRAY['social-media', 'seo-marketing'],
 ARRAY['13 social networks including TikTok', 'Agency workspace with approvals', 'AI caption and hashtag generator', 'UTM tracking built-in'],
 ARRAY['AI features less advanced than specialist tools', 'Free plan limited to 3 accounts', 'Reporting less detailed than Sprout Social'],
 ARRAY['Agency social media management', 'Multi-network content scheduling', 'Client account management with approvals'],
 NOW()),

('flick-social', 'Flick', 'AI-powered Instagram hashtag research and social media content planner',
 'Flick started as an Instagram hashtag tool and has expanded into a full AI content assistant for social media. The hashtag research engine analyzes reach, difficulty, and engagement potential across 500 million hashtags to find the best combination for each post. The AI content planner generates weekly post ideas based on your niche and brand, and the caption writer creates platform-specific text from your prompt. Flick supports Instagram, Facebook, LinkedIn, TikTok, and Twitter/X. A scheduling calendar, analytics dashboard, and competitor hashtag tracking complete the package. The hashtag sets feature lets you save and reuse curated hashtag groups for different content types, saving time on research for repeat content themes.',
 'https://flick.social', 'https://flick.social', 'paid', false, 14, 4.4, 2678,
 false, false, false,
 ARRAY['social-media', 'seo-marketing'],
 ARRAY['Best-in-class hashtag research engine', 'AI weekly content planner', 'Multi-platform scheduling', 'Competitor hashtag analysis'],
 ARRAY['No free tier', 'Analytics less detailed than dedicated tools', 'Caption AI quality varies by prompt'],
 ARRAY['Instagram hashtag strategy and growth', 'Social media content planning', 'Creator and brand audience growth'],
 NOW()),

('contentstudio', 'ContentStudio', 'All-in-one AI content creation and social media management platform',
 'ContentStudio combines a content discovery engine, AI writing tools, and social media management into one platform. The discovery feed aggregates trending content in your industry so you always have inspiration and can share relevant third-party content to fill gaps in your calendar. The AI writer creates blog posts, social captions, and ad copy from topic prompts. ContentStudio supports 8 social networks and includes a full publishing calendar, team collaboration, content approval workflows, and white-label reporting for agencies. One of the more comprehensive platforms at its price point. The influencer discovery feature helps brands and agencies identify relevant influencers in their niche for potential partnerships, adding a layer of audience research beyond just content creation.',
 'https://contentstudio.io', 'https://contentstudio.io', 'paid', false, 25, 4.5, 1987,
 false, false, false,
 ARRAY['social-media', 'writing-ai', 'seo-marketing'],
 ARRAY['Content discovery and curation engine', 'AI blog and social caption writer', 'Team collaboration and approval workflows', 'White-label agency reporting'],
 ARRAY['Interface can feel busy for new users', 'Less focused on Twitter/X than dedicated tools', 'Analytics not as deep as Sprout Social'],
 ARRAY['Content marketing and curation strategy', 'Agency client management', 'Social media calendar planning at scale'],
 NOW()),

('vista-social', 'Vista Social', 'Modern social media management with AI features for growing teams',
 'Vista Social is a modern social media management platform built to replace legacy tools like Hootsuite at a fraction of the cost. It supports 11 networks including TikTok, YouTube, Google Business Profile, and Pinterest. AI features include a caption generator, best-time-to-post recommendations, and an automated content recycler that resurfaces evergreen posts. The review management feature aggregates mentions and reviews from multiple sources into a single inbox. Agencies and growing teams use Vista Social for its clean UX and transparent pricing compared to Sprout Social and Hootsuite. The listening feature monitors keywords and brand mentions across social platforms, giving teams a real-time view of what is being said about their brand without needing a separate social listening tool.',
 'https://vistasocial.com', 'https://vistasocial.com', 'freemium', true, 15, 4.4, 3124,
 false, true, false,
 ARRAY['social-media', 'seo-marketing'],
 ARRAY['11 networks including TikTok and YouTube', 'Review and mention management inbox', 'Evergreen content recycler', 'Much cheaper than Hootsuite at similar feature depth'],
 ARRAY['Reporting less advanced than Sprout Social', 'Some learning curve for agencies', 'Limited third-party integrations'],
 ARRAY['Social media team management', 'Review and reputation monitoring', 'Content recycling and multi-network scheduling'],
 NOW()),

('pallyy', 'Pallyy', 'Social media scheduling and analytics platform built for agencies',
 'Pallyy is a social media management tool designed specifically for agencies managing multiple client accounts. The visual Instagram planner lets you drag and drop posts into a grid preview before publishing, ensuring the profile aesthetic looks correct before going live. Pallyy supports Instagram, Facebook, Twitter, LinkedIn, TikTok, Google Business, and Pinterest from one dashboard. An AI caption generator, hashtag groups, and first-comment scheduler are included on all plans. The bio link tool creates a mini landing page from your Instagram bio link. Pricing is per social set (a group of accounts for one client), making it cost-effective for agencies with many smaller clients who do not need enterprise-level feature depth.',
 'https://pallyy.com', 'https://pallyy.com', 'freemium', true, 18, 4.3, 1456,
 false, false, false,
 ARRAY['social-media'],
 ARRAY['Visual Instagram grid planner', 'Per-social-set agency pricing', 'Bio link tool included', 'First comment scheduler'],
 ARRAY['Analytics less detailed than competitors', 'No content discovery feed', 'Mobile app less polished than desktop'],
 ARRAY['Agency Instagram management', 'Visual brand consistency planning', 'Multi-client social scheduling'],
 NOW())

ON CONFLICT (slug) DO NOTHING;
