-- tools-batch-47.sql
-- 10 AI Proposal, Contract & Document Automation tools
-- All slugs verified NOT present in any prior tools-batch file
-- Run after compare-batch-46.sql

INSERT INTO tools (slug, name, tagline, description, logo_url, website_url, affiliate_url, tags, pricing_type, pricing_free_tier, pricing_starting_price, rating, review_count, featured, trending, editor_pick, pros, cons, use_cases)
VALUES

('pandadoc',
 'PandaDoc',
 'Create, send, and e-sign proposals, contracts, and quotes with AI-powered automation',
 'PandaDoc is a document automation and e-signature platform used by over 50,000 businesses to create, send, and track proposals, quotes, contracts, and onboarding documents. The platform includes an AI content assistant that helps draft proposal sections, suggest pricing structures, and generate product descriptions from a brief input. Templates cover the most common business document types - sales proposals, service agreements, NDAs, statements of work, and HR documents - and are customisable with drag-and-drop fields for text, images, pricing tables, and e-signature fields. Once a document is sent, PandaDoc tracks exactly when the recipient opened it, which sections they spent time on, and whether they forwarded it to another stakeholder, giving the sending team real-time visibility into deal engagement. The built-in e-signature is legally binding in most jurisdictions and requires no additional subscription. PandaDoc integrates with Salesforce, HubSpot, Pipedrive, and other CRMs to pull contact and deal data directly into documents, eliminating copy-paste errors. For teams that send a high volume of proposals or contracts, PandaDoc reduces the time from deal agreement to signed document from days to minutes. The free plan includes unlimited document uploads and e-signatures with basic features, making it accessible for freelancers and small teams before committing to a paid plan.',
 NULL,
 'https://pandadoc.com',
 'https://pandadoc.com',
 ARRAY['proposals', 'contracts', 'e-signature', 'document-automation', 'sales'],
 'freemium',
 true,
 0.00,
 4.6, 4100,
 false, false, false,
 ARRAY['Built-in e-signature included at no extra cost', 'Real-time open and engagement tracking on sent documents', 'Deep CRM integrations with Salesforce, HubSpot, and Pipedrive', 'Free plan available for basic proposal and signature workflows'],
 ARRAY['Advanced automation features require Business plan or higher', 'AI content generation quality varies by document type', 'Template customisation can be slow for complex brand guidelines'],
 ARRAY['Sales teams sending high-volume proposals with CRM integration', 'HR teams creating and collecting signed onboarding documents', 'Agencies sending client proposals with scope, pricing, and e-signature']),

('proposify',
 'Proposify',
 'Proposal software with templates, e-signature, and engagement analytics for closing deals faster',
 'Proposify is a proposal management platform built for sales teams and agencies that send high volumes of proposals to prospective clients. The core product is a template-based proposal builder where teams create a master proposal template covering the cover page, scope of work, pricing, terms, and case studies, then generate client-specific versions in minutes by customising the relevant sections. The platform tracks proposal opens, page-by-page time spent, and signature status in real time, giving sales managers visibility into where deals are stalling. Proposify includes an electronic signature workflow and a client portal where prospects can comment on specific sections before signing. The built-in content library stores approved copy, images, pricing options, and legal terms that any team member can pull into a new proposal, ensuring consistency and brand compliance across the whole team. Approval workflows allow managers to review and sign off on non-standard pricing or terms before a proposal goes out. The analytics dashboard shows which templates have the highest close rates and which sections prospects skip, allowing ongoing improvement of proposal content. Proposify is particularly strong for agencies selling services at volume - marketing agencies, design studios, consulting firms, and IT services companies - where consistent, professional proposals are a meaningful competitive advantage. Pricing starts at $49 per user per month with no free tier.',
 NULL,
 'https://proposify.com',
 'https://proposify.com',
 ARRAY['proposals', 'sales', 'e-signature', 'agencies', 'document-automation'],
 'paid',
 false,
 49.00,
 4.3, 1850,
 false, false, false,
 ARRAY['Detailed proposal analytics showing page-by-page engagement', 'Content library ensures brand and pricing consistency across the team', 'Approval workflows prevent non-standard terms going out without sign-off', 'Strong for agencies with high proposal volume and repeating templates'],
 ARRAY['No free plan - $49/user/month is a significant starting cost', 'Editor can feel slow with complex, image-heavy templates', 'Less suitable for simple one-page quotes or freelance use cases'],
 ARRAY['Agencies sending branded service proposals with scope and pricing', 'Sales teams tracking proposal engagement to time follow-ups', 'Businesses enforcing content and pricing consistency across a sales team']),

('qwilr',
 'Qwilr',
 'Turn proposals into interactive web pages that track engagement and accept payment',
 'Qwilr turns traditional PDF proposals into interactive web pages that feel modern, branded, and engaging to the recipient. Instead of sending a static document, Qwilr proposals are live web pages that load in any browser without a download, include embedded videos, interactive pricing configurators, and live content that can be updated even after sending. The interactive pricing feature is particularly distinctive - prospects can toggle between package options, add services, and see the total update in real time before accepting. Qwilr tracks every visit to the proposal page, showing when the recipient opened it, how long they spent on each section, and whether they shared it with colleagues. When the prospect is ready, they accept the proposal directly in the web page with a click without printing, signing, or scanning. Qwilr integrates with HubSpot, Salesforce, and Pipedrive to pull deal and contact data directly, and webhooks trigger CRM updates when a proposal is accepted. The template library covers common proposal types for agencies, SaaS companies, consultants, and professional services firms. Qwilr also accepts payment directly within the proposal page through Stripe integration, allowing clients to pay a deposit or full amount at the moment of acceptance without a separate invoice workflow. Qwilr web-based proposals tend to produce higher engagement and faster acceptance compared to PDF proposals, particularly with buyers who are used to modern SaaS experiences.',
 NULL,
 'https://qwilr.com',
 'https://qwilr.com',
 ARRAY['proposals', 'sales', 'interactive-content', 'e-signature', 'document-automation'],
 'paid',
 false,
 35.00,
 4.4, 940,
 false, false, false,
 ARRAY['Interactive web proposals are more engaging than static PDFs', 'Prospect can configure pricing and add services before accepting', 'Built-in Stripe payment collection at the moment of acceptance', 'Real-time engagement tracking with page-level time data'],
 ARRAY['No free plan - $35/user/month starting cost', 'Web page format may not suit all industries or buyer expectations', 'Less suitable for regulated industries that require PDF document delivery'],
 ARRAY['Agencies and consultants sending interactive service proposals', 'SaaS companies presenting configurable package options to prospects', 'Freelancers combining proposal acceptance and deposit payment in one step']),

('dealhub',
 'DealHub',
 'Revenue platform with CPQ, contract management, and digital sales rooms for B2B teams',
 'DealHub is a revenue platform that combines configure-price-quote (CPQ), contract management, and digital sales rooms in a single platform for B2B sales teams. The CPQ module handles complex product configurations and pricing rules, ensuring sales reps can generate accurate quotes for configurable products without errors or manual spreadsheets. Once a quote is approved, DealHub generates a contract and presents it alongside the quote in a shared digital sales room where both the sales team and the buyer can collaborate, comment, and negotiate terms without long email chains. The digital sales room provides a single URL for all deal-related content - proposals, case studies, technical documentation, pricing, and the contract - accessible to the buyer team throughout the sales cycle. DealHub uses AI to suggest the next best actions for stalled deals, identify risk signals from buyer behaviour, and recommend upsell opportunities based on deal context. The platform integrates deeply with Salesforce, HubSpot, and Microsoft Dynamics to ensure deal data stays synchronised across the revenue tech stack. Subscription management features handle recurring revenue changes - upgrades, downgrades, mid-term amendments, and renewals - without manual intervention from the finance team. DealHub is targeted at mid-market and enterprise B2B companies with complex product catalogues and multi-stakeholder sales cycles where accuracy, speed, and buyer experience all matter together.',
 NULL,
 'https://dealhub.io',
 'https://dealhub.io',
 ARRAY['cpq', 'sales', 'contracts', 'revenue-operations', 'digital-sales-rooms'],
 'paid',
 false,
 0.00,
 4.4, 620,
 false, false, false,
 ARRAY['CPQ handles complex product configuration and pricing rules accurately', 'Digital sales rooms centralise all deal content for the buyer team', 'AI-powered signals identify at-risk deals and upsell opportunities', 'Deep Salesforce integration keeps deal data synchronised automatically'],
 ARRAY['Custom enterprise pricing requires a sales conversation', 'Implementation complexity is high for teams without a rev-ops function', 'Overkill for companies with simple, fixed-price product catalogues'],
 ARRAY['B2B companies with configurable products needing accurate CPQ', 'Enterprise sales teams managing complex multi-stakeholder deals', 'Revenue operations teams standardising the quote-to-cash workflow']),

('oneflow',
 'Oneflow',
 'Contract management platform that turns contracts into live digital documents for faster signing',
 'Oneflow is a contract management platform that reimagines how business contracts work. Rather than static PDF documents that get emailed back and forth, Oneflow contracts are live digital documents that both parties can edit, negotiate, and sign in real time within a shared online workspace. The platform covers the full contract lifecycle - creating from templates, negotiating with tracked changes and comments, approving through internal workflows, collecting e-signatures, and storing in a searchable archive with automated renewal reminders. The template library includes standard business contracts across sales, HR, and procurement use cases, all customisable with variable fields that pull data from integrated CRM or HR systems. Oneflow AI assists with contract drafting by suggesting standard clauses, flagging missing required fields, and summarising contract terms in plain language for non-legal reviewers. The audit trail captures every change, comment, and approval action with timestamps, providing a complete history for compliance purposes. Oneflow integrates with Salesforce, HubSpot, Pipedrive, SuperOffice, and Microsoft 365. The live document format is particularly effective at reducing the negotiation cycle - both parties can propose changes inside the document and see each other''s edits in real time, removing the confusion of document version management by email. Free plan available for small teams with a limited monthly contract volume; paid plans from $38 per user per month.',
 NULL,
 'https://oneflow.com',
 'https://oneflow.com',
 ARRAY['contracts', 'e-signature', 'document-automation', 'legal', 'procurement'],
 'freemium',
 true,
 0.00,
 4.2, 780,
 false, false, false,
 ARRAY['Live document format eliminates email version confusion during negotiation', 'Complete audit trail with timestamps for compliance', 'Free plan available for small teams with basic contract needs', 'AI assists with clause suggestions and plain-language summaries'],
 ARRAY['Live document format may feel unfamiliar to counterparties used to PDF contracts', 'Advanced workflow features require paid plans', 'Integration depth with some CRMs is less mature than competitors'],
 ARRAY['Sales teams negotiating service agreements with prospects in real time', 'HR teams collecting employee contracts and onboarding agreements', 'Procurement teams managing supplier contracts with renewal reminders']),

('contractbook',
 'Contractbook',
 'Automate your entire contract workflow from creation to renewal in one platform',
 'Contractbook is a contract lifecycle management platform designed to bring all business contracts into a single, structured, searchable system. The core premise is that most companies manage contracts in a chaotic mix of email threads, shared folders, and physical files, making it impossible to track what has been agreed, when renewals are due, or what obligations exist across the business. Contractbook replaces that with a structured repository where every contract is stored with metadata, linked to the counterparty and deal, and searchable by term, value, or date. The AI layer assists with contract creation - generating first drafts from templates and briefs, suggesting standard clauses, and flagging unusual terms that deviate from the company standard. Automated workflows route contracts through the required approval steps before sending for signature, and renewal notifications alert responsible owners before contracts auto-renew or expire. Contractbook integrates with accounting systems, CRM tools, and HR platforms to pull relevant data into contracts automatically. The data extraction feature reads existing contracts and pulls key terms - start dates, values, renewal clauses, termination rights - into the database, making it practical to onboard a backlog of historical contracts. The platform is particularly useful for operations and legal teams at growing companies that have outgrown ad hoc contract management but are not ready for enterprise contract lifecycle management software. Pricing starts from $99 per month for small teams.',
 NULL,
 'https://contractbook.com',
 'https://contractbook.com',
 ARRAY['contracts', 'legal', 'document-automation', 'contract-lifecycle-management', 'procurement'],
 'paid',
 false,
 99.00,
 4.1, 430,
 false, false, false,
 ARRAY['Structured repository makes all contracts searchable by any term or date', 'AI data extraction onboards historical contract backlogs efficiently', 'Automated renewal alerts prevent contracts from auto-renewing unnoticed', 'Approval workflows prevent non-standard contracts from being signed without review'],
 ARRAY['No free plan - requires upfront commitment', 'Implementation requires time to import and tag existing contract backlog', 'Less suitable for companies with fewer than 50 active contracts'],
 ARRAY['Operations teams replacing shared-folder contract chaos with a structured repository', 'Legal teams tracking renewal dates and contractual obligations at scale', 'Growing companies building a formal contract management process for the first time']),

('juro',
 'Juro',
 'AI-native contract management platform for legal and business teams to move faster on contracts',
 'Juro is an AI-native contract management platform built for legal and business teams that want to reduce contract turnaround time without sacrificing accuracy. The platform distinguishes itself from traditional contract management tools by treating contracts as structured data rather than documents - every clause, obligation, and commercial term is stored as a searchable, reportable data point rather than text buried in a PDF. This approach lets legal teams answer questions like "which contracts include a most-favoured-nation clause" or "which supplier agreements renew in Q3" in seconds, without manual document review. Juro AI assists with contract generation by drafting standard agreements from a business brief, suggesting appropriate clauses for the contract type, and flagging terms that create unusual risk compared to the company playbook. The self-service workflow allows business teams in sales, HR, and procurement to generate routine contracts independently using approved templates, reducing the volume of low-complexity requests that reach the legal team. Electronic signature is built in without requiring a separate tool. Juro integrates with Salesforce, Greenhouse, BambooHR, and Slack, connecting contracts to the systems where business teams already work. The platform is particularly strong for legal teams managing a high volume of similar contract types such as NDAs, employment agreements, and vendor contracts, where a consistent, scalable process matters more than custom document handling. Pricing is available on request.',
 NULL,
 'https://juro.com',
 'https://juro.com',
 ARRAY['contracts', 'legal', 'contract-lifecycle-management', 'document-automation', 'ai-generation'],
 'paid',
 false,
 0.00,
 4.3, 560,
 false, false, false,
 ARRAY['Treats contracts as structured data - every term is searchable and reportable', 'Self-service workflows reduce legal team bottleneck for routine contracts', 'AI flags deviations from company playbook positions automatically', 'Built-in e-signature without a separate tool subscription'],
 ARRAY['Enterprise pricing is not publicly listed - requires a sales conversation', 'Best value for legal teams with high contract volume, not occasional use', 'Steeper learning curve to configure playbooks and self-service workflows'],
 ARRAY['Legal teams standardising and scaling NDA and vendor contract workflows', 'Companies enabling business teams to self-serve routine contract generation', 'Legal operations teams reporting on contractual obligations across the portfolio']),

('ironclad',
 'Ironclad',
 'Enterprise digital contracting platform for legal teams managing complex contract workflows',
 'Ironclad is an enterprise digital contracting platform used by legal teams at companies including Dropbox, Mastercard, and L''Oreal to manage high-volume, complex contract workflows at scale. The platform is built around a visual workflow designer that lets legal and operations teams map out the complete lifecycle of a contract type, from request through negotiation, approval, signature, and archiving, with branching logic for different scenarios, jurisdictions, and counterparty types. Non-legal teams initiate contract requests through a guided intake form, answer questions about the deal, and the system generates a first draft, routes it for review, and tracks its progress through the defined workflow automatically. Ironclad AI assists with contract review by flagging deviations from standard playbook positions, suggesting alternative language, and summarising long contracts for business stakeholders who need to understand the key terms without reading the full document. The contract repository provides a searchable, filterable view of all contracts with extracted terms, obligation dates, and counterparty information. Ironclad positions itself as the operating system for legal teams, not just a storage and signature tool, but a workflow management system for the full contractual relationship between a company and its counterparties. The platform handles the full range of contract types - sales agreements, procurement contracts, NDAs, employment agreements, and partnership deals - within a single governance framework. Enterprise pricing is custom.',
 NULL,
 'https://ironcladapp.com',
 'https://ironcladapp.com',
 ARRAY['contracts', 'legal', 'enterprise', 'contract-lifecycle-management', 'document-automation'],
 'paid',
 false,
 0.00,
 4.4, 890,
 false, false, false,
 ARRAY['Visual workflow designer handles complex branching contract approval logic', 'AI playbook review flags deviations from standard positions automatically', 'Handles all contract types within a single enterprise governance framework', 'Used by leading enterprise companies with mature legal operations functions'],
 ARRAY['Enterprise pricing requires custom negotiation - not suitable for SMBs', 'Implementation requires significant legal operations investment to configure properly', 'Feature depth creates complexity that small legal teams may not fully utilise'],
 ARRAY['Enterprise legal teams managing high volumes of complex multi-party contracts', 'Companies standardising contract request and approval workflows across business units', 'Legal operations teams implementing playbook-based AI review at scale']),

('better-proposals',
 'Better Proposals',
 'Proposal software for freelancers and agencies to create, send, and get paid faster',
 'Better Proposals is a proposal software tool built for freelancers, agencies, and small businesses that need to create professional, branded proposals quickly and close deals faster. The platform is built around simplicity - a straightforward template editor, a library of industry-specific proposal templates, and built-in electronic signature and payment processing that lets clients accept and pay in a single step. Unlike enterprise proposal tools, Better Proposals is priced and designed for individual contributors and small teams: the interface is learnable in an afternoon, templates are ready to use with minimal customisation, and the per-user pricing is affordable at team scale. The AI writing assistant helps draft proposal sections including executive summaries, scope of work descriptions, and pricing justifications from a brief description of the project. Proposal analytics track when clients open the proposal, how long they spend on each section, and when they share it with a colleague, giving the sender the right moment to follow up. Better Proposals integrates with Stripe and PayPal for payment collection, and with HubSpot, Pipedrive, and Zapier for CRM and workflow automation. The template library covers marketing agencies, web designers, consultants, coaches, and freelancers across dozens of verticals. Free trial available; paid plans start at $19 per user per month, making it one of the most affordable full-featured proposal tools available for independent professionals.',
 NULL,
 'https://betterproposals.io',
 'https://betterproposals.io',
 ARRAY['proposals', 'freelance', 'agencies', 'e-signature', 'sales'],
 'paid',
 false,
 19.00,
 4.3, 1240,
 false, false, false,
 ARRAY['Simple, learnable interface designed for non-enterprise users', 'Built-in Stripe and PayPal payment collection at proposal acceptance', 'Affordable at $19/month compared to enterprise alternatives', 'AI writing assistant for drafting scope and pricing sections'],
 ARRAY['No free plan - requires a paid subscription after trial', 'Template library less comprehensive than Proposify for complex agency proposals', 'Advanced automation requires Zapier for anything beyond basic CRM sync'],
 ARRAY['Freelancers sending service proposals with deposit payment collection', 'Small agencies creating branded project proposals efficiently', 'Consultants tracking proposal engagement to time follow-up calls']),

('loopio',
 'Loopio',
 'RFP response platform that automates answers with a searchable library of approved content',
 'Loopio is a response management platform designed for teams that respond to RFPs (Requests for Proposal), RFIs (Requests for Information), and security questionnaires at volume. Responding to RFPs manually is one of the most time-consuming activities in enterprise sales and procurement teams, involving copying answers from previous responses, finding the right subject matter expert, formatting to match the RFP template, and ensuring consistency across a document that may have hundreds of questions. Loopio addresses this by building a searchable library of approved responses - a content repository where every answer is tagged, attributed to a subject matter expert, and set with an expiry date to ensure it remains current. When a new RFP arrives, Loopio AI automatically matches questions to existing library responses and pre-fills the document, allowing the team to review and refine rather than write from scratch. The collaboration workflow routes unanswered or outdated questions to the appropriate expert within the platform, with deadline tracking and completion status visible to the project manager. Loopio integrates with Salesforce to link RFP projects to CRM opportunities and with Microsoft Office and Google Drive for document export. The platform tracks answer currency, flagging responses that have not been updated within a configurable timeframe, so the library does not drift out of date as products and policies change. Used by sales, proposal management, and pre-sales teams at mid-market and enterprise companies where RFP response volume is high enough to justify a dedicated workflow.',
 NULL,
 'https://loopio.com',
 'https://loopio.com',
 ARRAY['rfp', 'proposals', 'sales', 'document-automation', 'content-library'],
 'paid',
 false,
 0.00,
 4.4, 710,
 false, false, false,
 ARRAY['AI auto-matches new RFP questions to existing approved library responses', 'Currency expiry system prevents stale answers from being reused', 'Collaboration routing ensures the right expert answers each question', 'Salesforce integration links RFP projects directly to pipeline opportunities'],
 ARRAY['Custom pricing requires a sales conversation - not suitable for small teams', 'Library quality depends entirely on the team consistently maintaining approved answers', 'Primarily useful for organisations receiving 20+ RFPs per year'],
 ARRAY['Enterprise sales teams reducing RFP response time from weeks to days', 'Proposal management teams building a reusable content library across all bids', 'Pre-sales teams handling security questionnaires and vendor assessments at scale'])

ON CONFLICT (slug) DO NOTHING;
