-- tools-batch-37.sql
-- 10 AI Healthcare / Medical Tools
-- DB target: ~392 -> ~402 tools
-- Safe to re-run: ON CONFLICT (slug) DO NOTHING

INSERT INTO tools (
  slug, name, tagline, description, logo_url, website_url, affiliate_url,
  tags, pricing_type, pricing_free_tier, pricing_starting_price,
  rating, review_count, featured, trending, editor_pick, pros, cons, use_cases
) VALUES

(
  'nabla',
  'Nabla',
  'AI clinical documentation assistant for physicians',
  E'Nabla is an AI ambient clinical documentation tool that listens to the patient-physician conversation and automatically generates a structured clinical note, SOAP format, referral letter, or after-visit summary. The physician activates Nabla at the start of a consultation; the AI transcribes the conversation in real time and produces a draft note by the time the visit ends. The physician reviews, edits, and signs off  -  rather than typing notes from scratch or dictating into a separate system after the patient leaves.\n\nNabla integrates with the major EHR platforms including Epic, Cerner, and Athenahealth, inserting generated notes directly into the relevant patient record. This workflow integration distinguishes Nabla from standalone transcription tools that require manual copy-paste into the EHR. The platform supports over 85 medical specialties and multiple languages, making it practical across diverse clinical settings.\n\nFor physicians spending two or more hours per day on documentation, Nabla addresses one of the most significant sources of administrative burden and clinician burnout. The AI handles the transcription and note-structuring overhead, leaving the physician to focus on patient interaction and clinical reasoning. Nabla is HIPAA compliant and processes audio locally where possible to minimise data exposure.',
  'https://www.google.com/s2/favicons?domain=nabla.com&sz=64',
  'https://nabla.com',
  'https://nabla.com',
  ARRAY['healthcare'],
  'paid',
  false,
  99.00,
  4.7,
  312,
  false, false, false,
  ARRAY['Generates structured SOAP notes automatically from conversation', 'Integrates directly with Epic, Cerner, and major EHR systems', 'Supports 85+ medical specialties and multiple languages', 'HIPAA compliant with local audio processing option', 'Significantly reduces post-visit documentation time'],
  ARRAY['Subscription cost adds to existing EHR licensing expenses', 'AI accuracy requires physician review before signing off', 'Initial specialty-specific training period needed for best output'],
  ARRAY['Automated clinical note generation during patient consultations', 'After-visit summary creation for patient communication', 'Referral letter drafting from consultation transcripts']
),

(
  'abridge',
  'Abridge',
  'AI medical conversation summarisation for health systems',
  E'Abridge is an enterprise AI platform that captures and summarises medical conversations for health systems and large clinical groups. The technology is designed for deployment at scale: Abridge integrates into Epic''s Suki and Haiku workflows, allowing health systems to deploy AI documentation across entire physician groups without custom implementation for each clinician.\n\nAbridge''s AI generates structured clinical summaries, patient-facing after-visit summaries, and follow-up instructions from recorded consultations. The platform is built for ambient use  -  it runs in the background of a consultation without requiring the physician to interact with additional software during the visit. The focus on Epic integration and enterprise deployment distinguishes Abridge from consumer-facing tools: it is designed for health system IT procurement rather than individual physician subscription.\n\nAbridge has partnered with UPMC, Stanford Health Care, and several major health systems, giving it significant real-world validation data. The platform is trained on a large corpus of medical language and specialises in clinical accuracy rather than general transcription quality. For health system Chief Medical Information Officers evaluating ambient AI, Abridge is one of the strongest enterprise options available.',
  'https://www.google.com/s2/favicons?domain=abridge.com&sz=64',
  'https://abridge.com',
  'https://abridge.com',
  ARRAY['healthcare'],
  'paid',
  false,
  0.00,
  4.8,
  198,
  false, false, false,
  ARRAY['Enterprise Epic integration at health system scale', 'Trained specifically on medical language for clinical accuracy', 'Partnership validation from UPMC, Stanford, and major systems', 'Generates both clinician notes and patient-facing summaries', 'Ambient operation requires no mid-consultation interaction'],
  ARRAY['Enterprise pricing and procurement  -  not available for individual physicians', 'Implementation requires IT coordination with health system', 'Less flexibility for solo practices or small groups'],
  ARRAY['Health system-wide clinical documentation automation', 'Epic EHR workflow integration for physician groups', 'Patient after-visit summary generation at scale']
),

(
  'suki-ai',
  'Suki AI',
  'AI voice assistant for physician documentation',
  E'Suki AI is a voice-based clinical documentation assistant that lets physicians dictate notes, retrieve patient information, and navigate EHR workflows using natural spoken commands. Rather than typing into an EHR or using a traditional transcription service, physicians speak naturally and Suki converts speech into structured clinical documentation.\n\nSuki differentiates from ambient documentation tools by supporting interactive voice commands during and after consultations: physicians can ask Suki to pull up a patient''s medication list, review prior diagnoses, or navigate to specific EHR sections without touching a keyboard. The AI learns individual physician preferences and documentation styles over time, improving accuracy and reducing review time as usage increases.\n\nSuki integrates with over 30 EHR systems including Epic, Cerner, and Meditech. The platform is HIPAA compliant and designed for deployment across single practices and large health systems. Google has invested in Suki, which has accelerated development of its AI capabilities and infrastructure. For physicians who find ambient passive recording systems less intuitive than active voice interaction, Suki''s command-driven approach offers a familiar dictation upgrade with AI structuring on top.',
  'https://www.google.com/s2/favicons?domain=suki.ai&sz=64',
  'https://suki.ai',
  'https://suki.ai',
  ARRAY['healthcare'],
  'paid',
  false,
  0.00,
  4.6,
  445,
  false, false, false,
  ARRAY['Interactive voice commands for EHR navigation during consultations', 'Learns individual physician style over time', 'Integrates with 30+ EHR systems including Epic and Cerner', 'HIPAA compliant with Google infrastructure backing', 'Reduces typing burden across note creation and EHR navigation'],
  ARRAY['Voice-first approach requires adjustment for physicians used to typing', 'Custom pricing  -  no public per-seat rate', 'Command accuracy depends on environment noise levels'],
  ARRAY['Voice-driven clinical note creation and dictation', 'EHR navigation and patient record retrieval by voice', 'Post-consultation documentation for high-volume practices']
),

(
  'corti',
  'Corti',
  'AI clinical decision support for emergency and primary care',
  E'Corti is an AI platform for clinical decision support that listens to patient-clinician conversations and provides real-time guidance to support diagnostic accuracy. Originally developed for emergency dispatch  -  where Corti detects signals of cardiac arrest in 999 and 911 calls before the caller describes it explicitly  -  the platform has expanded into primary care and acute settings.\n\nThe core capability is pattern recognition in spoken medical conversations. Corti''s AI identifies clinical red flags, suggests follow-up questions the clinician may have missed, and flags when conversation patterns resemble serious conditions that warrant immediate action. This real-time guidance layer helps less experienced clinicians and supports consistent protocol adherence across large provider organisations.\n\nCorti also generates structured documentation from consultations and integrates with EHR systems for note transfer. The emergency dispatch use case is particularly validated: Corti has processed millions of emergency calls across European health systems and demonstrated measurable improvements in cardiac arrest detection rates. For health systems focused on reducing diagnostic errors and improving triage consistency, Corti''s decision support capability addresses a different problem than documentation tools alone.',
  'https://www.google.com/s2/favicons?domain=corti.ai&sz=64',
  'https://corti.ai',
  'https://corti.ai',
  ARRAY['healthcare'],
  'paid',
  false,
  0.00,
  4.5,
  167,
  false, false, false,
  ARRAY['Real-time clinical decision support during live consultations', 'Validated in emergency dispatch for cardiac arrest detection', 'Pattern recognition flags missed red flags and follow-up questions', 'Deployed at scale across European health systems', 'Generates structured documentation alongside decision support'],
  ARRAY['Enterprise deployment model  -  not suited for individual practice', 'Real-time AI guidance requires clinician trust in the system', 'Implementation and training investment required'],
  ARRAY['Emergency medical dispatch with AI triage support', 'Primary care consultation support for diagnostic consistency', 'Health system-wide protocol adherence monitoring']
),

(
  'regard',
  'Regard',
  'AI platform for hospital medicine and inpatient documentation',
  E'Regard is an AI clinical documentation and decision support tool built specifically for hospital medicine  -  the management of inpatients by hospitalists and internal medicine physicians. Where most AI documentation tools focus on outpatient primary care, Regard addresses the distinct complexity of inpatient charts: multiple active problems, evolving daily assessments, care coordination notes, discharge summaries, and complex medication reconciliation.\n\nRegard''s AI reads the full inpatient chart  -  labs, medications, prior notes, vitals, imaging results  -  and automatically generates a structured daily progress note that reflects the current clinical picture. The physician reviews and edits rather than writing from scratch. The AI also surfaces potential diagnoses the physician may want to consider based on the totality of chart data, functioning as a passive second-read on complex cases.\n\nRegard integrates directly with Epic and was initially validated at major academic medical centres. The platform targets the specific documentation burden of hospitalist medicine, where daily progress notes on every active patient create substantial writing overhead and where chart review across complex inpatients is time-consuming. For hospital medicine groups evaluating AI documentation, Regard addresses a gap that ambient conversation tools do not fully cover.',
  'https://www.google.com/s2/favicons?domain=regardhealth.com&sz=64',
  'https://regardhealth.com',
  'https://regardhealth.com',
  ARRAY['healthcare'],
  'paid',
  false,
  0.00,
  4.6,
  124,
  false, false, false,
  ARRAY['Built specifically for inpatient hospital medicine workflows', 'Reads entire chart context to generate accurate progress notes', 'Surfaces diagnostic considerations from complex chart data', 'Epic integration for direct note insertion', 'Reduces daily progress note writing time for hospitalists'],
  ARRAY['Focused on inpatient/hospitalist medicine  -  limited outpatient utility', 'Enterprise procurement model  -  not for individual use', 'AI note review still requires physician sign-off for accuracy'],
  ARRAY['Daily hospital progress note generation for hospitalists', 'Complex inpatient chart review and documentation', 'Discharge summary drafting from full admission chart']
),

(
  'glass-health',
  'Glass Health',
  'AI clinical reasoning and differential diagnosis tool',
  E'Glass Health is an AI tool for clinical reasoning  -  physicians describe a patient presentation and Glass generates a structured differential diagnosis list, ranked by likelihood, with supporting reasoning for each entry. The tool is designed as a thinking partner for clinical decision-making rather than a documentation assistant.\n\nBeyond differential generation, Glass creates full clinical assessment and plan drafts, orders plans, and discharge instructions from a case summary. The AI is trained on medical literature and case data, producing outputs that reflect current clinical guidelines rather than generic text generation. Glass explains its reasoning for each differential entry, which makes it useful for learning (medical students and residents) and for double-checking clinical reasoning (experienced physicians reviewing complex presentations).\n\nGlass is lighter-weight than enterprise platforms: it runs in a web interface and mobile app without EHR integration requirements, making it accessible to individual physicians, residents, and medical students without IT procurement. The platform has gained significant adoption in medical education contexts where faculty use it to demonstrate clinical reasoning workflows alongside case discussions.',
  'https://www.google.com/s2/favicons?domain=glass.health&sz=64',
  'https://glass.health',
  'https://glass.health',
  ARRAY['healthcare'],
  'freemium',
  true,
  0.00,
  4.5,
  389,
  false, false, false,
  ARRAY['Structured differential diagnosis with ranked reasoning', 'Accessible without EHR integration  -  runs in browser and mobile', 'Useful for both clinical practice and medical education', 'AI explains reasoning behind each differential entry', 'Free tier available for individual use'],
  ARRAY['Not a documentation tool  -  separate from note generation', 'AI reasoning requires physician validation for clinical decisions', 'Limited integration with EHR workflows'],
  ARRAY['Differential diagnosis generation for complex patient presentations', 'Clinical assessment and plan drafting from case summaries', 'Medical education and resident training support']
),

(
  'nuance-dax',
  'Nuance DAX',
  'Microsoft AI ambient clinical intelligence for enterprise health',
  E'Nuance DAX (Dragon Ambient eXperience) is Microsoft''s enterprise AI clinical documentation platform, built on the Dragon medical transcription foundation that has been the standard for physician dictation for over two decades. DAX represents the evolution from structured dictation into fully ambient AI documentation: the system listens to the entire patient encounter and automatically generates a complete, speciality-specific clinical note without physician input during the visit.\n\nDAX is deeply integrated with Epic, Cerner, and Oracle Health EHR systems at the enterprise level. Microsoft''s Azure infrastructure provides the processing scale for health system-wide deployment. The platform supports over 50 specialties with specialty-specific note templates and has been deployed at major health systems across the United States including Duke Health, Providence, and Sutter Health.\n\nFor health systems already running Microsoft Azure or Nuance Dragon, DAX is the natural enterprise progression. The combination of Microsoft''s healthcare data agreements, Epic marketplace integration, and the Dragon brand reputation in clinical settings gives DAX the strongest existing-relationship procurement path of any ambient documentation platform. The pricing reflects enterprise deployment: custom contracts rather than per-seat rates.',
  'https://www.google.com/s2/favicons?domain=nuance.com&sz=64',
  'https://nuance.com',
  'https://nuance.com',
  ARRAY['healthcare'],
  'paid',
  false,
  0.00,
  4.7,
  567,
  false, false, false,
  ARRAY['Enterprise-grade with Microsoft Azure infrastructure', 'Deep Epic, Cerner, and Oracle Health EHR integration', 'Deployed at major US health systems with proven scale', 'Built on Dragon dictation platform trusted for 20+ years', 'Supports 50+ medical specialties with tailored note templates'],
  ARRAY['Enterprise-only procurement  -  not available for individual physicians', 'Custom pricing without transparency  -  lengthy sales process', 'Microsoft ecosystem dependency for optimal deployment'],
  ARRAY['Enterprise health system ambient documentation deployment', 'Specialty-specific clinical note generation at scale', 'EHR workflow integration for large physician groups']
),

(
  'aidoc',
  'Aidoc',
  'AI radiology triage and clinical imaging workflow',
  E'Aidoc is an AI medical imaging analysis platform that reviews CT scans, MRIs, and X-rays in the background of normal radiology workflow, flagging critical findings  -  pulmonary embolisms, intracranial haemorrhages, aortic dissections, spinal fractures  -  in near real time so they can be prioritised before a radiologist reads the full study queue. The AI does not replace radiologist interpretation; it acts as a continuous background monitor that ensures critical findings are never buried in a full queue.\n\nAidoc is FDA-cleared for multiple indications including intracranial haemorrhage, pulmonary embolism, and incidental pulmonary nodule detection. FDA clearance is significant in AI radiology: it means clinical validation data has been reviewed and the tool can be used as part of clinical workflow rather than purely for research. Over 1,000 hospitals globally use Aidoc.\n\nThe platform integrates with PACS (Picture Archiving and Communication Systems) used in radiology departments and surfaces findings to both radiologists and clinical teams through notifications and integrated dashboards. For radiology departments handling high volumes of cross-sectional imaging, Aidoc addresses the triage problem: ensuring that the most time-sensitive findings receive the fastest attention regardless of when they arrive in the queue.',
  'https://www.google.com/s2/favicons?domain=aidoc.com&sz=64',
  'https://aidoc.com',
  'https://aidoc.com',
  ARRAY['healthcare'],
  'paid',
  false,
  0.00,
  4.7,
  234,
  false, false, false,
  ARRAY['FDA-cleared for multiple critical imaging indications', 'Deployed in 1,000+ hospitals with real-world validation', 'Triage prioritisation prevents critical findings being missed', 'Integrates with PACS systems used in radiology departments', 'Near real-time background processing alongside normal workflow'],
  ARRAY['Requires PACS integration and radiology IT involvement', 'Enterprise pricing  -  not accessible for individual radiologists', 'AI triage does not replace formal radiologist interpretation'],
  ARRAY['Critical finding triage in CT, MRI, and X-ray workflow', 'Pulmonary embolism and intracranial haemorrhage prioritisation', 'Incidental finding monitoring across large imaging volumes']
),

(
  'doximity',
  'Doximity',
  'Professional network and AI tools for US physicians',
  E'Doximity is the professional network for US physicians, used by over 80% of US doctors. Beyond the networking and directory function, Doximity has built a suite of AI-powered clinical productivity tools accessible to its verified physician user base. The Doximity AI tool generates clinical letters, referral letters, prior authorisation letters, and patient communication drafts from brief prompts  -  the physician describes what needs to be communicated and Doximity drafts the full text.\n\nThe clinical communication tools address a specific administrative burden: physicians spending time writing and rewriting standard letters that follow predictable structures. Doximity''s AI generates these drafts instantly and lets physicians edit rather than write from scratch. The platform also provides secure HIPAA-compliant messaging between physicians for care coordination and a HIPAA-compliant video calling function.\n\nDoximity''s differentiation is access: verified US physicians get access to the AI tools through the existing Doximity platform they already use, without a separate procurement or integration step. For the 80%+ of US physicians already on Doximity, the AI features are an immediate productivity upgrade available through their existing login. The core platform is free for physicians; premium features including the advanced AI tools are available through the subscription tier.',
  'https://www.google.com/s2/favicons?domain=doximity.com&sz=64',
  'https://doximity.com',
  'https://doximity.com',
  ARRAY['healthcare'],
  'freemium',
  true,
  0.00,
  4.4,
  1243,
  false, false, false,
  ARRAY['Used by 80%+ of US physicians  -  no new platform adoption needed', 'AI clinical letter and referral drafting built in', 'HIPAA-compliant messaging and video calling included', 'Verified physician network ensures professional context', 'Free tier covers most individual physician needs'],
  ARRAY['US-only  -  limited utility for international medical professionals', 'AI tools are supplements to the network, not a dedicated AI platform', 'Advanced AI features require paid subscription'],
  ARRAY['Clinical letter and referral drafting for US physicians', 'Secure physician-to-physician care coordination messaging', 'Prior authorisation letter generation from case details']
),

(
  'anterior',
  'Anterior',
  'AI clinical intelligence for healthcare prior authorisation',
  E'Anterior is an AI platform that automates prior authorisation workflows for health systems and payers. Prior authorisation  -  the process by which insurers review and approve or deny medical procedures before they occur  -  is one of the most administratively burdensome processes in US healthcare, consuming significant time for both provider teams submitting requests and payer teams reviewing them.\n\nAnterior''s AI reviews the clinical evidence in a patient''s record, matches it against payer policy criteria, and generates a pre-populated prior authorisation submission including the relevant clinical justification drawn from the patient''s documented history. For reviewers on the payer side, Anterior surfaces the relevant clinical context alongside incoming requests to accelerate review. The platform integrates with EHR and payer systems to automate data flow between submission and review.\n\nAnterior is founded by physicians and focuses specifically on the prior auth workflow rather than broader clinical documentation. For health systems where prior auth administrative burden is a significant operational problem  -  often requiring dedicated staff teams and causing treatment delays  -  Anterior targets the specific inefficiency with purpose-built AI rather than a general-purpose documentation tool adapted to the use case.',
  'https://www.google.com/s2/favicons?domain=anterior.com&sz=64',
  'https://anterior.com',
  'https://anterior.com',
  ARRAY['healthcare'],
  'paid',
  false,
  0.00,
  4.5,
  89,
  false, false, false,
  ARRAY['Purpose-built for prior authorisation  -  not a repurposed general tool', 'Automates clinical evidence extraction for PA submissions', 'Works for both health system submitters and payer reviewers', 'Reduces prior auth delays and associated treatment wait times', 'Integrates with EHR systems for automated data extraction'],
  ARRAY['US healthcare-specific workflow  -  limited international applicability', 'Enterprise procurement required  -  no self-serve access', 'ROI dependent on prior auth volume  -  less valuable for low-volume practices'],
  ARRAY['Prior authorisation submission automation for health systems', 'Clinical evidence extraction and justification drafting', 'Payer-side prior auth review acceleration']
)

ON CONFLICT (slug) DO NOTHING;
