-- tools-batch-46.sql
-- 10 AI Design & UI tools
-- All slugs verified NOT present in any prior tools-batch file
-- Run after compare-batch-45.sql

INSERT INTO tools (slug, name, tagline, description, logo_url, website_url, affiliate_url, tags, pricing_type, pricing_free_tier, pricing_starting_price, rating, review_count, featured, trending, editor_pick, pros, cons, use_cases)
VALUES

('framer',
 'Framer',
 'AI website builder that generates production-ready sites from text prompts',
 'Framer is a visual website builder that uses AI to generate complete, responsive websites from a text description. Unlike traditional page builders, Framer produces genuine code under the hood - React components with proper CSS - which means the output is fast, clean, and extensible by developers who want to customise further. The AI generation workflow starts by describing the type of site needed, after which Framer produces a full layout with sections, typography, and colour scheme that can be edited visually. The component system supports custom interactions and animations without code, while developers can drop into the code layer when needed. Framer also handles hosting, custom domains, and SEO settings in a single platform, making it practical for small businesses and solo creators who want a professional result without hiring a developer. Published sites are genuinely fast - built on a CDN with automatic image optimisation and minimal JavaScript. The free plan supports one project with a Framer subdomain.',
 NULL,
 'https://framer.com',
 'https://framer.com',
 ARRAY['design', 'website-builder', 'no-code', 'ai-generation'],
 'freemium',
 true,
 0.00,
 4.6, 3200,
 false, true, false,
 ARRAY['AI generation produces fast, production-ready React sites', 'Visual editing does not compromise code quality', 'Hosting, domains, and CMS included in one platform', 'Free plan available for personal projects'],
 ARRAY['Less suitable for complex database-driven applications', 'Template lock-in can make radical redesigns slower', 'CMS is limited compared to dedicated platforms like Contentful'],
 ARRAY['Landing pages and marketing sites for startups', 'Portfolio sites for designers and developers', 'Product launch pages with animations and interactions']),

('galileo-ai',
 'Galileo AI',
 'AI UI design tool that generates full interface screens from text descriptions',
 'Galileo AI is a generative AI tool for UI designers that converts text prompts into complete, editable interface mockups. A prompt like "a fitness tracking dashboard with weekly progress charts and a workout log" produces a full screen design with components, spacing, and colour that follows modern design conventions. The output is not a rough wireframe - it uses real UI components with proper layout grid, type hierarchy, and visual polish. Designs export directly to Figma, where they can be handed off to developers or refined further. Galileo AI is particularly useful at the beginning of a project when exploring directions quickly: a designer can generate ten different layout approaches in the time it would take to sketch one. The tool understands design system conventions, so the output is rarely arbitrary - it applies patterns familiar from established apps and platforms. This speeds up the exploration phase significantly without replacing the refinement and thinking that makes final designs excellent.',
 NULL,
 'https://usegalileo.ai',
 'https://usegalileo.ai',
 ARRAY['design', 'ui-ux', 'ai-generation', 'figma'],
 'paid',
 false,
 19.00,
 4.3, 780,
 false, true, false,
 ARRAY['Generates polished, convention-following UI in seconds', 'Direct Figma export for seamless designer workflow', 'Excellent for rapid direction exploration at project start', 'Understands real design system patterns, not arbitrary layouts'],
 ARRAY['Output requires substantial refinement for final production use', 'Not suitable as a replacement for full design thinking and iteration', 'Less effective for highly custom or brand-specific visual languages'],
 ARRAY['Rapid UI concept generation for client presentations', 'Design direction exploration during discovery phase', 'Fast mockups for user testing sessions']),

('locofy',
 'Locofy.ai',
 'Convert Figma and Adobe XD designs into production-ready frontend code',
 'Locofy.ai bridges the gap between design and development by converting Figma and Adobe XD designs into production frontend code. The AI analyses the design layers, infers component boundaries, and generates React, Vue, Next.js, Gatsby, or HTML/CSS code that matches the visual design. Rather than generic code that requires heavy rework, Locofy identifies design patterns - cards, navigation bars, forms, modals - and maps them to appropriate component structures. The generated code uses proper naming conventions, responsive breakpoints, and handles basic state like button hover effects. Developers typically save 30-60 percent of initial build time on design-to-code handoff, using the generated output as a scaffold rather than writing structure from scratch. Locofy integrates as a Figma plugin, so the conversion happens directly inside the designer''s workflow without exporting files.',
 NULL,
 'https://locofy.ai',
 'https://locofy.ai',
 ARRAY['design', 'design-to-code', 'frontend', 'figma'],
 'freemium',
 true,
 0.00,
 4.2, 640,
 false, false, false,
 ARRAY['Generates React, Vue, Next.js code that matches Figma designs accurately', 'Identifies component patterns - not just flat CSS output', 'Works as a Figma plugin for seamless designer workflow', 'Significant time savings on initial design-to-code handoff'],
 ARRAY['Generated code still requires developer review and cleanup', 'Complex interactions and animations require manual implementation', 'Best results require well-organised Figma files with named layers'],
 ARRAY['Accelerating frontend build from design handoff', 'Generating responsive component scaffolds from Figma', 'Reducing design-to-development friction for product teams']),

('uizard',
 'Uizard',
 'AI prototyping tool that turns sketches and screenshots into editable UI designs',
 'Uizard is an AI-powered design and prototyping tool built for speed, not perfection. Its most distinctive feature is the ability to take a hand-drawn sketch - photographed with a phone - and convert it into a digital wireframe with editable components. This makes it useful very early in the design process when ideas are still rough. Uizard also converts screenshots of existing apps into editable designs, which is useful for competitive analysis or when recreating a UI pattern you have seen elsewhere. The AI theme generator produces complete colour and typography systems from a description or a reference image. Uizard is explicitly designed for non-designers: product managers, founders, and startup teams who need to communicate interface ideas clearly without Figma expertise. The drag-and-drop editor uses a library of pre-built UI components that can be assembled quickly into clickable prototypes ready for user testing or stakeholder review.',
 NULL,
 'https://uizard.io',
 'https://uizard.io',
 ARRAY['design', 'prototyping', 'wireframing', 'no-code'],
 'freemium',
 true,
 0.00,
 4.1, 1150,
 false, false, false,
 ARRAY['Sketch-to-wireframe conversion is genuinely useful for early-stage ideation', 'No design experience required - aimed at product managers and founders', 'Screenshot-to-design feature useful for competitive benchmarking', 'Fast clickable prototypes for user testing'],
 ARRAY['Output quality is not suitable for final production design', 'Less powerful than Figma for professional UI designers', 'Component library less comprehensive than dedicated design tools'],
 ARRAY['Rapid prototyping for startup MVPs and investor demos', 'Non-designer communication of interface ideas to development teams', 'Converting hand-drawn sketches into digital wireframes for review']),

('visily',
 'Visily',
 'AI wireframing tool for teams to design product interfaces without design skills',
 'Visily is an AI wireframing and design tool that lets product teams create professional-looking interface mockups without a dedicated designer. The AI can generate a full wireframe from a text description, convert a screenshot from any app into an editable design, or suggest layout improvements to an existing mockup. The component library includes over 1,000 pre-built UI elements organised by pattern type - navigation, forms, dashboards, cards - which can be assembled without starting from scratch. Visily is particularly strong in the collaborative features: team members can comment, annotate, and iterate on designs in real time, making it practical for cross-functional teams who need to agree on interface direction before investing in development. The export to Figma feature ensures designers can take ownership of wireframes once the direction is agreed.',
 NULL,
 'https://visily.ai',
 'https://visily.ai',
 ARRAY['design', 'wireframing', 'prototyping', 'collaboration'],
 'freemium',
 true,
 0.00,
 4.2, 520,
 false, false, false,
 ARRAY['Text-to-wireframe AI removes the blank canvas problem', 'Strong team collaboration features for cross-functional design reviews', 'Screenshot-to-editable-design conversion for competitive analysis', 'Export to Figma for design team handoff'],
 ARRAY['Not a replacement for a professional design tool at production stage', 'Component library has some gaps for niche UI patterns', 'AI generation quality varies depending on prompt specificity'],
 ARRAY['Product team wireframing without dedicated design resource', 'Rapid iteration on layout direction before developer handoff', 'Collaborative interface review with stakeholders']),

('relume',
 'Relume',
 'AI website sitemap and wireframe builder that exports directly to Figma and Webflow',
 'Relume is an AI tool that accelerates the early stages of website design: sitemap planning and wireframing. Enter a description of the website - company type, primary goals, target audience - and Relume generates a complete sitemap with recommended pages, then produces wireframes for each page based on its library of best-practice layouts. The wireframes are not generic blocks - they are built from Relume''s component library of 1,000+ website sections that follow conversion-optimised patterns for landing pages, pricing pages, about pages, and more. Everything exports directly to Figma as editable frames or to Webflow as components. For web designers and agencies, Relume eliminates the most time-consuming part of new project setup: the blank-page problem of figuring out site structure and initial layout before doing any real design work.',
 NULL,
 'https://relume.io',
 'https://relume.io',
 ARRAY['design', 'website-builder', 'wireframing', 'figma', 'webflow'],
 'freemium',
 true,
 0.00,
 4.4, 890,
 false, true, false,
 ARRAY['AI sitemap generation eliminates early project planning bottleneck', '1,000+ conversion-optimised component library for quick wireframing', 'Direct Figma and Webflow export saves significant setup time', 'Well-suited for web design agencies handling multiple client projects'],
 ARRAY['Primarily useful for website projects - not for mobile app or product UI', 'Webflow export requires familiarity with Webflow to customise effectively', 'Less useful for highly custom brand aesthetics that deviate from common patterns'],
 ARRAY['Agency website project kick-off and sitemap planning', 'Rapid wireframe generation for client discovery presentations', 'Webflow site scaffolding for designers who want a head start']),

('subframe',
 'Subframe',
 'Visual UI builder that generates clean React code for web applications',
 'Subframe is a visual UI builder specifically designed for building web application interfaces - not marketing pages. It sits between a design tool and a code editor: designers build components visually, and Subframe outputs clean, maintainable React and Tailwind CSS code that developers can integrate directly into their codebase. The component library covers the common patterns of web applications - data tables, forms, navigation sidebars, dashboards, settings pages - and all components are responsive and accessible by default. Unlike tools that generate messy or brittle code, Subframe produces code that follows real development conventions. Teams use it to build internal tools, admin panels, and SaaS product interfaces where visual polish matters but the priority is shipping clean, maintainable code quickly rather than pixel-perfect design files.',
 NULL,
 'https://subframe.com',
 'https://subframe.com',
 ARRAY['design', 'ui-builder', 'react', 'web-apps'],
 'freemium',
 true,
 0.00,
 4.3, 340,
 false, true, false,
 ARRAY['Generated React and Tailwind CSS code is genuinely clean and maintainable', 'Component library covers real application UI patterns - dashboards, tables, forms', 'Accessible and responsive components by default', 'Bridges designer and developer workflow without code quality compromise'],
 ARRAY['Focused on web apps - not suitable for marketing sites or mobile', 'Smaller component library than mature design systems like MUI', 'Newer tool with less community documentation than established alternatives'],
 ARRAY['Building SaaS product UI with React without a dedicated designer', 'Internal admin panel and dashboard development', 'Prototyping application interfaces for developer review']),

('penpot',
 'Penpot',
 'Open-source design and prototyping tool built for designers and developers together',
 'Penpot is the leading open-source design and prototyping tool, providing a free, self-hostable alternative to Figma. It runs in the browser and produces SVG-based output that is natively portable - no proprietary formats. Designers work in a familiar interface with frames, components, auto-layout, and a full prototyping mode, while developers inspect designs using a CSS-properties panel that reflects the exact visual properties without interpretation. Penpot is free with no seat limits on the cloud version and can be self-hosted for organisations with data residency requirements. For design teams who moved to Figma from Sketch and are now looking for a privacy-first alternative with no per-seat pricing, Penpot is the most mature option available. The development is community-driven and active, with new features shipping regularly.',
 NULL,
 'https://penpot.app',
 'https://penpot.app',
 ARRAY['design', 'prototyping', 'open-source', 'collaboration'],
 'free',
 true,
 0.00,
 4.3, 1620,
 false, false, false,
 ARRAY['Completely free with no per-seat pricing', 'Self-hostable for organisations with data sovereignty requirements', 'SVG-based output is portable and not locked to a proprietary format', 'Active open-source development with growing plugin ecosystem'],
 ARRAY['Feature set is behind Figma in some advanced areas (variables, Dev Mode)', 'Fewer third-party integrations than Figma', 'Smaller community means fewer templates and educational resources'],
 ARRAY['Design teams needing Figma functionality without per-seat costs', 'Self-hosted design infrastructure for compliance-driven organisations', 'Open-source product teams contributing to design tool development']),

('diagram',
 'Diagram',
 'AI design tools for Figma - generate UI, rename layers, and write UX copy automatically',
 'Diagram is a collection of AI-powered Figma plugins that extend the design workflow with generative capabilities. The flagship plugin, Genius, generates UI components inside Figma from a text prompt - a button, a card, a form - directly in your existing design file. The Automator plugin batch-processes tedious tasks: renaming layers by content, applying consistent naming conventions to a messy Figma file, or converting text layers to auto-layout. The UX Writer plugin generates placeholder copy for designs - headlines, button labels, error messages - in the brand voice and tone of the product. Together, these plugins reduce the low-value repetitive work in design: layer cleanup, copy placeholder writing, and initial component drafts. Diagram sits inside the Figma workflow rather than requiring a separate tool, which makes adoption nearly frictionless for existing Figma users.',
 NULL,
 'https://diagram.com',
 'https://diagram.com',
 ARRAY['design', 'figma', 'ai-generation', 'productivity'],
 'freemium',
 true,
 0.00,
 4.2, 490,
 false, false, false,
 ARRAY['Works inside Figma as plugins - no context switching', 'Automates the most tedious parts of the design workflow', 'UX copy generation saves significant time on placeholder content', 'Zero setup for existing Figma users'],
 ARRAY['Quality of AI generation varies by component complexity', 'Most useful as a time-saver rather than a core design tool', 'Dependent on Figma - not useful if your team does not use Figma'],
 ARRAY['Speeding up repetitive Figma layer cleanup and renaming', 'Generating initial UI components for rapid exploration', 'Automating UX copy creation for design files']),

('magician',
 'Magician',
 'AI magic for Figma - generate icons, images, and copy from text inside your design files',
 'Magician is a Figma plugin that brings generative AI directly into the design canvas. It can generate custom icons from a text description (replacing the time spent searching icon libraries), create placeholder images and illustrations that match a specific style or subject, write UX copy for any text layer, and suggest design alternatives. The icon generation is particularly distinctive - rather than choosing from a fixed library, designers describe what they need and Magician produces a vector icon that matches. This is useful when working on a niche product where standard icon libraries lack the right visual metaphors. Magician works as a single Figma plugin, so it requires no separate subscription dashboard or context switch. It is priced as a simple monthly subscription for individual designers rather than a per-seat enterprise product.',
 NULL,
 'https://magician.design',
 'https://magician.design',
 ARRAY['design', 'figma', 'ai-generation', 'icons'],
 'paid',
 false,
 4.99,
 4.1, 720,
 false, false, false,
 ARRAY['Custom icon generation from text is genuinely unique and time-saving', 'All AI features available inside Figma with no context switch', 'Very affordable at individual designer price point', 'Image generation useful for placeholder content during design review'],
 ARRAY['Icon output quality requires selection and cleanup rather than direct use', 'Less comprehensive than dedicated AI design tools for full UI generation', 'Limited to Figma users - not a standalone design tool'],
 ARRAY['Generating custom icons for niche products where standard libraries fall short', 'Creating placeholder illustrations and images for design presentations', 'Writing UX copy variations for A/B testing in design files'])

ON CONFLICT (slug) DO NOTHING;
