-- tools-batch-31.sql
-- 10 new tools: clearscope, marketmuse, contentatscale, neuronwriter, dashword, alli-ai, originality-ai, scalenut, keyword-insights, diib
-- Theme: AI SEO tools and content marketing platforms
-- surfer-seo, semrush, ahrefs, frase, writesonic confirmed in DB from earlier batches
-- Safe to re-run: ON CONFLICT (slug) DO NOTHING

-- 1. Clearscope
INSERT INTO tools (
  slug, name, tagline, description,
  logo_url, website_url, affiliate_url,
  tags, pricing_type, pricing_free_tier, pricing_starting_price,
  rating, review_count, featured, trending, editor_pick,
  pros, cons, use_cases
) VALUES (
  'clearscope', 'Clearscope', 'AI-powered content grading and optimisation for SEO-driven writing',
  'Clearscope is an SEO content optimisation tool that analyses the top-ranking pages for a target keyword and produces a content grading report showing which topics, terms, and entities your content should cover to be competitive. The content editor scores your writing in real time as you add relevant terms, giving immediate feedback on completeness relative to what is ranking. Unlike tools that focus only on keyword density, Clearscope uses semantic analysis to identify the full topical context that Google associates with a query - covering related concepts and entities, not just the exact match keyword. Integrations with Google Docs and WordPress make it practical to use Clearscope within existing writing workflows without switching tools. The reporting is clean and the learning curve is low, making it accessible to content writers who are not technical SEOs. Clearscope is particularly effective for teams producing high-volume editorial content where consistent topic coverage is the primary quality lever.',
  'https://www.google.com/s2/favicons?domain=clearscope.io&sz=64',
  'https://clearscope.io', 'https://clearscope.io',
  ARRAY['seo-marketing', 'content'],
  'paid', false, 189.00,
  4.5, 680, true, true, false,
  ARRAY['Real-time content grading gives writers immediate feedback on topic coverage', 'Google Docs integration means writers never need to leave their primary tool', 'Semantic analysis covers related entities and concepts, not just keyword frequency', 'Clean, focused interface has a very low learning curve for non-technical writers'],
  ARRAY['No free tier - starts at $189/month, which is steep for individual creators', 'Less focus on keyword research and technical SEO than broader platforms like Semrush', 'Reports are useful at the content level but do not cover site-wide SEO issues'],
  ARRAY['Grading and improving existing articles to recover lost rankings', 'Training content writers to cover topics comprehensively without technical SEO knowledge', 'Scaling content production teams with consistent quality benchmarks']
) ON CONFLICT (slug) DO NOTHING;

-- 2. MarketMuse
INSERT INTO tools (
  slug, name, tagline, description,
  logo_url, website_url, affiliate_url,
  tags, pricing_type, pricing_free_tier, pricing_starting_price,
  rating, review_count, featured, trending, editor_pick,
  pros, cons, use_cases
) VALUES (
  'marketmuse', 'MarketMuse', 'AI content intelligence platform for content strategy and competitive analysis',
  'MarketMuse is an AI content intelligence platform that goes beyond optimising individual articles to provide strategic analysis of your entire content site. It compares your site''s content depth against competitors, identifies topical authority gaps, and prioritises which content to create or update based on projected traffic value. The Site Inventory feature audits every page on your site and scores it against what is ranking, surfacing which articles are underperforming and why. Content Briefs generated by MarketMuse include competitor analysis, recommended topics, word count guidance, and internal linking suggestions. The AI writing assistant generates first drafts within the brief context. MarketMuse is particularly valuable for content strategists who need to make portfolio-level decisions about content investment - not just individual article quality. The price point reflects the strategic rather than tactical nature of the tool.',
  'https://www.google.com/s2/favicons?domain=marketmuse.com&sz=64',
  'https://marketmuse.com', 'https://marketmuse.com',
  ARRAY['seo-marketing', 'content'],
  'freemium', true, 0.00,
  4.3, 420, true, false, false,
  ARRAY['Site-level content inventory identifies underperforming pages across the entire domain', 'Content Briefs include competitor analysis and topical gap identification', 'Topical authority scoring helps prioritise content creation for maximum SEO impact', 'Free tier with 10 queries/month allows meaningful evaluation before purchase'],
  ARRAY['Steeper learning curve than simpler tools like Clearscope', 'Premium plans are expensive for small teams or individual creators', 'AI writing output requires significant editing - better used as a brief generator than a draft tool'],
  ARRAY['Auditing a site''s content portfolio to identify the highest-ROI content updates', 'Building a topical authority strategy for a new website or content expansion', 'Creating data-driven content briefs for freelance writers or content teams']
) ON CONFLICT (slug) DO NOTHING;

-- 3. Content at Scale
INSERT INTO tools (
  slug, name, tagline, description,
  logo_url, website_url, affiliate_url,
  tags, pricing_type, pricing_free_tier, pricing_starting_price,
  rating, review_count, featured, trending, editor_pick,
  pros, cons, use_cases
) VALUES (
  'contentatscale', 'Content at Scale', 'AI content platform for producing long-form SEO articles that pass AI detection',
  'Content at Scale is an AI content generation platform focused specifically on producing long-form SEO articles that are both high quality and undetectable as AI-written by current AI detection tools. The platform uses a multi-model approach, combining multiple AI engines with real-time research and NLP analysis, to produce 2,500-4,000 word articles from a keyword input. The output includes structured headings, FAQs, key takeaways, and internal linking suggestions. Built-in AI detection scoring shows the likelihood that content will be flagged before publishing. The AIO (AI Output) editor integrates directly with WordPress for one-click publishing. Content at Scale is designed for publishers, content agencies, and SEO teams that need to produce high volumes of long-form content without proportionally increasing the human writing workload. The content still requires human review and editing, but the structural and research-intensive first draft is handled automatically.',
  'https://www.google.com/s2/favicons?domain=contentatscale.ai&sz=64',
  'https://contentatscale.ai', 'https://contentatscale.ai',
  ARRAY['seo-marketing', 'content'],
  'paid', false, 250.00,
  4.2, 380, false, true, false,
  ARRAY['Produces long-form articles with research, structure, and FAQs from a single keyword', 'Built-in AI detection scoring reduces the risk of flagged content before publishing', 'WordPress integration enables one-click publishing from the AI editor', 'Multi-model approach produces more varied and less pattern-predictable output than single-model tools'],
  ARRAY['High starting price of $250/month makes it a significant investment for small operations', 'Output still requires substantial human editing for brand voice and factual accuracy', 'Content depth is adequate but rarely matches the quality of expert human writers on complex topics'],
  ARRAY['Scaling a content publishing operation without proportionally increasing writing staff', 'Producing programmatic SEO content for large keyword sets', 'Generating first drafts for content teams to edit and publish faster']
) ON CONFLICT (slug) DO NOTHING;

-- 4. NeuronWriter
INSERT INTO tools (
  slug, name, tagline, description,
  logo_url, website_url, affiliate_url,
  tags, pricing_type, pricing_free_tier, pricing_starting_price,
  rating, review_count, featured, trending, editor_pick,
  pros, cons, use_cases
) VALUES (
  'neuronwriter', 'NeuronWriter', 'NLP-powered SEO content editor with AI writing assistance and competitive analysis',
  'NeuronWriter is an SEO content editor that combines NLP-based content optimisation with AI writing assistance. Like Clearscope and Surfer SEO, it analyses the top-ranking pages for a target keyword and identifies the semantic terms and topics your content needs to cover. The competitive analysis includes word count benchmarks, readability scores, and the specific NLP terms used most by ranking pages. The integrated AI writing assistant can generate complete article drafts or specific sections within the optimisation context, so AI-written content is already aligned with the ranking signals. NeuronWriter integrates with Google Search Console to surface which existing pages have the most opportunity for improvement. The pricing is significantly lower than Clearscope and MarketMuse, making it a strong option for agencies and freelancers who need robust content optimisation without enterprise-level budgets.',
  'https://www.google.com/s2/favicons?domain=neuronwriter.com&sz=64',
  'https://neuronwriter.com', 'https://neuronwriter.com',
  ARRAY['seo-marketing', 'content'],
  'paid', false, 19.00,
  4.3, 290, false, false, false,
  ARRAY['Strong price-to-value ratio compared to Clearscope and Surfer SEO at equivalent functionality', 'NLP term analysis goes beyond keyword frequency to semantic entity coverage', 'Google Search Console integration identifies improvement opportunities in existing content', 'AI writing assistant operates within the optimisation context for aligned output'],
  ARRAY['Interface is less polished than Clearscope or Surfer SEO', 'AI writing quality is adequate but does not match dedicated AI writing platforms like Jasper', 'Smaller integration ecosystem than the larger SEO tools'],
  ARRAY['Optimising content for semantic search without paying Clearscope or Surfer prices', 'Freelance SEO writers needing a cost-effective content grading tool', 'Identifying NLP term gaps in underperforming articles before a content update']
) ON CONFLICT (slug) DO NOTHING;

-- 5. Dashword
INSERT INTO tools (
  slug, name, tagline, description,
  logo_url, website_url, affiliate_url,
  tags, pricing_type, pricing_free_tier, pricing_starting_price,
  rating, review_count, featured, trending, editor_pick,
  pros, cons, use_cases
) VALUES (
  'dashword', 'Dashword', 'Content brief generation and SEO content scoring for writing teams',
  'Dashword is a content brief and SEO content optimisation tool designed for teams that manage writers rather than writing themselves. It generates detailed content briefs from a target keyword - including competitor analysis, recommended headings, topics to cover, and word count guidance - that writers can follow without SEO expertise. The content editor scores writing against these briefs in real time, giving writers clear feedback on what to improve. The brief quality is one of Dashword''s differentiators: it identifies specific questions from People Also Ask boxes, competitor headers, and related topics, so briefs cover the full content scope rather than just keyword frequency. Team management features allow assigning briefs to specific writers and tracking progress. Dashword is priced accessibly for small-to-medium content teams that need to systematise brief creation without the cost of MarketMuse or the complexity of full-platform SEO tools.',
  'https://www.google.com/s2/favicons?domain=dashword.com&sz=64',
  'https://dashword.com', 'https://dashword.com',
  ARRAY['seo-marketing', 'content'],
  'paid', false, 99.00,
  4.1, 180, false, false, false,
  ARRAY['Content brief quality covers PAA questions, competitor headers, and topical gaps', 'Team management features for assigning briefs to multiple writers', 'Accessible pricing compared to MarketMuse and Clearscope', 'Real-time content scoring gives writers clear optimisation targets'],
  ARRAY['Smaller feature set than full-platform SEO content tools', 'Limited technical SEO features beyond content grading', 'Fewer integrations than larger platforms'],
  ARRAY['Creating consistent content briefs for teams of freelance writers', 'Standardising content quality across a content production operation', 'Building SEO-aligned article structures before assigning to writers']
) ON CONFLICT (slug) DO NOTHING;

-- 6. Alli AI
INSERT INTO tools (
  slug, name, tagline, description,
  logo_url, website_url, affiliate_url,
  tags, pricing_type, pricing_free_tier, pricing_starting_price,
  rating, review_count, featured, trending, editor_pick,
  pros, cons, use_cases
) VALUES (
  'alli-ai', 'Alli AI', 'Technical SEO automation platform for implementing optimisations at scale',
  'Alli AI is a technical SEO automation platform that makes it practical to implement on-page and technical SEO changes across large websites without requiring developer resources for each change. It connects to your CMS and implements optimisations - meta titles, meta descriptions, schema markup, internal links, and page speed improvements - automatically using AI-generated recommendations. The deployment engine can push changes to thousands of pages at once rather than requiring manual page-by-page editing. Alli AI is designed for agencies and enterprise SEO teams managing large sites where the bottleneck is implementation speed rather than strategy. The A/B testing module runs split tests on different SEO approaches and measures the ranking impact before full deployment. For sites with thousands of pages where manual optimisation is impractical, Alli AI provides the automation layer that bridges SEO strategy and implementation.',
  'https://www.google.com/s2/favicons?domain=alliai.com&sz=64',
  'https://alliai.com', 'https://alliai.com',
  ARRAY['seo-marketing', 'automation'],
  'paid', false, 299.00,
  4.2, 210, false, true, false,
  ARRAY['Implements SEO changes across thousands of pages without developer involvement', 'A/B testing module validates SEO changes before full site deployment', 'Schema markup automation handles structured data at scale', 'CMS integrations cover WordPress, Shopify, and custom platforms'],
  ARRAY['Enterprise pricing is not suitable for small sites or individual SEO practitioners', 'Automated recommendations require review - AI can suggest suboptimal changes on niche content', 'Less useful for sites with fewer than 500 pages where manual optimisation is practical'],
  ARRAY['Deploying meta title and description optimisations across thousands of product pages', 'Implementing schema markup at scale for e-commerce and news sites', 'Running SEO A/B tests to validate whether proposed changes improve rankings before full rollout']
) ON CONFLICT (slug) DO NOTHING;

-- 7. Originality.ai
INSERT INTO tools (
  slug, name, tagline, description,
  logo_url, website_url, affiliate_url,
  tags, pricing_type, pricing_free_tier, pricing_starting_price,
  rating, review_count, featured, trending, editor_pick,
  pros, cons, use_cases
) VALUES (
  'originality-ai', 'Originality.ai', 'AI content detection and plagiarism checker for publishers and content teams',
  'Originality.ai is an AI content detection and plagiarism checking tool designed specifically for content publishers and editorial teams who need to verify whether submitted content was written by humans or generated by AI. It detects content produced by ChatGPT, Claude, Gemini, Llama, and other major AI models, and combines this with traditional plagiarism detection in a single scan. The detection accuracy is consistently rated among the highest available for current AI model versions. The readability score gives a supplementary signal on writing quality. Team management features allow multiple editors to share scans and results. Originality.ai is particularly important for publishers who accept contributor content or manage freelance writers, where the risk of AI-generated content being submitted as human-written is highest. The credit-based pricing is transparent and scales well for variable-volume use.',
  'https://www.google.com/s2/favicons?domain=originality.ai&sz=64',
  'https://originality.ai', 'https://originality.ai',
  ARRAY['seo-marketing', 'content'],
  'paid', false, 14.95,
  4.4, 520, false, true, false,
  ARRAY['Detects AI content from all major models including ChatGPT, Claude, and Gemini', 'Combines AI detection with plagiarism checking in a single scan', 'Credit-based pricing scales well for variable-volume editorial operations', 'Team workspace allows multiple editors to share and review results'],
  ARRAY['No AI detection tool achieves perfect accuracy - false positives and negatives exist', 'Does not provide rewriting assistance to humanise flagged content', 'Credit costs can add up for high-volume publishers reviewing hundreds of articles monthly'],
  ARRAY['Screening contributor submissions for AI-generated content before publication', 'Auditing existing published content for AI detection risk during a content review', 'Verifying freelance writer output when AI use is restricted by contract']
) ON CONFLICT (slug) DO NOTHING;

-- 8. Scalenut
INSERT INTO tools (
  slug, name, tagline, description,
  logo_url, website_url, affiliate_url,
  tags, pricing_type, pricing_free_tier, pricing_starting_price,
  rating, review_count, featured, trending, editor_pick,
  pros, cons, use_cases
) VALUES (
  'scalenut', 'Scalenut', 'AI-powered SEO content research, planning, and writing platform',
  'Scalenut is an AI content platform that covers the full SEO content workflow: keyword research, content planning, content brief generation, AI-assisted writing, and content optimisation scoring. The Cruise Mode automates long-form article creation by researching a topic, generating an outline, and writing a full draft in one workflow - targeting 2,000-2,500 word articles. The NLP Optimiser scores drafts against semantic terms used by competing pages. The keyword planner identifies clusters of related keywords to build topical authority rather than targeting isolated keywords. Scalenut competes with both Surfer SEO (on the optimisation side) and Jasper (on the writing side) at a price point below both. For content teams that want a single platform covering research, writing, and optimisation without separate tools for each step, Scalenut offers comprehensive coverage at a mid-market price.',
  'https://www.google.com/s2/favicons?domain=scalenut.com&sz=64',
  'https://scalenut.com', 'https://scalenut.com',
  ARRAY['seo-marketing', 'content'],
  'freemium', true, 0.00,
  4.1, 340, false, false, false,
  ARRAY['Covers keyword research, brief generation, AI writing, and content scoring in one tool', 'Cruise Mode automates long-form article production from a single keyword', 'Keyword cluster planning supports topical authority building strategies', 'Price point is below both Surfer SEO and Jasper for comparable combined functionality'],
  ARRAY['Writing quality in Cruise Mode requires significant editing before publication', 'NLP optimisation is less detailed than Clearscope or Surfer SEO at the individual article level', 'Keyword research depth does not match dedicated tools like Ahrefs or Semrush'],
  ARRAY['Content teams replacing multiple separate tools with a single unified platform', 'Scaling article production with AI-assisted research and writing in one workflow', 'Freelance SEO writers who need both optimisation and writing assistance on a budget']
) ON CONFLICT (slug) DO NOTHING;

-- 9. Keyword Insights
INSERT INTO tools (
  slug, name, tagline, description,
  logo_url, website_url, affiliate_url,
  tags, pricing_type, pricing_free_tier, pricing_starting_price,
  rating, review_count, featured, trending, editor_pick,
  pros, cons, use_cases
) VALUES (
  'keyword-insights', 'Keyword Insights', 'AI keyword clustering and content planning tool for SEO content strategies',
  'Keyword Insights is a keyword research and clustering tool that uses AI to group large sets of keywords into topical clusters based on search intent and SERP similarity. The core workflow: upload a list of keywords (often thousands exported from Ahrefs or Semrush), and Keyword Insights groups them by the pages that rank for them, identifying which keywords should be targeted on the same page vs separate pages. This prevents cannibalisation and helps content teams build logical site structures. The Search Intent filter classifies keywords as informational, navigational, commercial, or transactional. The Content Planner turns clustered keywords into a full site content plan with page titles and recommended article types. For agencies and in-house SEO teams managing large keyword research projects, Keyword Insights automates the most time-consuming part of the content planning process.',
  'https://www.google.com/s2/favicons?domain=keywordinsights.ai&sz=64',
  'https://keywordinsights.ai', 'https://keywordinsights.ai',
  ARRAY['seo-marketing', 'research'],
  'paid', false, 58.00,
  4.4, 290, false, true, false,
  ARRAY['AI clustering handles thousands of keywords in minutes instead of hours of manual grouping', 'SERP-based clustering is more accurate than simple semantic clustering - matches how Google actually groups topics', 'Search intent classification speeds up content planning and brief creation', 'Content Planner outputs a full site structure from a keyword research export'],
  ARRAY['Requires an existing keyword list from a tool like Ahrefs or Semrush - not a standalone keyword discovery tool', 'Less useful for small sites with limited keyword scope', 'Occasional clustering errors require manual review, especially on ambiguous keywords'],
  ARRAY['Clustering 10,000+ keyword exports into a manageable content plan for large sites', 'Preventing keyword cannibalisation by identifying which terms should live on the same page', 'Building a full site content architecture from a keyword research project']
) ON CONFLICT (slug) DO NOTHING;

-- 10. Diib
INSERT INTO tools (
  slug, name, tagline, description,
  logo_url, website_url, affiliate_url,
  tags, pricing_type, pricing_free_tier, pricing_starting_price,
  rating, review_count, featured, trending, editor_pick,
  pros, cons, use_cases
) VALUES (
  'diib', 'Diib', 'AI SEO tool for small businesses with automated daily growth recommendations',
  'Diib is an AI-powered SEO tool designed specifically for small business owners who lack technical SEO expertise. It connects to Google Analytics and Search Console and produces a daily Answer Engine output - a prioritised list of growth opportunities specific to your site, not generic advice. The recommendations cover keyword gaps, page speed issues, broken links, missing meta descriptions, and social media opportunities. The Weekly Growth Summary tracks progress against a personalised benchmark. Diib benchmarks your site against similar businesses in your industry, which is particularly useful for small business owners trying to understand how they compare without an SEO agency. The interface is deliberately non-technical - it explains what to do and why without assuming familiarity with SEO concepts. For small business owners who want actionable SEO guidance without a specialist or expensive agency, Diib provides accessible AI-driven recommendations at a fraction of the cost.',
  'https://www.google.com/s2/favicons?domain=diib.com&sz=64',
  'https://diib.com', 'https://diib.com',
  ARRAY['seo-marketing', 'business-intelligence'],
  'freemium', true, 0.00,
  4.1, 640, false, false, false,
  ARRAY['Daily prioritised recommendations make SEO actionable without technical expertise', 'Industry benchmarking shows how your site compares to similar businesses', 'Free tier connects to Google Analytics and provides basic growth opportunities', 'Non-technical interface is accessible to small business owners without SEO backgrounds'],
  ARRAY['Recommendation depth is shallower than professional SEO tools like Semrush or Ahrefs', 'Less useful for larger sites or experienced SEOs who need detailed technical analysis', 'Some recommendations are generic and require verification against current best practices'],
  ARRAY['Small business owners managing their own SEO without an agency or specialist', 'Getting a prioritised daily action list without interpreting raw SEO data', 'Benchmarking site performance against industry competitors for context']
) ON CONFLICT (slug) DO NOTHING;
