-- tools-batch-21.sql
-- 10 new tools: DB 232 → 242
-- Legal AI and document management tools
-- ON CONFLICT (slug) DO NOTHING (idempotent)

INSERT INTO tools (slug, name, tagline, description, logo_url, website_url, affiliate_url, tags, pricing_type, pricing_free_tier, pricing_starting_price, rating, review_count, featured, trending, editor_pick, pros, cons, use_cases)
VALUES

-- 1. Harvey AI
('harvey-ai', 'Harvey', 'AI platform for law firms and legal teams with deep legal domain expertise',
'Harvey is an enterprise AI platform built specifically for legal professionals at law firms and corporate legal departments. Unlike general-purpose AI assistants, Harvey is trained on legal data and understands contract language, case law, and regulatory frameworks at a level that general models often miss. Law firms use Harvey for contract review and due diligence, legal research and case preparation, document drafting, and regulatory compliance analysis. The platform processes large document sets, extracts key clauses, and surfaces relevant precedents at a speed that would take associates hours to match manually. Enterprise security standards are central to the platform design, with data isolation and audit logging built in for regulated environments. Harvey is enterprise-only with custom pricing based on firm size and usage volume. For large law firms and corporate legal departments handling significant document volumes, Harvey delivers measurable time savings on routine legal work and frees senior attorneys for higher-value strategic analysis that requires human judgment.',
'https://www.google.com/s2/favicons?domain=harvey.ai&sz=64',
'https://harvey.ai', 'https://harvey.ai',
ARRAY['legal-ai', 'writing-ai'], 'paid', false, 99.00, 4.5, 650, false, true, false,
ARRAY['Built specifically for legal workflows and trained on legal data', 'Processes large document sets for due diligence and contract review', 'Enterprise-grade security with data isolation and audit logging', 'Understands legal terminology better than general-purpose AI tools'],
ARRAY['Enterprise-only - not accessible for solo attorneys or small firms', 'Requires sales engagement and onboarding - no self-serve access', 'Higher cost than general-purpose AI alternatives'],
ARRAY['Contract review and due diligence for law firms', 'Legal research and case preparation at scale', 'Document drafting and regulatory compliance analysis']),

-- 2. Clio
('clio', 'Clio', 'Cloud-based legal practice management platform for law firms of all sizes',
'Clio is the leading cloud-based legal practice management platform, used by over 150,000 legal professionals across 90 countries to run their firms. The platform covers the operational side of legal practice: client intake, matter management, time tracking, billing, document storage, and client communications. Clio Duo, the AI layer, helps attorneys draft client communications, summarise case notes, pull relevant matter details during calls, and automate routine documentation tasks. Unlike specialised legal AI tools focused purely on contract review or legal research, Clio is the operational hub that integrates with court filing systems, payment processors, and calendar tools. The platform is particularly well-suited to solo practitioners and small to mid-size law firms who need one system to manage both the legal and administrative sides of their practice. Plans start at $49 per user per month. The AI features are included in higher-tier plans and continue to expand with each product update, making Clio an evolving AI platform rather than a static tool.',
'https://www.google.com/s2/favicons?domain=clio.com&sz=64',
'https://clio.com', 'https://clio.com',
ARRAY['legal-ai', 'productivity'], 'paid', false, 49.00, 4.6, 2840, false, false, false,
ARRAY['All-in-one platform covers billing, cases, and client management', 'Used by 150,000+ legal professionals globally across 90 countries', 'Integrates with 200+ tools including court filing and payment systems', 'Clio Duo AI handles routine drafting and case note summarisation'],
ARRAY['AI features require higher-tier plan beyond the entry level', 'Can feel complex for solo practitioners with simpler practice needs', 'More practice management than deep legal AI research capability'],
ARRAY['Law firm operations, billing, and client matter management', 'AI-assisted client communications and case note summarisation', 'All-in-one practice management for solo and small firm attorneys']),

-- 3. Lexis AI
('lexis-ai', 'Lexis AI', 'AI-powered legal research built into LexisNexis - the world''s largest legal database',
'Lexis AI is LexisNexis''s AI legal research platform, integrating large language model capabilities directly into the world''s largest legal database. For legal professionals who rely on Lexis for case law, statutes, and secondary sources, Lexis AI adds conversational research, brief analysis, and drafting assistance within the platform they already use. The AI retrieves relevant case law from natural language queries, summarises lengthy opinions, and drafts argument sections grounded in cited precedents. Because it draws from LexisNexis''s proprietary database rather than the public web, Lexis AI''s research is more reliable for jurisdiction-specific legal work than general-purpose AI tools. Hallucination risk on legal citations is significantly lower when the AI retrieves from a controlled, authoritative legal database rather than generating citations from training data. Access requires a LexisNexis subscription, with pricing varying significantly by firm size and usage tier. For law firms and legal researchers already on the Lexis platform, the AI features represent a substantial productivity upgrade to existing research workflows without requiring any change in tools.',
'https://www.google.com/s2/favicons?domain=lexisnexis.com&sz=64',
'https://lexisnexis.com', 'https://lexisnexis.com',
ARRAY['legal-ai', 'research'], 'paid', false, 0.00, 4.4, 1120, false, false, false,
ARRAY['Built on the world''s largest legal database - not public web searches', 'Lower hallucination risk for legal citations than general AI tools', 'Conversational research queries within existing LexisNexis workflow', 'Trusted by top law firms and legal departments globally'],
ARRAY['Requires existing LexisNexis subscription - not a standalone tool', 'Premium pricing is not accessible for small firms or individuals', 'Less useful for non-US legal work where database coverage is thinner'],
ARRAY['Case law research and brief preparation for litigators', 'Statutory analysis and regulatory research with authoritative citations', 'AI-assisted legal argument drafting grounded in verifiable sources']),

-- 4. Detangle AI
('detangle-ai', 'Detangle AI', 'Plain-language summaries of legal documents and contracts for non-lawyers',
'Detangle AI is a document simplification tool that translates complex legal documents into plain language, making contracts, terms of service, privacy policies, and legal agreements understandable to non-lawyers. Users upload or paste a legal document and receive a plain-language summary, a breakdown of key clauses, and highlighted sections that deserve particular attention before signing. This makes Detangle valuable both for individuals reviewing contracts and for legal teams explaining complex agreements to clients or business stakeholders without legal training. The free tier covers a limited number of documents per day. Paid plans remove usage limits and add features including contract comparison and priority processing. Detangle does not provide legal advice and positions itself as a document comprehension tool that helps users know the right questions to ask a lawyer, rather than replacing legal counsel entirely. For small business owners, freelancers, and non-legal professionals who regularly encounter contracts they struggle to parse, Detangle provides accessible document clarity without requiring a legal consultation for routine agreement review.',
'https://www.google.com/s2/favicons?domain=detangle.ai&sz=64',
'https://detangle.ai', 'https://detangle.ai',
ARRAY['legal-ai', 'productivity'], 'freemium', true, 9.99, 4.2, 890, false, true, false,
ARRAY['Translates complex legal language into plain English instantly', 'Free tier available for occasional document review without sign-up', 'Highlights clauses that deserve attention before signing', 'Works with any document type including NDAs, leases, and employment contracts'],
ARRAY['Not a replacement for professional legal advice on complex matters', 'Accuracy varies on highly technical or jurisdiction-specific language', 'Free tier limits daily document volume'],
ARRAY['Contract review for freelancers and small business owners', 'Understanding terms of service and privacy policies before signing up', 'Client-facing plain-language summaries of complex legal agreements']),

-- 5. Spellbook AI
('spellbook-ai', 'Spellbook', 'AI contract drafting and review for lawyers - works directly inside Microsoft Word',
'Spellbook is an AI contract drafting and review assistant built for legal professionals, operating as a Microsoft Word add-in that brings AI capabilities directly into the document editing environment lawyers already use daily. Built on GPT-4 and trained on commercial contract data, Spellbook suggests missing clauses, flags unusual provisions, explains legal language in plain terms, and drafts new contract sections from a brief description. Unlike general-purpose AI writing tools, Spellbook understands commercial contract norms and legal drafting conventions, making its clause suggestions appropriate for professional legal work. The Word integration means lawyers can review and draft contracts without switching applications, preserving existing workflows while adding AI assistance. Law firms using Spellbook report 50 to 70 percent reductions in routine contract task time, particularly on first-draft creation and playbook review. Pricing starts at $99 per user per month. Spellbook is primarily used by commercial lawyers and in-house legal teams handling high volumes of contract work who want AI that fits into existing Microsoft Office workflows.',
'https://www.google.com/s2/favicons?domain=spellbook.legal&sz=64',
'https://spellbook.legal', 'https://spellbook.legal',
ARRAY['legal-ai', 'writing-ai'], 'paid', false, 99.00, 4.4, 760, false, true, false,
ARRAY['Works as a Word add-in - fits directly into existing lawyer workflows', 'Trained on commercial contract data for legally appropriate suggestions', 'Flags unusual provisions and suggests missing standard clauses', 'Drafts new clause language from a plain-text description'],
ARRAY['Requires Microsoft Word - no standalone web editor available', 'Primarily focused on commercial contracts, less useful for litigation work', 'Higher price point than general-purpose AI writing tools'],
ARRAY['Commercial contract review and first-draft acceleration', 'Clause drafting and amendment generation for transactional lawyers', 'In-house legal team contract review at scale across business units']),

-- 6. Zuva
('zuva', 'Zuva', 'AI contract intelligence for bulk document analysis and structured clause extraction',
'Zuva is an AI contract intelligence platform designed for high-volume contract analysis, derived from the technology behind Kira Systems. Zuva reads and extracts structured data from unstructured contract documents, identifying parties, dates, obligations, termination rights, and custom clauses across large contract portfolios. The platform is used by legal teams, corporate development departments, and legal technology firms that need to analyse thousands of contracts during M&A due diligence, lease portfolio reviews, or regulatory audits. Zuva offers a self-serve API for developers integrating contract intelligence into legal workflows, as well as an enterprise platform for non-technical legal teams. The AI models are pre-trained on commercial legal language and can be fine-tuned for specific document types and custom clause definitions. Pricing is enterprise and usage-based, varying by document volume. For organisations managing large contract portfolios under time pressure, Zuva reduces manual review time by 50 to 80 percent on extraction-heavy legal work, with accuracy levels that hold up under legal scrutiny.',
'https://www.google.com/s2/favicons?domain=zuva.ai&sz=64',
'https://zuva.ai', 'https://zuva.ai',
ARRAY['legal-ai', 'productivity'], 'paid', false, 0.00, 4.3, 480, false, false, false,
ARRAY['Pre-trained on commercial legal language for high extraction accuracy', 'API access for integrating contract intelligence into legal platforms', 'Handles bulk contract analysis at scale for M&A and portfolio reviews', 'Custom model training for specific document types and clause definitions'],
ARRAY['Enterprise pricing - not accessible for smaller firms or individual users', 'Primarily an extraction tool, less useful for drafting or research tasks', 'Requires technical setup for API integrations into existing systems'],
ARRAY['M&A due diligence with large contract volumes and tight deadlines', 'Lease portfolio analysis and regulatory compliance audits', 'Contract data extraction for legal operations and CLM system ingestion']),

-- 7. ContractBook
('contractbook', 'ContractBook', 'AI-native contract management connecting creation, signing, and obligation tracking',
'ContractBook is a contract management platform that connects creation, signing, and storage in a single workflow with AI-powered data extraction. The platform uses AI to analyse uploaded contracts, populate a structured database of obligations, renewal dates, and counterparties, and send automated reminders for upcoming contract milestones. Unlike basic document storage, ContractBook builds a live contract database that teams can query and act on without manually reading through individual documents. The free tier supports unlimited contracts for up to 3 users, making it accessible for early-stage companies and small teams. Paid plans from $199 per month add workflow automation, advanced reporting, audit trails, and API access for larger operations teams. ContractBook is used by operations teams, finance departments, and in-house legal teams at companies managing 50 to 5,000 active contracts. The platform is particularly well-suited to companies that have outgrown spreadsheet-based contract tracking but do not need the full complexity of enterprise CLM platforms like Ironclad.',
'https://www.google.com/s2/favicons?domain=contractbook.com&sz=64',
'https://contractbook.com', 'https://contractbook.com',
ARRAY['legal-ai', 'productivity'], 'freemium', true, 199.00, 4.3, 920, false, false, false,
ARRAY['Free tier covers unlimited contracts for up to 3 users', 'AI extracts key dates and obligations from uploaded contracts automatically', 'Automated reminders for renewal dates and upcoming contract milestones', 'Bridges the gap between basic storage and enterprise CLM complexity'],
ARRAY['Advanced workflow automation requires higher-tier paid plans', 'Less powerful than enterprise CLM platforms for complex multi-team workflows', 'AI extraction accuracy varies by contract type and complexity'],
ARRAY['Company-wide contract database for operations and finance teams', 'Automated renewal tracking and obligation management at scale', 'Mid-market contract management without the cost of enterprise CLM']),

-- 8. DocuSign AI
('docusign-ai', 'DocuSign IAM', 'AI agreement intelligence on top of the world''s leading e-signature platform',
'DocuSign is the global standard for e-signatures, trusted by over one million customers across 180 countries. DocuSign IAM (Intelligent Agreement Management) extends the platform with AI-powered contract intelligence, adding obligation extraction, renewal tracking, and automated agreement analysis to the signing workflow that organisations already rely on. For companies that use DocuSign for e-signatures, the IAM features unlock contract data previously locked in signed PDFs, extracting payment terms, renewal clauses, and obligations into a structured, searchable format. DocuSign IAM includes pre-built AI models for specific document types including NDAs, employment agreements, and sales contracts. The platform integrates natively with Salesforce, Microsoft 365, SAP, and major HR platforms. Basic e-signature plans start at $15 per month. The AI features are available on Business Pro and higher plans. DocuSign''s breadth of integrations and global adoption make it the practical default for organisations adding AI to a signing workflow that already runs on DocuSign.',
'https://www.google.com/s2/favicons?domain=docusign.com&sz=64',
'https://docusign.com', 'https://docusign.com',
ARRAY['legal-ai', 'productivity'], 'freemium', true, 15.00, 4.5, 4120, false, false, false,
ARRAY['Global market leader with over 1 million customers and 180 countries covered', 'AI extracts structured data from executed agreements at scale', 'Native integrations with Salesforce, Microsoft 365, and major enterprise systems', 'Pre-built AI models for common document types including NDAs and employment agreements'],
ARRAY['AI features require Business Pro or higher plan - not included in base tier', 'More expensive than newer e-signature tools for basic signing use cases', 'Agreement intelligence features are still maturing compared to CLM-first platforms'],
ARRAY['E-signature collection with AI contract data extraction for existing DocuSign users', 'Agreement obligation tracking and renewal management at enterprise scale', 'Signing workflows with native Salesforce and Microsoft 365 integration']),

-- 9. Adobe Sign
('adobe-sign', 'Adobe Acrobat Sign', 'AI-enhanced e-signatures integrated with Adobe PDF editing and document creation tools',
'Adobe Acrobat Sign is Adobe''s enterprise e-signature and agreement management solution, integrated directly into the Acrobat PDF editing workflow that businesses rely on for document creation. The AI capabilities, powered by Adobe Sensei, include automatic form field detection, signature placement intelligence, and document summarisation through the Acrobat AI Assistant. For organisations that create documents in Acrobat and collect signatures in the same ecosystem, Adobe Sign provides the tightest integration between document creation and signature collection. The platform handles routing, tracking, and archiving of signed documents within the Adobe Document Cloud environment. Individual plans start at $16.99 per month. Team and enterprise tiers include advanced workflow automation, custom branding, and government compliance certifications. Adobe Sign is particularly strong for document-intensive industries where the entire creation-to-signature workflow lives within the Adobe ecosystem, including legal, financial services, and government organisations.',
'https://www.google.com/s2/favicons?domain=adobe.com&sz=64',
'https://acrobat.adobe.com', 'https://acrobat.adobe.com',
ARRAY['legal-ai', 'productivity'], 'paid', false, 16.99, 4.3, 2680, false, false, false,
ARRAY['Tight integration with Acrobat PDF editing for document-to-signature workflows', 'AI form field detection reduces manual signature placement work', 'Government-grade compliance certifications for regulated industries', 'Single Adobe subscription covers PDF creation and e-signature collection'],
ARRAY['More expensive than standalone e-signature tools like DocuSign basic plans', 'Adobe ecosystem lock-in limits flexibility for cross-platform workflows', 'AI features less advanced than purpose-built contract intelligence platforms'],
ARRAY['E-signature collection integrated with Acrobat PDF creation workflows', 'Regulated industry document signing with strict compliance requirements', 'Enterprise agreement management within the Adobe Document Cloud ecosystem']),

-- 10. Ironclad
('ironclad', 'Ironclad', 'Enterprise contract lifecycle management for legal and business operations teams',
'Ironclad is an enterprise contract lifecycle management (CLM) platform that covers every stage of the contract process from request and drafting through negotiation, execution, and ongoing obligation management. The AI layer assists with clause suggestion, risk flagging, contract summarisation, and automated obligation extraction from executed agreements. Unlike DocuSign or Adobe Sign, which are primarily e-signature platforms with added AI features, Ironclad is built specifically for contract operations teams and designed to replace email chains, shared drives, and spreadsheets as the system of record for all commercial agreements. Legal and business operations teams at enterprise companies use Ironclad to manage vendor agreements, customer contracts, NDAs, and employment agreements in a single platform with full audit trails and approval workflows. Pricing is enterprise and custom. For organisations where contract operations are a significant business function, Ironclad provides the most complete solution from initial contract request through ongoing obligation tracking and renewal management. The platform integrates with Salesforce, Slack, Google Workspace, and major document editing tools.',
'https://www.google.com/s2/favicons?domain=ironcladapp.com&sz=64',
'https://ironcladapp.com', 'https://ironcladapp.com',
ARRAY['legal-ai', 'productivity'], 'paid', false, 0.00, 4.5, 870, false, false, false,
ARRAY['Full CLM from contract request through obligation tracking - not just e-signatures', 'AI risk flagging and clause suggestions throughout the negotiation workflow', 'Purpose-built for contract operations teams with complex approval routing', 'Integrates with Salesforce, Slack, and major enterprise productivity systems'],
ARRAY['Enterprise-only with custom pricing - no self-serve for smaller teams', 'Significant implementation and onboarding time required before value is realised', 'Overkill for companies with simple or low-volume contract needs'],
ARRAY['Enterprise contract lifecycle management for legal operations teams', 'Vendor agreement and customer contract management at scale', 'Replacing email and shared drives as the company-wide contract system of record'])

ON CONFLICT (slug) DO NOTHING;
