-- tools-batch-40.sql
-- 10 specialized AI writing and content creation tools
-- Run AFTER tools-batch-39.sql is confirmed in DB
-- All slugs verified absent from tools-batch-1 through tools-batch-39

INSERT INTO tools (
  slug, name, tagline, description,
  logo_url, website_url, affiliate_url,
  tags, pricing_type, pricing_free_tier, pricing_starting_price,
  rating, review_count, featured, trending, editor_pick,
  pros, cons, use_cases
) VALUES

('sudowrite', 'Sudowrite', 'AI writing partner built for fiction novelists and storytellers',
 'Sudowrite is an AI writing tool built specifically for fiction writers, not business content. Where general AI writers optimize for persuasion and clarity, Sudowrite optimizes for narrative momentum, sensory detail, and prose style. The core features are organized around the novel-writing process: Describe generates sensory descriptions of scenes and characters from a few words; Brainstorm generates plot options when you are stuck; Rewrite shows you 8 different ways to rewrite any passage with different tones and styles; and Write continues your story with AI-generated text that matches your established voice. The Story Engine feature breaks a novel outline into scenes and drafts each one in sequence. Sudowrite trains on literary fiction and has a notably different output quality from general AI tools when it comes to metaphor, subtext, and scene-setting. Writers using Sudowrite typically do not replace their prose with AI output but use it to break through blocks, explore alternatives, and accelerate first drafts. The tool is used by published novelists, screenwriters, and serious fiction hobbyists who want AI assistance without producing generic corporate-sounding content.',
 'https://www.google.com/s2/favicons?domain=sudowrite.com&sz=64',
 'https://sudowrite.com', 'https://sudowrite.com',
 ARRAY['writing', 'ai-assistants'],
 'paid', false, 19.00,
 4.5, 734, false, true, false,
 ARRAY['Purpose-built for fiction - not business content', 'Describe and Brainstorm features unlock creative blocks', 'Story Engine drafts novel scenes in sequence', 'Output quality preserves literary voice better than general AI'],
 ARRAY['Monthly word limits can be restrictive for prolific writers', 'Not useful for non-fiction or business writing', 'Requires some prompt craft to get best results'],
 ARRAY['Drafting fiction novels faster without losing narrative voice', 'Breaking through writers block with scene alternatives', 'Exploring different prose styles before committing to one']),

('hypotenuse-ai', 'Hypotenuse AI', 'AI copywriting platform built for e-commerce product descriptions at scale',
 'Hypotenuse AI is an AI content platform built around a specific e-commerce problem: writing product descriptions, category pages, and marketing copy for large catalogs at scale. A retailer with 10,000 SKUs cannot write unique descriptions for each product manually, and generic descriptions hurt both SEO and conversion rates. Hypotenuse connects to product data via CSV or API, applies brand guidelines and tone-of-voice rules, and generates unique descriptions for each SKU automatically. The content workflow lets teams review, edit, and approve AI drafts in bulk rather than one at a time. For SEO, Hypotenuse generates keyword-rich meta descriptions and category page copy alongside product descriptions. The blog writing feature generates long-form articles from a topic brief, though the core value is the product catalog use case. Content is trainable to match your brand voice using existing approved copy as examples. Hypotenuse is used by e-commerce brands, marketplace sellers, and digital agencies managing product content for retail clients. Pricing scales with content volume, making it cost-effective for large catalogs and cost-prohibitive for occasional users.',
 'https://www.google.com/s2/favicons?domain=hypotenuse.ai&sz=64',
 'https://hypotenuse.ai', 'https://hypotenuse.ai',
 ARRAY['writing', 'seo-marketing'],
 'paid', false, 24.00,
 4.4, 512, false, false, false,
 ARRAY['Bulk product description generation from CSV or API', 'Brand voice training on existing approved copy', 'SEO meta descriptions generated alongside product copy', 'Batch review and approval workflow for large catalogs'],
 ARRAY['Pricing model favors high-volume users - expensive for small catalogs', 'Best results require brand voice examples and configuration time', 'Blog output quality is average compared to dedicated long-form tools'],
 ARRAY['Writing unique product descriptions for 1000+ SKU e-commerce catalogs', 'Generating SEO-optimized category page copy at scale', 'Maintaining brand voice consistency across large product ranges']),

('wordtune', 'Wordtune', 'AI writing companion that rewrites and improves your text while preserving your meaning',
 'Wordtune is an AI writing enhancement tool focused on making existing writing better rather than generating content from scratch. The core feature is rewriting: paste any sentence or paragraph and Wordtune suggests multiple rewrites with different tones (formal, casual, shorter, longer, more fluent). Unlike Grammarly, which corrects grammar and style rules, Wordtune understands meaning and rewrites substantively - it can shorten a wordy paragraph to one clear sentence or expand a brief note into a full explanation. The Chrome extension integrates directly with Google Docs, Gmail, LinkedIn, and any browser text field, making rewrites available in context without switching tabs. Wordtune Read summarizes long articles, reports, and PDFs into key points, useful for researchers and analysts processing large volumes of content. The AI Recommendations feature suggests content to add to incomplete writing, prompting you with facts, examples, and statistics relevant to your topic. For professionals who write frequently in a second language, Wordtune is particularly effective at producing fluent, natural-sounding English output from grammatically correct but stilted source text. The free tier is genuinely useful with a daily rewrite limit.',
 'https://www.google.com/s2/favicons?domain=wordtune.com&sz=64',
 'https://wordtune.com', 'https://wordtune.com',
 ARRAY['writing', 'ai-assistants'],
 'freemium', true, 9.99,
 4.3, 1847, false, false, false,
 ARRAY['Rewrites preserve meaning while improving clarity and tone', 'Browser extension works inside Gmail, Docs, LinkedIn directly', 'Excellent for non-native English writers', 'Wordtune Read summarizes long documents quickly'],
 ARRAY['Better for editing than generating from scratch', 'Free tier has daily limits that power users hit quickly', 'Suggestions sometimes miss nuanced domain-specific phrasing'],
 ARRAY['Improving email clarity and tone before sending', 'Editing non-native English text to sound fluent and natural', 'Summarizing long reports and articles into key takeaways']),

('simplified', 'Simplified', 'All-in-one AI platform for content creation, design, video, and social media',
 'Simplified is an all-in-one content creation platform that combines AI writing, graphic design, video editing, and social media scheduling in a single interface. The target user is a social media manager or small marketing team that needs to produce content across multiple formats without using five separate tools. The AI writer generates captions, blog posts, ad copy, and email content; the design editor works like Canva with AI-generated templates; the video editor handles short-form clips; and the scheduler publishes to all major social platforms from one queue. What differentiates Simplified from specialized alternatives is the integrated workflow: you can write a LinkedIn post with AI, drop it into a branded graphic template, add a short video clip, and schedule all three formats in one session without leaving the platform. The AI model learns your brand voice and can rewrite content to match your established tone. Simplified is particularly popular with solo founders, freelancers, and creator-economy businesses that need to produce high volumes of content without a dedicated content team. The free plan is generous enough for individuals at low volume.',
 'https://www.google.com/s2/favicons?domain=simplified.com&sz=64',
 'https://simplified.com', 'https://simplified.com',
 ARRAY['writing', 'design', 'productivity'],
 'freemium', true, 12.00,
 4.2, 2134, false, false, false,
 ARRAY['All-in-one: writing, design, video, and scheduling in one platform', 'Generous free plan for individual creators', 'Brand voice learning reduces repetitive prompt work', 'Unified workflow reduces context switching between tools'],
 ARRAY['Jack-of-all-trades depth issue - specialized tools outperform on each function', 'Video editing features are basic compared to dedicated platforms', 'AI output quality is inconsistent across formats'],
 ARRAY['Managing social media content production for multiple platforms solo', 'Creating branded content without separate design and writing tools', 'Building a content pipeline as a solo founder or small creator team']),

('narrato', 'Narrato', 'AI content workspace for content teams managing briefs, writers, and workflows',
 'Narrato is a content operations platform that combines AI content creation with project management and team collaboration features designed for content teams and agencies. Where most AI writing tools focus on individual productivity, Narrato is built for teams: content briefs are generated from target keywords and assigned to writers; AI writing assistance is available inside the editor; completed drafts go through a review and approval workflow; and published content is tracked in a content calendar. The SEO brief generator pulls NLP keyword recommendations, competitor analysis, and search intent data to create structured briefs that writers or AI can follow. Narrato AI can generate first drafts from briefs automatically, reducing the time from brief-to-draft for straightforward content. For content agencies managing 50+ articles per month across multiple clients, Narrato provides the project management layer that Jasper and similar tools lack. Custom brand voice profiles ensure output matches each client tone consistently. The content calendar gives editors visibility across all active content at once. Narrato is not the strongest individual AI writer, but as a workflow platform that keeps content teams organized while reducing manual work, it fills a genuine gap between general AI tools and full CMS platforms.',
 'https://www.google.com/s2/favicons?domain=narrato.io&sz=64',
 'https://narrato.io', 'https://narrato.io',
 ARRAY['writing', 'productivity'],
 'paid', false, 36.00,
 4.3, 318, false, false, false,
 ARRAY['Content brief generator with NLP and competitor analysis', 'Team workflow: brief assignment, review, and approval built in', 'Multiple client brand voice profiles for agencies', 'Content calendar gives editors full pipeline visibility'],
 ARRAY['Steeper learning curve than individual writing tools', 'AI writing quality is comparable but not superior to Jasper or Writesonic', 'Pricing per workspace can be expensive for small teams'],
 ARRAY['Managing content production for agencies with 10+ clients', 'Building repeatable content workflows with brief-to-publish tracking', 'Coordinating distributed writing teams with consistent brand guidelines']),

('longshot-ai', 'LongShot AI', 'AI long-form content generator with built-in fact verification',
 'LongShot AI is a long-form content generation platform that focuses on a problem that most AI writers ignore: factual accuracy. AI-generated articles frequently contain plausible-sounding but incorrect facts, statistics, and citations. LongShot addresses this with a built-in fact-checking feature that verifies claims in generated content against web sources and flags questionable statements before you publish. The long-form workflow starts with a keyword, generates a structured outline, then expands each section with supporting evidence and inline citations. The Blog Co-Pilot mode writes with the user in a back-and-forth conversation rather than generating a full draft at once, allowing for more control over direction and accuracy. Semantic SEO features ensure the content covers related concepts and questions that search engines associate with the target keyword. LongShot is particularly useful for content teams that need to produce authoritative, accurate articles in regulated industries (finance, health, legal) where hallucinated facts carry real risk. The fact-verification layer does not catch everything, but it significantly reduces the editorial review burden compared to unverified AI output.',
 'https://www.google.com/s2/favicons?domain=longshot.ai&sz=64',
 'https://longshot.ai', 'https://longshot.ai',
 ARRAY['writing', 'seo-marketing'],
 'freemium', true, 19.00,
 4.2, 423, false, false, false,
 ARRAY['Built-in fact verification reduces AI hallucination risk', 'Blog Co-Pilot allows conversational control over long-form content', 'Semantic SEO coverage of related concepts and questions', 'Inline citations and source attribution built into output'],
 ARRAY['Fact-checking catches common errors but not all inaccuracies', 'Long-form output still requires editorial review before publish', 'Steeper learning curve than simpler AI writers'],
 ARRAY['Producing factually accurate long-form articles in regulated industries', 'Building SEO content with verified statistics and citations', 'Writing authoritative guides where hallucinated facts carry credibility risk']),

('reword', 'Reword', 'Collaborative AI writing tool that learns from your best articles',
 'Reword is an AI writing assistant built inside a collaborative text editor, designed to learn from your existing published content and write in your established voice rather than a generic AI style. When you add your best articles to Reword, the AI trains on your sentence structure, vocabulary, terminology, and arguments, producing suggestions that sound like you rather than a generic AI writer. The collaborative editor allows multiple team members to work on an article simultaneously, with AI suggestions available inline as you type. Reword is particularly effective for consistent long-form content like newsletters, blog series, and thought leadership pieces where maintaining a distinctive voice across publications matters. The research assistance features pull relevant information from the web and suggest supporting evidence for claims as you write. Reword positions itself against the generic output problem: most AI writers produce recognizable AI prose that audiences have learned to identify. By training on your actual writing, Reword produces AI suggestions that are harder to distinguish from your natural output. The tool is popular with newsletters, independent publications, and content teams that have built an audience around a specific editorial voice.',
 'https://www.google.com/s2/favicons?domain=reword.co&sz=64',
 'https://reword.co', 'https://reword.co',
 ARRAY['writing', 'ai-assistants'],
 'paid', false, 38.00,
 4.4, 187, false, true, false,
 ARRAY['Trains on your actual articles to match your specific writing voice', 'Real-time collaborative editor with inline AI suggestions', 'Research assistance pulls supporting evidence as you write', 'Output sounds distinctly yours rather than generic AI prose'],
 ARRAY['Value compounds over time as AI learns more of your writing', 'Pricing is higher than simpler AI writing tools', 'Best for consistent long-form content - less useful for one-off copy'],
 ARRAY['Writing newsletters and blog series with a consistent distinctive voice', 'Scaling content production without losing editorial identity', 'Training an AI assistant on thought leadership and domain expertise']),

('cohesive-ai', 'Cohesive', 'AI content creation platform with 200+ templates and real-time collaboration',
 'Cohesive is an AI content creation platform that offers 200+ templates covering marketing copy, blog content, social media, email, product descriptions, and business documents. The visual editor combines AI generation with design elements, allowing teams to produce formatted content like landing page copy, LinkedIn posts, and ad creative in a single interface rather than moving between a writer and a design tool. The real-time collaboration feature allows multiple team members to work on content simultaneously, with comments and version history similar to Google Docs. Cohesive includes brand voice customization that applies your tone guidelines across all template outputs, ensuring consistency when multiple people use AI assistance. The translation feature generates localized content in 50+ languages from a single source, useful for businesses with international audiences. Cohesive positions itself as an accessible alternative to Jasper and Writesonic for teams that need template coverage across many content types without a high per-seat cost. The free plan is generous, and the team plan pricing is competitive for small marketing teams. Output quality is solid for structured content types but less differentiated for creative long-form work.',
 'https://www.google.com/s2/favicons?domain=cohesive.so&sz=64',
 'https://cohesive.so', 'https://cohesive.so',
 ARRAY['writing', 'productivity'],
 'freemium', true, 16.00,
 4.1, 643, false, false, false,
 ARRAY['200+ templates covering all major content types', 'Real-time collaboration with comments and version history', 'Translation to 50+ languages from a single source draft', 'Generous free plan for individuals and small teams'],
 ARRAY['Output quality is adequate but not best-in-class for specialized use cases', 'Less powerful for creative or nuanced long-form content', 'Template volume creates choice overload for new users'],
 ARRAY['Producing consistent marketing copy across multiple formats and channels', 'Translating content for international audiences from a single source', 'Building a shared AI writing workspace for small marketing teams']),

('writerly-ai', 'Writerly', 'Enterprise AI content platform with governance, approvals, and brand compliance',
 'Writerly is an AI content platform designed for enterprise teams where brand compliance, content governance, and approval workflows are non-negotiable requirements. Most AI writing tools are built for individual productivity; Writerly is built for the compliance requirements of regulated industries and large organizations. The platform includes role-based access controls so different team members can create content but only designated approvers can publish. Brand guardrails prevent AI from generating content that violates brand guidelines, tone rules, or prohibited topics. The audit trail records who created, edited, and approved every piece of content, meeting compliance requirements for regulated industries like financial services, healthcare, and legal. Templates are locked to prevent modification by content creators, ensuring that approved formats are always used. Writerly integrates with enterprise content management systems and marketing platforms via API. For large organizations where ungoverned AI use creates legal or brand risk, Writerly provides the control layer that makes AI content generation organizationally safe. The trade-off is implementation complexity and enterprise pricing that makes it impractical for small teams or startups.',
 'https://www.google.com/s2/favicons?domain=writerly.ai&sz=64',
 'https://writerly.ai', 'https://writerly.ai',
 ARRAY['writing', 'productivity'],
 'paid', false, 0.00,
 4.3, 156, false, false, false,
 ARRAY['Role-based access controls with approval workflows', 'Brand guardrails prevent non-compliant AI output', 'Full audit trail for content creation and approval', 'Purpose-built for regulated industries with compliance requirements'],
 ARRAY['Enterprise-only pricing and implementation timeline', 'Overkill for companies without strict governance requirements', 'Less flexible than consumer AI tools by design'],
 ARRAY['Deploying AI content creation in regulated industries like finance or healthcare', 'Maintaining brand compliance across large distributed content teams', 'Building AI content workflows with audit trails for compliance requirements']),

('rapidely', 'Rapidely', 'AI social media content generator with monthly calendar planning',
 'Rapidely is an AI-powered social media content platform focused on helping small businesses and solopreneurs maintain a consistent social media presence without hiring a social media manager. The key feature is the monthly content calendar: you input your business type, audience, and content pillars, and Rapidely generates a full month of social media posts, captions, and hashtags in a single workflow. Each post is tailored to the specific platform (Instagram, LinkedIn, Facebook, TikTok, Pinterest) with platform-appropriate length and format. The carousel post generator creates multi-slide Instagram and LinkedIn carousels from a topic, with both the layout concept and caption copy generated automatically. Rapidely also includes a trend-based content suggestion feature that identifies trending topics in your industry and suggests how to create content around them before the trend peaks. The scheduling integration publishes directly to social platforms from the calendar. For small businesses that struggle with the "what to post today" problem, Rapidely solves planning paralysis by generating a full content strategy upfront rather than requiring fresh ideas every day. The pricing is accessible for small businesses at well under $30 per month.',
 'https://www.google.com/s2/favicons?domain=rapidely.com&sz=64',
 'https://rapidely.com', 'https://rapidely.com',
 ARRAY['writing', 'seo-marketing'],
 'paid', false, 9.00,
 4.2, 298, false, true, false,
 ARRAY['Monthly content calendar generates 30 days of posts in one session', 'Platform-specific optimization for Instagram, LinkedIn, TikTok, and more', 'Carousel post generator creates multi-slide content automatically', 'Trend spotting suggests timely content before peak interest'],
 ARRAY['Output quality can be generic without sufficient brand customization', 'Best for small business use cases - not enterprise social media', 'Scheduling features are basic compared to dedicated tools like Buffer or Hootsuite'],
 ARRAY['Planning a full month of social media content in a single session', 'Creating platform-specific carousel posts for Instagram and LinkedIn', 'Maintaining consistent social media presence without a dedicated content team'])

ON CONFLICT (slug) DO NOTHING;
