-- tools-batch-20.sql
-- 10 new tools: DB 222 → 232
-- ON CONFLICT (slug) DO NOTHING (idempotent)

INSERT INTO tools (slug, name, tagline, description, logo_url, website_url, affiliate_url, tags, pricing_type, pricing_free_tier, pricing_starting_price, rating, review_count, featured, trending, editor_pick, pros, cons, use_cases)
VALUES

-- 1. Humanize AI
('humanize-ai', 'Humanize AI', 'Transform AI-generated text into natural, undetectable human writing', 'Humanize AI is a text transformation tool that rewrites AI-generated content to make it sound more naturally human - adjusting sentence rhythm, word choice, structural variety, and stylistic patterns that AI detectors use to identify machine-generated text. The tool is used by content teams, students, and professionals who use AI writing tools but need their final output to pass AI detection checks or simply read more naturally. Beyond detection avoidance, Humanize AI improves the quality of AI output by removing the repetitive patterns and overly formal phrasing that characterise first-draft AI text. Multiple rewriting modes allow users to choose the level of transformation from light editing to complete rewrite. The tool processes text in seconds and offers a free tier for limited daily use. Paid plans from $9.99/mo unlock higher word limits and batch processing.', 'https://www.google.com/s2/favicons?domain=humanizeai.pro&sz=64', 'https://humanizeai.pro', 'https://humanizeai.pro', ARRAY['writing-ai', 'productivity'], 'freemium', true, 9.99, 4.1, 2340, false, true, false, ARRAY['Multiple rewriting modes from light edit to full rewrite', 'Processes text in seconds with instant output', 'Free tier available for daily light use', 'Improves natural flow beyond just detection avoidance'], ARRAY['Output quality varies by input quality', 'Not a substitute for human editorial review', 'Heavy rewriting can lose specific technical accuracy'], ARRAY['Rewriting AI-generated content for natural readability', 'Improving AI first drafts before publishing', 'Making AI-assisted content pass editorial quality checks']),

-- 2. Writesonic Sonic Editor
('writesonic', 'Writesonic', 'AI writing platform with real-time web search and brand voice for content teams', 'Writesonic is an AI writing platform that combines content generation with real-time web search, making it one of the few writing tools whose output is grounded in current information rather than training data alone. The Sonic Editor integrates AI generation, research, and editing into a single long-form document workflow. Its Brand Voice feature trains on existing content samples to match a specific tone and style, maintaining consistency across all generated content. Writesonic covers the full content spectrum: blog posts, landing pages, product descriptions, ad copy, social posts, and email sequences. The AI Article Writer can produce a complete, SEO-optimised 1500-word article from a keyword in minutes, including real citations from current sources. Chatsonic, the conversational AI feature, offers similar capabilities to ChatGPT with the addition of real-time web access. Plans start at $16/mo.', 'https://www.google.com/s2/favicons?domain=writesonic.com&sz=64', 'https://writesonic.com', 'https://writesonic.com', ARRAY['writing-ai', 'seo-marketing'], 'freemium', true, 16.00, 4.3, 3890, false, false, false, ARRAY['Real-time web search grounds content in current information', 'Brand Voice feature for consistent tone across output', 'Full content type coverage from blogs to ad copy', 'SEO-optimised article generation from a keyword'], ARRAY['Output needs editing - not publish-ready without review', 'Interface can feel complex for new users', 'Real-time search adds latency to generation'], ARRAY['SEO blog content with current research citations', 'Ad copy and landing page variation testing', 'Brand-consistent content at scale for marketing teams']),

-- 3. Rytr
('rytr', 'Rytr', 'Budget-friendly AI writing assistant for fast first-draft content across 40+ use cases', 'Rytr is an affordable AI writing tool covering 40+ content use cases including blog posts, emails, social media captions, product descriptions, interview questions, and more. It is not the most capable AI writing tool available, but it is one of the most cost-effective options for individuals and small teams who need AI writing assistance without a large budget. The interface is simple: select a use case, provide a brief, and receive multiple variants to choose from. Rytr supports 30+ languages, making it practical for multilingual content teams. The Unlimited plan at $29/mo removes word generation limits entirely, making it one of the best value unlimited AI writing tools in the market. The free tier covers 10,000 characters per month - enough for regular light use.', 'https://www.google.com/s2/favicons?domain=rytr.me&sz=64', 'https://rytr.me', 'https://rytr.me', ARRAY['writing-ai'], 'freemium', true, 9.00, 4.1, 2760, false, false, false, ARRAY['Most affordable unlimited writing plan in category at $29/mo', 'Generous free tier at 10,000 characters/month', '40+ use cases covering most content types', '30+ language support for multilingual teams'], ARRAY['Output quality lower than Jasper or Copy.ai for complex content', 'Limited customisation compared to premium tools', 'Not suitable for long-form content that requires deep research'], ARRAY['Budget-constrained content teams needing AI assistance', 'Social media captions and short-form copy at volume', 'Multilingual content production for international markets']),

-- 4. Copy.ai workflows
('copy-ai', 'Copy.ai', 'Go-to-market AI platform with automated content workflows and research pipelines', 'Copy.ai is a go-to-market platform that extends beyond AI copywriting to cover full content workflows. Its Workflow feature connects research, content generation, and publishing steps into automated pipelines - a user can define a workflow that takes a product name, pulls competitor information, generates multiple content variants, and formats output for publishing, all without manual intervention at each step. The infobase feature allows teams to store brand guidelines, target audience profiles, and product information that automatically informs all generated content. Copy.ai covers the marketing content spectrum: blog posts, email sequences, social media content, ad copy, sales playbooks, and product descriptions. It is better suited to teams with defined content processes than individual writers looking for a simple AI assistant. Plans start at $49/mo.', 'https://www.google.com/s2/favicons?domain=copy.ai&sz=64', 'https://www.copy.ai', 'https://www.copy.ai', ARRAY['writing-ai', 'automation'], 'freemium', true, 49.00, 4.3, 4120, false, false, false, ARRAY['Workflow automation for end-to-end content pipelines', 'Infobase stores brand context for consistent output', 'Covers full GTM content spectrum from research to copy', 'Strong for teams with defined content processes'], ARRAY['Higher price point than simpler writing tools', 'Workflow setup requires time investment upfront', 'Overkill for individual writers needing occasional AI help'], ARRAY['Automated content pipelines for marketing teams', 'Consistent brand-voice content at scale', 'Go-to-market content from research through to copy']),

-- 5. Beautiful AI
('beautiful-ai', 'Beautiful.ai', 'AI presentation builder that designs slides automatically as you add content', 'Beautiful.ai is a presentation tool that applies design intelligence automatically - as users add content, the AI adjusts layouts, spacing, typography, and visual hierarchy to maintain professional presentation design standards without manual formatting. The Smart Slide feature selects the optimal layout for any content type (lists, comparisons, timelines, org charts, data tables) automatically. This removes the most time-consuming part of slide creation: making the design look right. Beautiful.ai includes a library of pre-designed templates and a brand kit system for maintaining consistent styling across an organisation''s presentations. The tool is particularly useful for teams producing a high volume of internal presentations where design consistency matters but design skill is variable. Team plans allow shared brand kits and collaborative editing. Plans from $12/mo.', 'https://www.google.com/s2/favicons?domain=beautiful.ai&sz=64', 'https://www.beautiful.ai', 'https://www.beautiful.ai', ARRAY['productivity', 'design'], 'freemium', true, 12.00, 4.3, 2140, false, false, false, ARRAY['Auto-design adjusts layouts as content is added', 'Smart Slide selects optimal layout per content type', 'Brand kit ensures consistency across team presentations', 'Faster than PowerPoint for non-designers'], ARRAY['Less design freedom than PowerPoint for custom layouts', 'Template range smaller than Canva', 'Export to PowerPoint loses some design fidelity'], ARRAY['Internal business presentations and reports', 'Sales decks with consistent brand styling', 'Fast presentation creation for non-designer teams']),

-- 6. Frase
('frase', 'Frase', 'AI SEO tool that generates research-backed content briefs and optimises articles for ranking', 'Frase is an AI-powered SEO and content tool that combines research, brief generation, and content optimisation into a single workflow. The research phase analyses the top-ranking pages for any target keyword and generates a structured content brief with recommended headings, topics to cover, questions to answer, and word count targets. The writing phase provides an AI editor that generates content based on the brief and scores it in real time against the top-ranking competitors. Frase''s main advantage over tools like Surfer SEO is its tighter integration between research and writing - users move from keyword to brief to draft within a single tool rather than switching between platforms. For content teams working on SEO-driven articles, Frase reduces research and brief creation time from hours to minutes. Plans start at $44.99/mo.', 'https://www.google.com/s2/favicons?domain=frase.io&sz=64', 'https://www.frase.io', 'https://www.frase.io', ARRAY['seo-marketing', 'writing-ai'], 'paid', false, 44.99, 4.3, 2340, false, false, false, ARRAY['Combines research, brief generation, and writing in one tool', 'Real-time content scoring against top-ranking competitors', 'Tighter research-to-writing workflow than Surfer SEO', 'Question research identifies what searchers actually want to know'], ARRAY['No free tier - paid from first use', 'Content quality lower than dedicated AI writing tools for long-form', 'Less comprehensive keyword research than Semrush or Ahrefs'], ARRAY['SEO content briefs and research for writers', 'Article optimisation and competitive gap analysis', 'Content team workflow from keyword to drafted article']),

-- 7. Riverside FM
('riverside', 'Riverside', 'Professional remote recording platform with AI editing and 4K video quality for podcasters', 'Riverside is a remote recording platform designed for professional podcast and video production. Unlike Zoom or Google Meet, Riverside records each participant locally and uploads the high-quality file after the session, eliminating the compression artefacts and quality degradation of streaming video recording. The result is studio-quality audio and up to 4K video from any location with a reasonable internet connection. The AI editing suite adds automatic transcript generation, speaker diarisation, clip creation, and noise reduction to the recording workflow. Magic Clips identifies the most shareable moments from a recording and generates short-form clips automatically for social media distribution. For podcasters and video creators who need to maintain production quality while recording remote guests, Riverside removes the primary technical constraint. Plans from $15/mo.', 'https://www.google.com/s2/favicons?domain=riverside.fm&sz=64', 'https://riverside.fm', 'https://riverside.fm', ARRAY['audio-ai', 'video-ai'], 'freemium', true, 15.00, 4.5, 3120, false, false, false, ARRAY['Local recording eliminates streaming compression artefacts', 'Up to 4K video quality from remote recording sessions', 'Magic Clips auto-generates social media clips from recordings', 'AI transcript and speaker diarisation included'], ARRAY['Guests must use Riverside in browser - no native app for guests', 'Upload time for local recordings can be significant on slow connections', 'Pricing can add up for high-volume recording teams'], ARRAY['Professional podcast recording with remote guests', 'Video interview and documentary production', 'Social media clip generation from long-form content']),

-- 8. Podcastle
('podcastle', 'Podcastle', 'AI podcast studio with recording, editing, transcription, and voice cloning in the browser', 'Podcastle is a browser-based podcast production platform that combines recording, editing, transcription, and AI voice tools into a single workflow accessible without software installation. The AI editing features remove filler words, background noise, and silence gaps automatically, handling the most time-consuming parts of podcast post-production without manual editing. The text-based editor lets users edit audio by editing the transcript - delete words from the transcript to cut them from the audio, making editing accessible to users without traditional audio editing experience. Podcastle''s Revoice feature creates a custom AI voice model from a recording sample, allowing users to generate voiceover content in their own voice without re-recording. For podcasters and audio creators who want professional output without professional software or a studio, Podcastle covers the full production workflow from recording to export. Plans from $11.99/mo.', 'https://www.google.com/s2/favicons?domain=podcastle.ai&sz=64', 'https://podcastle.ai', 'https://podcastle.ai', ARRAY['audio-ai', 'podcasting'], 'freemium', true, 11.99, 4.4, 1870, false, false, false, ARRAY['Text-based editing makes audio editing accessible to non-editors', 'AI removes filler words and silence automatically', 'Revoice creates a custom AI voice model from your voice', 'Full production workflow in the browser - no software install'], ARRAY['Audio quality not quite at Riverside''s level for professional use', 'Revoice quality varies by recording sample quality', 'Advanced mixing limited compared to dedicated DAW tools'], ARRAY['Solo podcast recording and production in the browser', 'Audio editing without traditional DAW experience', 'Voice cloning for consistent voiceover content']),

-- 9. Castmagic
('castmagic', 'Castmagic', 'AI content repurposing tool that transforms audio and video into written content automatically', 'Castmagic takes any audio or video file - podcast episodes, interview recordings, webinar recordings, YouTube videos - and automatically generates a full suite of written content from it: transcript, show notes, social media posts, newsletter content, blog post outlines, quotable moments, and email subject lines. Instead of spending hours manually extracting value from a recording, Castmagic processes the file and produces all the derivative content in minutes. This makes it particularly valuable for podcast producers, content marketers, and creators who produce long-form audio or video content and want to distribute it across multiple channels without additional writing effort. The tool handles multiple speakers accurately and can be configured to output in different tones and formats. Plans from $39/mo.', 'https://www.google.com/s2/favicons?domain=castmagic.io&sz=64', 'https://castmagic.io', 'https://castmagic.io', ARRAY['audio-ai', 'writing-ai'], 'paid', false, 39.00, 4.4, 1240, false, true, false, ARRAY['Generates full content suite from a single audio or video upload', 'Multi-speaker accuracy for interview and panel formats', 'Output covers transcript, show notes, social, email, and blog', 'Saves hours of manual content extraction per episode'], ARRAY['No free tier - paid from first use', 'Higher price point than simpler repurposing tools', 'Output requires editing before publishing - not fully automated'], ARRAY['Podcast episode repurposing across multiple content channels', 'Webinar and event recording to written content pipeline', 'Interview content extraction for newsletters and social']),

-- 10. Descript
('descript', 'Descript', 'All-in-one audio and video editor that lets you edit media by editing the transcript', 'Descript is an audio and video editing platform built around a text-based editing paradigm. Import any audio or video file and Descript generates a transcript. Edit the transcript - delete words to cut them from the media, rearrange paragraphs to rearrange scenes, highlight a sentence and replace it with new recorded audio. The result is video and audio editing that is accessible to anyone who can edit a document, without needing to learn traditional timeline-based editing software. AI features include Overdub (voice cloning to fix mispronounced words or add lines without re-recording), Studio Sound (one-click audio enhancement), filler word removal, and automatic silence trimming. Descript handles both podcasting and video production, including screen recording and multi-track editing. For agencies and content teams producing regular long-form audio and video, Descript reduces editing time by 40-60%. Plans from $24/mo.', 'https://www.google.com/s2/favicons?domain=descript.com&sz=64', 'https://www.descript.com', 'https://www.descript.com', ARRAY['video-ai', 'audio-ai'], 'freemium', true, 24.00, 4.5, 4560, false, false, false, ARRAY['Edit audio and video by editing the transcript - no timeline skills needed', 'Overdub voice cloning fixes recordings without re-recording', 'Handles both podcast audio and video production', 'Studio Sound enhances audio quality in one click'], ARRAY['Rendering can be slow for long-form video projects', 'Overdub voice quality varies by voice sample quality', 'Less powerful than Premiere Pro for complex multi-track edits'], ARRAY['Podcast recording and editing without audio engineering experience', 'Video content creation for agencies and content teams', 'Interview and talking-head video editing with transcript-based workflow'])

ON CONFLICT (slug) DO NOTHING;
