-- tools-batch-24.sql
-- No-code / low-code app builders and internal tool platforms
-- Target: DB 262 -> 272 tools
-- Safe to re-run: ON CONFLICT (slug) DO NOTHING

INSERT INTO tools (slug, name, tagline, description, logo_url, website_url, affiliate_url, tags, pricing_type, pricing_free_tier, pricing_starting_price, rating, review_count, featured, trending, editor_pick, pros, cons, use_cases)
VALUES

('bubble', 'Bubble', 'Build web applications without writing code',
'Bubble is the leading no-code platform for building complex web applications with real-time data and user accounts. Unlike template builders, Bubble provides a visual programming environment where you design the UI, define the data model, and build business logic through a drag-and-drop workflow editor - all without writing code. Applications built on Bubble are full-featured web apps that support multi-user roles, complex data relationships, API integrations, and custom workflows responding to user actions. The platform has a substantial marketplace of plugins and templates, and a large community that has built everything from SaaS products to marketplaces to internal tools. Bubble pricing starts free and scales with usage. It is the right tool when you need a sophisticated application with real business logic - not a simple landing page - but do not want to hire a development team. The learning curve is steeper than simpler no-code tools, but the capability ceiling is correspondingly higher. Many successful funded startups have launched their initial products on Bubble before rewriting in code.',
'https://www.google.com/s2/favicons?domain=bubble.io&sz=64',
'https://bubble.io', 'https://bubble.io',
ARRAY['no-code', 'app-builder', 'web-development', 'saas-builder'], 'freemium', true, 0.00, 4.5, 2100, false, false, false,
ARRAY['Full visual programming environment - not just templates', 'Supports complex data relationships and multi-user roles', 'Large plugin marketplace and active community', 'No coding required to build a production SaaS'],
ARRAY['Steeper learning curve than simpler no-code tools', 'Performance limitations on complex, data-heavy apps', 'Apps are tied to Bubble infrastructure - cannot export raw code'],
ARRAY['Building a SaaS MVP without a development team', 'Creating marketplace or multi-sided platform apps', 'Launching a startup product quickly before raising funding']),

('glide', 'Glide', 'Build powerful apps from Google Sheets and Excel',
'Glide turns Google Sheets, Excel, and Airtable into mobile and web applications without any coding. Connect your spreadsheet, choose a template, and Glide generates a working application that reads and writes back to your data source in real time. For teams already managing data in spreadsheets, Glide is the fastest path to a functioning app - often achievable in under an hour. Use cases include field service apps for teams without computers, customer-facing portals, inventory tracking tools, and simple CRM replacements. Glide handles authentication, offline support, and mobile-first layouts automatically. The free tier supports up to 500 rows of data, making it genuinely usable for small projects before any payment is required. Glide has introduced an AI column feature that uses GPT-4 to categorise, summarise, or generate text based on existing data, adding automation to spreadsheet-backed apps. Glide works best when your data already lives in a spreadsheet and you want to wrap it in a better user interface for mobile or web without building anything from scratch.',
'https://www.google.com/s2/favicons?domain=glideapps.com&sz=64',
'https://www.glideapps.com', 'https://www.glideapps.com',
ARRAY['no-code', 'app-builder', 'spreadsheet', 'mobile-apps'], 'freemium', true, 0.00, 4.4, 890, false, false, false,
ARRAY['Fastest path from spreadsheet data to a working app', 'Built-in AI column feature for automated data processing', 'Free tier is genuinely usable for small projects', 'Handles mobile-first layout and offline support automatically'],
ARRAY['Data model limited by spreadsheet structure', 'Not suitable for complex applications with many interconnected data types', 'Free tier limited to 500 rows'],
ARRAY['Building a field service app for non-office teams', 'Wrapping a Google Sheets dataset in a customer-facing interface', 'Creating a simple internal CRM or inventory tracker']),

('retool', 'Retool', 'Build internal tools and dashboards 10x faster',
'Retool is the standard platform for building internal tools - dashboards, admin panels, data management interfaces, and operational apps - for teams with at least some technical capacity. Unlike visual website builders, Retool is designed for connecting to databases, APIs, and internal systems. It has native connectors for PostgreSQL, MySQL, MongoDB, REST APIs, GraphQL, and more than 50 other data sources. Developers drag and drop UI components - tables, forms, charts, maps - and bind them to queries with minimal JavaScript. The result is internal tools that would take weeks to build from scratch, delivered in hours. Retool runs in the cloud or self-hosted, supports role-based access control, and audit logs make it suitable for enterprise environments. The free tier covers up to 5 users for cloud hosting, making it accessible for small teams. Retool also offers Retool AI, which lets you embed LLM-powered components - classification, summarisation, generation - directly into internal tools without building a separate AI layer. For engineering teams tired of building one-off admin panels, Retool standardises the approach and reduces ongoing maintenance cost significantly.',
'https://www.google.com/s2/favicons?domain=retool.com&sz=64',
'https://retool.com', 'https://retool.com',
ARRAY['no-code', 'internal-tools', 'developer-tools', 'dashboards'], 'freemium', true, 0.00, 4.6, 1450, false, false, false,
ARRAY['50+ native connectors to databases and APIs', 'Self-hosted option keeps sensitive data on your infrastructure', 'Free tier covers up to 5 users', 'Retool AI adds LLM-powered components without extra integration work'],
ARRAY['Per-user pricing scales up quickly for larger teams', 'Requires some technical knowledge to use effectively', 'Applications are tied to Retool infrastructure if not self-hosted'],
ARRAY['Building an admin panel for a SaaS product', 'Creating a customer support tool connected to multiple databases', 'Building data management interfaces for operations teams']),

('softr', 'Softr', 'Build web apps and client portals from Airtable and Google Sheets',
'Softr builds web applications and client portals directly from Airtable and Google Sheets data, with no code required. The platform targets non-technical teams that already use Airtable as their data layer: connect your base, choose which views to expose, and Softr generates a clean web interface with user authentication, search, filters, and forms. Common applications include member directories, customer portals, job boards, event listings, and partner dashboards. Softr handles authentication so that different users see only the data they are permitted to access - a feature that typically requires significant development effort to implement from scratch. The design system is polished enough for client-facing applications, not just internal tools. Softr supports custom domains and white-label branding on paid plans. The free tier supports unlimited pages with Softr branding and limited users. For marketing, operations, and HR teams that want to build a portal on top of their existing Airtable data without involving engineering, Softr is the most direct path from data to deployed application. It complements Airtable in the same way that Glide complements Google Sheets.',
'https://www.google.com/s2/favicons?domain=softr.io&sz=64',
'https://www.softr.io', 'https://www.softr.io',
ARRAY['no-code', 'app-builder', 'airtable', 'client-portals'], 'freemium', true, 0.00, 4.4, 620, false, false, false,
ARRAY['Connects directly to Airtable and Google Sheets', 'Role-based access control for multi-user portals', 'Polished design suitable for client-facing applications', 'Custom domain and white-label branding on paid plans'],
ARRAY['Tightly coupled to Airtable - switching backends is complex', 'Limited flexibility for complex custom UI requirements', 'Free tier includes Softr branding'],
ARRAY['Building a client portal on top of an Airtable database', 'Creating a member directory or job board for a community', 'Giving partners or customers a view into relevant data']),

('adalo', 'Adalo', 'Build native mobile and web apps without code',
'Adalo is a no-code platform for building native mobile applications for iOS and Android, as well as web apps, without writing code. Users design screens visually, connect components to a built-in database or external API, and define actions that respond to user interactions. Adalo publishes directly to the Apple App Store and Google Play Store, handling the submission and update process. This makes it one of the few no-code tools that produces genuine native mobile apps rather than progressive web apps or mobile-optimised websites. Use cases include community apps, marketplace apps, booking platforms, and simple service apps where a mobile-first experience matters. Adalo works best for applications with straightforward data models and navigation flows. The free plan allows building and testing in the browser; paid plans are required for publishing to the app stores and accessing custom actions and integrations. For founders and product teams that need a real mobile app but lack iOS or Android development resources, Adalo reduces the barrier to App Store publishing significantly, without requiring React Native or Swift knowledge.',
'https://www.google.com/s2/favicons?domain=adalo.com&sz=64',
'https://www.adalo.com', 'https://www.adalo.com',
ARRAY['no-code', 'mobile-apps', 'app-builder', 'ios', 'android'], 'freemium', true, 0.00, 4.2, 510, false, false, false,
ARRAY['Publishes genuine native apps to iOS and Android app stores', 'Visual screen design with real component library', 'External API connections for integrating with existing backends', 'No Swift, Kotlin, or React Native knowledge required'],
ARRAY['Performance limited compared to code-built native apps', 'App store publishing requires a paid plan', 'Less suitable for complex multi-step flows or heavy data operations'],
ARRAY['Building an MVP mobile app to validate a product idea', 'Creating a community or marketplace app for iOS and Android', 'Launching a service app without hiring mobile developers']),

('appsmith', 'Appsmith', 'Open-source platform for building internal tools and admin panels',
'Appsmith is an open-source platform for building internal tools, admin panels, and dashboards, designed for teams that want Retool-level capability without per-user licensing costs. Developers use a drag-and-drop interface to build UIs, connect to databases and APIs with built-in connectors, and write JavaScript to add custom logic. Appsmith runs self-hosted on Docker or Kubernetes - so sensitive data never leaves your infrastructure. More than 50 native integrations cover PostgreSQL, MySQL, MongoDB, S3, REST APIs, GraphQL, and common SaaS tools like Google Sheets and Twilio. Unlike Retool, which charges per user, the self-hosted version of Appsmith is free with no user limits. This makes it particularly attractive for larger engineering teams where Retool licensing becomes expensive as headcount grows. The community edition is actively maintained with regular releases and a strong contributor base. Appsmith Cloud offers a hosted alternative with a free tier for small teams who do not want to manage self-hosted infrastructure. For engineering teams that prefer open source and have the capacity to manage deployment, Appsmith delivers the same core internal tool building capability as commercial alternatives at zero licensing cost.',
'https://www.google.com/s2/favicons?domain=appsmith.com&sz=64',
'https://www.appsmith.com', 'https://www.appsmith.com',
ARRAY['no-code', 'internal-tools', 'open-source', 'developer-tools'], 'freemium', true, 0.00, 4.5, 980, false, false, false,
ARRAY['Fully open-source with no per-user licensing fees when self-hosted', '50+ native integrations including databases, APIs, and SaaS tools', 'Active community and regular release cycle', 'Hosted cloud option available for teams without infrastructure capacity'],
ARRAY['Requires self-hosting setup and maintenance', 'Less polished UI compared to commercial alternatives like Retool', 'JavaScript knowledge needed for custom logic beyond simple queries'],
ARRAY['Building admin panels without per-user licensing costs', 'Creating internal data management tools for large engineering teams', 'Self-hosting an internal tool platform on company infrastructure']),

('xano', 'Xano', 'Build scalable backends without writing backend code',
'Xano is a no-code backend platform that gives non-developers and developers a scalable server-side environment without writing backend code. Where all-in-one no-code builders like Bubble and Glide include a basic built-in backend, Xano is purpose-built as the standalone backend layer for applications built with any frontend. It provides a visual function builder for creating API endpoints, database tables, business logic, and authentication flows. Xano handles hosting, scaling, and security automatically, and generates a standard REST API that any frontend can connect to - whether that is Webflow, WeWeb, FlutterFlow, or a custom-coded frontend. For teams building with multiple no-code tools that need a robust, scalable backend, Xano is the most capable no-code option available. It also makes a strong case for software developers who want to skip writing boilerplate API and database code and focus on the business logic layer. Xano includes a visual debugger, real-time logs, and environment management. The platform is particularly popular in the FlutterFlow and WeWeb ecosystems as the recommended backend. A free tier supports up to 10,000 API requests per month and one workspace, making it viable for development and small production applications.',
'https://www.google.com/s2/favicons?domain=xano.com&sz=64',
'https://www.xano.com', 'https://www.xano.com',
ARRAY['no-code', 'backend', 'api-builder', 'developer-tools'], 'freemium', true, 0.00, 4.5, 740, false, false, false,
ARRAY['Purpose-built backend that works with any frontend', 'Visual function builder for API endpoints and business logic', 'Handles hosting, scaling, and security automatically', 'Free tier supports up to 10,000 API requests per month'],
ARRAY['Free tier limited to one workspace and moderate request volume', 'Not suitable as a primary backend for very high-traffic applications', 'Visual function builder has a learning curve for complex logic'],
ARRAY['Building the backend for a WeWeb or FlutterFlow frontend', 'Creating a REST API without writing server code', 'Replacing a hand-coded backend for a no-code app stack']),

('noloco', 'Noloco', 'Build custom internal tools and client portals from your existing data',
'Noloco builds internal tools and client portals from existing data sources including Airtable, Google Sheets, PostgreSQL, MySQL, and REST APIs, without any development work required. The platform focuses on giving teams a polished, permission-controlled interface over their data. Features include role-based access control, customisable forms, filtering and search, workflow automation triggers, and white-label branding for client-facing portals. Noloco targets operations teams, agencies, and SaaS companies that need to give clients or internal users controlled access to data. Unlike Retool and Appsmith, which require some technical knowledge to use effectively, Noloco is designed for non-developers who manage data in tools like Airtable and need to build a portal without engineering support. The interface builder is simpler than Bubble or Retool but more opinionated, which makes it faster to set up for standard use cases like client portals, team dashboards, and approval workflows. Starting at $32 per month, Noloco is priced for small teams and agencies. It works best when the primary requirement is presenting and editing data in a clean interface for multiple user roles, rather than building complex business logic.',
'https://www.google.com/s2/favicons?domain=noloco.io&sz=64',
'https://noloco.io', 'https://noloco.io',
ARRAY['no-code', 'internal-tools', 'client-portals', 'airtable'], 'paid', false, 32.00, 4.3, 290, false, false, false,
ARRAY['Non-developer friendly - no technical knowledge required', 'Connects to Airtable, Google Sheets, and SQL databases', 'White-label branding for client-facing portals', 'Role-based access control built in at the platform level'],
ARRAY['No free tier - starts at $32/month', 'Limited flexibility for complex custom UI requirements', 'Smaller ecosystem compared to Retool or Appsmith'],
ARRAY['Building a client portal for an agency without engineering resources', 'Creating an approval workflow dashboard over an Airtable database', 'Giving team members a controlled view into operational data']),

('windmill', 'Windmill', 'Open-source platform for scripts, workflows, and internal apps',
'Windmill is an open-source developer platform for building scripts, workflows, and lightweight internal applications. Unlike visual no-code tools, Windmill lets developers write scripts in Python, TypeScript, Go, Bash, or SQL, and then compose those scripts into workflows using a visual DAG editor. Each script is versioned, tested, and deployable as a standalone API endpoint, scheduled job, or triggered workflow. Windmill runs self-hosted on your own infrastructure or via Windmill Cloud, and includes a built-in secret manager, job queue, concurrency controls, and audit log. For engineering teams that want the automation power of tools like Airflow or Prefect but with a simpler self-hosted setup and a built-in UI for non-developers to trigger workflows, Windmill provides a practical middle ground. The open-source community edition is free with no limits on scripts or workflows. Commercial plans add team collaboration features, cloud hosting, and enterprise support. Windmill is particularly strong for data pipelines, internal automation, and operations workflows that require real code rather than a visual connector approach. The ability to write real scripts in a proper language, combined with a UI layer for non-technical users to trigger and monitor those scripts, makes Windmill well-suited for operations and data teams.',
'https://www.google.com/s2/favicons?domain=windmill.dev&sz=64',
'https://windmill.dev', 'https://windmill.dev',
ARRAY['no-code', 'workflow-automation', 'open-source', 'developer-tools', 'scripts'], 'freemium', true, 0.00, 4.5, 410, false, false, false,
ARRAY['Write real code in Python, TypeScript, Go, Bash, or SQL', 'Open-source self-hosted with no limits on the community edition', 'Visual DAG editor for composing scripts into workflows', 'Built-in secret manager, job queue, and audit log'],
ARRAY['Requires coding knowledge - not a true no-code tool for scripts', 'Self-hosting requires infrastructure capacity', 'Smaller ecosystem and community than Zapier or n8n'],
ARRAY['Building data pipelines that require real code execution', 'Creating internal automation workflows with a trigger UI for non-developers', 'Replacing cron jobs with a managed, auditable workflow system']),

('weweb', 'WeWeb', 'Build production-grade frontends visually, connect to any backend',
'WeWeb is a visual frontend development platform for building production-grade web applications that connect to any backend or API. Unlike all-in-one no-code builders, WeWeb focuses exclusively on the frontend layer - giving designers and developers a visual canvas that generates clean, exportable code. It connects natively to Supabase, Xano, Airtable, REST APIs, and GraphQL backends, and adds authentication, dynamic data binding, and complex logic through a visual interface. The output is standard HTML, CSS, and JavaScript that can be hosted anywhere. WeWeb targets teams that need more design control and production quality than tools like Bubble offer, but want to avoid writing React or Vue from scratch. Features include reusable component libraries, version history, multi-page navigation, custom CSS, and a formula editor for computed values. The free tier supports unlimited projects with WeWeb branding. For product teams with design requirements that exceed what template-based builders can deliver, WeWeb bridges the gap between no-code speed and coded quality. It pairs naturally with Xano or Supabase as the backend layer, and the Xano-WeWeb combination has become a popular full-stack no-code architecture for production applications.',
'https://www.google.com/s2/favicons?domain=weweb.io&sz=64',
'https://www.weweb.io', 'https://www.weweb.io',
ARRAY['no-code', 'frontend-builder', 'web-development', 'visual-development'], 'freemium', true, 0.00, 4.4, 380, false, false, false,
ARRAY['Generates clean exportable HTML, CSS, and JavaScript', 'Works with any backend - Supabase, Xano, REST APIs, GraphQL', 'More design control than all-in-one builders like Bubble', 'Reusable component libraries and version history'],
ARRAY['Frontend only - requires a separate backend like Xano or Supabase', 'Learning curve for non-developers coming from template builders', 'Free tier includes WeWeb branding on published apps'],
ARRAY['Building a polished frontend for a Xano or Supabase backend', 'Creating a production-quality SaaS UI without writing React from scratch', 'Replacing a coded frontend with a visually maintained alternative'])

ON CONFLICT (slug) DO NOTHING;
