-- tools-batch-50.sql
-- AI Translation & Localization Tools (10 tools)
-- Run BEFORE compare-batch-50.sql (FK dependency)

INSERT INTO tools (slug, name, tagline, description, logo_url, website_url, affiliate_url, tags, pricing_type, pricing_free_tier, pricing_starting_price, rating, review_count, featured, trending, editor_pick, pros, cons, use_cases)
VALUES

('phrase',
 'Phrase',
 'AI-powered translation management for software and product teams',
 'Phrase is an enterprise translation management system built for software development teams that need to localise applications, websites, and documentation at scale. The platform connects development workflows with translation processes through integrations with GitHub, GitLab, Bitbucket, and major CI/CD pipelines, allowing developers to push new strings for translation automatically without manual file handoff. Phrase AI provides machine translation from DeepL and Google, AI-powered translation memory suggestions, and automatic quality assurance checks that flag inconsistencies before they reach production. The platform supports over 40 file formats including JSON, YAML, XML, PO, and Android/iOS resource files, with plural form handling and context screenshots that help translators understand where strings appear in the UI. A built-in translation vendor marketplace connects teams with professional human translators when machine translation alone is not sufficient. Teams using Phrase typically reduce localisation turnaround time by 60 to 80 percent compared to email-based translation workflows.',
 'https://www.google.com/s2/favicons?domain=phrase.com&sz=64',
 'https://phrase.com',
 'https://phrase.com',
 ARRAY['translation', 'localization', 'i18n', 'TMS', 'software'],
 'paid',
 false,
 27.00,
 4.5, 1340,
 false, true, false,
 ARRAY['Deep developer workflow integrations with GitHub and GitLab', 'Supports 40 plus file formats including mobile app resource formats', 'Built-in AI translation from DeepL and Google with quality assurance checks'],
 ARRAY['Pricing scales steeply with seat count for larger teams', 'Setup complexity is high for non-technical users without developer support', 'Full feature set requires paid plan - free tier is limited'],
 ARRAY['Localising a SaaS product for multiple language markets simultaneously', 'Automating string extraction from code repositories into translation workflows', 'Managing translation memory and terminology consistency across a large content team']),

('lokalise',
 'Lokalise',
 'Collaborative localization platform for fast-moving product teams',
 'Lokalise is a localization platform built for product and engineering teams that need to ship multilingual features quickly without creating a bottleneck between developers and translators. The platform provides a central workspace where developers push strings, translators work on them in context, and localisation managers track progress and quality - all without emailing files back and forth. Lokalise AI translates content using OpenAI, DeepL, and Google, and learns from a team''s existing translations to produce suggestions that match brand voice and terminology. Key differentiators include real-time visual context - translators see screenshots of exactly where each string appears in the product - and over-the-air translation updates for mobile apps that push new translations without requiring an app store release. The branching workflow allows localisation to run in parallel with feature development, so translated content is ready the moment a feature ships. Lokalise also offers a dedicated translation marketplace with vetted human translation vendors for languages where machine translation alone is not sufficient.',
 'https://www.google.com/s2/favicons?domain=lokalise.com&sz=64',
 'https://lokalise.com',
 'https://lokalise.com',
 ARRAY['localization', 'translation', 'i18n', 'mobile', 'SaaS'],
 'paid',
 false,
 120.00,
 4.6, 1870,
 false, true, false,
 ARRAY['Real-time visual context shows translators exactly where strings appear in the UI', 'Over-the-air mobile translation updates without requiring an app store release', 'Branching workflow supports parallel localisation and feature development'],
 ARRAY['Higher starting price than competitors at the team plan level', 'Translation marketplace costs add up for projects requiring heavy human translation', 'API rate limits can constrain high-volume automated workflows'],
 ARRAY['Shipping a multilingual mobile app with OTA translation updates', 'Running localisation as a continuous parallel workflow alongside product development', 'Managing a global content team working across 20 plus language pairs']),

('smartling',
 'Smartling',
 'Enterprise AI translation platform with human quality guarantee',
 'Smartling is the enterprise translation management platform for global brands that need professional-quality multilingual content at scale, combining AI translation with a network of professional human translators who review, edit, and guarantee quality. The platform ingests content from websites, apps, marketing materials, and documentation simultaneously, applies AI pre-translation from a proprietary neural machine translation engine trained on brand-specific terminology, then routes content through human review workflows where linguists correct and refine the AI output. Translation Memory and Glossary management ensure consistent terminology across every content type and language. Smartling VisualContext technology gives translators in-browser views of exactly how translated text renders on the live page, eliminating the guesswork that causes layout-breaking translations. The platform integrates with Contentful, Sitecore, Salesforce, and Adobe Experience Manager, making it practical for enterprise marketing teams with complex content stacks. Reporting dashboards show spend, velocity, and quality scores by language pair, content type, and time period.',
 'https://www.google.com/s2/favicons?domain=smartling.com&sz=64',
 'https://smartling.com',
 'https://smartling.com',
 ARRAY['translation', 'localization', 'enterprise', 'content', 'global'],
 'paid',
 false,
 0.00,
 4.4, 890,
 false, false, false,
 ARRAY['Human-in-the-loop quality guarantee for every translated string', 'VisualContext shows translators how text renders on the live page', 'Deep enterprise CMS integrations including Contentful and Adobe Experience Manager'],
 ARRAY['Enterprise pricing - not suitable for startups or small teams', 'Requires sales engagement for pricing and onboarding', 'Full deployment can take weeks for complex enterprise content stacks'],
 ARRAY['Localising an enterprise website across 15 languages with brand consistency', 'Translating marketing campaigns simultaneously for a global product launch', 'Managing a continuous stream of support documentation updates across 10 languages']),

('crowdin',
 'Crowdin',
 'Community-powered localization platform for software and open-source projects',
 'Crowdin is a cloud-based localization management platform that serves both commercial software teams and open-source communities, making it the most versatile translation tool for projects that need to involve community contributors alongside professional translators. The platform supports over 50 file formats and integrates with GitHub, GitLab, Bitbucket, and major CMS platforms to automatically pull new strings into translation workflows as content is published. Crowdin AI translates content using pre-integrated providers including DeepL, Microsoft Translator, and Google Translate, while the Translation Memory engine learns from every approved translation to improve suggestions over time. For open-source projects, the crowdsourcing feature enables community members to contribute translations and vote on suggestions, reducing costs while building community engagement. The in-context localisation editor shows translators the live website so strings are translated in context without screenshots or separate reference materials. Enterprise features include custom workflows, QA checks for consistency and terminology, and dedicated support.',
 'https://www.google.com/s2/favicons?domain=crowdin.com&sz=64',
 'https://crowdin.com',
 'https://crowdin.com',
 ARRAY['localization', 'translation', 'open-source', 'community', 'i18n'],
 'freemium',
 true,
 0.00,
 4.5, 2310,
 false, true, false,
 ARRAY['Free for open-source projects - best community translation option available', 'Supports 50 plus file formats covering all major development frameworks', 'In-context editor shows translators the live website without screenshots'],
 ARRAY['Pricing for commercial projects can escalate with word volume', 'Community translation quality varies without a professional review workflow', 'Advanced workflow automation requires the Enterprise plan'],
 ARRAY['Localising an open-source project with community contributor translations', 'Running continuous localisation in parallel with a fast-moving SaaS product', 'Managing multilingual documentation alongside software string localisation']),

('transifex',
 'Transifex',
 'Continuous localization for agile product teams',
 'Transifex is a cloud-based translation management platform built for agile product teams that ship features frequently and need localisation to keep pace without manual coordination. The platform connects to code repositories and CMS platforms, automatically detecting new content and sending it through a translation workflow without any manual file handling. Transifex Native integrates directly into React, Angular, Vue, and other frontend frameworks via JavaScript or Python SDK, enabling over-the-air translation updates that push new strings to users without a deployment. Transifex AI applies machine translation pre-translation using DeepL, Google Translate, and Microsoft Translator, then routes strings to human review based on configurable confidence thresholds. The Glossary and Translation Memory system maintains brand consistency across all translated content. Teams can define multi-step review workflows where machine translation output passes through editor review, then proofreader sign-off, before strings go live. A Community plan enables open-source projects to engage volunteer translators alongside professional linguistic review.',
 'https://www.google.com/s2/favicons?domain=transifex.com&sz=64',
 'https://transifex.com',
 'https://transifex.com',
 ARRAY['localization', 'translation', 'continuous', 'agile', 'i18n'],
 'freemium',
 true,
 0.00,
 4.3, 1560,
 false, false, false,
 ARRAY['Native SDK for over-the-air translation updates without a code deployment', 'Flexible human review workflows with configurable approval steps', 'Strong community translation support for open-source projects'],
 ARRAY['Free tier limits are restrictive for production use cases', 'UI less polished than Lokalise or Phrase for everyday translator workflows', 'Native SDK integration requires developer setup time'],
 ARRAY['Shipping translation updates to a React frontend without a code deployment', 'Running agile localisation in parallel with two-week sprint cycles', 'Engaging community translators for an open-source documentation project']),

('weglot',
 'Weglot',
 'Website translation tool that makes any site multilingual in minutes',
 'Weglot is a website translation solution that makes any website multilingual without touching the codebase. Install a JavaScript snippet or a plugin for WordPress, Shopify, Webflow, or other CMS platforms, configure the target languages, and Weglot automatically detects and translates all text content on the site using machine translation from DeepL and Google, then serves the translated versions to visitors based on browser language or URL subdirectory. The visual editor lets marketers edit any translation directly on the live page without logging into a separate translation platform, making Weglot the most accessible translation solution for non-technical teams. Translation Memory stores every approved edit so the same phrase is never translated differently across pages. Weglot handles all multilingual SEO concerns automatically - hreflang tags, language-specific sitemaps, and indexed language subfolders that allow Google to rank the translated site separately from the original. For e-commerce teams, Weglot translates product descriptions, checkout flows, and email notifications, covering the complete customer journey in every language.',
 'https://www.google.com/s2/favicons?domain=weglot.com&sz=64',
 'https://weglot.com',
 'https://weglot.com',
 ARRAY['translation', 'website', 'multilingual', 'SEO', 'no-code'],
 'freemium',
 true,
 0.00,
 4.5, 2890,
 false, true, false,
 ARRAY['Works on any website without code changes - install and translate in minutes', 'Visual editor lets non-technical users edit translations directly on the live page', 'Handles multilingual SEO automatically including hreflang and language sitemaps'],
 ARRAY['Pricing scales with word count - can be expensive for large content sites', 'Less suitable for translating complex web apps with highly dynamic content', 'Translation quality relies on machine translation without mandatory human review'],
 ARRAY['Making a Shopify store available in French, German, and Spanish for European expansion', 'Translating a WordPress marketing site to reach non-English speaking markets', 'Running a multilingual Webflow site managed by a non-technical marketing team']),

('lilt',
 'Lilt',
 'AI translation platform built for enterprise speed and human accuracy',
 'Lilt is an enterprise AI translation platform that combines proprietary adaptive neural machine translation with professional human linguists to deliver translations that are both fast and accurate enough for regulated industries and global enterprise brands. The Lilt AI engine trains continuously on a company''s approved translations, adapting to brand voice, terminology, and writing style over time so translation quality improves with every project rather than remaining static. Human linguists review, post-edit, and approve AI output, giving enterprise buyers a quality guarantee that pure machine translation cannot provide. Lilt Connect integrations with Salesforce, Marketo, Adobe Experience Manager, and major content management systems enable content to flow into translation workflows automatically without manual export and import. The platform includes built-in Translation Memory, Glossary management, and Style Guide enforcement that maintain consistency across millions of words of enterprise content. Lilt is particularly strong for technical documentation, marketing localisation, and customer support content where both volume and accuracy are requirements.',
 'https://www.google.com/s2/favicons?domain=lilt.com&sz=64',
 'https://lilt.com',
 'https://lilt.com',
 ARRAY['translation', 'enterprise', 'AI', 'human-in-the-loop', 'localization'],
 'paid',
 false,
 0.00,
 4.4, 620,
 false, false, false,
 ARRAY['Adaptive AI that improves translation quality with each project using company data', 'Human linguist review layer provides a quality guarantee for regulated content', 'Strong integrations with enterprise content and marketing technology stacks'],
 ARRAY['Enterprise-only pricing model - not available for small or mid-market teams', 'Requires sales conversation and custom implementation for onboarding', 'Less developer-focused than Lokalise or Phrase for software localization'],
 ARRAY['Translating technical documentation into 20 languages for a global software product', 'Localising enterprise marketing campaigns with consistent brand voice across markets', 'Managing a high-volume multilingual customer support knowledge base']),

('unbabel',
 'Unbabel',
 'AI-powered customer support translation for global service teams',
 'Unbabel is a translation-as-a-service platform built specifically for customer support and customer experience teams that need to serve global customers in their native language without hiring multilingual support agents. The platform sits between support agents and customers, translating incoming tickets from any language into the agent''s working language in real time, then translating agent responses back to the customer''s language before they are sent. This enables a Portuguese-speaking support agent to handle a Japanese customer''s query without either party knowing a translation layer exists. Unbabel AI provides the initial translation using proprietary neural machine translation, then a global network of vetted human editors reviews translations above a configured complexity threshold before delivery. The human-in-the-loop model gives enterprise support teams the accuracy they need for sensitive customer interactions that pure machine translation alone would mishandle. Unbabel integrates natively with Zendesk, Salesforce Service Cloud, Freshdesk, and Kustomer, making it invisible within existing support workflows. For customer support leaders, the platform provides quality scores, resolution time by language pair, and cost-per-translation analytics.',
 'https://www.google.com/s2/favicons?domain=unbabel.com&sz=64',
 'https://unbabel.com',
 'https://unbabel.com',
 ARRAY['translation', 'customer-support', 'CX', 'enterprise', 'multilingual'],
 'paid',
 false,
 0.00,
 4.3, 540,
 false, false, false,
 ARRAY['Real-time translation within existing support tools - agents never leave Zendesk', 'Human editors review complex translations before delivery to customers', 'Enables support teams to serve global customers without hiring multilingual agents'],
 ARRAY['Enterprise-only pricing model - not accessible for small support teams', 'Per-word pricing can be expensive for high-volume global support operations', 'Primary use case is support translation - not a general localisation platform'],
 ARRAY['Running a single English-speaking support team serving customers in 15 languages', 'Improving customer satisfaction for non-English speaking markets without headcount increase', 'Managing SLA compliance for multilingual support tickets across global time zones']),

('trados',
 'Trados',
 'Professional translation software for linguists and language service providers',
 'Trados Studio is the industry-standard computer-assisted translation tool used by professional translators, translation agencies, and enterprise language service providers worldwide. Unlike cloud-based TMS platforms built for software teams, Trados is the tool that professional linguists use to translate efficiently - a desktop application that presents source and target text in a side-by-side editor, with Translation Memory matching, terminology lookup, and quality assurance built directly into the translation workspace. When a translator encounters a sentence that matches a previous translation in the TM at 75 percent or higher, Trados automatically suggests the previous translation so the linguist edits rather than translates from scratch, dramatically reducing time and cost for documents with repetitive content such as technical manuals, legal contracts, and software documentation. Trados GroupShare extends the platform to teams, enabling multiple translators and project managers to collaborate on a shared TM and project workflow. The cloud-based Trados Live tier provides browser-based access for translators who prefer a web interface. For enterprise buyers, Trados integrates with broader enterprise content workflows and is widely accepted by language service providers globally.',
 'https://www.google.com/s2/favicons?domain=trados.com&sz=64',
 'https://trados.com',
 'https://trados.com',
 ARRAY['translation', 'CAT-tool', 'LSP', 'professional', 'TM'],
 'paid',
 false,
 115.00,
 4.2, 1680,
 false, false, false,
 ARRAY['Industry-standard TM matching that professional translators rely on globally', 'Handles complex document formats including Word, InDesign, DITA, and XML', 'GroupShare enables enterprise team collaboration on shared translation memory'],
 ARRAY['Desktop-first software model is less suited to cloud-native team workflows', 'Steep learning curve for translators new to professional CAT tools', 'Less integrated with modern SaaS developer workflows than Phrase or Lokalise'],
 ARRAY['Translating technical documentation and user manuals with high repetition rates', 'Running a translation agency project with multiple linguists on a shared TM', 'Localising legal or regulatory documents where precision and consistency are critical']),

('poeditor',
 'POEditor',
 'Lightweight localization management for developers and small teams',
 'POEditor is a straightforward online localization platform for software developers and small teams that need to manage translation projects without the overhead of an enterprise TMS. The platform supports all major software localization file formats including PO, POT, XLIFF, JSON, Android XML, iOS Strings, ARB, and CSV, making it compatible with every major development framework. Developers connect GitHub, GitLab, or Bitbucket repositories to automatically sync new strings into POEditor when code is committed, and pull approved translations back into the codebase without manual file handling. Contributors can be added as translators, with configurable roles from viewer to administrator, enabling teams to involve professional translators, community volunteers, or internal bilingual team members. Machine translation from DeepL, Google Translate, and Microsoft Translator is available for pre-translation of new strings. Translation Memory stores approved translations and suggests them when identical or similar strings appear in future projects. The pricing model charges per project contributor rather than per word, making costs predictable for ongoing localisation projects. POEditor is the most cost-effective professional localization platform for development teams managing 2 to 20 languages.',
 'https://www.google.com/s2/favicons?domain=poeditor.com&sz=64',
 'https://poeditor.com',
 'https://poeditor.com',
 ARRAY['localization', 'translation', 'developer', 'i18n', 'lightweight'],
 'freemium',
 true,
 0.00,
 4.3, 940,
 false, false, false,
 ARRAY['Per-contributor pricing is predictable and affordable for small-to-medium projects', 'Supports all major software localization file formats in one platform', 'Clean, straightforward UI with minimal setup time for developers'],
 ARRAY['Less advanced than Phrase or Lokalise for large-scale enterprise localisation', 'No native mobile app OTA update support unlike Lokalise', 'AI features less developed than competitors - primarily for pre-translation only'],
 ARRAY['Managing localisation for a developer-built SaaS product with 5 to 10 languages', 'Involving community contributors in open-source software translation', 'Running a small translation team without investing in enterprise TMS infrastructure'])

ON CONFLICT (slug) DO NOTHING;
