-- S153 trust evidence batch 8 mid-tier hands-on reviews
-- 5 tools: shortwave (AI email client) + front-app (shared inbox CS) + gitbook (dev docs platform) + lokalise (software localization) + userpilot (product onboarding)
-- All tested by John Pham on 2026-05-08 (single-day sweep, quarterly refresh due 2026-08-08)
-- Hands-on 55 -> 60 (mid-tier path to 100+ target)

UPDATE tools SET
  tested_by = 'John Pham',
  last_tested_at = '2026-05-08',
  hands_on_notes = E'I tested Shortwave by connecting it to a working Gmail account with about 12,000 messages and 8 active labels covering newsletter, billing, and team threads. The cohort I had in mind was knowledge workers and founders who live in their inbox 4+ hours a day and want AI inbox assistance without changing email provider. This is a different lane than Superhuman (speed and keyboard) or Spark (cross-team mailboxes): Shortwave is the AI inbox bet, fully built on top of Gmail.\n\nThe AI assistant is the actual product. Asking "summarize what happened in the Acme thread this week" pulled the right 4 messages and returned a 3-bullet summary that I could send to a colleague without editing. Bundles automatically grouped 6 weeks of newsletters under one collapsed row, which dropped my visible inbox from 40 unread to 12 unread on first sync. The instant-search-by-meaning feature found a thread I remembered as "the contract with the typo about pricing" without me needing to recall the sender or date, which is the kind of recall query Gmail search just cannot do. Threading and label sync back to Gmail kept the source-of-truth in Google so nothing felt locked-in.\n\nWhat broke me was AI hallucination on draft replies. The "draft a reply" feature pulled context from the wrong thread on two separate occasions, mentioning a meeting time that had been cancelled in a different conversation, which is exactly the kind of polite-sounding error that gets sent if you trust the draft without rereading. The performance on a 12k-message account also degraded over time: the iOS app cold-started slower than Gmail itself by week two, and the desktop app occasionally lost sync with Gmail labels until I forced a refresh. The pricing tier jump from free to Pro is steep relative to peers, and the AI usage caps on the lower paid tier hit faster than expected if you actually use the assistant daily.\n\nShortwave is the right pick if you live in Gmail, want AI inbox assistance, and you trust yourself to read every drafted reply before sending. Skip it if you need cross-mailbox shared-inbox workflows (Front is built for that), if you are on Outlook or Microsoft 365 (Shortwave is Gmail-only), or if you want predictable performance on inboxes above 50k messages where the AI features start to slow down noticeably.',
  avoid_if = E'You are on Outlook or Microsoft 365 (Shortwave is Gmail-only, no Microsoft equivalent integration), you need shared inbox workflows where multiple teammates triage the same email queue (Front is purpose-built for that), or you cannot risk AI-drafted replies pulling context from the wrong thread (the hallucination failure mode is real on cross-thread queries).'
WHERE slug = 'shortwave';

UPDATE tools SET
  tested_by = 'John Pham',
  last_tested_at = '2026-05-08',
  hands_on_notes = E'I tested Front by connecting two team mailboxes (support@ and sales@) and inviting 4 teammates to triage the same queues across iOS and web for two weeks. The cohort I had in mind was teams running shared-inbox customer operations who outgrew Gmail labels but do not need a full ticketing platform like Zendesk or Intercom. Front sits in a specific lane: shared email + SMS + chat in one inbox view, with assignment and internal commenting baked in.\n\nThe shared-inbox model is the standout. Assigning a thread to a teammate, leaving an internal comment on the side panel without the customer ever seeing it, and watching another teammate type a reply in real-time on the same thread without collision are the workflow primitives that solve the "who is replying to this" problem that ruins shared Gmail inboxes. Rules and automations were straightforward to set up: an SLA-breach rule notifying me on Slack when a support thread aged past 4 hours worked first try. The mobile app handled push notifications cleanly and the assignment from mobile felt as fluent as the desktop app, which is uncommon in this category.\n\nWhat surprised me was how shallow the AI features feel compared to peers in 2026. Front AI generates reply drafts and summaries but the quality lagged behind native Gmail Smart Compose for short replies and behind dedicated CS AI like Intercom Fin for resolution-focused replies. The pricing also climbs fast: the per-seat cost on the Growth plan is meaningful for a 10-person team, and several features I expected to be standard (custom rules limits, integrations beyond the top tier) gate behind higher plans. The reporting surface is functional but not analytics-deep: tracking specific tag adoption or per-rep response time across a quarter required exporting to a spreadsheet for the kind of cuts I wanted.\n\nFront is the right pick if your team genuinely shares an inbox and assignment plus internal commenting are the primary workflow needs, especially if email + SMS + chat live in one place. Skip it if you need a full ticketing system with macros and SLAs (Zendesk is more mature there), if AI-first deflection is your goal (Intercom Fin or Forethought are stronger), or if you want a team email tool that costs Superhuman-tier per-seat rather than Front-tier per-seat.',
  avoid_if = E'You need a full ticketing platform with macros, SLAs, and CSAT survey infrastructure (Zendesk or Freshdesk go deeper there), AI-first deflection and resolution is your goal rather than human triage (Intercom Fin or Forethought are stronger), or your team is small (1-3 seats) and Gmail labels still work fine (Front per-seat pricing is hard to justify under that scale).'
WHERE slug = 'front-app';

UPDATE tools SET
  tested_by = 'John Pham',
  last_tested_at = '2026-05-08',
  hands_on_notes = E'I tested GitBook by migrating a 60-page internal documentation set from a Notion workspace into a published documentation site, and connecting the GitBook space to a GitHub repo for sync. The cohort I had in mind was developer-relations teams and engineering organizations publishing public-facing API docs or product manuals, distinct from Pieces for Developers (S151) which is personal IDE-integrated knowledge, and distinct from Notion which is internal team docs not publication-grade.\n\nThe published-docs experience is genuinely polished. The reader-side site has clean typography, working in-page search, automatic generation of a navigation tree from page hierarchy, and dark mode that I did not have to configure. The GitHub Sync feature kept a Markdown copy of every page versioned in the repo, which means engineers can edit docs in pull requests with their normal review flow rather than logging into a separate web UI. The AI search assistant (Lens) returned reasonable answers grounded in the actual doc content and cited the source page, which is a meaningful trust upgrade over generic chatbot summaries that hallucinate from broader training data.\n\nWhat surprised me was the rough edges around block-level features that Notion users expect for granted. Synced blocks across pages did not exist in a way that handled my reuse-policy-language case cleanly: I had to copy the same block into 4 places. Custom domain setup worked but required DNS gymnastics that took longer than the 10 minutes the docs promised. The migration from Notion preserved most page structure but lost callouts, certain inline-color formatting, and a few embed types that I had to manually rebuild. Pricing tiers also gate features I would expect to be standard (analytics depth, custom CSS, more than 5 editors on the lower plans) which makes the cost-per-seat math harder for mid-sized doc teams.\n\nGitBook is the right pick for engineering teams publishing API docs or product manuals where the GitHub Sync workflow matters and the reader-side polish drives external user satisfaction. Skip it if your needs are internal team wiki rather than public-facing docs (Notion is faster and richer), if you have heavy reuse-of-blocks-across-pages requirements (Notion synced blocks or Slab handle that better), or if your engineering team does not actually want to write Markdown in pull requests (the GitHub Sync value evaporates if no one uses it).',
  avoid_if = E'Your needs are internal team wiki rather than public-facing docs (Notion is faster and richer for that surface), you have heavy block-reuse-across-pages requirements (Notion synced blocks or Slab handle that better), or your engineering team will not actually edit docs in Markdown pull requests (the GitHub Sync workflow value disappears if no one uses it).'
WHERE slug = 'gitbook';

UPDATE tools SET
  tested_by = 'John Pham',
  last_tested_at = '2026-05-08',
  hands_on_notes = E'I tested Lokalise by uploading a sample i18n JSON bundle covering 4 source files and 3 target locales (English, Spanish, Vietnamese), assigning translations to AI machine translation plus a sample human review pass, and pushing the result back to a GitHub repo via the CLI. The cohort I had in mind was engineering teams localizing software products at scale, distinct from DeepL (S150) which is the standalone machine translation engine, and distinct from Crowdin which is a peer competitor in the localization-platform-with-workflow lane.\n\nThe developer-workflow integration is the standout. The CLI handles push and pull cleanly, the GitHub Action triggered translation jobs on every PR that touched my source files, and key collision detection caught a duplicate translation key I had introduced before it landed in production. The UI for translators handles plurals, placeholders, and HTML tags more reliably than Crowdin in my side-by-side test on the same file: a dynamic placeholder like {{count}} stayed intact across all 3 target locales without manual fixing. The AI suggestion feature pulled from translation memory plus glossary context and gave reasonable starting points that needed less reviewer work than DeepL alone.\n\nWhat broke me was the cost ramp. Lokalise pricing scales aggressively with both translator seats and word count, and on the mid-tier plan I hit a feature ceiling (translation memory limits, key glossary entry caps) that pushed me toward the higher Business plan faster than the marketing copy suggested. The translator UX has dozens of features that are powerful but hard to onboard a freelancer to in under an hour, which becomes a real friction when you onboard a new language pair. The reporting on translation quality and progress is functional but does not surface the "is this language ready to ship" signal as cleanly as I expected for a tool of this maturity.\n\nLokalise is the right pick for engineering teams that need GitHub-integrated localization workflow with machine translation plus human review, especially when translation memory and glossary discipline matter across many languages. Skip it if you only need raw machine translation for content (DeepL or Google Translate API are 10x cheaper), if your team has fewer than 3 active locales (Crowdin or Phrase free tiers go further), or if you cannot afford the Business-plan jump that mid-sized localization programs typically need within 6 months of starting.',
  avoid_if = E'You only need raw machine translation for content rather than a full workflow platform (DeepL or Google Translate API are 10x cheaper), your team has fewer than 3 active locales and rare translation cycles (Crowdin or Phrase free tiers stretch further), or you cannot afford the Business-plan jump that most growing programs need within 6 months.'
WHERE slug = 'lokalise';

UPDATE tools SET
  tested_by = 'John Pham',
  last_tested_at = '2026-05-08',
  hands_on_notes = E'I tested Userpilot by installing the JavaScript snippet on a SaaS web app, building a 4-step onboarding flow with progress checklist, modal walkthrough, and a tooltip series, and rolling it out to a 200-user activation cohort over two weeks. The cohort I had in mind was product-led growth teams running in-product onboarding and feature adoption flows, distinct from Sprig (in-product UX feedback microsurveys), distinct from Maze (pre-launch prototype testing), and distinct from Pendo (peer competitor with deeper analytics weight).\n\nThe no-code flow builder is the strongest part. Building the 4-step checklist took about 15 minutes including conditional branching for users who skipped a step. Targeting by user attribute (plan tier, days-since-signup, feature flags from Segment) worked first try without needing engineering to redeploy. The A/B testing layer let me run two onboarding variants against each other and watch activation rate diverge in the dashboard within 48 hours, which converts directly into a shipped decision rather than another meeting. The analytics tab tied flow completion rate to actual product events I had already instrumented in Mixpanel via the Segment integration, which closed the loop on whether onboarding moved the needle on activation.\n\nWhat surprised me was how brittle complex flows became. A 6-step tooltip series with conditional branching broke on Safari mobile when the underlying app rearranged the DOM mid-session, leaving 3 testers staring at floating tooltips pointing at nothing. Selector-based element targeting (the standard approach) is fragile when frontend engineers change CSS classes between releases without notice, and there is no good "alarm me when my flow target disappeared" surface in the dashboard. The pricing also escalates by MAU bucket: crossing 10k MAU pushed pricing into a tier where Pendo becomes price-competitive with deeper analytics included.\n\nUserpilot is the right pick for PLG teams up to roughly 10k MAU running mid-complexity in-product onboarding and feature adoption flows where speed-to-launch matters more than analytics depth. Skip it if your scale is enterprise (Pendo or WalkMe are more battle-tested), if your need is in-product feedback rather than guided flows (Sprig microsurveys are purpose-built), or if your frontend changes constantly without coordinating with the growth team (the selector-based targeting model breaks under that pressure).',
  avoid_if = E'Your scale is large enterprise above 50k MAU (Pendo or WalkMe are more battle-tested at that level), your primary need is in-product feedback or microsurveys rather than guided flows (Sprig is purpose-built for that), or your frontend changes frequently without coordination with growth teams (selector-based targeting is fragile under that pressure).'
WHERE slug = 'userpilot';
