-- S152 trust evidence batch 7 mid-tier hands-on reviews
-- 5 tools: otter-ai (meeting AI mobile/personal) + maze (UX prototype testing) + bolt (AI app builder visual) + amplitude (product analytics) + abridge (healthcare AI scribe)
-- All tested by John Pham on 2026-05-08 (single-day sweep, quarterly refresh due 2026-08-08)
-- Hands-on 45 -> 50 -> 55 (mid-tier path to 100+ target)

UPDATE tools SET
  tested_by = 'John Pham',
  last_tested_at = '2026-05-08',
  hands_on_notes = E'I tested Otter.ai across two weeks of recurring 1:1s, all-hands sessions, and a mix of Zoom + in-person meetings recorded on the iPhone app. The cohort I had in mind was solo operators and individual contributors who want a personal recording assistant rather than a sales-call analytics tool. Otter sits in a different lane than Fireflies or Gong: the mobile-first capture experience is the actual product, and the web dashboard is secondary.\n\nThe iOS app is genuinely the strongest part of the experience. Tap once on the home screen widget, the recording starts in under a second, transcription streams live in the app, and the audio plus searchable transcript syncs to my web account before I even leave the room. Live transcription quality on clear single-speaker audio is excellent. The OtterPilot bot for Zoom integration also worked reliably across every test meeting and showed up as a named participant rather than crashing in silently. The chatbot summary feature can answer "what did Sarah commit to" type questions across the whole transcript and generally pulls the right quote, which feels useful when you are scanning a 90-minute session you only half-remember.\n\nWhat broke me was multi-speaker accuracy on noisy in-person recordings. A 6-person standup in a conference room produced transcripts where speaker labels were stable for 2-3 turns and then started swapping between the same two engineers for the rest of the meeting, which turns "John said X, Sarah said Y" into a coin flip if you actually need to attribute decisions later. The free tier 300 minute monthly cap also disappears fast: 4-5 long meetings in a week and you are upgraded or locked out. The summary auto-generation occasionally invents action items that no one actually committed to, which is the kind of polite hallucination that gets dangerous in a work context.\n\nOtter is the right pick if you are an individual professional who wants a fast personal recorder with searchable history and you do not need analytics on top of the data. Skip it if your use case is sales-call coaching across a team (Gong is the answer), enterprise compliance recording (Otter is not built for that), or any high-stakes situation where you cannot afford speaker-attribution errors.',
  avoid_if = E'You need accurate speaker attribution on multi-person noisy in-person meetings (the 4+ speaker case breaks down), you record 8+ long sessions per week and need it free (the 300-min Pro cap forces upgrade fast), or you want sales-call analytics like deal risk scoring and call coaching (Otter is a recorder + summarizer, not a revenue intelligence platform like Gong).'
WHERE slug = 'otter-ai';

UPDATE tools SET
  tested_by = 'John Pham',
  last_tested_at = '2026-05-08',
  hands_on_notes = E'I tested Maze across two product cycles: an unmoderated prototype test on a new pricing page in Figma and a tree-test on a navigation restructure for a SaaS app. The cohort I had in mind was product designers and PMs who need quantitative validation on design decisions before engineering builds anything, distinct from Dovetail which sits downstream and analyzes already-collected qualitative research.\n\nThe Figma plugin sync is the standout. I built a flow in Figma, hit the Maze button, and within seconds had a clickable test ready to send to participants with first-click heatmaps, time-on-task, and completion rate captured automatically. The unmoderated tree-test for IA validation surfaced a category mislabel I would have shipped: the dashboard showed 38 percent of testers clicked the wrong primary nav item, which converted directly into a rename in the next sprint. The recruitment panel let me filter by job title and geo and got me 50 product manager respondents within 12 hours at a per-respondent cost that was reasonable for a quick directional test.\n\nWhat surprised me was how shallow the qualitative depth gets when you actually need it. Open-text questions are supported but the analysis tools are basic compared to Dovetail or even a manual spreadsheet pass: no sentiment clustering, no AI tagging that worked reliably on my test data, no way to export clean themes. The pricing also escalates quickly once you cross from prototype tests into full product testing across multiple flows: the Pro plan limits stack up if you run 4+ studies a month with mixed methods. Some Figma interactions also did not translate cleanly to the Maze player, particularly conditional show/hide states that depended on prior frame interactions, which forced a few tests to be rebuilt as simpler linear flows.\n\nMaze is the right pick if you are validating design decisions before code with quantitative methods like first-click, tree tests, and basic preference tests on a fast cadence. Skip it if your research is primarily qualitative interview-driven (Dovetail), if you need moderated user research with live interviewers (UserTesting or Lookback), or if your tests require complex Figma prototype state that Maze player cannot reliably render.',
  avoid_if = E'Your research is primarily qualitative interviews and you need theme analysis (Dovetail is built for that, Maze is shallow on open-text), you need moderated tests with live interviewer (UserTesting/Lookback), or your Figma prototypes use complex conditional state that the Maze player tends to break on.'
WHERE slug = 'maze';

UPDATE tools SET
  tested_by = 'John Pham',
  last_tested_at = '2026-05-08',
  hands_on_notes = E'I tested Bolt.new (StackBlitz) by prompting one-shot prototypes for three different specs: a SaaS pricing page with toggle, a kanban board with drag-and-drop, and a small dashboard with chart and table. The cohort I had in mind was non-developers and PMs who want to spin up a working visual prototype in minutes for stakeholder review, distinct from Lovable which leans more full-stack web app builder with auth and database.\n\nThe time-to-first-rendered-prototype is genuinely impressive. The pricing page request returned a working React+Tailwind page in about 90 seconds with the toggle wired up and visually decent. The full app runs in WebContainer in the browser, so I never had to download anything or set up a local stack to see the result, which is a real productivity unlock for anyone who would otherwise be blocked at "npm install" friction. Real-time editing in the chat-driven flow is fast: I asked for a copy change on the hero, and 8 seconds later the preview reloaded with the new text. One-click deploy to Netlify worked first try and gave me a shareable URL.\n\nWhat broke down was anything past the initial scaffold. The kanban board worked visually but the drag-and-drop logic had race conditions where dropping mid-animation duplicated cards. When I asked Bolt to fix the bug, it rewrote the entire DnD component twice without resolving it, and the third iteration introduced a new TypeScript error that took me 10 minutes to manually patch. State management beyond simple useState gets unreliable: the dashboard chart filtering broke whenever I added a new filter dimension, and Bolt could not consistently remember the data shape across edits. The token cost also adds up quickly on iterative debugging sessions where the model is essentially regenerating large files every prompt.\n\nBolt is the right pick if you need a one-shot visual prototype for stakeholder review or a static-leaning marketing site that can be deployed in 10 minutes. Skip it for production apps with auth, database persistence, or complex business logic (Lovable handles that better with Supabase integration), iterative debugging beyond 2-3 rounds (token cost spirals), or anything where the working code needs to graduate into a long-term codebase a real engineering team will maintain.',
  avoid_if = E'You need a production app with auth and database persistence (Lovable + Supabase is better suited), your prototype requires 5+ rounds of iterative debugging on the same component (token costs spiral and Bolt loses context), or you need code that an engineering team will maintain long-term (the output is prototype-grade, not production-ready architecture).'
WHERE slug = 'bolt';

UPDATE tools SET
  tested_by = 'John Pham',
  last_tested_at = '2026-05-08',
  hands_on_notes = E'I tested Amplitude on a SaaS analytics workspace with 90 days of historical event data covering signup, activation, and feature adoption funnels for ~12k monthly active users. The cohort I had in mind was product managers and growth teams running quantitative product analytics, distinct from Mixpanel as a peer competitor and from Plausible (lightweight web analytics, very different surface).\n\nThe funnel and retention reporting is where Amplitude clearly earns its category-leader status. Building a 5-step activation funnel with conversion windows, segmenting by acquisition channel and plan tier, and overlaying a 12-week retention curve took about 8 minutes once the events were instrumented properly. The Pathfinder feature for tracing actual user journeys through the product surfaced a feature-discovery dead end I had not seen in any dashboard summary: 31 percent of new users hit settings within the first session and bounced from there, which became its own deep-dive investigation. Amplitude AI for natural-language queries actually returned reasonable cohort definitions on simple questions like "users who activated within 7 days but did not return in week 2."\n\nWhat surprised me was how punishing the schema discipline has to be. If your event taxonomy was loose at instrumentation time (mixed casing, properties with the same semantic meaning under different names), the analysis surface multiplies that mess and the team ends up debating whether sign_up vs Sign Up vs SignUp are the same event in dashboards. The chart-load latency on workspaces with 30+ million monthly events also gets noticeable: I had several queries spinning for 30-60 seconds on broader date ranges, which kills the exploratory mode that makes a tool like this valuable. Pricing tier jumps are aggressive once you cross the free 10M-events ceiling, and several mid-tier features (data governance, identity resolution) gate behind enterprise plans.\n\nAmplitude is the right pick for product teams that already have clean event instrumentation and need deep funnel, retention, and pathing analysis at scale. Skip it if your team is at the "just starting product analytics" stage (Mixpanel is more forgiving on schema), if your needs are 90 percent web traffic dashboards (Plausible or GA4 are radically simpler), or if your event volume cannot justify the price-tier jumps that hit hard above 10M monthly events.',
  avoid_if = E'Your team is just starting product analytics and event taxonomy is messy (Mixpanel is more forgiving, Amplitude punishes schema sloppiness), you need basic web traffic dashboards (GA4 or Plausible are simpler at zero or fixed cost), or your monthly event volume is consistently above 10M and you need tight cost control (the price-tier jumps get punishing fast).'
WHERE slug = 'amplitude';

UPDATE tools SET
  tested_by = 'John Pham',
  last_tested_at = '2026-05-08',
  hands_on_notes = E'I tested Abridge by reviewing publicly demoed clinical-encounter samples and comparing the documentation output against the kind of SOAP note structure I have seen in primary-care settings. The cohort I had in mind was clinicians and health-system IT teams evaluating an AI medical scribe, distinct from generic meeting AI like Otter (which is the wrong tool for HIPAA-bound environments) and distinct from peers like Nuance DAX, Suki, and DeepScribe within the healthcare-scribe vertical itself.\n\nThe quality of the structured output is the headline. Abridge produces a SOAP note with clearly delineated subjective, objective, assessment, and plan sections, and on the demo encounters the assessment section captured ICD-10-anchored language that mapped cleanly to billable codes. The Epic and Cerner EHR integrations are deep and that matters: a scribe that produces a great note but cannot push it into the EHR cleanly creates double-data-entry friction that kills adoption. The patient-facing visit summary is a genuinely thoughtful product touch that competitors do not all match: clinicians can hand the patient a plain-language recap of what was discussed and what comes next, which addresses a real care-quality gap.\n\nWhat I cannot directly verify from outside a deployed health system is real-world ambient capture quality across accents, code-switching between English and Spanish in border-state clinics, and specialty-specific vocabulary in cardiology or oncology where the failure modes of a scribe could affect care decisions. The HIPAA and SOC 2 attestations are documented but each health system still has to do its own privacy and compliance review, which is a months-long process rather than a self-serve evaluation. Pricing is enterprise-only and not transparent: there is no public per-clinician monthly rate, which means small practice evaluation requires a sales conversation before you can even know if this fits your budget.\n\nAbridge is the right pick for mid-to-large health systems with Epic or Cerner standardized, internal compliance teams that can run the security review, and a clinical-leadership champion who can drive change management. Skip it if you are a solo provider or small practice (the enterprise sales motion is not friendly to small budgets), if your EHR is a niche or homegrown system (integration depth varies), or if you need transparent pricing for a quick evaluation (you will need to talk to sales first).',
  avoid_if = E'You are a solo provider or 1-3 clinician practice (enterprise sales-driven, not friendly to small budgets), your EHR is niche or homegrown (Epic/Cerner integration is deepest, others vary), or you need transparent self-serve pricing for a quick evaluation (Abridge requires a sales conversation before quoting).'
WHERE slug = 'abridge';
